src/object.di
src/object_.d

Resurrected from https://github.com/D-Programming-Language/druntime/pull/574.
The basic idea is to provide this functionality in druntime, and if people insist, add a wrapper to Phobos that returns `Tuple`s as people clamored for last time. Or just recommend users add this one-liner wrapper to their own code:
````
auto r = aa.byPair().map!(a => tuple(a.key, a.value));
````
then you'll a `Tuple` range out of it for no extra charge. :-)

Implement AA byPair.

---

src/object.di

We seriously need to automate the generation of `object.di`... this is an embarrassment.

Fix wrong copy-pasta from object_.d.

---

src/object.di
src/object_.d

Fixes iteration over `byKeyValue` with const loop variables.

byKeyValue should also work with const loop variables.

---

src/object.di
src/object_.d

Sigh... yet one more thing overlooked in `byKeyValue`.

.save needs to be @property otherwise isForwardRange fails.

---

benchmark/gcbench/conmsg.d

- tests producer-consumer pattern
- both ends allocate lots of short lived garbage
- trigger many (~200) collections but heap remains very small (5MB)

add new GC benchmark

---

src/core/atomic.d

16-Byte operations added for atomicStore, atomicLoad and CAS (module: core.atomic).
(ie. double-word added for 64 bit machines.  It is already available on 32 bit machines.)

16-Byte Cas, AtomicStore and AtomicLoad added to core.atomic.

---

src/core/thread.d

`core.sys.posix.sys.types` privately imports `core.sys.posix.config`, so `c_long` should be invisible via `core.sys.posix.sys.types` module.

Add missing imports

---

benchmark/runbench.d
src/gc/gc.d

* measures maximum pause time (time the world is suspended)
* outputs summary line for runbench with pool mem, number of collections, overall collection time, overall pause time and maximum pause time

add some useful metrics to GC summary

---

src/gc/gc.d

Refactor GC

---

src/gc/gc.d

- or the else branch gets executed on a successful pool allocation

allocating a pool must be done in the if (disabled) block

---

src/core/demangle.d

Refer: https://github.com/D-Programming-Language/dlang.org/commit/416e78085d70c964c29136fe2707b9efec4c1980

Update core.demangle to follow the newest mangling scheme

---

src/gc/gc.d

This also reverts changing the functions' return type (back from a struct to a delegate).

gc.gc: Simplify implementation of rootIter and rangeIter

---

src/gc/gc.d

- collect all live objects in a todo stack
to be marked later
- remove outer anychanges loop and scan GCBits
- only mark todo items after current mark(p1, p2) is done
to benefit from cache locality, prefetcher and tail recursion

use todo stack when traversing GC heap

---

src/core/sync/mutex.d

- replace with alias to lock/unlock which are now nothrow

begin to deprecate Mutex.lock_nothrow/unlock_nothrow

---

src/core/sys/posix/sys/shm.d

Fixes [Issue 14007 - shmctl with IPC_STAT returns wrong number of attachments. shmid_ds is defined wrong.](https://issues.dlang.org/show_bug.cgi?id=14007)
Fix originally by [tcak via Bugzilla](https://issues.dlang.org/show_bug.cgi?id=14007#c4).

version away __unused1/2/3 for X86_64

---

src/core/thread.d

- nanosleep can only fail on invalid arguments
which would be a bug in druntime itself

mark Thread.sleep as nothrow

---

src/rt/lifetime.d

These changes were missed when merging #864 due to some recent changes to the array handing.

fixup merge error with array reallocation for struct destructors

---

src/rt/lifetime.d

According to the documentation, GC.extend expects the "root" pointer of an allocation, not the base pointer of an array, which can have an offset.

fix GC.extend calls in rt.lifetime

---

src/object.di
src/object_.d
src/rt/aaA.d

This is needed for precise scanning of heap objects allocated by the AA implementation.
- add _aaGetY with full type info
- supply more type info to _aaValues, _aaKeys
- return normal dynamic array, not "raw" array
I'm not sure how obsolete this becomes with the new AA implementation, though.

Provide more TypeInfo for AA allocations

---

benchmark/gcbench/rand_large.d
benchmark/gcbench/rand_small.d

- seeds were produced by running unpredictableSeed

use fixed seeds for rand_{small,large} benchmark

---

src/rt/lifetime.d

In anticipation of Walter's usual objection: we have broken druntime ABI compatibility in the last 24 hours with #1037 so now is a good time to make a second break, as bisecting users will likely have to rebuild druntime anyway.
This pull request completes the cleanup of the variadic runtime functions.

[cleanup] Delete unused variadic runtime functions

---

src/core/stdc/stdarg.d

Remove va_start's body, as it is not an intrinsic function.  The old body was incorrect, and leaving it intact results in wrong-code when it is inlined.
https://github.com/D-Programming-Language/dmd/pull/4336

Required fix for issue 9495

---

src/core/thread.d

- avoids extra complications in signal handler
because the TLS thread reference is set when
suspension can occur
- required for parallel suspend #1110

don't suspend starting threads

---

src/gc/gc.d
src/gc/proxy.d

- avoids virtual calls
- inheritance isn't needed

make GC a struct

---

src/rt/aaA.d

_d_newarrayU returns an array of `void[]`, but the length is set with respect to the actual type T of `new T[n]`. That's why a normal indexing causes a range error when building a debug version of druntime.
I think returning `void*` would be better, but the result is forwarded by `_d_newarrayT`, `_d_newarrayiT` and `_rawDup!T`. I didn't want to open that can of worms.

fix RangeError in _aaKeys

---

src/core/stdc/stdarg.d

Needs to be merged at the same time as https://github.com/D-Programming-Language/dmd/pull/4343

Remove va_start's body on posix64 so it doesn't get inlined

---

src/core/stdc/stdarg.d

It's actually a `char*`, not a `void*`.

Cast va_list calculation to correct type on x86

---

src/core/sys/posix/sys/resource.d

If `__USE_FILE_OFFSET64` is specified we need to use the `*64` functions.

Fix posix resource.d header for ARM

---

src/gc/gc.d

- move getBits,setBits,etc, runFinalizers, getInfo into Pool
- split Pool into LargeObjectPool and SmallObjectPool
This yields a small perfomance improvement:
```
Test         Win64 master     this PR       Win32   master   this PR
R bulk             2.105 s,   2.074 s               0.765 s, 0.754 s
R resize           0.875 s,   0.868 s               0.757 s, 0.756 s
R string           0.023 s,   0.023 s               0.024 s, 0.024 s
R conalloc         0.703 s,   0.677 s               0.061 s, 0.063 s
R conappend        0.011 s,   0.011 s               0.012 s, 0.012 s
R concpu           0.835 s,   0.821 s               0.084 s, 0.085 s
R conmsg           0.583 s,   0.557 s               0.619 s, 0.597 s
R dlist            1.609 s,   1.388 s               1.448 s, 1.416 s
R huge_single …
```

refactor GC.Pool 

---

mak/COPY
mak/MANIFEST
src/core/sys/freebsd/sys/cdefs.d
src/core/sys/freebsd/sys/mman.d
src/core/sys/linux/sys/mman.d
src/core/sys/osx/sys/cdefs.d
src/core/sys/osx/sys/mman.d
src/core/sys/posix/sys/mman.d
win32.mak
win64.mak

- remove MAP_ANON for linux from core.sys.posix.sys.mman
(has been deprecated since sep 2013)
- add platform specific headers for mman (OSX, FreeBSD)
and deprecate MAP_ANON for those in the posix header

update deprecation of MAP_ANON from core.sys.posix.sys.mman

---

src/core/sys/linux/sys/mman.d

---
Noticed this when working on Android stuff; untested, but everything else spells it `AArch64`.

mman: fix AAarch64 version check

---

src/gc/gc.d

also refactored LargeAllocPool.allocPages for better readibility and performance.
This dropped execution time of the rand_large benchmark from >3sec to 0.8 sec on Win32. It didn't have much influence on the other tests, though.

GC: cache the largest free chunk of pages in LargeAllocPool

---

src/gcstub/gc.d

- otherwise the modulename collides with gc.gc
in the druntime archive leading to a linker error
when linking against gcstub.o

use BlkAttr and BlkInfo from core.memory

---

src/object_.d
src/rt/aaA.d
src/rt/typeinfo/ti_ptr.d

- the internal TypeInfo_P.getHash for pointers trucated the hash to
32-bit unlike the TypeInfo_Pointer.getHash
- internal TypeInfos are used when no full type information is needed
so they must behave identical
[Issue 14104 – aa with pointer key type doesn't find existing value](https://issues.dlang.org/show_bug.cgi?id=14104)

fix Issue 14104 - aa with pointer key type doesn't find existing value

---

src/core/sys/posix/sys/stat.d
src/core/sys/posix/sys/statvfs.d
src/core/sys/windows/stat.d

fstat is trusted - it does not escape the pointer passed to it and never does unsafe stuff even if passed a wrong handle

Make fstat @trusted

---

src/rt/lifetime.d

The constant `LARGEPAD` was used instead of `LARGEPREFIX` when offsetting array elements in large arrays. `LARGEPAD` is used to determine *total* array size, not just the extra space at the beginning, and this includes 1 sentinel byte for avoiding cross-block issues. See https://issues.dlang.org/show_bug.cgi?id=14126 for a better explanation.

Fixed issue 14126 -- GC seemingly corrupting memory

---

src/core/stdc/stdarg.d

@ibuclaw @andralex 
This doesn't fix the underlying problem, but by allocating new storage with alloca it allows most cases to work, which is a lot better that the current situation.
https://issues.dlang.org/show_bug.cgi?id=14131

Partial fix for Issue 14131 - va_copy is broken on posix X86_64

---

src/core/time.d

The druntime unittests fail for my desktop system that returns a tick counter frequency of 3906245 Hz. The tests involve floating point operations, so they should allow for some inaccuracy and rounding errors. 
An alternative could be to use normal rounding in the conversoin functions, but that would be a larger change with possible side-effects.

fix core.time unittests for odd ticksPerSec

---

src/rt/lifetime.d

https://issues.dlang.org/show_bug.cgi?id=14134
"delete slice" now destroys and frees the full array

issue 14134 -  Free of large array does not work

---

src/test_runner.d

Per https://github.com/D-Programming-Language/phobos/pull/2946, we need to specify debug vs. release in the PASS/FAIL information. I've also added 32/64.

Better printed information in unittests

---

src/rt/critical_.d

- needed for nothrow synchronized statements

mark rt.critical_ as nothrow

---

benchmark/runbench.d

this brings back the short GC profiling summary when redirecting GC ouptut to gcx.log

runbench: fix omission when changing GC profiling summary text

---

src/core/sys/freebsd/sys/mman.d
src/core/sys/linux/sys/mman.d
src/core/sys/osx/sys/mman.d
src/core/sys/posix/sys/mman.d

- it's not Posix standard but literally supported
by every OS and also a widely used flag, therefor
we consider it standard
- group MS_SYNC/ASYNC/INVALIDATE flags

move MAP_ANON back to core.sys.posix.sys.mman

---

src/core/stdc/complex.d
src/core/stdc/ctype.d
src/core/stdc/errno.d
src/core/stdc/fenv.d
src/core/stdc/float_.d
src/core/stdc/inttypes.d
src/core/stdc/limits.d
src/core/stdc/locale.d
src/core/stdc/math.d
src/core/stdc/signal.d
src/core/stdc/stdarg.d
src/core/stdc/stddef.d
src/core/stdc/stdint.d
src/core/stdc/stdio.d
src/core/stdc/stdlib.d
src/core/stdc/string.d
src/core/stdc/tgmath.d
src/core/stdc/time.d
src/core/stdc/wchar_.d
src/core/stdc/wctype.d

Fix C API header blurb call to prevent accidental formatting of symbol names

---

src/rt/sections_win32.d
src/rt/sections_win64.d

This restricts root ranges for the GC to section ".data"  and ".bss" ~~".bss$B" and ".data$B" for Win64 (also excludes C/C++ sections)~~ and excludes the "CONST" section and a bit more for Win32.
On linux, similar functionality already exists as constant data (strings/float) is written to the .text section.
~~For Win64, this depends on https://github.com/D-Programming-Language/dmd/pull/4445~~

Issue 4650 - only scan data and bss, not const

---

src/core/time.d

Fix for computing ticksPerSec for OSX where the denom and numer need to be reversed.  The problem is not noticed on MacOSX because both are 1, but on iPhoneOS this is not the case.

Fixed ticksPerSec for OSX (in particular iOS)

---

src/core/atomic.d

- was already inferred, but explicit annotation
is needed for CoreDdoc declarations

add pure and @nogc to cas

---

src/core/sys/osx/sys/event.d

The file is a copy of FreeBSD events.d but with minor changes in the enum identifiers for the EVTFILT_* names.

OSX Events

---

src/core/sys/posix/stdio.d

Otherwise the unit test will not compile because of @nogc.
It's also a bug in 2.067.0-rc1.

core.sys.posix.stdio: Change dynamic to static array.

---

src/rt/lifetime.d

Library code may conservatively call assumeSafeAppend on an array without knowing if the block will be appended to. However, if the block is not cached in the block info cache, it would not add it to the cache. This meant that code that continually calls assumeSafeAppend is constantly looking up the block info from the heap. This fixes that situation.

When calling assumeSafeAppend, cache the block info for subsequent calls

---

src/core/stdc/fenv.d

VCRT 2013 uses a minimally different <tt>feraiseexcept()</tt> implementation than this one from VCRT 2014 CTP 3 (2013 additionally sets the exception flags via <tt>fesetexceptflag</tt>), but I guess that doesn't make a huge difference. The rest of 2013 is identical to 2014, so MSVC 2013 should be supported too.
More important are the correct constants and the implementation of 2 inline functions (to prevent linking errors).

core.stdc.fenv: proper support for Microsoft C Runtime (Visual Studio >= 2013)

---

src/gc/gc.d

The out-of-bounds access occurs 3 lines below:
`pagetable[i + p]`
We never check that `i + p < npages`.
This patch also acts as a small optimization (don't look at the last `n-1` pages because it's impossible to find a free chunk of at least `n` pages from those positions).
Found using Vagrind: https://github.com/D-Programming-Language/druntime/pull/1197#issuecomment-85671211

gc.gc: Fix out-of-bounds pagetable access

---

src/core/sys/posix/stdio.d

The memstream family of POSIX functions are not available as of MacOSX 10.10.
Something like this is needed to link all unittests on OS X (and iOS).  Not sure of the the best approach to disabling these POSIX functions because other OS might be involved, but wanted to start the conversation with this pull request.

fmemopen, open_memstream unavail on OSX

---

src/core/thread.d
src/gc/gc.d
src/object.di
src/object_.d
src/rt/lifetime.d

https://issues.dlang.org/show_bug.cgi?id=14401
`TypeInfo_Class` needs to override `init()` method for the `TypeInfo_Const` and its derived TypeInfo classes.
Now all `typeid(X).init` for any type `X` is typed as `const(void)[]`.
This is a small but necessary breaking change. If a class instance contains reference type fields, the instance image must be typed as `const(void)[]` rather than `byte[n]`.

Issue 14401 - typeid(shared X).init is empty for class types

---

src/core/stdc/math.d

These commits add proper support for Microsoft C runtimes to <tt>core.stdc.math</tt>. It is especially useful in combination with MSVCRT v12 (VS 2013) with its greatly improved C99 support (30+ new math functions, in single and double precision).
Microsoft's lacking 80-bit x87 support is approximated by 64-bit double-precision wrappers.

core.stdc.math: proper support for Microsoft C Runtime (Visual Studio >= 2013)

---

src/gc/config.d
src/gc/gc.d

Here's a benchmark result with API time:
```
R bulk             1.075 s,    38 MB,   16 GC  173 ms, Pauses   79 ms <   15 ms API  616 ms
R resize           0.872 s,    12 MB,   11 GC   24 ms, Pauses    2 ms <    0 ms API  133 ms
R string           0.027 s,     5 MB,    2 GC    0 ms, Pauses    0 ms <    0 ms API    1 ms
R conalloc         0.069 s,     5 MB,   83 GC   10 ms, Pauses   10 ms <    0 ms API   12 ms
R conappend        0.014 s,     5 MB,    6 GC    0 ms, Pauses    0 ms <    0 ms API    4 ms
R concpu           0.092 s,     5 MB,   79 GC   34 ms, Pauses   33 ms <    0 ms API   34 ms
R conmsg           0.805 s,     5 MB,  130 GC   44 ms, Pauses   15 ms <    0 ms API  552 ms
R dlist            1.834 s,    12 MB,   52 GC  331 ms, Pauses  227 ms <    4 ms API  692 ms
R huge_single …
```

allow GC API profiling with --DRT-gcopt=profile:2

---

win64.mak

This adds targets `druntime32mscoff` and `unittest32mscoff` to win64.mak.
The 32-bit compiler is derived from the setting for the 64-bit compiler, but can be overwritten on the make command line with `CC32=`
The usual conditions for `VCDIR` and `SDKDIR` apply, ~~though the default is improved by using `$(ProgramFiles)`~~. As for Win64 since the `-conf=` setting, it is necessary to set `LINKCMD`and `LIB` in the environment to link the unittests.

add win32coff targets

---

mak/MANIFEST
mak/SRCS
src/rt/typeinfo/ti_cent.d
src/rt/typeinfo/ti_ucent.d

The types are defined in the spec but not yet implemented. Add the
required TypeInfo classes for supporting compilers. The classes are
guarded to prevent compile errors on non-supporting compilers.
See https://github.com/D-Programming-Language/dmd/pull/4565 for
the name mangling.

Add TypeInfo classes for cent/ucent.

---

src/core/memory.d
src/core/sync/mutex.d
src/core/sys/posix/pthread.d
src/core/sys/windows/windows.d
src/gc/gc.d
src/rt/util/container/common.d
src/rt/util/container/treap.d
src/rt/util/random.d

NOTE: this is my first druntime PR, please be sure to check it extra carefully and feel free to give me tips.
This addresses [issue 14171](https://issues.dlang.org/show_bug.cgi?id=14171). Phobos utilities that use the non-allocating GC functions in areas that should be nogc(see: std.container.array, refcounted, etc,) this should make them able to infer nogc.
I'm completely unsure of how to handle throwing errors in nogc, what I did is probably completely incorrect(? I know it shouldn't be done for exceptions - are errors an exception(heh) to this?) so I could use some advice.

Mark core.memory.GC.addRange/removeRange as nogc

---

src/core/stdc/math.d

The constants are wrong for FreeBSD, and we see issues with it in https://github.com/D-Programming-Language/phobos/pull/3161
The FreeBSD choice of constants is also C99 compliant.

Fix FP_ILOGB0 and FP_ILOGBNAN constants for FreeBSD

---

.gitignore
src/core/atomic.d

This is the placeholder pull request for the work on improving performance around fetchAdd atomic operations. This has a new implementation for += and -= atomicOp and provides a new method atomicFetchAdd. I'd debate if we require atomicFetchSub for this feature, but I'm open to thoughts.
Ideally, I need help for someone to benchmark this PR to see if it does indeed improve performance on x86 and x86_x64.
https://issues.dlang.org/show_bug.cgi?id=12891

fix Issue 12891: add atomicFetchAdd to core.atomic

---

benchmark/aabench/bulk.d
benchmark/aabench/int.d
benchmark/aabench/obj.d
benchmark/aabench/ptr.d
benchmark/aabench/resize.d
benchmark/aabench/string.d

- cover different key types (int, obj, ptr)
- fix string to be AA limited, instead of benchmarking text splitting

better AA benchmarks

---

src/object.di
src/object_.d
src/rt/aaA.d
src/rt/lifetime.d

This builds an appropriate TypeInfo_Struct for aaA.Entry at runtime whenever a new Impl is created.
I've removed the old unused _aaGetX as it doesn't provide enough type info, and disabled the future yet unused _aaGetZ for the same reason.

fix Issue 14423 - struct destructors not finalized for AA values 

---

src/object.di
src/object_.d

The exception class constructors do not themselves allocate any memory in the garbage collector, so they can be marked as @nogc. This enables the exception constructors to be used with custom allocators in the future in @nogc code.
I admit that this change was so trivial I just did it directly through GitHub.

Mark exception class constructors as @nogc

---

src/gc/gc.d

(Note, reopened from https://github.com/D-Programming-Language/druntime/pull/1226)
In small object pool, the bits retrieved when using `Pool.getInfo` should be for the block, not the specific pointer. This was changed in https://github.com/D-Programming-Language/druntime/pull/1127 accidentally, I believe. This PR restores the original meaning.
Also, I noticed there is no other unit tests in this file. I don't know if I put the unit test in the right place.
Bugzilla: https://issues.dlang.org/show_bug.cgi?id=14467

Fix issue 14467 - arr.capacity sometimes erroneously returns 0

---

src/core/internal/traits.d
src/object.di
src/object_.d

Discussed in [this thread](http://forum.dlang.org/thread/krccldftrbbczahasvbi@forum.dlang.org).
With this patch, the `@safe`ty etc. of object.destroy depends on the destructor of the struct.
Also adds `postblitRecurse` to enable explicit copying with attribute inference, to be used in `emplace`.
Attribute inference for destruction/postblit of fixed-length arrays with struct elements seems to be broken even for implicit/in-built destruction/postblit, so that needs to be fixed in the compiler before it's tackled here.
This impacts attribute inference in a couple of key Phobos building blocks, such as `emplace` and the `Array` container. Grepping for `malloc` tends to be a good way to find code that uses explicit destruction.
I plan to file one or more dependent Phobos PRs to leverage this.

Make .destroy() work with attribute inference

---

src/object.di
src/object_.d
src/rt/aaA.d
src/rt/lifetime.d

- new AA implementation
- uses open addressing with quadratic probing (triangular numbers) and pow2 table
- uses NO_SCAN for entries when applicable
- minimizes alignment gap for values
- calls postblit on aa.keys and aa.values
[Issue 14385 – AA should use open addressing hash](https://issues.dlang.org/show_bug.cgi?id=14385)

fix Issue 14385 - AA should use open addressing hash

---

src/core/exception.d

https://github.com/D-Programming-Language/dmd/pull/4606
I assume it is proper for first deprecating ``HiddenFuncError`` and ``onHiddenFuncError`` just incase there's any client-side usage of these.

Remove _d_hidden_func and deprecate helper class and function

---

src/core/stdc/stdint.d
src/core/stdc/stdio.d
src/core/stdc/stdlib.d
src/core/stdc/string.d
src/core/stdc/time.d
src/core/stdc/wchar_.d
src/core/sys/linux/stdio.d
src/core/sys/posix/fcntl.d
src/core/sys/posix/signal.d
src/core/sys/posix/sys/mman.d
src/core/sys/posix/sys/shm.d
src/core/sys/posix/sys/socket.d
src/core/sys/posix/sys/stat.d
src/core/sys/posix/sys/types.d
src/core/sys/posix/sys/uio.d
src/core/sys/posix/unistd.d

[Ketmar is right](https://issues.dlang.org/show_bug.cgi?id=14215), `size_t` and `ptrdiff_t` were moved to `object.di` at least five years ago, so all these imports and references to them are wrong.  The four deleted public imports might still be inadvertently used to import the remaining `wchar_t` alias, but since that only seems likely for `core.sys.posix.sys.types`, I only left that one public import in.

Fix 14215 - Unnecessary imports of core.stdc.stddef for size_t and ptrdiff_t

---

src/rt/trace.d

https://issues.dlang.org/show_bug.cgi?id=14511
This is a refactoring to modernize the code a bit and enhancement to handle multithreaded programs. The idea, suggested by Andrei, is to use thread local data for profiling data in each thread, then on thread termination merge the thread local data into the global profiling data.
The code could still be improved by using a hash table instead of a binary tree, and getting rid of the linked lists, but we'll save that for another day.

fix Issue 14511 - Profiler does not work with multithreaded programs

---

src/core/time.d

This adds an enum for indicating which type of clock to use when it's
appropriate for a time function to have multiple options for the source
clock. Currently, it only supports "normal" and "coarse," but we may add
more in the future, since some systems do support others (e.g
clock_gettime has several other options depending on the system).
This is in support of https://github.com/D-Programming-Language/phobos/pull/2584.

Add ClockType enum to core.time for issue# 13433.

---

benchmark/aabench/stomper.d
benchmark/aabench/string.d

- on average pollutes 1000 bytes of cache between each lookup
- import splitter from std.algorithm instead of std.array

new AA benchmark with cache stomping

---

src/rt/typeinfo/ti_cent.d
src/rt/typeinfo/ti_ucent.d

The same check is used in Phobos in module std.traits.

Simplify the check if cent/ucent is supported.

---

src/core/stdc/fenv.d
src/core/sys/posix/setjmp.d
src/core/sys/posix/sys/msg.d
src/core/sys/posix/sys/socket.d

The missing definitions were found while cross compiling for AArch64.

Add missing definitions for AArch64.

---

posix.mak
src/object.di
src/object_.d
src/rt/deh_win32.d
src/rt/dmain2.d
src/rt/monitor_.d
src/rt/util/string.d
win32.mak
win64.mak

Updating object.di and object_.d is a maintenance liability. This PR removes non-public code from object._d and adds a bit from object.di in order to generate the latter automatically.
Comparing object.di to the generated header reveals:
- aliases for string,wstring,dstring not converted correctly, needs https://github.com/D-Programming-Language/dmd/pull/4594
- overriding methods often not declared in classes declared in object.di. This can cause unexpected results when deriving from this class and calling `super.method()`.
- different types for `TpeInfo_Class.defaultConstructor`
- different return types for `TypeInfo_Struct.xtoHash`
- missing fields in classes `MemberInfo_field` and `MemberInfo_function`, can have bad effects when deriving from it or using `__traits(classInstanceSize)`. …

Copy object.di from object_.d

---

src/core/thread.d

Discussion: http://forum.dlang.org/thread/bltdzwskligncpgwdmxc@forum.dlang.org

Allow a fiber in HOLD state to be reset bypassing scope(exit) etc.

---

src/core/time.d

This makes it so that ClockType isn't actually used in core.time in the
documentation build (since if it is, it triggers static assertions,
since none of the systems support all of the ClockTypes, but they all
have to be defined for the documentation build in order to show up in
the docs).

Fix bug# 14546 - Make the druntime documentation buildable again.

---

src/core/stdc/stdio.d
src/core/stdc/wchar_.d

I noticed `fpos_t` was defined wrongly in `core.stdc.stdio` a while back, finally fixing it.  I couldn't find where [`__darwin_off_t` was defined in Apple's libc headers for `OSX`](http://www.opensource.apple.com/source/Libc/Libc-1044.1.2/include/stdio.h), probably because the definition is automatically generated, so @jacob-carlborg or someone else will have to fill me in on that one.  [I read the headers for Solaris](http://src.illumos.org/source/xref/illumos-gate/usr/src/ucbhead/stdio.h#78), @redstar can tell me if I got it wrong.  The others were checked with a test C file run through the native preprocessor, so they should be okay.
I had to fix `mbstate_t` for glibc, didn't bother checking that one on the other OS's.  I also deleted the comments about removing the shared file handle …

Fix Issue 12289 - incorrect core.stdc.stdio.fpos_t alias and mbstate_t for glibc

---

src/core/sys/posix/sys/msg.d

MIPS definition was incomplete and MIPS64 and PPC64 missing.

Add missing definitions to core.sys.posix.sys.msg

---

src/core/time.d

https://github.com/D-Programming-Language/druntime/pull/1190 was not tested throughout, it has a missing "this".
TickDuration t;
auto tf = to!("nsecs",float)(t);
Update:
found this while making the plotting for my benchmark module better
Update2:
best PR number ever :-)

TickDuration UFCS "to" was broken for float

---

src/core/demangle.d

Follow up to #1263 
@MartinNowak - this adjustment I've made is by assuming that the ABI is followed precisely.
I have yet to get the serenity library and rebuild it to check whether the ABI mangling reported in 2011 is still the same as today.

Also fix complex template test in core.demangle

---

src/object.d

- needed to weakly link against classinfo (Isssue 14555)
[Issue 14555 – ModuleInfo should weakly link against classes](https://issues.dlang.org/show_bug.cgi?id=14555)
https://github.com/D-Programming-Language/dmd/pull/4638

skip null classinfo

---

src/core/thread.d

- the newly created thread fails because of a stack overflow
in a syscall to sbrk triggered by pthread_attr_get_np/calloc
- [Issue 14476 – core.thread unit tests failing on FreeBSD 9+](https://issues.dlang.org/show_bug.cgi?id=14476)

fix Issue 14476 - core.thread unit tests failing on FreeBSD 9+

---

benchmark/aabench/stomper.d
benchmark/gcbench/vdparser.extra/vdc/ast/type.d

stomper uses `lround` that is not implemented on Windows.
vdparser tries to write `TypeInfo_Const.next`, must be `base` now.

fix benchmarks

---

src/core/cpuid.d
src/core/runtime.d
src/core/stdc/config.d
src/core/stdc/signal.d
src/core/stdc/stddef.d
src/core/stdc/string.d
src/core/stdc/time.d
src/core/sync/barrier.d
src/core/sync/rwmutex.d
src/core/sys/posix/pthread.d
src/core/sys/posix/sched.d
src/core/sys/posix/semaphore.d
src/core/sys/posix/signal.d
src/core/sys/posix/stdio.d
src/core/sys/posix/sys/resource.d
src/core/sys/posix/sys/stat.d
src/core/sys/posix/unistd.d
src/core/sys/windows/dll.d
src/core/sys/windows/stacktrace.d
src/core/sys/windows/windows.d
src/core/sys/windows/winsock2.d
src/rt/cover.d

As mentioned on the newsgroup, this pull starts cleaning up unnecessarily separated version(OS) blocks, so that porters aren't given unneeded work.  Also, inside modules that are only available to Posix, `version(Posix)` checks are removed and catch-all uses of `else version(Posix)` are expanded to name each OS instead, as Sean said is the way it should be done.
I'm putting this pull up before it's done so that I can get comment on any of the proposed cleanups early on, before I spend time tracking more of these down.

Clean up unnecessary version(Posix) and version(OS) and try to more narrowly scope catch-all else blocks

---

src/core/stdc/fenv.d
src/core/sys/posix/dirent.d
src/core/sys/posix/fcntl.d
src/core/sys/posix/setjmp.d
src/core/sys/posix/signal.d
src/core/sys/posix/sys/ipc.d
src/core/sys/posix/sys/mman.d
src/core/sys/posix/sys/socket.d
src/core/sys/posix/sys/stat.d
src/core/sys/posix/sys/types.d
src/core/sys/posix/sys/uio.d
src/core/sys/posix/time.d

When I first added Android support, it was based on the x86 headers of Android API 9, with any definitions coming from architecture-dependent headers placed inside a `version(X86)` block, just in case.  For this pull, I checked each of those blocks for the three 32-bit platforms from Android API 9, `X86`, `ARM`, and `MIPS32`.  If they're all the same, the versioning was removed.  If any arch varied, the definition was put inside its own `version(ARM)` block.
I did not check the new 64-bit platforms added with the latest Android API 21.  This pull overlaps and obsoletes some of #764, which has not been updated in a while.
I need to add one last bit to `core.stdc.errno`, but cannot do so till a change to that module in my previous #1010 is merged first.  Once that's merged, I can add the …

Add Android/ARM support

---

mak/MANIFEST
mak/SRCS
src/rt/aaA.d
src/rt/util/mem.d

This PR tries to restore performance of the AA after changing it to "state-of-the-art" dense hash map.
Results of AA related benchmarks on my mobile i7:
```
Win32:
oldAA     newAA     newAA_tweaked
R bulk             0.293 s   0.328 s   0.299 s
R int              0.106 s   0.117 s   0.115 s
R obj              0.129 s   0.128 s   0.127 s
R ptr              0.110 s   0.112 s   0.106 s
R resize           0.393 s   0.420 s   0.401 s
R stomper          1.026 s   1.007 s   1.013 s
R string           0.149 s   0.142 s   0.142 s
R testgc3          1.825 s   2.201 s   1.919 s
```
Win64 benefits from these optimizations aswell:
```
Win64:
oldAA     newAA     newAA_tweaked
R bulk             0.444 s   0.388 s   0.365 s
R int              0.139 s   0.116 s   0.113 s
R obj              0.164 s   0.144 …
```

Tweak new AA implementation to get similar performance as the old one on Win32

---

src/core/stdc/stdio.d
src/core/sys/windows/windows.d

- SetEndOfFile (Windows API)
- open/sopen/fdopen/close (CLIB stdio)
- fileno DMC
- add missing underscore aliases for DMC

add missing IO declarations for Windows

---

src/rt/critical_.d
src/rt/dmain2.d
src/rt/monitor_.d

- reuse mutex declarations from rt.monitor_
- fix race condition (incorrect double checked locking)
- modernize code for readability
- use shared(D_CRITICAL_SECTION)* when dealing with
unsynchronized data
- replace STI/STD style C constructors
- fix Issue 6607
- hopefully fix Issue 14584 - spurious autotester deadlocks
[Issue 14584 – spurious autotester deadlocks](https://issues.dlang.org/show_bug.cgi?id=14584)
DEPENDS ON: #1272

cleanup and rewrite rt.critical_

---

src/core/time.d
src/gc/gc.d
src/rt/dmain2.d

Also:
- Factor out translation of ClockType enums to POSIX clock types as a parameter to clock_gettime, etc.
- Remove reimplementation of getting MonoTime.ticks from GC code, since the initializer is now run before the gc initializer.
- Factor out translation of clock type to clock type enum index.
- Factor out traits lookup of enum name.

Some updates to MonoTime to better initialize the ticks per second

---

src/core/sys/posix/pthread.d

This adds an initializer to pthread_mutex_t so it is correct by default on OSX. Not sure if this will work, it failed my unittest build on OSX with a link error. I think possibly types.d is not included in the unit test build.

Fix issue 14617 - PTHREAD_MUTEX_INITIALIZER does not work on OSX

---

src/object.d

It was supposed to be used for the still unimplemented
ModuleInfo.xgetMembers(), but the latter only returns
void*.

Remove unused object.MemberInfo

---

osmodel.mak
posix.mak

There were slight difference between the logic in `posix.mak` compared to `osmodel.mak` (DRY)
Also see https://github.com/D-Programming-Language/dmd/pull/4684

Use osmodel.mak from dmd repo

---

mak/MANIFEST

Because nobody ever remembers to update MANIFEST when adding files, leading to files missing from the zip file.
grumble, grumble

add osmodel.mak to MANIFEST

---

src/core/demangle.d
src/core/runtime.d

Found by adding -w to Ddoc command line.

Fixed DDoc warnings

---

posix.mak
win32.mak
win64.mak

This gives control to the repository rather than the auto-tester.
The choice of target is based on current behavior.  For auto-tester-build, the tester isn't specifying a target, so the behavior is 'whatever is first in the makefile'.  That's 'target' for all the current makefiles.  For auto-tester-test, that's explicitly 'unittest' in the current tester build scripts.
This will need to be merged to the other branches before the tester can switch to using these new targets.

add auto-tester specific targets

---

src/core/stdc/math.d
src/core/sys/posix/fcntl.d
src/core/sys/posix/unistd.d
src/rt/cover.d

lockf isn't provided in Bionic and the ilogb constants are defined differently.

Two fixes for Bionic

---

src/core/checkedint.d

* thanks to dip56 we have forced inlining
* for https://github.com/D-Programming-Language/phobos/pull/3389 dmd,ldc,gdc failed to inline functions of checkedint 
this should fix it

checkedint functions force inline

---

src/object.d

- also fix _postblitRecurse
- replace recursive templates with _xdtor and _xpostblit
[Issue 14746 – [REG2.068a] Behavior change with struct destructor and alias this](https://issues.dlang.org/show_bug.cgi?id=14746)

fixup Issue 14746

---

src/core/cpuid.d

These properties are immutable. They should be made immutable, so that users of them won't need to use static constructors in order to have pure functions, such as in std.digest.sha.
Doing just one to see how it goes.

core.cpuid - make ssse3 immutable

---

src/rt/minfo.d

This'll say whether it's global or shared constructors, and marks with a '*' which modules in the cycle have a ctor/dtor.

improve diagnostics for circular static construction failure

---

posix.mak
src/core/atomic.d
src/core/stdc/math.d
src/core/sys/linux/epoll.d
src/core/sys/linux/sys/xattr.d
src/core/sys/posix/sys/statvfs.d
src/core/sys/posix/sys/types.d
src/core/sys/posix/syslog.d
src/core/sys/posix/unistd.d
src/core/sys/windows/winsock2.d
src/core/thread.d
src/core/threadasm.S
src/gc/gc.d
src/rt/util/container/treap.d
src/rt/util/random.d

Trying not to commit bad line endings again, I added checkwhitespace to my build batch. This fails for some existing files, though.

detab, tolf, remove trailing whitespace

---

src/object.d
src/rt/typeinfo/ti_C.d
src/rt/typeinfo/ti_byte.d
src/rt/typeinfo/ti_cent.d
src/rt/typeinfo/ti_char.d
src/rt/typeinfo/ti_dchar.d
src/rt/typeinfo/ti_delegate.d
src/rt/typeinfo/ti_int.d
src/rt/typeinfo/ti_long.d
src/rt/typeinfo/ti_ptr.d
src/rt/typeinfo/ti_short.d
src/rt/typeinfo/ti_ubyte.d
src/rt/typeinfo/ti_ucent.d
src/rt/typeinfo/ti_uint.d
src/rt/typeinfo/ti_ulong.d
src/rt/typeinfo/ti_ushort.d
src/rt/typeinfo/ti_void.d
src/rt/typeinfo/ti_wchar.d

This is an alternative implementation for https://github.com/D-Programming-Language/druntime/pull/1306
It makes `TypeInfo.init()` abstract, and defers implementation to the derived classes.
**Motivation** (copied from https://github.com/D-Programming-Language/druntime/pull/1306 for convenience)
Per http://dlang.org/library/object/type_info.init.html (or the comment in the source):
>Return default initializer. If the type should be initialized to all zeros, an array with a null ptr and a length equal to the type size will be returned.
Currently it just returns null. I figure it would be best to fix this before someone starts building dependencies on the current (apparently) incorrect behavior.
This was brought to my attention by this thread: …

Modify TypeInfo.init to match the spec - Take 2 - Derived class implementation

---

posix.mak

- do not abuse MAKEFILES, it is a predefined variable in some versions of make
- make grep overloadable (grep installed with git on windows is too old to support -P)
- add -U to the command line, otherwise \r is not detected when run under windows

make checkwhitespace runnable on windows

---

src/core/internal/convert.d

Change unittest to ignore any pad bytes in a floating point type because
those bits are undefined. Fixes test part of ldc issue #788.
p.s. that's https://github.com/ldc-developers/ldc/issues/788

Ignore real pad in core.internal.convert unittest

---

mak/COPY
mak/DOCS
mak/MANIFEST
mak/SRCS
src/core/attribute.d
src/object.d
win32.mak
win64.mak

The runtime part of https://github.com/D-Programming-Language/dmd/pull/4321. This could be pulled before the DMD pull request and should not affect anything.

Add UDA for specifying selector for Objective-C methods.

---

posix.mak
test/common.mak
test/coverage/Makefile
test/exceptions/Makefile
test/init_fini/Makefile
test/shared/Makefile

- change druntime's makefile structure to match phobos
- define ROOT folder as generated/$(OS)/$(BUILD)/$(MODEL)
- unittest rule recursively invokes debug/release unittest
- factor out common.mak from test/*/Makefile and test debug/release
[Issue 11414 – druntime should run debug unittest](https://issues.dlang.org/show_bug.cgi?id=11414)

fix Issue 11414 - druntime should run debug unittest

---

posix.mak

The shared library unit tests are currently failing on FreeBSD when
they're built in debug mode, so this disables the recently added debug
unit test build so that the autotester passes again. The debug unit test
build should be re-enabled once the problem with FreeBSD is fixed.
https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=90669&dataid=625858
The release unit test build was failing on FreeBSD 9 and 10 already, but the autotester is on 8 still, where the release unit test build seems to pass, but it looks like they all fail the unit tests in the debug build (I've verified that with 10 and I assume that 9 does, since 8 clearly does given the failure on the autotester and the fact that 10 fails). It looks like the failing tests are all in the tests for shared library …

Disable debug build of unit tests.

---

src/core/atomic.d

Also removes private ``isHoistOp`` and ``isSinkOp`` templates.
@MartinNowak - we might be able to do away with the ``cmpxchg`` entirely given that load/stores on x86 should always have the desired semantics.

Make use of invalid MemoryOrder semantics a compile-time error

---

src/rt/dmain2.d

Windows:unhandled exception dump should not show dialog if stderr is redirected

---

src/core/internal/traits.d
src/object.d

https://issues.dlang.org/show_bug.cgi?id=14626
Until 2.065, compiler had substituted all inout qualifiers in the Key and Value types to const, then those had passed to the template struct AssociativeArray.
https://github.com/D-Programming-Language/dmd/blob/v2.065.0/src/mtype.c#L4897
This change emulates that.
Additionally add an overload of bykeyValue function for AA pointer types.

[REG2.066] Issue 14626 - byValue doesn't work with inout AA

---

src/object.d

https://github.com/D-Programming-Language/druntime/pull/1307 missed to implement abstract init functions for TypeInfo_Pointer, TypeInfo_AssociativeArray, TypeInfo_Function, TypeInfo_Delegate and TypeInfo_Interface

PR 1307: add missing overrides for TypeInfo.init

---

src/core/time.d

https://issues.dlang.org/show_bug.cgi?id=14863
I realized, MonoTime.currTime is already checking for 0 and asserting (and any use of 0 for ticksPerSecond will have a divide by zero error anyway), we should simply defer to that. I made a note in the code so people don't add the asserts back in later.
This still doesn't eliminate a segfault for anyone who actually *uses* CLOCK_BOOTTIME on an unsupported system, since assert(0) turns into halt statement, but that is really a separate issue.

Fix issue 14863 - CLOCK_BOOTTIME should be optional to support <2.6.39 kernels

---

src/core/demangle.d

I wonder how many more int=>string converters there are in druntime/phobos. There were two in demangle.
dmangle.d is worth attention because it is linked into every D executable. Also, it is rarely called, so performance is not an issue. But it needs to be as compact as possible.

core.dmangle: remove another custom int to string converter

---

posix.mak
src/rt/sections_elf_shared.d
test/shared/Makefile
test/shared/src/host.c
test/shared/src/lib.d
test/shared/src/link_mod_collision.d
test/shared/src/load_mod_collision.d

- add tests for module collision check
- fix copy relocation check so it can deal with
__bss_start/_end being defined in a DSO
- workaround FBSD bug ([Issue 14824](https://issues.dlang.org/show_bug.cgi?id=14824))
- reenable druntime-debug unittests

fix FBSD shared library issues

---

src/core/cpuid.d

maxCores for AMD is currently calculated using the theoretical maximum number of cores, not the actual enabled maximum number of cores.
This causes all bulldozer CPUs(and possibly others) to report the wrong value.
http://support.amd.com/TechDocs/25481.pdf
>The size of this field determines the maximum number of cores (MNC) that the processor could theoretically support, not the actual number of cores that are actually implemented or enabled on the processor, as indicated by CPUID Fn8000_0008_ECX[NC]. 
[issue](https://issues.dlang.org/show_bug.cgi?id=8973)

Issue 8973 - core.cpuid.coresPerCPU returning incorrect value. 

---

mak/COPY
src/core/sys/linux/fcntl.d
src/core/sys/posix/fcntl.d
win32.mak
win64.mak

This adds prototypes for posix_fallocate (which was present but commented out) and the linux-specific fallocate (http://man7.org/linux/man-pages/man2/fallocate.2.html).

Import fallocate in sys/linux/fcntl.d

---

mak/MANIFEST
mak/SRCS
src/core/stdc/stdio.d
src/core/sys/windows/stdio_msvc12.d
src/core/sys/windows/stdio_msvc14.d
src/rt/dmain2.d
win64.mak

This PR extracts internals of the VS runtime implementation of stdio into a separate module that can be implemented depending on the VS version.
This avoids having VS version specific conditionals in the public stdio module just leading to confusion when mixing prebuilt libraries with new code.
~~For now, this PR links the code for VS2013 or earlier versions, but the final version should put each module in a separate library. The compiler could then figure out what environment is used for linking and add the respective library to the link comand.~~
This PR works in combination with D-Programming-Language/dmd#4879 by the compiler selecting the appropriate object file for the version of the LIBCMT library that will be used by link.exe.

first support for VS2015

---

test/coverage/Makefile
test/coverage/src-basic.lst.exp
test/coverage/src-merge.lst.exp
test/coverage/src-merge_true.lst.exp
test/coverage/src/basic.d
test/coverage/src/merge.d
test/coverage/src/merge_true.d

- release and debug tests might run in parallel

output coverage reports to $(ROOT) to avoid test interference

---

win32.mak
win64.mak

- use C objs depending on MODEL so that we
never end up with the wrong obj file in a lib

fix -m32mscoff issue with errno_c.obj

---

src/core/stdc/stdio.d
src/rt/stdio_msvc.c

And add some comments about changed constants.

Visual Studio 2015: exploit C99-conformant (v)snprintf in core.stdc.stdio

---

src/rt/stdio_msvc.c

Alternate symbol name declarations need prefix "_" for Win32 builds.

Fix building for COFF32

---

mak/COPY
src/core/stdc/stdio.d
src/core/sys/linux/fcntl.d
src/core/sys/linux/unistd.d
win32.mak
win64.mak

Pull #1344 placed them with fallocate. While the three are often used in conjunction, SEEK_DATA and SEEK_HOLE should be placed with SEEK_SET, SEEK_CUR, and SEEK_END.

Place SEEK_DATA, SEEK_HOLE in core.sys.linux.unistd

---

src/rt/stdio_msvc.c

Stringizing operator ('#') adds extra quotes when used with string macro argument.
Causing commit: de0e1e10b4d88cc8e1657f326150f7565f4a9ef3, pull #1363.

Accept identifiers instead of strings in `DECLARE_ALTERNATE_NAME` macro.

---

src/core/demangle.d
src/rt/config.d

Removes an unnecessary function and an unnecessary reference to the GC. I've never encountered a C mangling method that did more than simply add a prefix. Having an abstraction for a possibility that will never happen is useless bloat.

replace mangleC with Cprefix

---

src/core/bitop.d

The original (D1) core.bitop module had both the 32 and 64 bits versions, but only the 32 bits version was added to druntime.
This commit contains the original tango code of bitswap(ulong), only slightly modified using feedback from the 32 bits version.
FYI @mihails-strasuns-sociomantic

Add core.bitopt.bitswap(ulong)

---

src/core/checkedint.d

This pull request fixes druntime [Issue #14785](https://issues.dlang.org/show_bug.cgi?id=14785).
```D
/** Test cases that fail without this PR **/
import core.checkedint;
void main(string[] args)
{
bool overflow = false;
assert(subs(-1L, long.min, overflow) == long.max);
assert(!overflow); // Assertion failure
overflow = false;
assert(muls(-1L, long.min, overflow) == long.min); // Floating Point Exception!
assert(overflow);
}
```

Fix Issue 14785 - Some corner cases are not handled properly by core.checkedint.

---

posix.mak

- fixes make CC=/path/to/cc
- fixes Issue 15012
[Issue 15012 – Druntime Makefile whitelists compilers](https://issues.dlang.org/show_bug.cgi?id=15012)

filter on basename of compilers

---

mak/COPY
mak/MANIFEST
mak/SRCS
src/core/internal/abort.d
src/core/internal/string.d
src/core/stdc/stdlib.d
src/core/time.d
win32.mak
win64.mak

See discussion here: http://forum.dlang.org/post/mpq93n$mh3$1@digitalmars.com
`abort(msg)` Will ALWAYS print msg, unlike `assert(0, msg)` which does not when compiled in -release mode. `abort` will eventually call `assert(0)`, so the end result is similar, but with a good message for debugging.
The only drawback is that `assert(0, msg)` is pure, but this function cannot be, since it has no mutable references as parameters or return, and the functions it calls to output the message are not pure.
So we can't replace all `assert(0, msg)` calls with `abort(msg)` (I had to leave out one case of `assert(0, msg)` in core.time because it was in a pure function).
In addition, the optimizer may not see that `abort(msg)` does not terminate, I'm not sure.
I have reworked core.time to use this …

Fix Issue 14870 Add new "abort" internal module and function

---

mak/SRCS
src/core/runtime.d
src/rt/backtrace/dwarf.d
src/rt/backtrace/elf.d
src/rt/util/container/common.d
test/exceptions/Makefile
test/exceptions/line_trace.exp
test/exceptions/src/line_trace.d

This work provides file and line info by reading the DWARF debug section `.debug_line` and resolving the stacktrace addresses.
Example stacktrace output on exception when program is compiled with `-g`:
```d
std.format.FormatException@/home/administrator/Projects/d-devel/phobos/std/format.d(487): Orphan format specifier: %s
----------------
/home/administrator/Projects/d-devel/phobos/std/exception.d:589 pure @safe bool std.exception.enforceEx!(std.format.FormatException).enforceEx!(bool).enforceEx(bool, lazy immutable(char)[], immutable(char)[], ulong) [0x4335b7]
/home/administrator/Projects/d-devel/phobos/std/format.d:487 pure @safe uint std.format.formattedWrite!(std.array.Appender!(immutable(char)[]).Appender, char).formattedWrite(std.array.Appender!(immutable(char)[]).Appender, …
```

Add file and line info to backtraces under Linux

---

.gitignore
test/.gitignore

For a reason, the content of the test folder is in the gitignore preventing people from adding or fixing tests.

Remove tests from .gitignore

---

test/exceptions/Makefile
test/profile/Makefile

See for instance, this test: https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=1739475&isPull=true
Output:
```
make[2]: Leaving directory `/home/braddr/sandbox/at-client/pull-1739475-Linux_32_64/druntime/test/exceptions'
make[2]: Entering directory `/home/braddr/sandbox/at-client/pull-1739475-Linux_32_64/druntime/test/profile'
Testing basic
Testing merge
Testing merge_true
make[2]: Leaving directory `/home/braddr/sandbox/at-client/pull-1739475-Linux_32_64/druntime/test/coverage'
make[2]: Entering directory `/home/braddr/sandbox/at-client/pull-1739475-Linux_32_64/druntime/test/profile'
Testing profile
make[2]: execvp: ./obj/linux/64/profile: Permission denied
make[2]: *** [obj/linux/64/profile.done] Error 127
make[2]: Leaving directory …
```

Fix tests for druntime so debug and release tests do not conflict if run in parallel

---

benchmark/gcbench/vdparser.extra/vdc/versions.d
src/core/sys/linux/sys/mman.d
src/core/sys/posix/sys/mman.d
src/core/sys/posix/sys/types.d

The 64-bit architecture is called System z since 2000.

Use new version identifier SystemZ instead of S390X.

---

src/core/thread.d
src/rt/deh_win32.d
src/rt/deh_win64_posix.d

https://issues.dlang.org/show_bug.cgi?id=15104

Fix Issue 15104 - Fiber context switch in finally blocks breaks EH

---

src/core/sys/linux/timerfd.d

I want to use this in a project... it appeared about the same time as epoll and has a similarly small header file so I just followed that and ported the C headers.

Header file for Linux-specific timerfd API

---

src/core/sys/posix/signal.d

They were aliases to private functions, which meant they never worked. This fixes https://issues.dlang.org/show_bug.cgi?id=15073

Bug 15073: statically-initialize SIGRTMIN/MAX

---

src/core/exception.d
src/gc/gc.d
src/rt/lifetime.d
test/exceptions/Makefile
test/exceptions/src/invalid_memory_operation.d

- creating a stacktrace currently uses the GC (thus might recurse
infinetely when the GC throws an exception itself)
- suppress stack traces for OutOfMemoryError,
InvalidMemoryOperationError, and FinalizeError
[Issue 14993 – Allocating in a destructor segfaults instead of throwing InvalidMemoryOperationError](https://issues.dlang.org/show_bug.cgi?id=14993)

fix Issue 14993 - segfault for InvalidMemoryOperationError

---

src/core/cpuid.d

Doc formatting fixes needed for https://github.com/D-Programming-Language/dmd/pull/4745

Doc formatting fixes for DMD PR 4745

---

src/core/sys/windows/ntsecpkg.d

`core.sys.windows.winnt` privately imports `core.sys.windows.basetyps`, so `GUID` is not selective though `basetyps` module.
Required by: https://github.com/D-Programming-Language/dmd/pull/3416

Fix imports

---

src/rt/dmain2.d
test/exceptions/line_trace.exp

https://issues.dlang.org/show_bug.cgi?id=14327
stdin,stdout,stderr handles are only initialized when running d_run_main, but not rt_init.

issue 14327: move call to init_msvc() into rt_init()

---

src/core/exception.d
src/core/thread.d

- fix a deadlock caused by lock order inversion
- must not use the GC while holding slock

fix Issue 15268 - deadlock for Thread.getAll/Thread.opApply

---

src/core/thread.d

- as signals are no longer send during thread startup we can use
a TLS variable to store Thread.getThis()
- make sure to set the variable (and probably trigger lazy TLS
allocation) before adding the Thread to the global list
[Issue 15270 – use TLS to store Thread.getThis (pthread_getspecific causes heavy lock contention)](https://issues.dlang.org/show_bug.cgi?id=15270)

fix Issue 15270 - use TLS to store Thread.getThis

---

src/core/stdc/string.d

Required to compile Phobos on OpenSolaris.

Add strerror_r() for OpenSolaris.

---

mak/COPY
mak/MANIFEST
src/core/sys/posix/time.d
src/core/sys/solaris/time.d
src/core/time.d
win32.mak
win64.mak

Required to compile druntime on OpenSolaris 11.2.

Add clock definitions for Solaris.

---

src/core/sys/windows/windef.d

These are not part of the Windows API and will just conflict with the std.algorithm ones.

core.sys.windows.windef: Remove min/max functions

---

src/core/thread.d

- heavily reduce suspendAll time with many threads by signalling all N
threads in parallel and then waiting N times for the semaphore rather
than doing that serially
- won't improve anything on OSX/Windows which do use a synchronous
suspend API

suspend threads in parallel

---

mak/COPY
mak/MANIFEST
src/core/sys/linux/sys/socket.d
src/core/sys/posix/sys/socket.d
win32.mak
win64.mak

See title.  Pretty simple and self-explanatory.

Add constants AF_RXRPC and PF_RXRPC on Linux

---

src/core/time.d

Fix for https://issues.dlang.org/show_bug.cgi?id=15334
The `_d_initMonoTime()` `version(OSX)` calculation for ticksPerSecond is using a flipped mach_timebase_info ratio numer/denom when it should be denom/numer.
This is a redo of #1430 on stable per @schveiguy with some of his suggestions.

Fix issue 15334 - OS X core.time ticksPerSecond calculation is incorrect

---

src/object.d

DDSUBLINK uses ROOT_DIR which is more robust than a relative path.
Together with https://github.com/D-Programming-Language/dlang.org/pull/1159 this fixes the link in the online DDox docs.

use DDSUBLINK instead of LINK2

---

src/core/stdc/config.d

We need this in LDC too; I guess GDC and SDC too (if they support `version(CRuntime_Microsoft)` at all).

Use __c_long_double for CRuntime_Microsoft in general, not just DMD

---

src/rt/msvc.c
src/rt/msvc_math.c
win64.mak

The x86 runtime lacks most *f versions (asinf(), acosf() etc.), i.e., they are only inline-declared in the C headers (and use the 64-bit double version).
The available symbols apparently depend upon whether one's linking against the static or dynamic MS runtime (libcmt.lib vs. msvcrt.lib), and possibly upon the Visual Studio version too.
So provide alternate implementations here in druntime to prevent linker errors. I came up with these 19 missing functions about a year ago by inspecting the VS 2013 headers (these should be all inline-declared ones, iirc).
Pinging @rainers.

MSVC: Provide alternate implementations for 32-bit math functions

---

src/object.d

Having `msg` as a user accessible field turns out to make customized exceptions more difficult than they should be. Turning it into a property function can break existing code. So added an overridable `message` function instead, and undocumented `msg`.

Add message() to object.Throwable

---

win32.mak
win64.mak

- build minit.obj explicitly
- fixes sporadic build failures caused by different timestamps after
checkout
- requires to explicitly rebuild minit.obj, but we haven't touched the
asm code since ages

fix nightly builds

---

src/object.d

https://issues.dlang.org/show_bug.cgi?id=15434

Fixes #15434: object.d must not import from rt

---

src/core/thread.d
src/rt/dwarfeh.d

Added function needed to swap contexts for fibers. For transitional porpoises, support both old and new eh functionality at the same time, detect which at runtime.
This is blocking https://github.com/D-Programming-Language/dmd/pull/5324

Dwarf EH: add _d_eh_swapContextDwarf

---

src/test_runner.d

Because when a test crashes, I have no idea which one it was, because the logging only logs upon completion.

add indication of which test is being started

---

src/core/sys/posix/unistd.d

- Add F_ULOCK/F_LOCK/F_TLOCK/F_TEST
- Comment out duplicate definitions of lockf(), pread(), pwrite(), truncate()

Fix core.sys.posix.unistd for OpenSolaris.

---

mak/COPY
mak/MANIFEST
mak/SRCS

The druntime build system is error-prone. Having to duplicate the file names over so many places when it really should just do something like *.d means these things are forgotten and almost slip by the beta unnoticed!
Without this, the file is never copied from src/ over to import/ (why does it even use separate folders for that anyway? pointless waste of time), nor is the init blob included in the object file, meaning the structs need to be void initialized to avoid linker errors! (I noticed that with epoll too and shoved its line in here too.)
I recommend these makefiles be rewritten. I knew the Windows one was laughably bad, but I didn't realize the posix one made many of the same mistakes. But until then, this keeps my new addition from being broken on new installs.

forgot to add timerfd to the makefile

---

src/core/bitop.d

This PR adds `ulong` versions of `bsf()`, `bsr()`, and `popcnt()`. (It also fixes a small error in the `_popcnt()` docs.)
I use these `core.bitop` functions fairly often, and am always annoyed that the maximum bit-ness of the input depends on what architecture I'm compiling for; it makes using these ops from generic code painful.
There is no good reason for this, as even on 32-bit systems the 64-bit op can be trivially implemented in terms of a couple of calls to the 32-bit op.
**EDIT:** I have created a [companion PR for Phobos](https://github.com/D-Programming-Language/phobos/pull/3888). While working on it, I discovered two different private implementations of `bsr()` for `ulong`, one of which is bugged.

Add bsf(ulong), bsr(ulong), and popcnt(ulong).

---

src/rt/dwarfeh.d

Requires:
https://github.com/D-Programming-Language/dmd/pull/5342

Add catching C++ exception support to dwarfeh.d

---

src/rt/dwarfeh.d

because having Dwarf register numbers line up with the CPU register numbers wouldn't make any sense (!)

dwarfeh: EDX and RDX are different register numbers for dwarf

---

src/rt/arraycast.d

In web servers and crypto, there is frequent back-and-forth casting between ubyte[] and string. This created a bottleneck where perf gave this function a 7% sampling prevalence. After this optimization, it went down <1%.

Optimize array cast for equivalence

---

test/shared/src/finalize.d

The call to `unloadLibrary()` should not be in an assert, because when compiled with `-release` it gets elided.
This appears to be blocking https://github.com/D-Programming-Language/dmd/pull/5359 so please pull.

essential code should not be in assert's

---

posix.mak

When the makefile fails, like it does here:
https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=1929728&isPull=true
it's really hard to figure out what was being executed when it went wrong when in quiet mode. I have no idea where this desire to hide what commands are being executed comes from.

There's no reason to hide what the makefile is doing

---

changelog.dd
src/object.d
src/rt/aaA.d

This is a reworking of #999 using new AA implementation.
Note, clear has been gone as a deprecated alias since [March 2015](https://github.com/D-Programming-Language/druntime/commit/fa624c472f2357e375d3b52eaa473dad709c725a).
I also changed firstUsed cache code to be more accurate.
@MartinNowak, I'm curious why you keep a running total of deleted elements (and flag them differently)? What purpose does this serve? It seems to make the code more complex than it needs to be.

Add ability to clear AA of all elements

---

src/core/bitop.d

Adds functions for a bitwise rotate left and rotate right operation. This operation is common enough that some architectures such as x86 have it as its own instruction; while many compilers will detect the used pattern and optimise it down to one instruction, some compilers (e.g. DMD) won't do so, in which case having this as a part of druntime allows for one hand-written assembly implementation later on.
The choice of `uint` as the type for the number of shifts is a bit arbitrary; any unsigned integer type would do, as the number of places to shift is usually fairly small (and wraps at `T.sizeof` anyway).

core.bitops: Add bitwise rotate functions

---

src/gc/gc.d

druntime is compiled with -inline by default, so it's needlessly limited by the compiler's inlining capability. Removing it would have no problem.
From: https://github.com/D-Programming-Language/druntime/pull/1491#issuecomment-181357376

Remove pragma(inline, true) in runLocked function template.

---

mak/COPY
src/core/stdcpp/exception.d
src/core/stdcpp/typeinfo.d
win32.mak
win64.mak

add core.stdcpp.exception and core.stdcpp.typeinfo

---

src/gc/gc.d
src/gc/pooltable.d

There are some low-hanging micro optimizations for the GC.
This is an average 24.7% reduction in running time for the mark phase on my test-case. The speed up should translate well for other cases as it just improves the throughput by minimizing branching and inlining the pool search.
This is my test program:
```d
import core.memory;
enum Prime = cast(uint)3147655439;
void main() {
uint start = 1000;
void* lptr = null;
GC.collect();
foreach (i; 0.. 2_000_000) {
auto size = cast(uint)(start++ * Prime) % (8 << 10);
if (size < 8) size = 8;
auto ptr = GC.malloc(size);
if (lptr) *cast(void**)lptr = ptr;
lptr = ptr;
}
lptr = null;
GC.collect();
}
```
Timings were computed over 20 runs of this program with and without the patch, passing `"--DRT-gcopt=profile:1"` and recording the mark phase …

Optimize GC mark phase implementation

---

src/core/stdc/math.d
src/core/sys/linux/config.d
src/core/sys/posix/arpa/inet.d
src/core/sys/posix/grp.d
src/core/sys/posix/netinet/in_.d
src/core/sys/posix/netinet/tcp.d
src/core/sys/posix/pthread.d
src/core/sys/posix/sched.d
src/core/sys/posix/semaphore.d
src/core/sys/posix/signal.d
src/core/sys/posix/stdlib.d
src/core/sys/posix/sys/mman.d
src/core/sys/posix/time.d
src/core/sys/posix/unistd.d
src/core/sys/posix/utime.d
src/rt/backtrace/dwarf.d
src/rt/sections_android.d

Pull in some necessary declarations from bionic, exclude some `CRuntime_Glibc` definitions, add ARM support extracted from my work with ldc, and replace all uses of `Android` with `CRuntime_Bionic` or `linux`.

Android update

---

src/core/sys/bionic/fcntl.d
src/core/sys/bionic/unistd.d
src/core/sys/posix/fcntl.d
src/core/sys/posix/unistd.d
src/rt/cover.d
src/rt/sections_android.d
src/rt/sections_solaris.d

The recently-merged support for linker-generated section brackets (#1379) causes a segfault on Android, when `rt_term` tries to free module info that is no longer malloced.  I'm guessing it broke for Solaris too, though I haven't tested it.  This PR seems to fix it- all druntime and phobos tests on Android/x86 and linux/x86 pass locally- let me know if any further tweaks are necessary.

Properly free module info when using linker-generated section brackets

---

src/core/sys/linux/epoll.d

X86 is the only architecture where epoll_event is actually packed. All other architectures define epoll_event as a normal struct:
http://code.metager.de/source/search?q=__EPOLL_PACKED&path=%2Fgnu%2Fglibc%2F&project=gnu
See also: http://bugzilla.gdcproject.org/show_bug.cgi?id=214

Fix epoll_event for non-X86 architectures

---

src/core/sys/linux/epoll.d

These are most of the missing definitions. I don't have the MIPS and SPARC
definitions at hand.

Add missing epoll_event structures.

---

mak/COPY
mak/SRCS
src/core/exception.d
src/core/internal/spinlock.d
src/core/memory.d
src/core/runtime.d
src/core/thread.d
src/gc/gc.d
src/gc/proxy.d
src/gcstub/gc.d
win32.mak
win64.mak

- less overhead than pthread_mutex
- uses test and test-and-set algorithm with configurable backoff
Had to reopen [spinlock for GC by MartinNowak · Pull Request #1153](https://github.com/D-Programming-Language/druntime/pull/1153) after force pushing, please look the existing review before repeating any questions.

spinlock for GC

---

posix.mak
test/common.mak
test/exceptions/Makefile
test/init_fini/Makefile
test/profile/Makefile
test/shared/Makefile

- restrict any test to 10s
- don't trigger the 1h timeout for the auto-tester
- get a make error message w/ a specific test on timeout failure
- the timelimit program is used b/c the auto-tester already relies on it

use timelimit to kill deadlocked tests

---

src/test_runner.d

- we now have make non-quiet by default and apply timelimit
to each test so it's easy to figure out deadlocked tests
- with parallel make it wasn't easily possible to see which
STARTING/PASS lines belong together anyhow

remove the pointless STARTING output during testing

---

src/core/sys/posix/dirent.d
src/core/sys/posix/sys/stat.d
src/core/sys/posix/sys/types.d

This updates the stat and dirent family of types and functions (dirent.h and sys/stat.h) to use the newer 64-bit inode versions.  These functions are the default for C compiled code on OS X > 10.5 and provide extra fields and longer filenames.
This also removes the 32-bit inode versions as I believe they are intended for compatibility with binaries build pre 64-bit inode OS X.  I would think all new code should use 64-bit inode versions.
But just in case that isn't preferred, I do have two other versions of this PR that allows:
- selection of 64-bit or 32-bit, configurable at compile time, or
- both 64-bit and 32-bit coexist, where 32-bit is selected by `import core.sys.osx.sys.stat_ino32`

OS X - Use 64-bit inode stat and dirent functions

---

src/core/math.d

core.math: Add unit test for 128bit reals.

---

changelog.dd
src/gc/gc.d

- use separate locks for GC.add/removeRange/Root
- avoids GC.lock contention for manual memory management

fix Issue 15822 - InvalidMemoryOperationError when calling GC.removeRange/Root from a finalizer

---

mak/SRCS
posix.mak
src/rt/osx_tls.c
src/rt/sections.d
src/rt/sections_osx_x86.d
src/rt/sections_osx_x86_64.d

Runtime part of https://github.com/D-Programming-Language/dmd/pull/5346.

Add support for native TLS on OS X

---

src/gc/gc.d

The condition should have been `if (npools > 1)` but I removed it because we should not optimize for the unlikely state that the application is using less than 1MB of memory. Instead this improves the situation when more moemory is used and scan speed matters more.

GC: remove condition that is never false

---

src/core/math.d

This PR adds a unit test for the `ldexp()` function using the IBM
extended (double double) format. This format uses two doubles.
The exponent range is the same as the one of the double type.

core.math: Add unit test for ldexp()

---

mak/SRCS
src/rt/typeinfo/ti_n.d

Add `TypeInfo_n` for `typeid(typeof(null))`.
Needs to be merged before dmd codegen fix #5459.

Issue 15680 - TypeInfo broken for typeof(null)

---

src/core/sys/posix/fcntl.d
src/core/sys/posix/sys/stat.d

For https://github.com/D-Programming-Language/phobos/pull/4089
Linux only for now.
FreeBSD will support it in the next major release:
https://github.com/freebsd/freebsd/commit/67db24d0f2b81a222335fe5bb13977ef0c2258a9
Solaris seems to support it according to their documentation, but I can't test it or get the constant values.

Add POSIX.1-2008 utimensat/futimens

---

src/gc/gc.d

report out-of-memory for allocation a bit below size_t.max
even though reported as a regression, this doesn't seem like anything new, so it might not be necessary to merge into stable.

Fix Issue 1180 - the GC failes to handle large allocation requests propperly 

---

src/rt/arrayassign.d
src/rt/arraybyte.d
src/rt/arraycast.d
src/rt/arraycat.d
src/rt/arraydouble.d
src/rt/arrayfloat.d
src/rt/arrayint.d
src/rt/arrayreal.d
src/rt/arrayshort.d

All were missing `Source:` tags, removed redundant text.
All are subtly different in terms of Author, Copyright date, Source link, and description. Please double check for any copy/pasta errors!

fix Ddoc header comments in rt.array*

---

src/rt/tlsgc.d

When the memory is limited for the process, malloc fails, and data is null. Hence, it creates Segmentation Fault by trying to write a null pointer.

If malloc fails, prevent getting Segmentation Fault

---

src/core/sys/windows/msacm.d

modified constants for the buffer sizes used from some structs,
whiche have been pseudo value(256).

Fix Issue 15987 - core.sys.windows.msacm remains pseudo definitions

---

src/core/sys/windows/iptypes.d
src/core/sys/windows/winldap.d

I realized that there were still two imports to Tango in our codebase. I assume they ended up by mistake?

remove old tango imports

---

src/core/stdc/stdio.d
src/core/stdc/wchar_.d

Fix stdio issue for x64 Solaris (SmartOS x64) by add correct struct _iobuf.

Solaris: fix stdio issue for x64 OS.

---

src/core/sys/windows/commctrl.d

This removes all usage of the comma expression in D runtime.
One of the commit is a bug fix, the second one should be no-ops.
The only useful pattern I could find for `CommaExp` is within `for` loops, however the cost/benefit ratio is too damn low to justify it.
Ideally we should have a way to do it in a more D-ish maner, e.g. `for (; i < j; { i++; j-- })` however this isn't currently inlined in `-O -inline` by DMD, so I do not want to introduce such a syntax ATM.
About the changes: If the condition is dependent on both the post-loop operations, I moved them together to make it more readable (see the `for` -> `while` change for example).

Remove usage of CommaExp

---

src/core/sys/posix/dirent.d

In x64 OS not present readdir64.

Solaris: fix readdir for x64 OS.

---

src/core/sys/windows/mswsock.d
src/core/sys/windows/nspapi.d
src/core/sys/windows/windows.d

Hey guys,
_Disclaimer_: I don't know much about druntime & windows.
However I saw a couple of missing imports showing up to "winsock.d", which I couldn't find in the sources.
I couldn't find much about the history, but I assume that winsock2.d replaced it?
Don't hesitate to close, if I am wrong ;-)

cleanup remaining imports to removed winsock

---

src/core/sys/windows/dll.d
src/core/sys/windows/mswsock.d
src/core/sys/windows/objbase.d
src/core/sys/windows/objidl.d
src/core/sys/windows/winbase.d

These are simple replaces,
which are required by x64 Win32 programs.
Mostly in this form:
DWORD/int/uint/ULONG -> SIZE_T
This should make no change in x86 programs.

More fix of issue 15959 (size_t)

---

src/object.d
src/rt/util/utf.d

WIKI is no longer used
> These tags are back from the days when the official D wiki was http://www.prowiki.org/wiki4d/wiki.cgi.
See also
https://github.com/dlang/phobos/pull/4369
https://github.com/dlang/dlang.org/pull/1310

remove the deprecated wiki macros

---

posix.mak

Since the update to use native TLS on OS X the minimum deployment
target is now OS X Lion (10.7).

Set deployment target to the minimum supported version of OS X

---

src/core/time.d

As has been done in phobos: <https://github.com/dlang/phobos/pull/4364>.
Done by:
sed -i -r 's/\$\(XREF\s+([^(),]*),\s*([^(),]*)\)/$(REF \2, std,\1)/g' \
src/core/time.d
Confirmed that there are no other instances of XREF with `grep -r '$(XREF'`
(no hits).

Ddoc: Replace XREF with REF

---

src/core/sys/linux/sys/inotify.d

This typo seems to be D specific, coming all the way from Tango:
https://www.google.com/search?q=%22IN_UMOUNT%22

core.sys.linux.sys.inotify: Fix typo in identifier

---

mak/DOCS
posix.mak

Turns out that for every page in Phobos, C++ is listed on the menu, but the HTML docs never get generated.

fix C++ documentation

---

changelog.dd
src/core/memory.d
src/core/time.d

This removes the last traces of XREF from druntime.
Be aware that removing the macros from changelog.dd may be controversial. I suggest to discuss this in a central place over at phobos: https://github.com/dlang/phobos/pull/4404

XREF purge: CXREF, custom SXREF, changelog.dd

---

src/core/sys/windows/basetsd.d
src/core/sys/windows/commctrl.d
src/core/sys/windows/commdlg.d
src/core/sys/windows/cpl.d
src/core/sys/windows/mmsystem.d
src/core/sys/windows/msacm.d
src/core/sys/windows/nb30.d
src/core/sys/windows/ras.d
src/core/sys/windows/rasdlg.d
src/core/sys/windows/richedit.d
src/core/sys/windows/richole.d
src/core/sys/windows/setupapi.d
src/core/sys/windows/shellapi.d
src/core/sys/windows/shlobj.d
src/core/sys/windows/snmp.d
src/core/sys/windows/winhttp.d
src/core/sys/windows/winldap.d
src/core/sys/windows/winnt.d
src/core/sys/windows/winuser.d

https://issues.dlang.org/show_bug.cgi?id=16049
A set of small fixes of Win32 structs.
- Add/Remove align specifiers
- Paddings under some conditions
- Helper macro 'AlignedStr' to switch alignment between x64/x86 environment
I detect and verify these correct sizes by  comparing with ones of Windows SDK in MSVC.

Fix issue 16049 - core.sys.windows structs have wrong sizes and aligns

---

src/object.d

Can't think of a reason why `capacity()` shouldn't be trusted.

fix Issue 6333 - The 'capacity' function is not pure/nothrow/@safe

---

src/core/internal/string.d
src/rt/util/array.d

array.ptr is no longer considered @safe 
Needed for https://github.com/dlang/dmd/pull/5860

fix unsafe .ptr accesses in druntime

---

src/rt/util/hash.d

When this gets pulled, all users of hashOf() need to be changed, and the old way deprecated.

[critical] change hashOf() to safe interface

---

src/object.d
src/rt/typeinfo/ti_Ag.d
src/rt/typeinfo/ti_Aint.d
src/rt/typeinfo/ti_Along.d
src/rt/typeinfo/ti_Ashort.d
src/rt/typeinfo/ti_cent.d
src/rt/typeinfo/ti_delegate.d
src/rt/typeinfo/ti_long.d
src/rt/typeinfo/ti_ucent.d
src/rt/typeinfo/ti_ulong.d
src/rt/util/container/hashtab.d
src/rt/util/hash.d
src/rt/util/typeinfo.d

Because the array interface is safer.

use array interface to hashOf()

---

src/rt/typeinfo/ti_ulong.d
src/rt/util/hash.d

1. remove the old unsafe interface
2. remove default argument so it won't cause any more bugs
3. add decent unittest

remove old hashOf overload

---

src/rt/util/utf.d

Trivial. Just added annotations that the compiler would pass.

rt.util.utf: add attributes

---

mak/COPY
src/core/sys/linux/elf.d
src/core/sys/linux/sys/auxv.d
win32.mak
win64.mak

This header file provides access to the auxiliary vector. It was added
to glibc version 2.16. See https://lwn.net/Articles/519085/ for some
background information.
Also adds the missing AT_HWCAP2 index to the elf module.

Add new module for Linux header file sys/auxv.

---

src/rt/util/utf.d

Slicing a ref static array is equivalent to taking the address of a ref, which is not allowed in safe code.

rt.util.utf: remove 'return'

---

src/core/threadasm.S
src/rt/minit.asm

Sister-PR to https://github.com/dlang/phobos/pull/4411 (see that for the reasoning).
It basically just touches the license links to the Boost license - speaking of which: shouldn't we link to our own copy at https://github.com/dlang/druntime/blob/master/LICENSE?

Fix broken WEB links

---

src/gc/config.d
src/gc/proxy.d
test/exceptions/Makefile
test/exceptions/src/unknown_gc.d

- would match more than just an identifier, e.g.
'gc:conservative profile:1' was parsed as gc='conservative profile:1'
- was restricted to known GC names, instead we now check
that one GC was initialized
- parse const(char)[] arguments as simple identifier [_a-zA-Z][_a-zA-Z0-9]*

fix --DRT-gcopt string argument parsing

---

src/rt/util/utf.d

Blocking https://github.com/dlang/dmd/pull/5860

utf.d: use safe construct for .ptr instead

---

src/core/time.d

blocks https://github.com/dlang/dmd/pull/5860

core.time.d: fix unsafe use of .ptr

---

src/core/stdc/stdint.d

This is a better approach than just commenting out the lines.

Enable uint128_t/int128_t if ucent/cent type is implemented.

---

.travis.yml
posix.mak
src/test_runner.d

I copied the `.travis.yml` from Phobos over and kept the code style bits. For the simple style checks there exist regexes that can be applied in future work, see e.g. https://github.com/dlang/phobos/pull/4385 and enabling Dscanner is also an open task (volunteers wanted!).
- coverage of the separate `test` files isn't included at the moment. While it is possible to set the coverage directory with `dmd_coverDestPath`, a global way to set the coverage destination dir is missing. Maybe we can add a CLI flag to DMD and modify the `common.mak` or has anyone a better idea?
- coverage for 32-bit - can we simply run with `-m32` on Travis?
- coverage for more platforms ([codecov-bash](https://github.com/codecov/codecov-bash) should be run on the AutoTester too)
edit: a preview of the coverage view …

Enable coverage statistics

---

src/core/internal/hash.d

See <http://forum.dlang.org/post/gmeowrdivjpjhezbdror@forum.dlang.org>.
By the way, `bytesHash` should not be `@trusted`. It takes pointer and length separately.

add @nogc to bytesHash

---

src/core/internal/hash.d

Blocking https://github.com/dlang/dmd/pull/5860

hash.d: make .ptr @safe

---

src/core/internal/hash.d

The default argument is also a bad idea.

@trusted function is really @system

---

src/test_runner.d

There is a weird case with `std.stdio` where `doTest` is called 4x and for the first three times currently without the merge flag been set.
This is a simple fix that just moves the setting of the merge flag in the static constructor, however if someone wants to look deeper into this, here's a strip down version of the `test_runner`.
```d
import core.runtime, core.time : MonoTime;
import core.stdc.stdio;
ModuleInfo* getModuleInfo(string name)
{
foreach (m; ModuleInfo)
if (m.name == name) return m;
assert(0, "module '"~name~"' not found");
}
bool testModules()
{
printf("testModules\n");
doTest(getModuleInfo(Runtime.args[1]));
return true;
}
void doTest(ModuleInfo* moduleInfo)
{
if (auto fp = moduleInfo.unitTest)
{
printf("fp");
fp();
}
}
shared static this()
{
Runtime.moduleUnitTester = …
```

Fix test coverage merging with the test_runner

---

src/core/stdc/math.d

These constants are actually architecture dependent:
http://osxr.org:8080/glibc/ident?v=glibc-2.19&_i=FP_ILOGBNAN

Fix FP_ILOGB constants for GlibC and non-X86

---

src/object.d

Ddoc interprets multiple /// comments as multiple paragraphs. That's not
wanted in these cases.
Exemplary before/after shot:

[Ddoc] replace multiline /// comments with /** */ ones

---

src/object.d

The Static array typeinfo only returns an initializer for a single element. This documents that behavior.

Fix issue 16394 -- document the intializer function behavior correctly.

---

src/core/stdcpp/typeinfo.d
src/core/sys/posix/sys/msg.d

C array declaration syntax is deprecated.

refactor: replace C array syntax with D array

---

src/core/sys/linux/sys/auxv.d

The constants are well hidden in glibc. :-(
Adds the constants for ARM, AArch64 and SystemZ.

Add more HWCAP_* constants to auxv.d

---

src/object.d

This change simplifies the function signature of __ctfeWrite and __ctfeWriteln.
This is beneficial for the compiler implementation.
For context see:  https://github.com/dlang/dmd/pull/6101

[blocks __ctfeWriteln]change __ctfeWrite/ln to a signature which is easier to support

---

src/rt/util/container/array.d

This was quite useful for debugging a memory corruption issue.

util.container.array: Add invariant for _ptr/_length

---

src/core/sys/posix/time.d

https://issues.dlang.org/show_bug.cgi?id=15088

Bug 15088: timer_t should be void* on glibc

---

src/rt/util/container/array.d
src/rt/util/container/common.d

Array and HashTab are used before the GC is even initialised.

rt.util.container: Use outOfMemoryErrorNoGC

---

src/rt/sections_elf_shared.d

finiTLSRanges() is called from the destructor of core.Thread. At this point,
the OS thread has already ceased to exist, so what was formerly a pointer
to _loadedDSOs is no longer valid.
In other words, `tdsos.reset()` was a use-after-free bug. It is unclear why
the issue didn't surface on Linux/FreeBSD yet; for example, glibc might not
actually re-use the TLS address range after a thread exits. On OS X, however,
this did quite frequently trigger a crash when running the Phobos unit tests,
since `tdsos` would have already been overwritten with unrelated contents.
@MartinNowak

sections_elf_shared: Do not access TLS of dead thread in finiTLSRanges()

---

test/shared/Makefile

--no-as-needed/--export-dynamic are neither known nor required on OS X.

test/shared: Only use ELF-specific linker flags on Linux/FreeBSD

---

src/object.d

see: https://github.com/dlang/dlang.org/pull/1441

[docs] default opEquals does not compare object contents

---

src/core/sys/windows/errorrep.d
src/core/sys/windows/lmmsg.d

This feature will hopefully be deprecated soon.

[TRIVIAL] Remove use of implicit string concatenation

---

src/rt/aaA.d

There's one test in `rt.aaA` which uses a completely empty struct as the key for an associative array. According to the D spec, such a struct has a size of 1 byte. But I don't think we ever defined that such a struct must have a certain, fixed value (e.g. always 0). In GDC the value of such a struct is currently undefined and therefore the generated hashes for such a struct vary.
Modifying GDC to always treat these structs as a 1-byte '0' seems to be difficult. If we add a fake internal field to the struct for the GCC backend this messes up the C++ ABI for these structs. And GCC generally doesn't copy padding between fields, so unless we somehow add such a field to the struct the GCC backend will sometimes fill these structs with random data.
See …

rt.aaA: Do not use a struct without fields as AA index in unittest

---

src/rt/sections_elf_shared.d

Not needed since druntime switched to Dwarf exception handling tables.

remove EH table support - no longer used

---

src/core/runtime.d

Fixup pull #1656 to assign `Runtime.moduleUnitTester` only once.

Fixup pull #1656 to assign unittester only once.

---

src/rt/dmain2.d
test/exceptions/Makefile
test/exceptions/src/static_dtor.d

- must call finiSections when an exception is thrown in a destructor
- marks runtime as shut down, so final unloading
of executable doesn't try to run module dtors again

fix Issue 16594 - static dtors called twice w/ exception

---

posix.mak
src/rt/minfo.d
test/cycles/Makefile
test/cycles/src/mod1.d
test/cycles/src/mod2.d
test/cycles/src/mod3.d

Changes in this:
1. Allow ignoring/just printing of cycles
2. Remove all GC usage except when throwing an exception.
3. Because edges are needed every time we print a cycle, I'm mallocing them at the beginning, and only use the hashtable there (findModule goes away).
~~NOTE: I have NOT tested this properly, because I cannot build dmd on MacOS, see https://issues.dlang.org/show_bug.cgi?id=16536. I'd like to add tests for the switches, but I'm not sure how to do this, especially since I cannot build. I'm throwing this in the mix to at least test the default functionality.~~
I will add a changelog once this is more solid.
Update: Was able to download binary of MacOS dmd and run unit tests.

Allow configuration of cycle detection via command line parameters.

---

changelog.dd

Even though both of these items are from the same pull request, I chose to address them individually because of the manual GC implementation was added.
Let me know if anything is not in order or if I should change anything. I didn't see anything in CONTRIBUTING.md on change log style.

Updated changelog to reflect #1581

---

src/core/threadasm.S

The threadASM code requires a vfp or newer unit for the vpush and vpop instructions. There's exaclty one older floating point ARM unit: The fpa unit. This unit is not supported in GCC but it is
supported in binutils.
This causes the following problem: When GCC is not explicitly configured with --with-fpu it will not pass fpu flags to binutils as. So binutils will use the binutils standard mode which is fpa! This then causes compilation errors.
So in the end even though the gcc preprocessor claims vfp support via __ARM_PCS_VFP we still have to request vfp explicitly in the ASM.
Note that this is not a restriction: As GCC doesn't support FPA we can't compile phobos in FPA mode anyway. Newer floating point units are fully compatible with vfp, so we can specify .fpu vfp
and still compile …

ARM: Explicitly specify required FPU mode in Fiber ASM

---

src/core/sys/posix/sys/select.d

This fixes it so that the FD_* functions (which are macros in C/C++) are
pure on POSIX systems. The Windows versions (in
core.sys.windows.winsock2) are already pure.

Make FD_* functions for select pure.

---

src/core/time.d

Fix conflict with other `copy` functions when user programs are built with `-unittest`.
CC @jmdavis

[trivial] core.time: Make private helper private

---

src/object.d

This reverts commit 35cd63567095bf865e0c7b4bb8bb92945b6244a5, reversing
changes made to aee373fb541dafce2769792b4430be82ef25bd2b.
- fixes Issue 16504 - dup can't use storage class scope for its parameter in general
Original PR #1637

Revert "Merge pull request #1637 from WalterBright/scope-dup"

---

src/core/stdc/stdlib.d
src/core/sys/posix/stdlib.d

In response to https://github.com/dlang/dmd/pull/6197
Why does the FreeBSD_32 target fail?

Qualify C-style memory allocation functions as pure

---

src/object.d

I noticed this when I attempted to run unittests for a module in which I defined a method called `isnan` and received a conflicts-with error. This method should definitely not be public.

Added private qualifier to one-off unittest helper isnan in object.d

---

src/core/time.d

I haven't tried it in production yet so unable to confirm if this is the only fix that is needed.
It do contains an additional check for negative time which I've also observed.

fix issue 16797 - Zero clock resolution lead to division by zero

---

src/rt/dmain2.d

This converts an exception message to the active codepage when writing to the Windows console.
- used for writes to the console window only. Output to pipe is not affected.
- works around [bug 1448](https://issues.dlang.org/show_bug.cgi?id=1448) for exception messages
- generally recommended practice of just using codepage 65001 is not enough, as it depends on a user setting outside the scope of program and there are some other bugs with UTF8 output.
I'd like to eventually propose something similar for stdio.
A question to debate is whether to convert an output to pipe too. It would make the following work correctly in any codepage:
`prog 2>&1 | find "error"`

Convert exception message to Windows console codepage

---

src/rt/dmain2.d

This corrects a wrong length used in #1687. Sorry for the mess-up.
Ping @rainers.

Fixup PR #1687 - wrong buffer length used

---

src/object.d

Solves issues 16654 & 16764.
See: https://github.com/dlang/druntime/pull/1595#r67473386
Issue links: [16654](https://issues.dlang.org/show_bug.cgi?id=16654) and [16764](https://issues.dlang.org/show_bug.cgi?id=16764)

[REG 2.072] Revert object.hashOf changes from "use array interface to hashOf()"

---

src/rt/lifetime.d

Appending an invalid UTF8 character now throws a UnicodeException:
core.exception.UnicodeException@src/rt/lifetime.d(2031): Invalid UTF-8 sequence
https://issues.dlang.org/show_bug.cgi?id=5995

fix issue 5995 - string append negative integer causes segfault

---

mak/COPY
src/core/sys/linux/sys/netinet/tcp.d
win32.mak
win64.mak

This just adds these constants. It doesn't add the stuff behind `#ifdef __USE_MISC`.

Add TCP_* constants from Linux's netinet/tcp.h

---

mak/COPY
src/core/sys/posix/iconv.d
win32.mak
win64.mak

This adds bindings for `iconv_open`, `iconv` and `iconv_close`.

Add bindings for POSIX iconv library

---

circle.yml
circleci.sh

Similar to https://github.com/dlang/phobos/pull/4955.
In general it makes a lot of sense to merge to merge with the upstream branch, s.t. changes are always tested as they would be merged  (DAutoTest and auto-tester behave in the same way).
I added some minor updates to the script as well, e.g. always using `--depth 1` caused a stupid error at Phobos when done with the tools repo.

CircleCi: merge PRs with upstream branch

---

src/rt/aaA.d

Use correct overload of `hashOf` in `_aaGetHash`.
This incorrect usage is possible because of [Issue 16973 - `hashOf` has error-prone signature as `(T, seed)` may be confused with `(ptr, length)`](https://issues.dlang.org/show_bug.cgi?id=16973).

[REG2.068] Fix Issue 16974 - Equal associative arrays with associative array keys are considered unequal

---

src/object.d

The 2 argument foreach is not yet well supported.
In the new ctfe engine.
The following change removes it form the code and makes the codegen more straightforward.

simplify _ArrayEq to make it work with the new ctfe engine

---

mak/COPY
src/core/sys/linux/sys/prctl.d
win32.mak
win64.mak

On Linux it is possible to perform various operations like setting and getting a process name via `prctl`.
This patch creates a convenience wrapper over GNU/Linux's `prctl` implementation, inspired from `inotify.d`.
Please let me know if we need any improvements on this.

linux/prctl: Added support for prctl.

---

src/object.d

Came across it fixed in a commit by Ingrater [here](https://github.com/Ingrater/druntime/commit/114e783acc828f7f102cac871d2ee7d477092ab5#diff-a68e58fcf0de5aa198fcaceafe4e8cf9R980), adding as a separate commit.

Fix style in object.d file.

---

src/core/stdcpp/typeinfo.d

Implementing them (wrongly btw, ignoring the msg) leads to an implicit call to the `super` ctor of base class `core.stdcpp.exception.std.exception`, which is only declared in D. Even if the ctor signature was correct (see below), it's mangled differently (see https://github.com/dlang/dmd/pull/5884), so there'd be an unresolved external anyway. So don't implement it, just declare it (also done for Glibc) to defer the linking error.
Quality-wise, the 2 `core.stdcpp` modules are at most at an alpha stage for MSVCRT. Other issues I've noted so far using **VS 2015**:
* The signature of the `core.stdcpp.exception.std.exception.this()` ctor is wrong. There's no default, i.e., parameter-less one, only `std::exception::exception(const char *_Message = "unknown", int x=1)`.
* `std::exception` only …

[MSVCRT] core.stdcpp.typeinfo: Don't implement exception ctors

---

src/core/stdcpp/typeinfo.d

https://issues.dlang.org/show_bug.cgi?id=17081

Workaround Issue 17081 - Bodies in extern cpp functions in D files are not linked

---

src/core/stdc/stdlib.d
src/core/sys/posix/stdlib.d

This reverts commit 65d9a071b244611ca3973d79c8e64388af5c5439.
See https://github.com/dlang/druntime/pull/1718#issuecomment-271855366

Revert "Qualify C-style memory allocations functions as pure"

---

mak/COPY
src/core/sys/linux/sys/file.d
win32.mak
win64.mak

This adds core.sys.linux.file module which contains
flock function definition and values of the parameters
to pass.

Add linux-specific `core.sys.linux.file` module

---

src/gc/impl/conservative/gc.d
src/gc/pooltable.d
src/rt/lifetime.d

> If both operands are pointers, and the operator is -, the pointers are subtracted and the result is divided by the size of the type pointed to by the operands. **It is an error if the pointers point to different types**. The type of the result is ptrdiff_t.
See DMD's PR [here](https://github.com/dlang/dmd/pull/6440)

Always use same-type pointers when subtracting them

---

src/core/sys/posix/iconv.d

FYI @nemanja-boric-sociomantic

Add missing const to iconv bindings

---

src/rt/monitor_.d
win64.mak

druntime.lib is agnostic to the used MS C runtime, but preselects one. Creating the automatic reference when building main/WinMain/DllMain is good enough.

Issue 12125: do not enforce specific MS C runtime

---

src/core/sys/freebsd/dlfcn.d
src/core/sys/linux/dlfcn.d
src/core/thread.d
src/object.d
src/rt/deh_win32.d
src/rt/deh_win64_posix.d
src/rt/dwarfeh.d
src/rt/minfo.d
src/rt/sections.d
src/rt/sections_android.d
src/rt/sections_elf_shared.d
src/rt/sections_osx_x86.d
src/rt/sections_osx_x86_64.d
src/rt/sections_solaris.d
src/rt/sections_win32.d
src/rt/sections_win64.d
src/rt/tlsgc.d

While working on adding attributes to `std.random` (and in particular `unpredictableSeed`) in PR https://github.com/dlang/phobos/pull/4136, I noticed that much of the functions in `core.thread` don't have appropriate attributes (in particular `Thread.getThis`), so I added them where possible.
As a result, after going through the whole module, here's what's left before the `core.thread` can be
fully `@nogc` and `nothrow`:
* `thread_entryPoint`
-> calls `Thread.run`, which is not `@nogc` and `nothrow`
* thread_suspendHandler
-> calls `callWithStackShell` which takes a non-`@nogc` `delegate`
* `Thread.start`
-> calls `onThreadError` which is not `@nogc`
* `Thread.id`/`name`/`isDeamon`
-> synchronized is not `nothrow`
* `Thread.priority`
-> throws `new ThreadException`
* `Thread.run`
-> …

Add attributes to core.thread

---

src/core/stdc/stdio.d

core.stdc.stdio: annotate with 'scope'

---

src/core/memory.d

In response to https://github.com/dlang/phobos/pull/4832#issuecomment-272195784

Add pure wrappers for C style allocation

---

src/rt/dmain2.d

This is to resolve the following error messages:
```
src/rt/dmain2.d(507): Error: none of the overloads of 'toString' are callable using argument types (void delegate(const(char[]) s) nothrow), candidates are:
src/object.d(1701):        object.Throwable.toString()
src/object.d(1714):        object.Throwable.toString(scope void delegate(const(char[])) scope sink)
src/rt/dmain2.d(499): Error: none of the overloads of 'toString' are callable using argument types (void delegate(const(char[]) s) nothrow), candidates are:
src/object.d(1701):        object.Throwable.toString()
src/object.d(1714):        object.Throwable.toString(scope void delegate(const(char[])) scope sink)
```
from compiling with -dip1000.

[scope] add 'scope' to delegates

---

src/core/demangle.d

Goes with mangling change in https://github.com/dlang/dmd/pull/6496 although 6496 does not have to be pulled first.

[scope] update core.demangle for 'scope' mangling

---

src/core/exception.d

The "m" functions are no longer used. The "p" versions use fewer bytes of code to call. The efficiency loss with the strlen is irrelevant.

add _d_assertp, _d_unittestp, _d_arrayboundsp

---

src/core/sys/windows/stacktrace.d

Need to move towards making Object.toString() `@safe`.

make toString() @safe in core.sys.windows.stacktrace

---

src/core/stdc/stdlib.d
src/rt/profilegc.d
src/rt/qsort.d
src/rt/trace.d

For -dip1000. Also corrects problem where `strtold` can be used to convert pointer to immutable to pointer to mutable.

core.stdc.stdlib: annotate with 'scope'

---

src/rt/minfo.d

We missed the window to switch to abort in 2.073, and actually in hindsight, the master branch should have been updated early on in the cycle to give people time to deal with it.
This just pushes it to 2.074 (and updates the message appropriately). I will add a PR to switch to abort in the master branch once this is pulled and merged into master.

Push back deprecation of bad cycle detection one more major release

---

posix.mak
src/rt/lifetime.d
test/allocations/Makefile
test/allocations/src/overflow_from_existing.d
test/allocations/src/overflow_from_zero.d

https://issues.dlang.org/show_bug.cgi?id=16470

Add some more overflow checks inside array allocation

---

changelog/README.md

Updates the `changelog` README to the same version as the one at [Phobos](https://github.com/dlang/phobos/tree/master/changelog).

Update changelog README

---

src/rt/minfo.d

This completes the deprecation. In a future version, we may remove the "deprecate" option.
Note, I didn't change the message/version number to 2.074, because that was done in #1764, and should get into master soon.

Update handling of previously undetected cycles to abort execution.

---

src/core/sys/linux/sched.d

Fix for CI breakage caused by https://github.com/dlang/druntime/pull/1771

core.sys.linux.sched: Fix DDoc syntax

---

.gitignore
posix.mak
test/typeinfo/Makefile
test/typeinfo/src/comparison.d

PR #1781 is moving array comparisons to a new template; the initial implementation included changes which may have introduced performance and behavior regressions.
Add explicit tests for these cases to detect such regressions.

Add tests for class/struct/array comparisons

---

circle.yml
circleci.sh

Similar to https://github.com/dlang/phobos/pull/4996 - this should make CircleCi more resilient when used with branches that don't exist at DMD / Druntime, so this shouldn't be the usual case.

CircleCi: use master as fallback for DMD

---

Jenkinsfile

- should transfer the ownership of the ci repo to dlang/ci
Repeated #1776, this time from a branch on dlang upstream, so that the PR's Jenkinsfile is considered trusted.

adding Jenkinsfile to hook with new ci2.dawg.eu instance

---

src/object.d

This is an initial implementation of the template function to replace all overloads of ```TypeInfo.compare```.
The purpose is to have the compiler generate calls to this template, rather than a function (adCmp2 in this case https://github.com/dlang/druntime/blob/master/src/rt/adi.d#L445)
Array comparisons will be lowered to this template after a ```dmd``` patch. An example:
```
bool fun(int[] a, int[] b) {
return b[] < a[]; // generates call to the template
}
void main()
{
import std.stdio;
writeln(fun([1,2,3], [4, 1, 5]));
writeln(fun([4,6,5], [1, 2, 3]));
}
```

Array Compare Template Function

---

src/core/internal/string.d
src/object.d

A few more improvements to `__cmp` to reduce number of templates generated and tighten the code.

One more pass through __cmp

---

Jenkinsfile

- to avoid executor startvation, see Dicebot/dlangci#30

run pipeline outside of node block

---

src/core/time.d

We already have the type with Args[i], so there's no need to ask args[i] for
its type.

[trivial] Small code simplification in core.time.

---

circleci.sh

After the ddmd -> dmd transition the `dmd.conf` target won't be needed as well - in fact will probably error.
See also:
https://github.com/dlang/dmd/pull/6586#discussion_r104297885
CC @RazvanN7 @MartinNowak

Remove dmd.conf target from CircleCi

---

osmodel.mak
src/core/runtime.d
src/core/stdc/config.d
src/core/stdc/errno.d
src/core/stdc/fenv.d
src/core/stdc/locale.d
src/core/stdc/math.d
src/core/stdc/stdio.d
src/core/stdc/stdlib.d
src/core/stdc/string.d
src/core/stdc/tgmath.d
src/core/stdc/time.d
src/core/thread.d
src/core/threadasm.S
src/core/time.d
src/gc/os.d
src/rt/bss_section.c
src/rt/dmain2.d
src/rt/sections.d
src/rt/sections_elf_shared.d
test/exceptions/line_trace.exp
test/shared/src/load.d

It is LDC based port. My pull request merged to LDC master already. 
Druntime:
I decide try to repeat LDC team forkflow and cherry-pick my commit to ldc branch. There are a couple simple conflicts in src/core/stdc/locale.d & src/core/sys/posix/signal.d, and one absent (in master) file: src/rt/sections_ldc.d 
I successfully build and run druntime unittests on NetBSD after resolving conflicts.

NetBSD path

---

changelog/disable-TypeInfo.init.dd
src/object.d

As planned (one release behind schedule).

@disable TypeInfo.init

---

src/object.d

This is similar to what happened to ```adCmp```, or ```__cmp```, only that it's a first step, rather than the whole implementation. This is the template function for testing equality on arrays of structs (basetype is struct).
I also worked on a ```dmd``` patch lowering ```EqualExp``` to this code for arrays of structs. Locally, ```Druntime``` and ```Phobos``` tests are passing with the new implementation.
```__equals``` is a bit more interesting than ```__cmp``` because for arrays of basic types the compiler makes an optimization and generates a call too "memcmp" directly rather than call a ```druntime``` function. See here: https://github.com/dlang/dmd/blob/master/src/ddmd/e2ir.d#L2282
I avoided changing that bit for the time being until we can agree on what the best approach is. This is …

_equals druntime template for structs

---

src/core/time.d

Checking whether a duration is zero or not is a handy mechanism. Furthermore, it allows one to check if a duration is zero, and allows declaring a new duration variable at the same time:
```D
if(d = calculateDuration())
{
// do something with d
}
```

Fix issue 8411 - add opCast!bool support for Duration.

---

src/object.d

Catching `Throwable` is a bad idea most of the time.
* In the first case, it was a relic that can be safely removed
* ~~In the second case, there's no obvious reason why we would want to catch `Error`s from user code generated by the `TraceInfo.opApply`~~

Remove a catch of Throwable in object.d

---

src/rt/minfo.d

because that would leak it and cause corruption.

Fix cannot throw scoped exception

---

mak/COPY
src/core/sys/linux/sys/eventfd.d
win32.mak
win64.mak

This adds bindings for linux-specific eventfd_* calls.

Add eventfd bindings

---

src/rt/profilegc.d

Fixes issue 15947 (https://issues.dlang.org/show_bug.cgi?id=15947)
Fixes issue 14511 (https://issues.dlang.org/show_bug.cgi?id=14511)
Root problem was trying to increment non-existent AA field upon merging profile
stats. The code was also simplified to remove unnecessary condition.

[REG] Simple multithreaded program + "-profile=gc" = crash

---

src/object.d

In order to fix https://github.com/dlang/dmd/pull/6634, I created overloads for __equals with array literal arguments.

Array Literal Overloads

---

src/core/stdc/math.d
src/core/sys/posix/fcntl.d
src/core/sys/posix/pthread.d
src/core/sys/posix/signal.d
src/core/sys/posix/stdlib.d
src/core/sys/posix/sys/stat.d

All prior Android declarations were taken from Android API 9, which is [soon to be deprecated](https://github.com/android-ndk/ndk/wiki/Changelog-r15-beta1), so I note the few that were needed by Phobos and taken from a newer API with a comment.

Add some Bionic declarations needed in latest phobos, plus two fixes

---

changelog/fiber-configure.dd
changelog/fiber.dd
posix.mak
src/core/thread.d
test/thread/Makefile
test/thread/src/fiber_guard_page.d

Windows Fiber implementation already uses the fiber stack guard page.
This brings the similar protection for mmaped fiber stacks, using
mprotect.

Add Fiber's guard page in Posix as well

---

benchmark/gcbench/vdparser.extra/vdc/versions.d
src/core/sys/linux/sys/mman.d
src/core/sys/posix/sys/mman.d

Also known as SH5, this is a dead architecture.

Remove SH64 version code.

---

src/rt/minfo.d

Followup to #1799 
ping @WalterBright this is what I meant.

Clean up awkward inner function for cycle sorting.

---

src/core/sys/linux/sys/inotify.d

inotify_event's last member is flexible array member, where
the real size of the array is contained in `len` field. However,
D's runtime will not copy this field at all, producing garbage in
the copied instances.
This disables automatic copying of this struct.

Disable copying of inotify_event

---

src/object.d

as per title.
I found this mistake using `-vcg-ast`

correct mistake which caused idx to be inferrred as int

---

mak/COPY
mak/SRCS
win32.mak
win64.mak

Some files were not part of `mak/SRCS`, and thus were not compiled it.
Since they are C bindings, it was unnoticed for a long time,
as most operations won't require the rare symbols this module defined.
However for things such as static array declarations,
the `__init` of the struct might be required, which triggers a linker error.
One simple way to trigger the issue was to use the function `timersub` defined in
`core.sys.linux.sys.time`:
```
src/ocean/core/UnitTestRunner.d:671: undefined reference to 'core.sys.linux.sys.time.timersub(const(core.sys.posix.sys.time.timeval*), const(core.sys.posix.sys.time.timeval*), core.sys.posix.sys.time.timeval*)'
```
The patch is a superset of: https://github.com/sociomantic-tsunami/ocean/blob/fef725ca9643af4ffcccb44bcc8a2ff7598c4e24/docker/dmd-transiti …

[STABLE] Add missing binding in SRCS

---

src/object.d

The testcase dies with an access violation with DMD 2.074 on Windows:
```
object.Error@(0): Access Violation
----------------
0x0041C60D in memcmp
0x00402263 in pure nothrow @nogc @safe int object.__cmp!(void, const(void)).__cmp(void[], const(void)[]) at C:\LDC\dmd2\windows\bin\..\..\src\druntime\import\object.d(3407)
0x004021F7 in _Dmain at C:\LDC\ninja-ldc\..\current.d(27)
```

Fix __cmp(void[], void[])

---

src/gc/impl/manual/gc.d

By returning a delegate, the `this` is implicitly returned, and should be annotated.

gc.d: annotate escaping return

---

src/core/sys/windows/winerror.d

Instead of turning the initializers into `true`/`false` I've just changed its type to `uint`, the values are usually used in bitwise operations and it makes not much sense to keep those as `bool`. I think.

Turn the SECURITY_ enum into a uint.

---

src/gc/impl/conservative/gc.d

Calling `removeRoot` on something that was not added
by addRoot should be possible.
https://issues.dlang.org/show_bug.cgi?id=9275

Add tests for GC.removeRoot

---

src/core/sys/windows/objidl.d

see https://msdn.microsoft.com/en-us/library/windows/desktop/ms680062(v=vs.85).aspx, it took a `DWORD*` before

GetMarshalSizeMax takes a DWORD as second last arg

---

src/object.d

Seems like we should really check for such errors automatically ...
Discovered in https://github.com/dlang/dlang.org/pull/1694#issuecomment-308663796

Fix invalid undefined Ddoc macros

---

src/rt/util/typeinfo.d

```
Deprecation: identity comparison of static arrays implicitly coerces them to slices, which are compared by reference
```

fix deprecation messages when compiling typeinfo.d

---

osmodel.mak

osmodel.mak: add comments

---

src/core/sync/mutex.d
src/core/thread.d
src/rt/sections_android.d

Tested with @kinke's WIP ldc branch merge-2.074, these are the last remaining changes for a fully working druntime on Android.

Last tweaks for Android

---

changelog/fiber.dd

During the review of GitHub #1698, the "END OF FIBRE" marker data
was removed to avoid dirtying the guard page. Hence, the corresponding
comment in the release notes doesn't apply anymore.

Fixup fiber guard page changelog

---

benchmark/gcbench/conalloc.d
benchmark/gcbench/conappend.d
benchmark/gcbench/concpu.d
benchmark/gcbench/conmsg.d
benchmark/gcbench/rand_large.d
benchmark/gcbench/rand_small.d

conalloc, conappend and concpu by default run with super low number to gen any meaningful results.
Similarly extended rand_small, rand_large and conmsg to get more significant digits.
Also some parameters were meant to be global but got TLS due to crude porting from D1.

Enlarge the benchmarks to get meaningful diff

---

mak/COPY
mak/DOCS
mak/SRCS
src/core/stdc/assert_.d
win32.mak
win64.mak

For those who would want to call the C assert function rather than the druntime one.

add core.stdc.assert_

---

src/core/demangle.d
src/core/memory.d
src/core/thread.d
src/object.d

Change aliases to new syntax in several files

---

src/object.d

* Show `destroy(T)` and `destroy(ref T)` instead of only showing `destroy` with class constraint.
* Minor doc tweaks.

Tweak object.d docs

---

src/core/demangle.d

Preparation for changing the mangling of pascal function types: https://github.com/dlang/dmd/pull/6702

use __traits(getLinkage) instead of mangleof to determine linkage

---

changelog/unhandled.dd
src/rt/dwarfeh.d
test/exceptions/Makefile
test/exceptions/src/rt_trap_exceptions.d

Previously, dwarf exception handler was relying on a fact that running
user code is always enclosed in the catch-all exception handler.  That
might not be the case if the user (with debugger, for example) change
value of `rt_trapExceptions` to false. To cover this scenario, instead
of issuing fatal error, we wil just print exception info and abort the
program.

Print exception and abort if no handler is found

---

src/core/atomic.d

Different NAN patterns can be generated by various code paths, and comparing the bit patterns is a mistake. In this case, a signalling nan is compared against a quiet nan.
Use `0` instead.
This is blocking https://github.com/dlang/dmd/pull/6974

core.atomic: avoid comparing nan bit patterns

---

src/core/atomic.d

atomicOp!(double) unittests depend on has64BitCAS

---

src/core/stdc/math.d

Every target defines these as `int.max` and `-int.max`, except of course x86.

Add support for MIPS32, SPARC64 and SystemZ architectures in stdc/math.d

---

src/core/sys/posix/sys/types.d

Add support for SPARC64 in sys/posix/sys/types.d

---

src/rt/sections_elf_shared.d

In case finalizers are called from the runtime linker
we shouldn't try to get handle to and reference the
dying shared object. This was used just for the asserting,
so this simply removes the assert making it working on the
platforms where this is strictly forbiden (e.g. FreeBSD 12).

Fis issue 16856: Don't use dlopen from the fini sections

---

src/core/stdc/errno.d

Just so happened to notice that EDEADLOCK was wrong on PPC, so went through every CPU header that GDC builds for and spot checked each one just incase, and found a few more (`asm/errno.h` and overrides in `bits/errno.h`).
Added/Modified:
- x86: `ERFKILL(132)`, `EWPOISON(133)`.
- x86_64: `ERFKILL(132)`, `EWPOISON(133)`.
- ARM: `ERFKILL(132)`, `EWPOISON(133)`.
- AArch64: `ENOTSUP(EOPNOTSUPP)`, `ENOTRECOVERABLE(131)`.
- MIPS64: `ENOTSUP(EOPNOTSUPP)`.
- PPC: `EDEADLOCK(58)`, `ENOTSUP(EOPNOTSUPP)`, `ENOTRECOVERABLE(131)`.
- PPC64: `EDEADLOCK(58)`, `ENOTSUP(EOPNOTSUPP)`, `ENOTRECOVERABLE(131)`.
- SystemZ: `ENOTSUP(EOPNOTSUPP)`, `ENOTRECOVERABLE(131)`.
Don't have RISCV headers to hand, so did not verify them.

Add missing errno codes in existing linux platforms.

---

posix.mak
test/common.mak

This fixes it so that the builds in the test folder are built with
-fPIC when the unittest build is run with PIC=1. Unfortunately, the
line_trace test in test/exceptions is then failing (at least on my
system), because it doesn't actually generate a stacktrace. So, this
doesn't seem to completely fix it so that the PIC=1 unittest build
works, but it's close.

Partial fix for running druntime unittest with PIC=1.

---

src/object.d

Fix Issue 17624 - typo in Fields documentation section of object/exception

---

.codecov.yml

Due to many random coverage changes, the current CodeCov is suboptimal
at Druntime as it triggers many red crosses for perfectly healthy PRs.
As there's no way to configure CodeCov nor GitHub to change the
behavior to _not_ showing an overall failed status for coverage failures,
the simple solution is to turn the CodeCov status notifications off.
However, in the future the Dlang-Bot might display the CodeCov summary
as part of his comment.
Furthermore, the CodeCov commits will continue to get logged at [1], a
summary coverage for each file on e.g. master can always be found at [2] and
the CodeCov browser extension [3] will be working as well.
[1] https://codecov.io/gh/dlang/druntime
[2] https://codecov.io/gh/dlang/druntime/list/master
[3] https://github.com/codecov/browser-extension

Disable Codecov status messages

---

src/gc/impl/conservative/gc.d

These tests are pretty implementation specific, but should avoid some code locations indeterministically not showing up in coverage.

GC: add tests to make coverage a bit more deterministic

---

src/core/demangle.d

support for https://github.com/dlang/dmd/pull/5855 and a couple of fixes.

core.demangle: add support for type, identifer and symbol back references

---

test/profile/Makefile
test/profile/bothnew.def.exp

needed for https://github.com/dlang/dmd/pull/6998

profile test: allow both the old and the new mangling

---

src/core/sys/linux/fcntl.d

This adds constants for Linux's F_OFD_GETLK, F_OFD_SETLK and
F_OFD_SETLKW.

Add constants for F_OFT_* locks

---

src/core/memory.d

To be used in contexts such as `RefCounted`-destructor instead of having to define local overloads such as here https://github.com/dlang/phobos/pull/4832/files#diff-4e008aedb3026d4a84f58323e53bf017R5087.
AFAICT, `free` doesn't set `errno`.

Add pureFree to core.memory

---

src/object.d

typedef is long gone. However TypeInfo_Enum is inheriting from TypeInfo_Typedef, so we rename the later in the former.

Remove TypeInfo_Typedef

---

posix.mak
test/common.mak

Regarding https://github.com/dlang/druntime/pull/1721
> Unfortunately, the
line_trace test in test/exceptions is then failing (at least on my
system), because it doesn't actually generate a stacktrace. So, this
doesn't seem to completely fix it so that the PIC=1 unittest build
works, but it's close.
The test works on my system.
See also:

Enable -fPIC by default

---

src/core/atomic.d

Fixes #17665: Win64 atomicLoad for T[] cannot be cast from size_t[2].

Fixes issue #17665

---

src/core/stdc/fenv.d

It has been a pet peeve of mine for a while that these are defined as a different name in `std.math`, but not reflected here.

core.stdc.fenv: Add platform-specific FE_XXX flags

---

benchmark/arrayops/arrayops.d
benchmark/arrayops/plot.R
changelog/vectorized_array_ops.dd
mak/COPY
mak/SRCS
src/core/internal/arrayop.d
src/core/internal/traits.d
src/object.d
win32.mak
win64.mak

- runtime implementation of templated array operations w/ vectorization
- expresion tree is passed in RPN to encode operator precendence
- converts the expression to a simple loop
- for dmd the loop is vectorized
- gdc/ldc rely on auto-vectorization
- huge performance and latency improvements for some operations
- small throughput decreases due to loop overhead with dmd's optimizer
and the `floatArray[] / scalar` change mentioned in the changelog
- supports vectorization of more complex operations

templated array ops

---

src/core/thread.d

The Windows implementation does not need any initialization.

Eliminate one shared static this from thread.d

---

src/core/internal/arrayop.d

fixup for #1891, required by dlang/dmd#7032.
Unfortunately not really possible to test those with druntime's unittests as PowExp depends on phobos' std.math.pow.

add missing ^^ and ^^= arrayop support

---

mak/SRCS
src/core/sys/darwin/netinet/in_.d
src/core/sys/freebsd/netinet/in_.d
src/core/sys/linux/netinet/in_.d

Both FreeBSD and Linux add quite a few items to netinet/in.h which are not part of POSIX (some being part of other standards, some not). I'd be shocked if the other *nix systems out there didn't do the same, but I don't have any such systems set up, so I haven't dealt with them. This adds core.sys.{freebsd,linux}.netinet.in_ which include the non-POSIX declarations and publicly import core.sys.posix.netinet.in_. It includes quite a few of the constants that are in std.c.linux.socket (which is deprecated and overdue for removal), including ones that vibe.d uses and has never bothered to redeclare itself or add to druntime in order to not use the deprecated symbols. With this, hopefully, it can stop using the deprecated symbols.
Not all of the symbols from those header files have been …

Added system-specific bindings for netinet/in.h

---

changelog/vectorized_array_ops.dd
src/core/internal/arrayop.d
src/core/internal/traits.d

- add support for mixed vector types
- fix argument index in initScalarVecs

two fixups for the arrayop implementation

---

src/object.d

It's notably missing from http://dlang.org/phobos/object.html as the existing Ddoc comment was malformed.

provide missing Ddoc for object.ModuleInfo

---

src/core/sys/linux/epoll.d

Epoll functions not usable in nogc code, mark added

@nogc for core.sys.linux.epoll

---

src/gc/impl/conservative/gc.d

Passing static array `buf` to `new` causes the message:
```
src/gc/impl/conservative/gc.d(3252): Error: returning `&buf` escapes a reference to local variable `buf`
```
with PR https://github.com/dlang/dmd/pull/7101 which it blocks.
While the allocated memory is not actually escaped, the destructor has access to the expired stack frame for `buf`, and so needs to be corrected.

fix reference escape

---

src/object.d
test/exceptions/Makefile
test/exceptions/src/future_message.d

This patch introduces `Throwable.message` method which returns
`Throwable.msg`'s contents. In order to prevent name clashes with the
code already defining `message` method inside their own subclasses of
Throwable, `Throwable.message` is marked as `@__future`, providing
"forward deprecation" message to users.

(Re)Introduce Throwable.message

---

src/core/sys/linux/netinet/in_.d

Apparently, I made it cover more than it was supposed to. I think that
the fact that the #endif ending that section in the header file was
right after a #define threw me off, and I incorrectly thought that
the #endif went with the #define even though that doesn't make sense. In
either case, this should fix my mistake.
And man does the way that github show this diff look weird. All it does is add a brace in order to end a static if earlier, remove the brace that used to end the static if, and then fix the indentation. :|

Fix a static if (__USE_MISC) section in core.sys.linux.netinet.in_.

---

src/core/sys/posix/fcntl.d
src/core/sys/posix/signal.d
src/core/sys/posix/sys/stat.d

This should get all compilable tests in the testsuite to pass gdc's CI.

Add support for SPARC64 in sys/posix

---

src/rt/sections_win64.d

with VS2017 15.3.1 segment .tls is no longer written to a separate image section, so _tls_start and _tls_end no longer happen to work as both __gshared and TLS section offsets.

fix issue 17788: MSCOFF: TLS broken with VS2017 15.3.1

---

src/core/stdc/stdio.d

Having `stdout`, etc., be a variable means druntime needs to be linked in, meaning they do not work for `-betterC`. Switching to an enum makes it work.

core.stdc.stdio - change stdout, etc., to enum for -betterC

---

src/core/thread.d
src/rt/sections_elf_shared.d

Solves the problem described in https://github.com/dlang/druntime/pull/1557 (which got stalled)
- Release such memory explicitly by `destroy`ing
the main thread on threading module termination
- Prior to this PR `rt.sections_elf_shared.finiTLSRanges` already contains the necessary logic to `reset` `_tlsRanges` to zero length in the not `Shared` version, it just isn't used; instead the `_tlsRanges` (which only have one element) are cleared by calling `_tlsRanges.popBack` in `_d_dso_registry`.
This PR removes that `popBack` call and instead uses the preexisting logic in `finiTLSRanges` via
core.thread.thread_term -> ~Thread on the main thread -> rt.tlsgc.destroy -> rt.sections.finiTLSRanges

Fix leaking main thread held memory

---

src/rt/sections_elf_shared.d

When built as a shared library, druntime allocates memory for storing DSO dependencies in a custom dynamic array via [`_d_dso_registry`](https://github.com/dlang/druntime/blob/95fd6e1e395e6320284a22f5d19fa41de8e1dcbb/src/rt/sections_elf_shared.d#L355) (init path) -> [`getDependencies`](https://github.com/dlang/druntime/blob/95fd6e1e395e6320284a22f5d19fa41de8e1dcbb/src/rt/sections_elf_shared.d#L650) -> [`deps.insertBack`](https://github.com/dlang/druntime/blob/95fd6e1e395e6320284a22f5d19fa41de8e1dcbb/src/rt/sections_elf_shared.d#L694), which never gets freed. This explicitly frees that memory in `_d_dso_registry`'s deinit path by resetting that array.
Side note: This together with the now merged https://github.com/dlang/druntime/pull/1857 means that valgrind no longer shows any memory lost …

Fix leaking memory in shared druntime

---

src/gc/impl/conservative/gc.d

These are a few optimizations I recently noticed while staring at the precise GC. 
Benchmarks are not very stable, but show an improvement of 1 to 5 %. The graph shows the incremental performance change from bottom to top in percent, unfortunately not in the order of the commits:

GC micro-optimizations

---

src/core/memory.d
src/core/stdc/errno.d

This avoids needing druntime by connecting directly to the C implementation of `errno`. The C function actually returns an `int*`, but we call it `ref int` so it automagically dereferences when called.

fix Issue 17829 - core.stdc.errno does not work with -betterC

---

src/rt/config.d

`pragma(mangle, ...)` allows specifying a 'base' mangle for the symbol's linkage. So by using `extern(C) pragma(mangle, ...)`, a base C mangle can be specified, without having to take care of a platform-specific prefix; that is handled by the compiler.
The previous code relied on D symbols not getting prefixed, which isn't the case for LDC on OSX [and Win32, but that's subject to change].

rt.config: Make custom mangling more robust

---

benchmark/plot.R
benchmark/runbench.d

- parses runbench output
- plots times for all tests as boxplots (log1p y-axis)
- also plots any GC stats if available
Also usable to compare the other benchmarks, e.g. aabench.

add plot script for runbench

---

src/core/sys/posix/setjmp.d
src/core/sys/posix/sys/msg.d
src/rt/sections_elf_shared.d

MIPS is not documented as a valid version identifier for the MIPS 32-bit architecture.

Use MIPS32 version condition instead of MIPS.

---

src/core/sys/linux/epoll.d

Add epoll_event struct for MIPS32.

---

src/core/sys/linux/sys/mman.d

This code depends heavily on order of declarations, even though it shouldn't.
There was also a syntax error in the SPARC and SPARC64 ports.

Add workaround for issue 17883 in core.sys.linux.sys.mman

---

src/object.d

moved bad assertion that failed for arrays of arrays with mixed modifiers to the memcmp version which should work on values anyway.
Also fixed bad comparison via memcmp only comparing first element.

fix Issue 17876 - [REG 2.074] Internal error when comparing inout(Foo[][]) with Foo[][]

---

src/core/time.d

The last function in std.datetime which uses FracSec has now been
removed from Phobos (it was deprecated previously), so this now
deprecates FracSec, which probably should have been deprecated a while
ago, but oh well. All of the functionality that used it was switched to
use Duration for simplicity.

Deprecate core.time.FracSec.

---

src/core/threadasm.S

According to the instruction manual, neither of these instructions exist:
http://math-atlas.sourceforge.net/devel/assembly/mips-iv.pdf
However, `ldc1` and `sdc1` do, and they have the correct instruction format also, so it does appear to be a typo.
@MartinNowak - as you are the original author, could you have a look to confirm?

Fix 'unrecognised opcode ldcl/sdcl' in threadasm.S

---

src/core/threadasm.S

Looks like a copy-pasto from #988.

core/threadasm.S: PPC64 fix undefined reference to core.thread.callWithStackShell

---

src/core/sys/posix/sys/utsname.d

Gleaned from FreeBSD 11's .h file.

update ancient FreeBSD sys/utsname.h support

---

src/core/memory.d

These functions do not produce any garbage.
`GCAllocator.resolveInternalPointer` needs this change in order to be `@nogc`
@andralex

Mark GC addrOf and sizeOf as nogc

---

src/core/sys/windows/winsock2.d

To prevent duplicate symbols when pulling in that object file and the implementations in the ws2_32 library during linking.
Fixes https://github.com/ldc-developers/ldc/issues/468.

core.sys.windows.winsock2: Don't implement htons() etc.

---

src/core/sys/windows/winsock2.d

- as with the other sockaddr structs, the lowercase name
is also aliased as upcase name

add missing lowercase sockaddr_storage name

---

src/core/thread.d

Since adding the fiber's stack guard pages prevents operating system
from merging the mmaped regions together, this increases the number of
mapped regions, so the OS imposed limit can be hit earlier than before.
This documents this in the Fiber's constructors, so the users are
aware of this
cc @schveiguy @MartinNowak

Fix issue 17914: Document connection between fiber guard and mmap limit

---

src/core/sys/linux/config.d
src/core/sys/linux/stdio.d
src/core/sys/linux/sys/mman.d
src/core/sys/posix/config.d
src/core/sys/posix/sys/wait.d

See:
https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=c941736c92fa3a319221f65f6755659b2a5e0a20
https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=498afc54dfee41d33ba519f496e96480badace8e
Current documentation lists `_DEFAULT_SOURCE` as enabling BSD and SVID features.
https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html
For us, this is a no-op, as the same features are still enabled.

Remove deprecated and undocumented feature macros

---

src/core/exception.d
src/object.d

Compiler lowers final switch default case to this (which is a runtime error).
Old implementation is in core/exception.d
Compiler changes: https://github.com/somzzz/dmd/commit/d1bbf1e99737508b362c8f135ba2d6cefb18ab37

Final switch on default error template

---

src/core/stdc/assert_.d
src/core/stdc/errno.d

These were needed to get ldc 1.6 and 1.7 to compile.  All stdlib tests pass with this pull, same for the dmd-testsuite with 1.7 on Android/ARM.

Add two Bionic declarations

---

posix.mak
test/common.mak

- use MODEL=64/32 to decide on default
- allow overriding default with explicit PIC=0/1 make args

fix Issue 17966 - don't build libphobos2.a with PIC for i386

---

mak/COPY
mak/SRCS
src/core/internal/parseoptions.d
src/gc/config.d
win32.mak
win64.mak

mostly just moving code. The biggest complication is passing a display name for errors. I opted to require a method `string errorName()`.
Supposed to make the functionality available to other parts of druntime, e.g. https://github.com/dlang/druntime/pull/1916

refactor GC option parsing into core.internal.parseoptions.d

---

win32.mak
win64.mak

So I'm trying to move ahead with the ddmd -> dmd transition (https://github.com/dlang/dmd/pull/7135) and due to https://github.com/braddr/at-client/pull/4 we are stuck at the moment.
Hence, this PR tries to set the `DMD` binary path by default to one in the `generated` directory. As I have no Windows machine, I'm doing this more or less blindly, but it looks trivial enough.
See also: https://github.com/dlang/phobos/pull/5892

Fix DMD path to ../generated

---

src/rt/aaA.d

The bug is caused by the wrong assumption that the length of the literal is identical to the number of unique keys.

Fix issue 15290: account for duplicated keys in AA literals.

---

src/core/atomic.d
src/core/internal/parseoptions.d
src/core/sync/barrier.d
src/core/sync/condition.d
src/core/sync/mutex.d
src/core/sync/semaphore.d
src/core/thread.d
src/gc/bits.d
src/gc/impl/conservative/gc.d
src/gc/pooltable.d
src/object.d
src/rt/cover.d
src/rt/lifetime.d
src/rt/monitor_.d
src/rt/sections_elf_shared.d
src/rt/sections_osx_x86.d
src/rt/sections_win32.d
src/rt/sections_win64.d
src/rt/util/container/array.d
src/rt/util/container/hashtab.d
src/rt/util/utf.d

Automatic replacement with
sed -i "s/^\([ ]*\)body/\1do/" -i **/*.d
See also: https://github.com/dlang/phobos/pull/5869

Replace `body` keyword with its replacement: `do`

---

CODEOWNERS

Similarly to https://github.com/dlang/phobos/pull/5573
> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own. When someone with admin permissions has enabled required reviews, they can optionally require approval from a code owner.
Moreover, it's a simple plain-text format:
> A CODEOWNERS file uses a pattern that follows the same rules used in gitignore files. The pattern is followed by one or more GitHub usernames or team names using the standard @username or @org/team-name format. 
For more information, the [help page](https://help.github.com/articles/about-codeowners/) goes into more details.
I tried to use some insights from [@MartinNowak's git blame analyzer](https://github.com/dlang/phobos/pull/5573#issuecomment-314227 …

Add initital codeowners file

---

changelog/core-runtime-unittestEnhancement.dd
posix.mak
src/core/runtime.d
src/rt/dmain2.d
src/test_runner.d
test/unittest/Makefile
test/unittest/customhandler.d

Currently, if unit tests run and all pass, the program is started. Typically users expect the main function to exit immediately, so they instrument their main program with
``` D
version(unittest) { void main() {} }
else int main(string[] args)
{
...
}
```
But this sucks. D shouldn't be running the main program after unit testing (by default). This can be an opt-in for the user, but should default to exiting.
This modification changes the unit test handler to return `int` instead of `bool` to signify different handling of the unit test result. If the handler function returns 0, then the main function is run. If the handler returns nonzero, the main function is not run. If the result is `int.min`, then the program exits with a failure exit code. If the result is negative, the program prints …

Modify unittest handling

---

changelog/covopts.dd
src/gc/config.d
src/rt/cover.d

```
Make coverage reports configurable via --DRT-covopt
The coverage module has a couple of options that can be set through some
weirdly looking dmd_coverSetMerge(), dmd_coverSourcePath() and
dmd_coverDestPath() functions (I guess the dmd prefix comes from
pre-druntime times).
These options don't only use non standard names, they also don't use the
standard --DRT-xxx / DRT_XXX runtime options passing mechanism, and they
can only be overridden in code.
This commit plugs the runtime options mechanism and adds support to set
these options via --DRT-covopt (and matching environment variables),
providing the sub-options merge, dstpath and srcpath.
The old functions are kept for backwards compatibility (they are used by
DMD itself for example), but should probably be removed in some distant …
```

Add --DRT-covopt: merge, srcpath and dstpath options

---

CONTRIBUTING.md

It's been more than a year since we allow including the changelog directly in the PR, updating this `CONTRIBUTING` guide has been forgotten.
It's actually not OK to _not_ update the changelog in the respective PR.

Improve changelog directory advise

---

benchmark/aabench/bulk.d
benchmark/gcbench/conalloc.d
benchmark/gcbench/conappend.d
benchmark/gcbench/concpu.d
benchmark/gcbench/testgc3.d
benchmark/gcbench/vdparser.extra/stdext/string.d
benchmark/gcbench/vdparser.extra/vdc/ast/aggr.d
benchmark/gcbench/vdparser.extra/vdc/ast/expr.d
benchmark/gcbench/vdparser.extra/vdc/ast/type.d
benchmark/gcbench/vdparser.extra/vdc/interpret.d
benchmark/gcbench/vdparser.extra/vdc/lexer.d
benchmark/gcbench/vdparser.extra/vdc/parser/aggr.d
benchmark/gcbench/vdparser.extra/vdc/parser/decl.d
benchmark/gcbench/vdparser.extra/vdc/parser/engine.d
benchmark/gcbench/vdparser.extra/vdc/semantic.d
benchmark/runbench.d
posix.mak

Running the benchmark suite at the moment already triggers deprecation warnings. This PR intends to avoid that the suite doesn't compile in the future.
The test files of the benchmark suite are only compiled - not run (`--repeat=0`) and the more expesnive release flags are dropped too.
See the individual commits for more details.
If the increased run time of the auto-tester is a concern, we can also move this to the `circleci.sh` script.

Compile benchmark suite on the auto-tester to avoid a broken state

---

src/object.d
src/rt/aaA.d

The unit test added in this PR should demonstrate what to avoid. If we make sure we have an actual AA, then casting to void * will not be intercepted by a malicious `opCast`.
Note, the declaration of `const(V[K])` is *necessary* since any type modifiers on the actual T are not conveyed anywhere. For example, if you passed in `inout(int[int])` to the range generating function, then `V == inout(int)` and `K == int`. If the `const` isn't there, then you can't assign to the temporary.
I'm not in love with how I'm extracting the AA itself, but I don't know of a better way. I'm going to post something in the forums to see if anyone can figure out a better way.

Fix 18071 -- safe casting of AA to void * when getting ranges

---

posix.mak

Also it's a good practice to depend on the compiler which means that
if it gets recompiled, all dependent files will have to be updates too.
Originating from https://github.com/dlang/phobos/pull/5929

Allow to use a debug DMD executable

---

mak/SRCS
src/core/thread.d
src/object.d
src/rt/deh_win32.d
src/rt/deh_win64_posix.d
src/rt/dwarfeh.d
src/rt/ehalloc.d

see https://github.com/dlang/dmd/pull/6681 which is blocking this

implement druntime side of DIP1008

---

src/core/bitop.d

Required for https://github.com/dlang/dmd/pull/7440

Halt on Ddoc errors & fix the existing ones

---

.circleci/run.sh

Yet another boring CI improvement. The idea here is that we use at least one CI to test `BUILD=debug`.
See https://github.com/dlang/dmd/pull/7477 for details.

[CircleCi] Make a BUILD=debug build of DRuntime first

---

.codecov.yml

Propagating the config from https://github.com/dlang/dmd/pull/7470.

Update CodeCov configuration to be always green/successful

---

src/core/sys/posix/sys/resource.d

 Add musl libc definitions to:  src_core_sys_posix_sys_resource

---

src/core/sys/posix/stdlib.d

 Add musl libc definitions to:  src_core_sys_posix_stdlib

---

src/core/sys/windows/winbase.d

Needed for https://github.com/dlang/dmd/pull/7577
See also:
https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=2975538&isPull=true

Fix duplicate core.sys.windows.winbase.GetEnvironmentStringsW declaration

---

LICENSE.txt

It seems that https://github.com/dlang/druntime/pull/2021 hasn't worked.
Apparently GitHub does a 1:1 file comparison as it detects the Phobos license file correctly:
https://github.com/dlang/phobos/blob/master/LICENSE_1_0.txt
Hence I presume that removing the header will allow GitHub to detect the license file.

Remove header from LICENSE.txt, s.t. GitHub can detect it

---

.circleci/run.sh
.codecov.yml

After we finally figured out a nicely working CodeCov YAML configuration, propagate this to DRuntime.
See also:
- https://github.com/dlang/dmd/pull/7574 (Use GitHub's merge head)
- https://github.com/dlang/dmd/pull/7596 (Don't wait for other CIs, attempt IV)
- https://github.com/dlang/dmd/pull/7542 (Don't wait for other CIs, attempt III)
- https://github.com/dlang/dmd/pull/7540 (Use domains to ignore CI providers)
- https://github.com/dlang/dmd/pull/7532 (Fix 'No parent commit was found' by allowing coverage offsets)

Update CodeCov config

---

src/core/stdcpp/exception.d

Needed for https://github.com/dlang/dmd/pull/7577
FWIW I think we should just drop the C++ definitions and move them into a DUB project.
Now that we even have the project tester, there's _zero_ reason to keep them here.
On the other hand, having them as part of [`dlang-stdx`](https://github.com/dlang-stdx)
allows active development and version mangement allows to make breaking changes without worrying about them.

Fix duplicate definition

---

src/object.d

The point is to encapsulate a common operation in `std.parallelism` and `core.thread` into this function.

add Throwable.chainTogether()

---

src/core/thread.d

 Add musl libc definitions to:  src_core_thread

---

src/rt/lifetime.d

AFAICT this function isn't used anymore. Let's check whether the CI systems agree.

Remove unused _d_delarray

---

src/core/sys/posix/sched.d

 Add musl libc definitions to:  src_core_sys_posix_sched

---

src/core/stdc/wchar_.d

Functions in core.stdc.wchar_ should have the same purity as the corresponding non-wide functions in core.stc.string. Also regularize qualifiers to match core.stdc.string.

Fix Issue 18240 - core.stdc.wchar_ wmemset, etc. should be pure

---

mak/DOCS
posix.mak
src/rt/cover.d
src/rt/minfo.d

I didn't see any reason why this hasn't been done before. I often missed this.
Exposing the docs, will also make it easier to find respective functions on Google.
Note: this won't be visible (part of the menu) for now. That will require https://github.com/dlang/dlang.org/pull/2084
Of course this is still a bit unpolished, but it won't change if we don't expose it.

Build rt documentation on dlang.org

---

benchmark/gcbench/vdparser.extra/vdc/ast/expr.d
benchmark/gcbench/vdparser.extra/vdc/interpret.d

The DRuntime testsuite contains an old copy of VisualD.
However, this is preventing us to move forward with the complex deprecation:
https://github.com/dlang/phobos/pull/6014
It's save to remove this as is just the GC performance testsuite.

Remove complex numbers form the gcbench suite

---

src/rt/dmain2.d

The source path of many `rt` files is absent or broken. This fixes it for one file.

[trivial] Fix ddoc source path of `rt_dmain2`

---

src/object.d

- add missing handling of associative arrays as array elements to __equals

fix Issue 18252 - comparison of arrays of associative arrays broken

---

src/core/time.d

Start to dig into the CircleCi failures seen here:
- https://github.com/dlang/druntime/pull/2046#issuecomment-358487445
- https://github.com/dlang/druntime/pull/2047
Reproducible locally with:
```
TEST_COVERAGE=1 make -f posix.mak unittest-debug
```
Failure:
```
****** FAIL debug64 core.time
core.exception.AssertError@src/core/time.d(527): unittest failure
----------------
```

Attempt to fix CircleCi

---

benchmark/runbench.d

On osx I was getting a “No such file” exception for dante.txt
because CWD depended on where I executed `rdmd benchmark.d` from.
And the object files were generated in a directory also depending
on that.
This fixes obj dir to same level as bin dir within the benchmarks
dir, and allows the runCmd to take a workDir parameter for running
the benchmark executables

Fix paths in benchmark runner

---

.circleci/config.yml

See also: https://github.com/dlang/dmd/pull/7718

Run CircleCi coverage for 32-bit too

---

src/object.d

The current documentation for `destroy` says that it sets the object to an "invalid state", but that's not what I've found in my testing, so I changed the documentation to explain what I think is happening, and added an example for illustration.

Improve destroy's documentation

---

src/rt/sections.d
src/rt/sections_elf_shared.d

These changes are probably not correct. Compiled D programs will crash when trying to load shared libphobos.
All helps are welcomed.

Add musl libc definitions to rt/*

---

src/rt/util/utf.d

The offending pattern:
```d
wchar[] r;
size_t slen = s.length;
r.length = slen;
r.length = 0;
// ... followed by code that appends to r with ~=
```
The apparent intention is to preallocate the buffer but this idiom doesn't work [as pointed out by Dmitry Olshansky](https://github.com/dlang/phobos/pull/6024#discussion_r160918451): "On append the slice is not the tail so it will reallocate."

Fix Issue 18279 - rt.util.utf does not properly reserve buffer in toUTF16/toUTF16z

---

src/core/stdc/assert_.d
src/core/stdc/fenv.d
src/core/stdc/locale.d
src/core/stdc/math.d
src/core/stdc/stdio.d

This is splitted from #1997.
I think I addressed all the comments. Thanks to all the reviewers.

Add musl libc definitions to core/stdc/*

---

src/core/sys/posix/config.d
src/core/sys/posix/dirent.d
src/core/sys/posix/fcntl.d
src/core/sys/posix/netdb.d
src/core/sys/posix/netinet/in_.d
src/core/sys/posix/pthread.d
src/core/sys/posix/pwd.d
src/core/sys/posix/semaphore.d
src/core/sys/posix/signal.d
src/core/sys/posix/sys/ioctl.d
src/core/sys/posix/sys/mman.d
src/core/sys/posix/sys/select.d
src/core/sys/posix/sys/socket.d
src/core/sys/posix/sys/stat.d
src/core/sys/posix/sys/types.d
src/core/sys/posix/sys/uio.d
src/core/sys/posix/sys/wait.d
src/core/sys/posix/time.d
src/core/sys/posix/unistd.d

Add musl libc definitions to core/sys/posix/*

---

src/core/sync/mutex.d

Required for https://github.com/dlang/dmd/pull/7816

Fix error due to deprecated rwm for shared variables

---

changelog/core-memory-__delete.dd
src/core/memory.d

See also:
- https://github.com/dlang/dmd/pull/7342
- https://dlang.org/deprecate.html#delete
- https://dlang.org/spec/expression.html#delete_expressions
I didn't add any tests for [Class deallocators](https://dlang.org/spec/class.html#deallocators)
as they have been deprecated since D2 and we call the existing functions.
CC @JinShil

Add __delete for migration from delete

---

src/core/atomic.d

On 64 bit platforms int[] has size 128 bit. Sadly, not all of these
platforms support cas with 128 bit, which breaks the unit test.
Example is ppc64.

Guard unittest for atomicLoad() of int[].

---

src/core/stdc/math.d

These include:
* ~~cos, sin, tan,~~ [atan](https://linux.die.net/man/3/atan);
* [tanh](https://linux.die.net/man/3/tanh), [asinh](https://linux.die.net/man/3/asinh);
* [frexp](https://linux.die.net/man/3/frexp), [modf](https://linux.die.net/man/3/modf);
* [cbrt](https://linux.die.net/man/3/cbrt);
* [erf](https://linux.die.net/man/3/erf);
* [ceil](https://linux.die.net/man/3/ceil), [floor](https://linux.die.net/man/3/floor), [trunc](https://linux.die.net/man/3/trunc), [round](https://linux.die.net/man/3/round), [rint](https://linux.die.net/man/3/rint), [nearbyint](https://linux.die.net/man/3/nearbyint);
* [copysign](https://linux.die.net/man/3/copysign), nan;
* [fdim](https://linux.die.net/man/3/fdim), [fmax](https://linux.die.net/man/3/fmax), [fmin](https://linux.die.net/man/3/fmin);
* …

Fix Issue 18247 - core.stdc.math functions that never set errno should be pure

---

.codecov.yml

There are still many parts of Phobos which have a low coverage. Touching them shouldn't make a PR fail.
See also: https://github.com/dlang/phobos/pull/6124
Example from https://github.com/dlang/druntime/pull/2079
> codecov/patch — 21.052% of diff hit (target 74.653%)
Phobos and DMD already use this behavior.

[Codecov] Replace threshold:5 with informational:true

---

posix.mak

Begin copying all the `style_lint` stuff from phobos.  It's better to apply this one at a time, as there are _many_ lint failures that get flagged up.

posix.mak: Add check for trailing whitespace from phobos

---

CODEOWNERS
mak/COPY
mak/SRCS
posix.mak
src/core/sys/dragonflybsd/dlfcn.d
src/core/sys/dragonflybsd/execinfo.d
src/core/sys/dragonflybsd/netinet/in_.d
src/core/sys/dragonflybsd/pthread_np.d
src/core/sys/dragonflybsd/sys/_bitset.d
src/core/sys/dragonflybsd/sys/_cpuset.d
src/core/sys/dragonflybsd/sys/cdefs.d
src/core/sys/dragonflybsd/sys/elf.d
src/core/sys/dragonflybsd/sys/elf32.d
src/core/sys/dragonflybsd/sys/elf64.d
src/core/sys/dragonflybsd/sys/elf_common.d
src/core/sys/dragonflybsd/sys/event.d
src/core/sys/dragonflybsd/sys/link_elf.d
src/core/sys/dragonflybsd/sys/mman.d
src/core/sys/dragonflybsd/time.d
win32.mak
win64.mak

Split PR : #1999
Moved the src/core/sys/dragonflybsd related changes into this PR
Related PR:
- https://github.com/dlang/dmd/pull/7463

 Add DragonFlyBSD support : Split PR : src/core/sys/dragonflybsd related changes

---

src/core/thread.d
src/gc/proxy.d
src/rt/dmain2.d
src/rt/monitor_.d

- make thread_init/term @nogc
- move thread_init/term from GC to rt_init/term

separate thread_init/term from gc_init/term

---

src/core/time.d

The issue... 
go to ...
https://dlang.org/phobos/core_time.html
Search for 'edit' ( i.e. find the first runnable example ). Run the example, for me anyway example is broken.

Duration examples fail to run on dlang.org without import.

---

changelog/lazy-gc-init.dd
mak/SRCS
src/gc/impl/proto/gc.d
src/gc/proxy.d
src/rt/dmain2.d
test/exceptions/src/unknown_gc.d
test/nogc.d

This PR removes the requirement of having the GC initialized at startup. Instead, ```gc_init``` is called when the GC is first invoked.

GC Initialized on First Alloc

---

src/core/sys/posix/sys/types.d

Seems to be uint32_t for every platform, but I'm not too familiar with it, maybe some build config somewhere changes it or uses a different file.
https://android.googlesource.com/platform/bionic/+/fb96db14d11fa75a5a44162188d6bc441f9491e0/libc/include/sys/types.h#74

Add missing types for cruntime bionic.

---

src/core/thread.d
src/object.d
src/rt/deh_win32.d
src/rt/deh_win64_posix.d
src/rt/dmain2.d
src/rt/dwarfeh.d

because `next` is so generic it's too hard to find the uses of it.

change Throwable.next to ref counted property

---

src/core/sys/posix/fcntl.d
src/core/sys/posix/sys/socket.d
src/core/sys/posix/sys/stat.d

The first and last are needed for higher-precision linux-only tests of `std.file.setTimes`, while `std.socket` and `std.net.curl` tests broke because of the wrong type in `sockaddr`.
@yshui, let me know if you need anything else in.

Last remaining Musl declarations needed for Phobos

---

src/core/runtime.d
src/core/thread.d
src/gc/os.d
src/rt/backtrace/dwarf.d
src/rt/qsort.d
src/rt/sections.d
src/rt/sections_elf_shared.d

This is the final patch with uCLibc definitions for druntime.
This will get the druntime test runner working on an ARMv7 machine running OpenWRT. All this using a hacked LDC 1.7 compiler.
Phobos tests run also, except some missing math functions and related formatting issues re. real.
This means that you can hack your *Open*WRT ARM router and run D on it!

Add rest of core.*, rt.* and gc.os of uClibc definitions.

---

src/gc/impl/proto/gc.d

Also added global scope operator to all `gc_*` calls from `ProtoGC` to clarify that they are the global functions and not members (would have potentially helped catch the original issue).
See https://github.com/dlang/druntime/pull/2057#discussion_r168266752
Ping @somzzz @andralex @klickverbot @MartinNowak 
I did not do anything about the race condition on the root/range lists, as I don't know the correct direction to choose there.

Fix recursive reserve call in ProtoGC

---

src/gc/impl/proto/gc.d

> Dammit, I just realized this should have targeted stable, I didn't realize Martin had forked after the ProtoGC thing was added. @MartinNowak can you cherry pick this
CC @schveiguy
Well, cherry-picking isn't ideal as it leads to more merge conflicts, but the master/stable branch-off already happened.

Fix recursive reserve call in ProtoGC. Also added global scope operator to all gc_* calls from ProtoGC to clarify that they are the global functions.

---

src/rt/cast_.d

I don't think these have ever been used since they were added 9 years ago.

Remove unused and unreferenced function in rt.cast_

---

src/object.d

Supersedes #2094 
Returns `int.min` instead of `-1` in the case of no match so we can add the whole length of the string case list and not worry about accidentally selecting a valid case label. Will work as long as the number of strings to compare against does not exceed `uint.max`
Also factored out `$ / 2` to be an enum for easier understanding.

Improve string switch code, removing extra test for -1.

---

src/core/sys/posix/sys/shm.d

This one was overlooked (and noticed by @joakim-noah in backporting to ldc-ltsmaster)

[Trivial] Add dragonfly implementation for shared memory

---

src/core/memory.d

See also: https://github.com/dlang/druntime/pull/2104#issuecomment-368101722

__delete shouldn't segfault for null

---

src/core/sys/posix/dirent.d
src/core/sys/posix/sys/stat.d
src/core/sys/posix/sys/types.d

Convenient when checking for correctness

add FreeBSD github URLs

---

src/core/thread.d

Before/after Ddoc:
Before/after DDOX:

[Ddoc] move documentation of Fiber.State members to those members

---

src/core/sys/posix/grp.d
src/core/sys/posix/time.d

With this patch and cherry picking all of @yshui's Musl port, everything builds and runs with the ldc 1.8 beta.  This was apparently missed before because [ldc builds all of `core.sys.posix` for its testrunner for non-Windows platforms](https://github.com/ldc-developers/ldc/blob/master/runtime/CMakeLists.txt#L161), but the default dmd makefiles build very little of it. Nothing actually there to be built of course, but this means static assert blocks and redundancies are not checked, like they are for ldc.
Might be worth doing so for dmd too, at least for the tests.

Musl: Add missing grp.h declarations and remove kernel constants

---

src/core/demangle.d

The range error occurs if the demangler happens to hit the length of the buffer (which is a multiple of 4000 by default) with the chunk it tries to write into the buffer.
I didn't add the test case to the unittests because it's a 17k string which seems excessive.

fix issue 18300: range error demangling long symbol

---

src/core/internal/arrayop.d

skip executing simd instructions at compile time

Issue 17964 - [CTFE] If array is large enough it hits __simd at CTFE

---

src/core/sys/dragonflybsd/pthread_np.d

This caused a unittest issue in ldc-ltsmaster. Would like to keep these files in sync.
Note: The file does not seem to be used at this moment, and was copied over from the FreeBSD implementation (which does not seem to use it's version either). Maybe instead of renaming the module name, we should opt to remove this file. Not sure what the reason for it's creation is or was.

[Trivial] Match the module name to the file name (pthread_np)

---

src/core/sys/windows/stacktrace.d

dmdDecodeString is harmful for non-mangled names, disable it for anything but OMF

fix issue 18536 - Bad stack traces when building with -m32mscoff

---

src/core/stdc/stdlib.d

- remove scope as it's not checked for `@system` functions anyhow
- adding overloads would be an alternative approach, but it's 32
variants to support all of `scope`, `@safe`, `pure`, `nothrow`, `@nogc`

fix Issue 17188 - qsort predicate requires scope parameters

---

src/core/sys/posix/time.d

definitions are pulled form Posix and Linux versions.

uClibc remove conflicting enum definitions in core.sys.posix.time

---

mak/COPY
src/core/sys/posix/aio.d
win32.mak
win64.mak

Added interface for posix aio in D (only for linux x64 for now).
The aiocb struct can have various implementations, for linux x64 I tested the following in C and created the equivalent in D:
```
C aiocb
Sizeof aiocb: 168 bytes
Offsets:
aiocb.aio_fildes:	 0
aiocb.aio_lio_opcode:	 4
aiocb.aio_reqprio:	 8
aiocb.aio_buf:		 16
aiocb.aio_nbytes:	 24
aiocb.aio_sigevent:	 32
aiocb.aio_offset:	 128
```

add aio.d for linux x64

---

src/core/stdc/math.d

uClibc warps those functions to double variant

uClibc fix core.stdc.math to use the wrapping variants for long double

---

src/core/thread.d

increase the default stack size because exception handling might need up to 16k. The actually used stack can depend on the version of DbgHelp.dll, the existence of debug information and possibly other conditions.

fix issue 18547 - Win32: throwing exception in fiber crashes application

---

src/core/internal/parseoptions.d

allow DRT arguments to include '=' or ':', splitting is done by ' '

fix Issue 18537 - Cannot pass absolute path to coverage options

---

src/core/sys/posix/netinet/in_.d

This constant causes a collision for Bionic, but not for Glibc or UClibc because they have declaration blocks earlier.  Technically, this constant comes from the kernel headers, but it's usually also defined by the C runtime headers, so probably easier to put it there.

Musl: Move IPV6 constant that breaks Bionic

---

src/rt/util/random.d

There is no need for seedval to be non-zero. The assertion should be removed.

Issue 18332 - rt.util.random.Rand48 remove unnecessary assert

---

src/object.d

Trying to fix [1] and that line blocks it. const/immutable/shared postblits are going to be illegal so it does not make any sense to have `@disable` on a `const` postblit. This PR currently blocks [2]
[1] https://issues.dlang.org/show_bug.cgi?id=18417
[2] https://github.com/dlang/dmd/pull/8032

[Trivial] Delete -@disable this(this) const- in object.d

---

src/core/sys/posix/config.d

Include missing config definitions that got lost in previous commits.

[uClibc] include config definitions

---

src/core/sys/linux/netinet/in_.d

`Glibc` definitions cover `uClibc` also.
Probably `Musl` needs to be included also?
This fixes build and run of `vibe.d`. See https://github.com/lindt/docker-dmd/issues/1 and https://forum.dlang.org/post/oyrmgpvyncuanzokkxba@forum.dlang.org

[uClibc] extend `core.sys.linux.netinet.in_` definitions

---

src/object.d

This is to correct the error:
```
src/object.d(4450): Error: returning `S(& p)` escapes a reference to local variable `p`
```
which is blocking https://github.com/dlang/dmd/pull/8030

object: fix escaping p

---

CODEOWNERS

Remove my work account from code owners, but leave my personal account (Geod24) here,
so I don't get notified twice.

Remove myself as code owner

---

src/core/sync/mutex.d

See also: https://github.com/dlang/dmd/pull/7816
First attempt: https://github.com/dlang/druntime/pull/2072 (still triggers the error)
~~~The `@trusted` lambda is needed because casting away shared isn't `@safe`.~~~
edit: Apparently, the compiler doesn't mind.

Fix deprecated rwm operation in core.sync.mutex

---

src/core/sys/posix/sys/statvfs.d

Although POSIX uses statvfs, statvfs does not give good results on FreeBSD.
However statfs works fine on FreeBSD as described here[1].
@edi33416 helped me test the functionality on FreeBSD. Statfs should be used for implementing "getAvailableDiskSpace" on FreeBSD as discussed here[2].
[1] - https://www.freebsd.org/cgi/man.cgi?query=statfs&sektion=2
[2] - https://github.com/dlang/phobos/pull/5776

Added statfs for FreeBSD

---

src/core/sys/posix/ucontext.d

fix MIPS32 declarations.
Fore reference https://github.com/kraj/uclibc-ng/blob/57f820bab9108550907f03828d61525c833004a4/libc/sysdeps/linux/mips/sys/ucontext.h

[uClibc] MIPS32 fix core.sys.posix.ucontext defs

---

src/core/stdc/math.d

Phobos Compile Error:
std/math.d(4598): Error: `pure` function `std.math.nearbyint` cannot call impure function `core.stdc.math.nearbyintl`
Issue got apparent when https://github.com/dlang/phobos/pull/6409 was merged.
Note: This fix only references DragonFly specific code

(Trivial) (DragonFly) Some of the core/stdc/math c-library functions had the 'pure' attribute set

---

src/core/sys/posix/netinet/in_.d

Fixes the member type and name.
See https://github.com/kraj/uclibc-ng/blob/85c9aaf9e4410bcd367c3e5f6dab13ce9ba936f4/include/netinet/in.h#L288

[uClibc] core.sys.posix.netinet.in_ definition fix

---

src/object.d

An import of `dstrcmp` already happens on [line 3680](https://github.com/thaven/druntime/blob/93269b4d820b55495b4cf7a99d63b797298e2a48/src/object.d#L3680), though that one is inside a template, and this one isn't.
Usage of `externDFunc` in this case looks like a leftover of when it was `rt.util.string.dstrcmp`.

Use regular import for dstrcmp

---

src/core/sys/posix/unistd.d

As described ie here: http://man7.org/linux/man-pages/man2/getgroups.2.html

[trivial] added missing setgroups to posix

---

src/core/stdc/config.d

needs https://github.com/dlang/dmd/pull/8152

config.d: use enums instead of structs for __c_long, etc.

---

changelog/getsect.dd
src/core/sys/darwin/mach/getsect.d
src/core/sys/darwin/mach/loader.d

Add missing declarations to the `core.sys.darwin.mach.getsect` and `loader` modules.

Add missing declarations to Mach-O interface

---

benchmark/runbench.d

This is particularly useful when trying different runtime options to see
how they impact on the performance.

benchmark: Add option to avoid (re) compiling

---

src/core/sys/posix/netdb.d
src/core/sys/posix/netinet/in_.d
src/core/sys/posix/signal.d
src/core/sys/posix/sys/socket.d

Looks like the Musl port was done a bit sloppily, I needed these to build the `vibe-d` package with dub.

Musl: add missing declarations needed for vibe.d

---

src/core/stdc/config.d
src/core/stdc/stdint.d

Provides better interoperability with C++, hence betterC.

set core.stdc.stdint types so mangling matches C++

---

changelog/cpp_destroy.dd
src/object.d

Fix issue 14536 - destroy() works on extern(C++) classes
Depends on https://github.com/dlang/dmd/pull/8224

Fix issue 14536 - destroy() works on extern(C++) classes

---

posix.mak

Analogous to Phobos: https://github.com/dlang/phobos/blob/6c11b77dbc07a2de293cb9f9c14a55890773331d/posix.mak#L307
BTW I wonder whether we should include the [DRuntime development page](https://wiki.dlang.org/DRuntime_development) that I wrote just within this repo (e.g. README.md or CONTRIBUTING.md). Thoughts?

Add 'lib' Makefile target

---

src/core/stdc/math.d

Most of the Android port was done against API 9, when Android only supported 32-bit platforms and defined `long double` to always be 64-bit, so they didn't bother with even providing aliases for several `long double` math functions. However, they started adding those with the following APIs, culminating in API 21, Lollipop, which also added 64-bit platforms with different native `long double` sizes.
This pull updates the math function declarations for Bionic and notes when they were added with Lollipop. Some functions were added in between API 9 and 21, though not for 64-bit till API 21 obviously, so those were left uncommented, since they were added at different APIs for different CPU arches.
This pull is especially needed for the dmd 2.080 frontend, which switches to using them for CTFE …

Android: update core.stdc.math with real declarations

---

src/object.d

This PR alters the "hasCustomToHash" case of object.getArrayHash so changes in ordering perturb the hash of the sequence, and zeroes have some effect.

Fix Issue 18768 - object.getArrayHash with custom toHash shouldn't just sum hashes of array elements

---

src/core/memory.d

From https://github.com/dlang/dlang.org/blob/master/dlang.org.ddoc#L353
> The REF1 variants work around DDoc limitations and allow linking to
modules not inside packages (i.e. object.)
Argh...
See also: https://github.com/dlang/dlang.org/pull/2191

Use REF1 for references to object

---

src/core/stdc/config.d

And fix `cpp_ptrdiff_t` alias for 32-bit macOS.
Frontend support in https://github.com/dlang/dmd/pull/8262.

core.stdc.config: Add cpp_(u)longlong aliases

---

posix.mak
src/object.d
test/betterc/Makefile
test/betterc/src/test18828.d

I don't really like this fix, but I'm not sure how else to do it, and maybe this PR will elicit some ideas from others.

Fix Issue 18828 - [-betterC] helpless error in object.d

---

src/core/stdc/stdint.d

C++ `int64_t` is defined as `long long` on both 32/64-bit OS X, so use the appropriate alias defined in `core.stdc.config`.

[Trivial] OS X: Make core.stdc.stdint independent of D `long` C++-mangling

---

changelog/cpp_destroy.dd

Description is currently rendering like code.  See https://dlang.org/changelog/pending.html#cpp_destroy

Fix typo in changelog

---

src/object.d

This is a subset of https://github.com/dlang/druntime/pull/2184 to remove unnecessary imports from object.d when compiling with -betterC, yet without the controversy surrounding `nothrow` attribution in -betterC.
Although -betterC does not link with druntime or phobos, it still imports object.d. There is a large amount of code in object.d that not utilized when compiling with -betterC, but it is not versioned out like it should be, and that causes the compiler to emit errors for code that isn't even being utilized under certain circumstances.
It is likely future PRs will need to be made to hoist certain templates out of the version(Not_BetterC) area up to the version(D_BetterC)` area as users utilize -betterC more and file issues identifying certain language features that don't work in a …

Don't needlessly import everything in object.d when compiling with -betterC

---

src/core/internal/hash.d
src/rt/aaA.d

Fix Issue 18924 - Use addition rather than XOR for order-independent hash combination

---

src/core/internal/hash.d

This PR makes this pass:
```d
unittest
{
import core.internal.hash : hashOf;
assert(hashOf(null, 0) != hashOf(null, 123456789));
}
```

Fix Issue 18932 - core.internal.hash.hashOf(val, seed) ignores `seed` when val is a raw pointer

---

src/core/stdc/fenv.d
src/core/stdc/stdlib.d
src/core/sys/posix/fcntl.d
src/core/sys/posix/setjmp.d
src/core/sys/posix/signal.d
src/core/sys/posix/sys/ipc.d
src/core/sys/posix/sys/mman.d
src/core/sys/posix/sys/socket.d
src/core/sys/posix/sys/stat.d
src/core/sys/posix/sys/types.d
src/core/sys/posix/sys/uio.d
src/core/sys/posix/time.d

This is WIP, as right now it assumes llvm's brand of emulated TLS, which cannot be passed to the GC, so that part will have to change. Just putting this up early in case @ZombineDev or someone else wants to help with the Android/AArch64 port.

Bionic bindings for AArch64 and a Glibc/AArch64 fix

---

src/object.d

It is with great disappointment that I must revert #2194, which reduced imports in object.d when compiling with -betterC to just the language features supported by that subset of the language.
The problem is not actually with that PR per se, but rather with a fundamental design flaw in D:  There is no way to determine which code is needed at compile-time and which code is needed at runtime.
Users of -betterC may wish to employ features of D at compile-time that are not available in the -betterC subset of the language at runtime.  An obvious example is `pragma(msg, typeid(size_t));`.  That code, as ridiculous as it is, is currently possible in -betterC despite the fact that it requires `TypeInfo` which is a feature not available in -betterC at runtime.  If users are doing such things in …

Revert PR 2194 - Don't needlessly import everything in object.d when compiling with -betterC

---

src/object.d
test/betterc/Makefile
test/betterc/src/test18828.d

This is a followup to https://github.com/dlang/druntime/pull/2178
My fix was insufficient.  Although it fixed the compiler error, there was still a linker error.  Because we were copying two arrays, it was making a runtime call to `_d_arraycopy`.  Since the runtime is not linked in -betterC, it resulted in an unresolved reference error at link time.
See the implementation of `_d_arraycopy` at https://github.com/dlang/druntime/blob/4a1d176fb9f26441d16aa8ae12bb8beacc6e1972/src/rt/arraycat.d#L22.  It basically just forwards to `memcpy`, so the array copy code was simply replaced with a direct call to `memcpy`.
The test case was also updated to compile and link.
Sorry for the mistake.

Fix linker error in destroy under -betterC

---

src/rt/lifetime.d

Based on recommendation from @WalterBright 
See: https://forum.dlang.org/post/pfm73g$1ria$1@digitalmars.com

Clarify why we are doing a postblit when setting array length

---

src/core/stdc/stdlib.d
src/rt/profilegc.d
src/rt/trace.d

This PR is required for https://github.com/dlang/dmd/pull/8253.  Please read the motivation there for context.
~Despite the enabling features this provides for https://github.com/dlang/dmd/pull/8253, this PR is still quite useful and forward-looking.~
~Although -betterC does not link with druntime or phobos, it still imports object.d.  There is a large amount of code in object.d that not utilized when compiling with -betterC, but it is not `version`ed out like it should be, and that causes the compiler to emit errors for code that isn't even being utilized.  This is not only necessary for https://github.com/dlang/dmd/pull/8253, but also for other planned -betterC features like enabling the use of classes with only `static` members (See https://github.com/dlang/dmd/pull/8204 for an already …

Fix Issue 18493 - [betterC] Can't use aggregated type with postblit

---

src/core/stdc/stdio.d

Using a template means that druntime will not need to be linked in if these functions are used.

BetterC: use templates in core.stdc.stdio instead of functions

---

src/core/sync/semaphore.d

For example now, if i want to create a `NamedSemaphore` class, i have to copy and paste most of the code while i would only need to write a custom `this()` after the change proposed in this PR.

Set the semaphore handle `protected` instead of `private`

---

src/gc/impl/proto/gc.d
test/init_fini/Makefile
test/init_fini/src/test18996.d

The original behavior was to assert(false), but this is inconsistent with the standard GC, which ignores removal of ranges it didn't already know about.
The code in question, `Array!string`, whenever it would realloc, it would removeRange on the previous array, and addRange on the new one. Since it starts out with a null array, `removeRange(null)` was called.
Arguably, this is not behavior we want (`Array` could easily be changed to not try and `removeRange(null)`), but the `ProtoGC` shouldn't behave differently from the actual GC while it is in charge of things.
Added a simple test to make sure this doesn't happen again.

Fix issue 18996 - ProtoGC should support removing roots and ranges that were not originally added

---

changelog/backtrace_debug_info_macos.dd

At the end of the changelog entry, only the first line is rendered into the black box while the remaining lines are rendered outside the box.

Fix the backtrace changelog entry

---

src/core/internal/convert.d

Resubmission of https://github.com/dlang/druntime/pull/2224 to target stable.

Fix Issue 19008 - core.internal.convert.toUbyte doesn't work on enums

---

src/core/internal/convert.d
src/core/internal/hash.d

The default `hashOf` implementation used for types that do not have `toHash` uses `toUbyte` to get the byte representation which during CTFE requires allocation but during execution does not. The compiler currently takes CTFE-only code into account when inferring attributes but we can give it some help.
This PR is based on the premise that it is correct to label a function as `@nogc` if it only uses GC for CTFE interpretation. If that's not true then this PR should be rejected.

Fix Issue 19009 - core.internal.hash.hashOf default hash (absent `toHash`) should be `@nogc`

---

src/core/sys/posix/aio.d

Consists of two seperate commits:
1. Fix the previous implementation (#2074).
Note: ```ssize_t aio_return(const(aiocb)* aiocbp);``` should have been ```ssize_t aio_return(aiocb* aiocbp);``` (According to Linux, BSD's and [OpenGroup-Posix](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/aio.h.html) )
2. Add implementations for FreeBSD, NetBSD and DragonFly
Port Requested by @ibuclaw : https://github.com/dlang/druntime/pull/2074#issuecomment-370154627
Ping @Darredevil

Added aio.h implementations for FreeBSD, NetBSD and DragonFly

---

src/core/sys/posix/aio.d

The implementation of AIO isn't architecture specific in the slightest.

core.sys.posix.aio: Update CRuntime_Glibc bindings to be LARGEFILE64 aware

---

src/rt/backtrace/dwarf.d
src/rt/backtrace/elf.d
src/rt/backtrace/macho.d

This is an attempt at adopting #2172

Fix Issue 18068 - No file names and line numbers in stack trace

---

src/core/stdc/time.d

seems to have been switched from 100 to 1_000_000 with OSX 10.4/10.5

fix Issue 19046 - OSX: bad value for core.stdc.time.CLOCKS_PER_SEC

---

src/core/internal/convert.d
src/core/internal/hash.d

Example of what this PR will make pass:
```d
unittest
{
static struct S { string array; }
auto s1 = S("abc");
auto s2 = S(s1.array.idup);
assert(hashOf(s1) == hashOf(s2));
enum e = hashOf(S("abc"));
assert(hashOf(s1) == e);
}
```
The eventual goal is to make core.internal.hash usable as a replacement for `typeid(x).getHash(&x)` that doesn't require runtime type info (useful for `betterC`) and doesn't ignore `const`-correctness.

Fix Issue 18918 - core.internal.hash should perform memberwise hashing of structs with references

---

src/core/internal/convert.d
src/core/internal/hash.d

This PR reduces template proliferation by not using `auto ref` unnecessarily. Scalars, dynamic arrays, raw pointers, delegates, objects, and associative arrays don't need to be passed by reference to `hashOf`. Additionally by adding `const` where we know it's legal this PR lets IFTI produce fewer distinct instantiations. For instance we can avoid having separate template instantiations for `core.internal.hash.hashOf(const int(1))` and `core.internal.hash.hashOf(int(1))`. While I was doing this I also added `scope` when references are known not to escape.

Fix Issue 19048 - In core.internal.hash.hashOf reduce template bloat: remove `auto ref` where unneeded and add `const` where possible

---

src/core/stdc/stdlib.d
src/core/sys/posix/sys/types.d
src/rt/sections_android.d

This patch brings Bionic/AArch64 almost to parity with Glibc/AArch64 in terms of stdlib tests passing, see ldc-developers/ldc#2153.

Add fixes to get Android/AArch64 working

---

src/rt/dwarfeh.d
test/exceptions/Makefile

As `_d_print_throwable()` itself may throw multiple times when calling core.demangle, and with the uncaught exception still on the EH stack, this doesn't bode well with core.demangle's error recovery.
You can see this in the traceback that an `assert(0)` is hit (Illegal instruction).
```
uncaught exception
object.Exception@rt_trap_exceptions.d(14): this will abort
----------------
??:? int rt_trap_exceptions._main() [0xacdc668b]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll().__lambda1() [0xacdc6b2b]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xacdc6a06]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0xacdc6a9a]
??:? void …
```

rt.dwarfeh: Free current inflight exception before calling _d_print_throwable()

---

.circleci/run.sh
changelog/exceptions-opt.dd
src/core/internal/parseoptions.d
src/rt/dmain2.d
src/rt/dwarfeh.d
test/exceptions/Makefile
test/exceptions/src/rt_trap_exceptions_drt.d

See the changelog or http://arsdnet.net/this-week-in-d/2016-aug-07.html for a motivation.
> Hopefully, druntime will expose this variable in a more easier way in the future. Currently, on Windows, it is automatically set if a debugger is detected, but on Linux, debugger detection is quite a bit harder and hackier, so it might not happen any time soon. Druntime could (and should!) also potentially offer it as a command line switch, like it does with GC profiling now.
> DRUNTIME DEVS: if you read this, make it happen!
CC @adamdruppe

Fix Issue 18220 - Allow `rt_trapexceptions` to be set from the CLI

---

src/core/sys/posix/signal.d

Because the static if condition determining `__SI_PAD_SIZE` and `__SIGEV_PAD_SIZE` being default false, the overall size of `sigevent` and `siginfo_t` was 8 bytes too much, this affects all users of these types also, such as `core.sys.posix.aio`.

core.sys.posix.signal: Fix size of sigevent and siginfo_t on 64bit.

---

.circleci/config.yml

During the setup-repos stages, the PR is merged back into its respective target branch.
This should help issues like https://github.com/dlang/druntime/pull/2243#issuecomment-406562044 in the future.

CircleCi: run setup repos before installing dependencies

---

src/core/internal/hash.d
src/core/internal/traits.d

- Make hash of static arrays more efficient.
- More precise test for when memberwise hashing of structs is necessary (fewer false positives).
- Make required return type of `toHash` less brittle.
- Special handling for structs wrapping a single element (like std.typecons.Typedef).
_EDIT x6:_
- Infer `const scope` for some arrays.
- Fix Issue 19073 - core.internal.hash should not bitwise hash representations of floating point numbers
- As previously, `int` and `uint` have same hash.
- Infer `scope const` for some structs and unions.
- Infer `scope const` and remove unnecessary `auto ref` for some enums.
- Infer `scope const` and specialize for final classes that don't override `toHash`.

Fix Issue 19073 - core.internal.hash should not bitwise hash representations of floating point numbers, plus minor improvements and refactoring

---

src/core/internal/string.d

Implementation for https://github.com/dlang/dmd/pull/8521
This makes `dstrcmp` a template so it can be used from `object.__cmp` when compiling with -betterC.
See https://github.com/dlang/druntime/blob/cb5efa9854775c5a72acd6870083b16e5ebba369/src/object.d#L63
We don't have good testing infrastructure for -betterC in druntime.  I'm hoping reviewers can test locally by pulling down the druntime and dmd PRs and running `test/run.d test/runnable/betterc.d` from the dmd repository.
@wilzbach This PR pair is a good example of the kinds of things that we don't have good test infrastructure for.

-betterC: Add support for types when comparing arrays

---

mak/COPY
mak/SRCS
src/core/sys/freebsd/sys/mount.d
src/core/sys/posix/sys/statvfs.d
win32.mak
win64.mak

For some reason, FreeBSD's declarations for core.sys.posix.sys.statvfs are statfs declarations that come from sys/mount.h rather than sys/statvfs.h. This adds core.sys.freebsd.sys.mount and moves the statfs stuff to there and then adds the correct declarations to core.sys.posix.sys.statvfs.

Fix FreeBSD's statvfs

---

src/core/internal/string.d
src/object.d

This is all dead code (well, except for the unittest).  The idea is to verify this implementation first, merge it, then merge https://github.com/dlang/dmd/pull/8531 (assuming it passes all tests).

Convert _d_arraycast to template

---

dub.sdl

This is only to allow opening in IDEs and editors and have browsable sources in the project inspectors,
i.e not to build the runtime. For example in Coedit, this already works for dmd and phobos:

Add a DUB receipt

---

src/core/sys/posix/setjmp.d
src/core/sys/posix/ucontext.d

Tested with ldc ltsmaster.
Relevant headers:
https://github.com/freebsd/freebsd/blob/master/sys/arm64/include/setjmp.h
https://github.com/freebsd/freebsd/blob/master/sys/arm64/include/ucontext.h

Add setjmp/ucontext definitions for FreeBSD/aarch64

---

src/rt/config.d

It's pretty empty here:
https://dlang.org/phobos-prerelease/rt_config.html

Expose DRuntime config module header to the docs

---

src/core/simd.d

This is blocking https://github.com/dlang/dmd/pull/7065

Add overrides for __simd intrinsics

---

src/core/internal/hash.d
src/object.d
src/rt/aaA.d
src/rt/typeinfo/ti_Aint.d
src/rt/typeinfo/ti_Along.d
src/rt/typeinfo/ti_Ashort.d
src/rt/typeinfo/ti_C.d
src/rt/typeinfo/ti_byte.d
src/rt/typeinfo/ti_cent.d
src/rt/typeinfo/ti_char.d
src/rt/typeinfo/ti_dchar.d
src/rt/typeinfo/ti_int.d
src/rt/typeinfo/ti_long.d
src/rt/typeinfo/ti_n.d
src/rt/typeinfo/ti_ptr.d
src/rt/typeinfo/ti_short.d
src/rt/typeinfo/ti_ubyte.d
src/rt/typeinfo/ti_uint.d
src/rt/typeinfo/ti_ulong.d
src/rt/typeinfo/ti_ushort.d
src/rt/typeinfo/ti_wchar.d
src/rt/util/typeinfo.d

Each hash function in `core.internal.hash` currently has the form:
```d
size_t hashOf(T)(auto ref T val, size_t seed = 0);
```
This PR changes it to:
```d
size_t hashOf(T)(auto ref T val, size_T seed);
size_t hashOf(T)(auto ref T val);
```
This allows the non-"chained" form to be distinguished from the chained form, which avoids unnecessary work for types for which `hashOf` is not a wrapper around `bytesHash`.
The impetus for this was seeing the needless rehashing @IgorStepanov had to perform in https://github.com/dlang/druntime/pull/2243 to make `typeid(T).getHash(&val)` produce the same result as `hashOf(val)`.

Fix Issue 19071 - core.internal.hash should have non-chained toHash overloads

---

src/core/stdc/config.d

That was only necessary while DMD was mangling long as C++ `long long` on 64-bit OSX, i.e., in 2.079-2.081.
This is required for 2.082-based LDC to build itself successfully on 64-bit Linux (conflicting `Array!ulong` vs. `Array!__c_ulong` template instantiations with identical C++ mangling...).

[stable] core.stdc.config: Don't define cpp_[u]long as special enum on 64-bit Posix

---

posix.mak

tl;dr: there are some things which are really hard to add to the auto-tester, but should really run on all dmd,druntime and phobos repositories. Adding such tests separately to the existing CircleCi setups is painful (and we want to retire CircleCi anyhow), so we want to be able run the full testsuite on Buildkite too (and do customizations to it.)
For now, it's equivalent to auto-tester's target though.
See also:
- https://github.com/dlang/ci/pull/287
- https://github.com/dlang/phobos/pull/6669
- https://github.com/dlang/dmd/pull/8590

Add buildkite-test target

---

src/core/stdc/time.d

This is a rebase of https://github.com/dlang/druntime/pull/2287 on stable.

Fix issue 19177: add clock() and CLOCKS_PER_SEC for Solaris

---

src/core/internal/convert.d

This is a WIP pull, as I'm going to add another commit that reworks how druntime initializes TLS data on Android before passing it to the GC, based on a suggestion of Martin from the ldc team. I wanted to get this first math commit up now to run it through the CI and review, as this one should be done.
I've tested this commit with ldc 0.17 natively on Android/AArch64 and linux/AArch64, and by cross-compiling with ldc 1.11 master for Android/AArch64 (all tests build and pass, but only because they're all truncated at 80-bit precision), along with making sure it didn't break anything on linux/x64. With this patch, all the druntime unit tests finally compile and pass on AArch64.

core.internal.convert: add IEEE Quadruple support

---

src/core/stdc/stdint.d

In VS 2017's `stdint.h`, `int32_t` is a typedef for `int`, not `long`; also verifiable on [MSDN](https://msdn.microsoft.com/en-us/library/323b6b3k.aspx) (incl. VS 2015). I haven't checked DMC for conformance.
This also fixes one part of [issue 19249](https://issues.dlang.org/show_bug.cgi?id=19249).

[stable] core.stdc.stdint: Fix some aliases for Windows/MSVC

---

benchmark/gcbench/conmsg.d

Avoid issues with https://github.com/dlang/phobos/pull/6716 : preemptively make std.json const correct.
See also https://issues.dlang.org/show_bug.cgi?id=19256

Fix use of std.json in gcbench.conmsg

---

src/core/stdc/stdint.d

Requires https://github.com/dlang/dmd/pull/8729 to be merged first.

[stable] core.stdc.stdint: Fix some [u]int_fast<N>_t aliases for Win64 and FreeBSD

---

src/core/time.d

`QueryPerformanceCounter` doesn't fail on Windows XP or later.
https://msdn.microsoft.com/en-us/library/windows/desktop/ms644904(v=vs.85).aspx
`gettimeofday` called with a valid timeval address and a null second parameter doesn't fail.
http://pubs.opengroup.org/onlinepubs/9699919799/functions/gettimeofday.html
`clock_gettime` called with a valid clock_id and a valid timespec address is in principle allowed to fail if the number of seconds doesn't fit in time_t, so even though no known implementation does this it is probably best to retain the error check at this time.
http://pubs.opengroup.org/onlinepubs/9699919799/functions/clock_getres.html

Fix Issue 19280 - Remove unnecessary error checks in core.time.currSystemTick

---

src/core/internal/hash.d
test/hash/src/test_hash.d

Without this PR the following code crashes:
```d
extern(C++) class SomeCppClass {}
void main()
{
SomeCppClass c = new SomeCppClass();
size_t h = .hashOf(c);
}
```

Fix Issue 19282 - hashOf segfaults for non-null C++ objects

---

src/core/thread.d
src/core/threadasm.S

Currently in GDC, when throwing an Exception in the Fiber the backtrace generation crashes. GDB backtrace generation also tries to generate some more function frames as it does not find the stack bottom. `Using .cfi_undefined x30` tells the debug info that the value in the lr is unknown, which seems to be the nicest way to stop the unwinder. Setting `x30` to 0 is another option, however it still creates one invalid frame in gdb, so the `.cfi` variant is used here.
We need to introduce an extra function for this, as we can't do it in fiber_entryPoint directly and it cannot be in fiber_switchContext either.
The root problem is that fiber_switchContext effectively always generates a function return, i.e.:
* Set link register lr to destination
* Jump to destination
Which is correct most of …

[AArch64] [GDC] AArch64: Fix backtraces in Fibers

---

src/rt/sections_elf_shared.d

~~**NOTE**: I'll close this PR once tests have ran, or if some fail, I'll add some extra debugging for comparison.~~
~~I am curious to know if DMD generates code that could suffer from a heisenberg I'm seeing with GC scanning in dynamic executables.~~
Sometimes the p_vaddr for a data segment may not start at an address that is aligned for the target (in my case, x86_64, and the start address is aligned to 4 bytes).
```
#0  0x00002accccd3ff2d in gc.gc.Gcx.mark() (this=..., pbot=0x600ce4, ptop=0x601000) at /home/runner/GDC/libphobos/libdruntime/gc/gc.d:2060
(gdb) p pbot
$1 = (void *) 0x600ce4
(gdb) p *(void**) 0x600ce4
$2 = (void *) 0x4008a000000000
(gdb) p (void**)(((size_t)pbot + 7) & ~7)
$3 = (void **) 0x600ce8
(gdb) p *(void**) 0x600ce8
$4 = (void *) 0x4008a0 <frame_dummy>
```
The …

Ensure that the writable data segment is aligned.

---

src/rt/sections_elf_shared.d

An `assert(0)` in the release libs yields an "invalid instruction" error, which isn't very helpful for troubleshooting.
Normal assertions (throwing `AssertError`s) aren't really usable as the GC may not be initialized (yet or anymore).

rt.sections_elf_shared: Replace (almost) all runtime assertions by abort()

---

test/aa/src/test_aa.d
test/exceptions/src/static_dtor.d
test/hash/src/test_hash.d

Bugs may come from a vagary of issue trackers (dmd, gdc, gcc, ldc), so is good to be explicit.

[testsuite] Replace issue numbers with bugzilla urls

---

src/core/stdcpp/exception.d
src/core/stdcpp/typeinfo.d

Look at the list of commits for a full description of what is being done.
This does not pass currently, because of what I suspect to be a DMD bug, but will check this weekend.
@TurkeyMan you might be interested in it.
We really need to document this test-suite better.

Refactor core.stdcpp to use extern(C++, string) and CppRuntime_* versions

---

src/core/stdc/stdio.d

Importing windows.d makes anything importing stdio.d painfully slow.

don't include windows.d in stdio.d

---

src/gc/impl/conservative/gc.d
test/thread/Makefile
test/thread/src/external_threads.d

Part of https://issues.dlang.org/show_bug.cgi?id=19288
Issue comes from combination of two factors:
1) Calling `thread_attachThis` does `new Thread` as part of its
implementation (because any thread context has to be wrapped into
Thread class for registration in runtime).
2) Current GC implementation is not prepared to be called from external
thread context and will crash in several places if `Thread.getThis`
returns `null`.
There are different possible fixes but it seems that the least intrusive
one is to simply skip collection when called from the context of
unregistered thread. Worst thing it can possibly do for any other code
not affected by the issue is to delay garbage collection a bit.

Fix crash on attaching external threads

---

src/core/exception.d

Not fully sure about this as the `SwitchError` does contain a lot more information.
Maybe we should version this and only use `assert` in betterC and otherwise throw the exception?

[RFC] Issue 19087 - final switch cannot be used in -betterC

---

src/core/thread.d
test/thread/src/external_threads.d

Part of https://issues.dlang.org/show_bug.cgi?id=19288
Expectation is that after thread is detached from druntime, it becomes
responsibility of external environment to terminate it properly (for
example, by calling `join` from C/C++ code).
However, `Thread` object for that thread will still remain and will
eventually be collected by GC. Destructor tries to call `pthread_detach`
unconditionally but it is undefined behaviour if thread was alread
joined before (see `man pthread_detach`).
This fix invalidates thread object when it is detached so that
destructor can't conflict with external thread management code.

Fix crash in destructor of detached thread

---

src/core/internal/traits.d

See https://github.com/dlang/phobos/pull/6402

Port more efficient allSatisfy/anySatisfy from dlang/phobos#6402

---

src/rt/dwarfeh.d

We should explicitly remove our reference to the caught Throwable, such that there are no lingering references to it. 
This enables the code in line 71 to work (where we want to reuse the preallocated ehstorage). Without this patch, only the very first exception thrown is using `ehstorage` and all other exceptions cannot use that struct any more because of the dangling ehstorage.object reference.

Dwarf EH: explicitly remove our reference to caught Throwable

---

src/core/internal/hash.d
test/hash/src/test_hash.d

Example of non-compiling code that this PR fixes:
https://run.dlang.io/is/46J93Z
```d
struct NotOkay
{
int canBitwiseHashInts;
size_t toHash() /* not const */ { return 0; }
}
struct Okay
{
float cantBitwiseHashFloats;
size_t toHash() /* not const */ { return 0; }
}
void main()
{
const okay = Okay.init;
hashOf(okay); // Compiles but writes a message about the non-callable toHash.
const notOkay = NotOkay.init;
hashOf(notOkay); // Compilation fails!
}
```

hashOf fails to compile for const struct that has non-const toHash & has all fields bitwise-hashable

---

src/core/stdc/fenv.d
src/core/sys/posix/aio.d
src/core/sys/posix/ucontext.d

Posted and reviewed on gcc-patches, I suspect it's only enough support needed in order to have an initial build, it's a start at least.

Add druntime bindings for Solaris/SPARC

---

.editorconfig
changelog/array.dd
mak/COPY
mak/DOCS
mak/SRCS
mak/WINDOWS
posix.mak
src/core/stdcpp/array.d
src/core/stdcpp/xutility.d
test/common.mak
test/stdcpp/Makefile
test/stdcpp/src/array.cpp
test/stdcpp/src/array_test.d
test/stdcpp/win64.mak
win64.mak

First and simplest of the bunch. I'd like to get this in to establish layout and styling for the others.

Added std::array<>

---

src/core/stdc/fenv.d
src/core/sys/posix/config.d
src/core/sys/posix/fcntl.d
src/core/sys/posix/setjmp.d
src/core/sys/posix/signal.d
src/core/sys/posix/sys/ipc.d
src/core/sys/posix/sys/mman.d
src/core/sys/posix/sys/socket.d
src/core/sys/posix/sys/stat.d
src/core/sys/posix/sys/types.d
src/rt/sections_android.d

This ~is a WIP~ pull is ready, ~as~ I'm going to add another commit (__Update:__ in a later pull) that reworks how druntime initializes TLS data on Android before passing it to the GC, based on a suggestion of Martin from the ldc team.
This first commit adding Bionic/x64 declarations and consolidating where possible is pretty much done, so putting it up for review. All druntime tests for Android/x86 and x64 pass when cross-compiled from linux/x64 to Termux running in [an Anbox Android/x64 container](https://anbox.io).
Pretty much the same Phobos tests pass as other Android platforms, ie only some math-related modules like `std.math` or `std.internal.math.gammafunction` assert, with the only difference that ~`std.random` asserts or segfaults in the massive last test block on both x86/x64 …

Bionic: Add x64 declarations, switch to single TLS function, and define __USE_GNU

---

src/core/atomic.d

https://forum.dlang.org/thread/vzzitsnvsxljscrzbcnm@forum.dlang.org
"Hoist-load", "hoist-store", "sink-load", and "sink-store" are used in the documentation but they're not formally defined. A full description would be nice but minimally linking to an external site makes the documentation more useful.

Fix Issue 19398 - Document meaning of core.atomic.MemoryOrder

---

src/core/internal/hash.d

MurmurHash3 is optimized for long inputs. For short inputs a byte-oriented hash function can be faster. In my informal benchmarking using `ldc2 -O2 -release` FNV is faster than MurmurHash3 for inputs of around 10 bytes and fewer which is [similar to what others have reported](https://aras-p.info/blog/2016/08/09/More-Hash-Function-Tests/#conclusions).

core.internal.hash prefer FNV to MurmurHash3 for short sequences of statically known length

---

src/core/internal/traits.d

As https://github.com/dlang/phobos/pull/6763

Make allSatisfy public so it can be unified with std.meta

---

src/rt/sections_elf_shared.d

Running all druntime unittests, this is the only place where an X32 regression was found, the effect seen was that live TLS data was being collected and freed at runtime.

rt.sections_elf_shared: Fix struct tls_index definition on x32

---

src/core/internal/convert.d
src/core/internal/hash.d

The exact contents of the padding is not specified. Usually it's 0, but some optimizations in GDC sometimes lead to different padding content.
* For floating point types without padding, the code is unchanged.
* For real or imaginary types with padding, just ignore the trailing padding.
* For complex types where the real/imaginary types have padding, we can't hash the value as one contiguous memory block, as there will be a padding 'hole'. Here, hash real and imaginary part
individually. Complex types without padding are still hashed as one memory block.
ping @ibuclaw

[GDC] Do not include padding when hashing floating point types

---

src/core/stdc/fenv.d
src/core/stdc/math.d
src/core/sys/linux/dlfcn.d
src/core/sys/linux/epoll.d
src/core/sys/linux/link.d
src/core/sys/linux/sys/eventfd.d
src/core/sys/linux/sys/inotify.d
src/core/sys/linux/sys/mman.d
src/core/sys/posix/dlfcn.d
src/core/sys/posix/fcntl.d
src/core/sys/posix/setjmp.d
src/core/sys/posix/signal.d
src/core/sys/posix/sys/mman.d
src/core/sys/posix/sys/msg.d
src/core/sys/posix/sys/socket.d
src/core/sys/posix/sys/stat.d
src/core/sys/posix/ucontext.d
src/rt/sections_elf_shared.d

Tested on riscv-qemu.
```
function qemu_risv {
~/riscv-qemu/build/./riscv64-linux-user/qemu-riscv64 \
-L /usr/riscv64-linux-gnu \
-E LD_LIBRARY_PATH=~/gdc/riscv/riscv64-linux-gnu/libgcc $@;
}
for test in $(qemu_risv ./unittest_static); do
qemu_risv ./unittest_static $test;
done
0.010s PASS release64 core.atomic
0.001s PASS release64 core.bitop
0.001s PASS release64 core.checkedint
0.129s PASS release64 core.demangle
0.002s PASS release64 core.exception
0.031s PASS release64 core.internal.arrayop
0.000s PASS release64 core.internal.hash
0.002s PASS release64 core.internal.parseoptions
0.001s PASS release64 core.internal.string
0.000s PASS release64 core.math
0.004s PASS release64 core.memory
0.000s PASS release64 core.stdc.stdlib
0.027s PASS release64 core.sync.barrier
0.044s PASS …
```

Add support for RISCV{32,64} to glibc bindings

---

src/core/sys/posix/sys/msg.d

This more closely matches how glibc arranges all port headers (all the arch/bits/msq.h sources are now removed).

[refactor] core.sys.posix.msg: Genericize msqid_ds definition

---

src/object.d

...so that the documentation reflects that fact.

Make `assumeSafeAppend` explicitly `@system`

---

src/core/sys/linux/sys/mman.d

This was not picked up when rebasing #2355.

core.sys.linux.sys.mman: Group all CPU versions together

---

src/core/stdc/time.d

Preferably this needs to be looked at by @WalterBright. May break some third-party code. Phobos tests passed though.

Fix Issue 11168: attributes for functions in core.stdc.time.

---

src/object.d

```
This was introduced in PR 2366.
While the workaround is not needed, the unittest is useful,
and as such the PR was not reverted.
```
CC @radcapricorn

Remove unnecessary workaround

---

changelog/destroy_noinit.dd
src/object.d

Fixes Issue 19214 - Support object.destruct() for efficient (and correct!) destruction
Implement via template argument to `destroy` as discussed in https://github.com/dlang/druntime/pull/2292

destroy() receives initialize argument

---

posix.mak
win32.mak
win64.mak

All unittests pass when compiled with gdc.  Don't need to bother wasting auto-tester time here.

[dmd-cxx] Disable auto-tester-test from running

---

src/rt/dmain2.d

To avoid problems with shifting definitions of `WCHAR`.

use WCHAR instead of wchar_t when interfacing to Windows API

---

src/core/stdc/errno.d

[Trivial] Fix core.stdc.errno for dragonflybsd
Old Code would result in:
```
src/core/memory.d(914): Deprecation: core.stdc.errno.getErrno is not visible from module memory
src/core/memory.d(917): Deprecation: core.stdc.errno.setErrno is not visible from module memory
```

[Trivial] Fix core.stdc.errno for dragonflybsd

---

src/rt/minfo.d

Make it clear that the dependency cycle is between module ctors/dtors, otherwise users may be misled to fix the non-existent problem of cyclic imports.

Fix issue 19468: improve cyclic dependency error message.

---

src/rt/sections_osx_x86.d
src/rt/sections_osx_x86_64.d
src/rt/sections_solaris.d
src/rt/sections_win32.d
src/rt/sections_win64.d

Notably, Solaris doesn't build because:
```
error: @nogc function 'rt.sections_solaris.initSections' cannot call non-@nogc function 'rt.sections_solaris.SectionGroup.moduleGroup'
```

rt/sections.d: Update SectionGroup signatures to match on all targets

---

src/object.d

Removes one `version(unittest)` block.

Remove private isnan function with only one caller

---

mak/COPY
mak/DOCS
mak/SRCS
mak/WINDOWS
src/core/internal/utf.d
src/rt/aApply.d
src/rt/aApplyR.d
src/rt/adi.d
src/rt/cover.d

This is the first step in reusing some of druntime's `utf.d` implementations in Phobos.
Please see [forum](https://forum.dlang.org/post/ahieisavseagdkzvexps@forum.dlang.org) discussion.

Make rt utf publicly available

---

src/core/thread.d
src/gc/impl/conservative/gc.d

The only targets I'm aware of where version != StackGrowsDown are PA-Risc and Sanyo's Stormy16 (we don't care about the latter, however).
Regarding rationale of fix, see documentation of `pthread_attr_getstack`:
http://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_attr_getstack.html
> The base (lowest addressable byte) of the storage shall be stackaddr, and the size of the storage shall be stacksize bytes.
So the implementation of this function should look something like the following:
```
int pthread_attr_getstack (in pthread_attr_t* attr, void** stackaddr, size_t* stacksize)
{
auto iattr = cast(pthread_internal_attr *)attr;
version (StackGrowsDown)
*stackaddr = iattr.stackaddr - iattr.stacksize;
else
*stackaddr = iattr.stackaddr;
*stacksize = iattr.stacksize;
return 0;
}
``` …

 core/thread: Support StackGrowsUp in getStackBottom()

---

src/rt/arrayassign.d

Fix issue 19128 - argument to alloca may be too large

---

src/gc/impl/conservative/gc.d

add bins with about 3/2 of existing sizes
As @kinke noticed when enabling the GC for dmd (see https://github.com/ldc-developers/ldc/pull/2916), about 40% more memory is used than with the bump-pointer-allocation. This PR should drop the overhead to approximately 15% (similar to the overhead when using C malloc).
The example in the bugzilla report drops from 247 MB to 176 MB.
Unfortunately, std.experimental.gc_allocator makes some assumptions about the GC that are not guaranteed and are only valid for the existing GC (and might also break if you use another replacement GC).

fix issue 19455 - GC wastes too much memory

---

src/gc/bits.d

Extracted from #2418. I removed the unused changes to BitRange and the slightly complicated optimization that won't be hit with the large object pool optimization anymore for 64-bit systems and is also very unlikely to make a big difference for 32-bits.

add range operations to GCBits to help copying bitmaps in a precise GC

---

src/core/checkedint.d

Do this by making everything in checkedint a zero-argument template function. The risk is that this changes the function mangling and may cause `mulu` etc. to cease being intrinsic functions if a compiler had been handling them specially, although DMD does not appear to have been doing this.

Fix Issue 19524 - Make core.checkedint work in betterC

---

src/core/memory.d
src/gc/impl/conservative/gc.d

keep track of free bits during malloc and free, so that it can be checked when determining pointer validity
this also avoids having to "prepare" them during collection

fix Issue 19522 - [GC] GC.query/addrOf/sizeOf fail for freed memory

---

src/gc/impl/conservative/gc.d

while debugging #2436 I noticed an issue introduced by #2430.

fix spurious crashes/freezes due to corruption in GC.realloc caused by #2430

---

changelog/gc_realloc.dd
src/core/memory.d
src/gc/impl/conservative/gc.d
src/rt/lifetime.d

fix Issue 11446 - [GC] GC realloc doesn't ignore non-GC owned pointers
changed specification of GC.realloc to something more robust:
- return null for failure (returning the original pointer is no indication of failure as it might also be returned on success. This can easily lead to overwriting memory)
- allow freeing old memory immediately (previous implementation did this for large objects when shrinking)
- only set attribute bits on existing block if reused (previous implementation didn't set bits if it reused a small block)
refactor realloc to match that spec

fix Issue 11393 - [GC] GC realloc and free don't ignore interior pointers

---

changelog/emplace.dd
mak/COPY
mak/DOCS
mak/SRCS
mak/WINDOWS
src/core/internal/traits.d
src/core/lifetime.d

`destroy()` is in object.d, which makes sense, because one of the most primitive operations you can perform is to cause destruction of an object.
Strangely, we can't construct objects though... because `emplace()` is in phobos, which isn't helpful for projects that don't link phobos. (it's huge, and it's not `nothrow @nogc`)
I think `emplace()` really needs to live right next to `destroy()`; it's a direct counterpart, so here it is.
If this is accepted, we'll make phobos emplace alias this one moved here.

Move `emplace` to druntime for symmetry with `destroy`.

---

changelog/core-memory-gc-profile-stats.dd
mak/COPY
mak/SRCS
src/core/memory.d
src/core/sys/freebsd/pthread_np.d
src/gc/gcinterface.d
src/gc/impl/conservative/gc.d
src/gc/impl/manual/gc.d
src/gc/impl/proto/gc.d
src/gc/proxy.d

Add access to GC runtime profile stats

---

src/core/thread.d

- all zero initializers are not stored in the typeinfo although
classes currently always come with a non-zero vtable
fixup for #2079

zero class storage when initializer is null

---

changelog/cpp_new.dd
changelog/std_allocator.dd
mak/COPY
mak/DOCS
mak/SRCS
mak/WINDOWS
src/core/stdcpp/allocator.d
src/core/stdcpp/new_.d
src/core/stdcpp/xutility.d
test/common.mak
test/stdcpp/Makefile
test/stdcpp/src/allocator.cpp
test/stdcpp/src/allocator_test.d
test/stdcpp/src/new.cpp
test/stdcpp/src/new_test.d
test/stdcpp/win64.mak

Final piece of foundation before `std::string` and `std::vector` can move in.

std::allocator

---

changelog/emplace.dd
src/core/internal/traits.d
src/core/lifetime.d

WIP, I still need to wrangle phobos dependencies...

Moved `move`, `moveEmplace`, and `forward` to `core.lifetime`

---

src/core/internal/hash.d
src/rt/typeinfo/ti_byte.d
src/rt/typeinfo/ti_cent.d
src/rt/typeinfo/ti_int.d
src/rt/typeinfo/ti_long.d
src/rt/typeinfo/ti_short.d

There is not a reason to keep this and removing it lets us remove a template.

Don't avoid sign-extension when hashing byte/short/int

---

src/core/demangle.d

Normally `-dip1000` infers the `return`, but when compiling code that links to druntime without `-dip1000` and with `-inline`, it doesn't get inferred so we add it manually. In particular, runnable/testconst.d.
This is blocking https://github.com/dlang/dmd/pull/9220

dmangle.d: add 'return' to constructor args

---

changelog/gc_cleanup.dd
src/gc/config.d
src/gc/proxy.d

This is another change I meant to do for a while, see changelog entry for details.
The druntime benchmarks dlist, slist and vdparser benefit from this by running 10-20% faster on Win32, hardly noticable on Win64, though. This happens because Win32 runs fewer collection but uses more memory (probably due to false pointers), with the last collection taking up to half a second for the dlist test.
Please note that the final collection is currently also run if the GC is disabled.

GC cleanup can now be configured as a DRT GC option

---

mak/SRCS
src/core/stdcpp/exception.d
src/core/stdcpp/new_.d

This had old-style virtual destructors. Also, there's a lot more commonality in the code than the original makes it appear.

Overhaul of std::exception

---

changelog/assert.dd
mak/COPY
mak/SRCS
mak/WINDOWS
src/core/internal/dassert.d
src/object.d
test/exceptions/Makefile
test/exceptions/src/assert_fail.d

Requires https://github.com/dlang/dmd/pull/8517
This adds `_d_assert_fail` to `object.d` which allows for nicely formatted and informative error messages on an assertion failure.
```
int a = 1, b = 2;
assert(a == b); // 1 != 2 (and no longer) 
```
Compare at the moment, it would yield sth. like `core.exception.AssertError@onlineapp.d(4): Assertion failure`. But I think we all agree that we can do better.
The printing supported added here is pretty minimalistic as
- this is still behind a version flag
- the program will terminate after this formatting (so saving a few bytes isn't a huge concern)
- Phobos shouldn't be used to reduce the compilation overhead of this feature
tl;dr: yes, the formatting can be improved (and should be before this feature gets activated by default), but this PR …

_d_assert_fail: Add formatting for Assertion errors

---

src/core/stdc/limits.d

The only one of interest to me is `PATH_MAX`, needed for a portability bug fix in dmd.
Ping the port maintainers @joakim-noah @jacob-carlborg @dkgroot @nrTQgc @redstar for adding missing systems.

core.stdc.limits: Define some common filesystem limits

---

src/core/stdc/limits.d

Followup on https://github.com/dlang/druntime/pull/2460 for Darwin.

Add constants for file system limits for Darwin

---

src/rt/ehalloc.d
src/rt/lifetime.d

The initializer member is a virtual function call, potentially called at least three times without inline in both _d_newThrowable and _d_newclass.
Couldn't see any other place where this pattern was used in druntime.

rt: Remove side-effects from 'p[0..ci.initializer.length] = ci.initializer[]'

---

src/core/sys/posix/aio.d

@jacob-carlborg - Answer, yes.

core.sys.posix.aio: Use version Darwin instead of OSX

---

src/core/stdc/assert_.d
src/core/stdc/wchar_.d
src/core/sys/netbsd/dlfcn.d

Uncomment dlinfo, provide assert and mbstate_t
The one patch I have left for is that I had trouble using src/core/sys/netbsd/execinfo.d with GDC, it didn't seem to provide `D_InlineAsm_X86_64` or `D_InlineAsm_X86` (I am building on x86-64)
I worked around it by providing a declaring matching [libexecinfo](https://man-k.org/man/NetBSD-current/3/backtrace?r=1&q=backtrace) but that required supplying -lexecinfo.
One remaining issue I have to resolve is that time_t (src/core/sys/posix/sys/types.d:177) is considered c_long, it is actually 64bit on all archs, but only if you use the newer functions.
NetBSD has a funky way of updating libc functions, where it relies on the inclusion of headers to use the new functions (as opposed to relying on the linker with symbol versioning), which is a …

Basic NetBSD support needed to build GDC

---

src/core/stdc/stdio.d
src/core/stdc/wchar_.d

It's the one remaining platform that still has an alias in core.stdc.stdio.

[Solaris] core/stdc/wchar_.d: Move alias for mbstate_t here

---

src/object.d

`object.d` had some weird indentation (leading whitespace) in some places.
While cleaning this up, I also noticed that not all the `unittest`s had `@safe`/`@system` so I added those as well.

Remove leading whitespaces in object.d

---

src/gc/gcinterface.d

This is currently blocking [1]. A few explanations: before this patch, whenever 2 Range objects were compared for equality (`==`/`!=`), the comparison would have been made directly between the aliased this members (in this case `lhs.pbot == rhs.pbot`). That comparison is a bitwise one so it's nothrow. After the 
dmd patch, the comparison is going to be made using the generated opEquals (which bitwise compares the basic types and uses the opEquals of subfields); since Range has a TypeInfo member, its opEquals is going to get call which may throw. That will make this line [2] to fail compilation, because all the opApply functions expect a `nothrow` delegate, while the foreach body contains a call to a throwing opEquals [3]
[1] https://github.com/dlang/dmd/pull/9289
[2] …

Add opEquals to gc.gcinterface.Range

---

test/gc/precisegc.d

It makes no sense to have the assert before debug print.
Also, the assert was producing heisenbugs.

precisegc.d: copy-pasta bug fix

---

src/rt/qsort.d

Backport to fix PR d/88127.
As I said in review, I suspect glibc is not the only C library that may not have had this implemented in older releases.  That depends on how far back we want to support though...  Not a blocker for anything, just that this may change in future.

[dmd-cxx] GCC bug 88127: qsort_r is not available in old glibc

---

src/rt/sections_elf_shared.d

These destructors are superfluous. In addition, they block [1] because some structs that are used to instantiate array and hashtab are destroyed manually (_loadedDSO[3]/_handleToDSO[4]). For more information see: [1], [2].
[1] https://github.com/dlang/dmd/pull/8688
[2] https://forum.dlang.org/thread/lykddibnholrmtkotzxq@forum.dlang.org
[3] https://github.com/dlang/druntime/blob/master/src/rt/sections_elf_shared.d#L328
[4] https://github.com/dlang/druntime/blob/master/src/rt/sections_elf_shared.d#L340

Replace module-level data with Meyers singletons

---

src/core/internal/dassert.d
test/exceptions/src/assert_fail.d

Requires https://github.com/dlang/dmd/pull/9264

Add support for the in operator in dassert

---

src/core/sys/linux/sys/eventfd.d

uClibc uses some different definitions see: https://github.com/kraj/uClibc/search?q=EFD_NONBLOCK&unscoped_q=EFD_NONBLOCK

[uClibc][core.sys.linux.sys.eventfd] Fix definitions for mips and sparc

---

src/rt/util/container/array.d
src/rt/util/container/common.d
src/rt/util/container/hashtab.d

Benefit is for an alternative method of running unittests that I'm testing for gdc.
Builds and runs each module separately, rather than compile all with `-unittest`.  Only array and hashtab failed due to missing symbols.

rt.util.container: Templatize struct RC

---

test/shared/src/load.d

The OS-specific bindings are only required for getting `RTLD_NOLOAD`.
Everything else is covered by the Posix bindings.

test/shared: Support more platforms in test

---

src/core/sys/posix/sys/stat.d

It was found that both st_nlink and st_blksize were the wrong size on RISCV64, as well as st_blocksize missing entirely.
Both AArch64 and RISCV use glibc generic headers, so should have identical layouts.
(There is a clean-up that's begging to be done here, as this block will be duplicated across many targets, but that can be kicked down the road for later).

RISCV: Fix stat_t definition to match AArch64

---

posix.mak

Analog to https://github.com/dlang/dmd/pull/9392

Disable OSX-32 on the auto-tester

---

mak/COPY
mak/SRCS
mak/WINDOWS
src/core/internal/lifetime.d
src/core/lifetime.d

Move `emplaceRef` to `core.internal.lifetime` so we can remove the code duplication from Phobos.
`emplaceRef` is intentionally non-ddoc'ed

Move emplaceRef to core/internal

---

win64.mak

The escaping is required for https://github.com/dlang/dmd/pull/9398.

Quote variables in win64.mak

---

win64.mak

Reverts dlang/druntime#2499 (as it appears to have broken win-farm2)

Revert "Quote variables in win64.mak"

---

posix.mak

Part 2 of https://github.com/dlang/phobos/pull/6883

Disable OSX-32 on the auto-tester (build)

---

mak/COPY
mak/DOCS
mak/SRCS
mak/WINDOWS
posix.mak
src/core/gc/config.d
src/core/gc/gcinterface.d
src/core/gc/registry.d
src/gc/impl/conservative/gc.d
src/gc/impl/manual/gc.d
src/gc/impl/proto/gc.d
src/gc/proxy.d
test/init_fini/src/custom_gc.d

This allows compiling new GC implementations without requiring adding an import path to druntime/src.
Not sure if this is better than just adding the 3 gc-files to the import folder as is. Comments?

move modules necessary to implement a GC to core.gc

---

win64.mak

...not when setting variable. This avoids having to skillfully quote variables with spaces in them: use `"CC=%cl64%"` instead of `"CC=\"%cl64%\""`
Not sure how the existing misquoting was supposed to work. Using quotes with the command is agnostic to using `/` instead of `\` as a path separator, too.

fix quoting in win64.mak: add them only when invoking command

---

src/gc/impl/conservative/gc.d
src/rt/lifetime.d

LDC is picky about this: https://github.com/dlang/druntime/blob/f2276846d53306cb8e2832fc0319c1ac89eddd71/src/core/exception.d#L590

[stable] gc.impl.conservative.gc: Fix fwd declaration signature

---

src/gc/impl/conservative/gc.d

missing start time initialization without GC option profile:1

fix Issue 19723: wrong time values in GC.profileStats

---

src/core/internal/dassert.d
src/core/internal/traits.d
src/object.d
test/exceptions/src/assert_fail.d

The program will be terminated after the assertion error message has been printed and its not considered part of the "main" program. Also, catching an AssertError is Undefined Behavior.
Hence, we can fake purity and @nogc-ness here.
An alternative would be to directly ignore the `assert` message expression directly in DMD's type checker (see e.g. https://issues.dlang.org/show_bug.cgi?id=15100 for this).

Fix Issue 19635 - -checkaction=context not working with attributes

---

changelog/core_sync_event.dd
mak/COPY
mak/DOCS
mak/SRCS
mak/WINDOWS
src/core/sync/config.d
src/core/sync/event.d

extracted from https://github.com/dlang/druntime/pull/2514

add core.sync.event to be used as Windows events

---

mak/WINDOWS

Noticed in some logs, e.g. https://ci.appveyor.com/project/greenify/druntime/builds/23381487#L163
Not sure why the copy failure doesn't cause the build to fail.

Windows: not all import folders created

---

src/core/stdcpp/array.d

Due to a  bug in dmd, there was an implicit cast inserted by the compiler. This is currently blocking [1]. For more information check [1]
[1] https://github.com/dlang/dmd/pull/9505

Fix implicit cast issue in stdcpp.array

---

src/gc/impl/conservative/gc.d

This simple change is what yields the larger time difference of https://github.com/dlang/druntime/pull/2520#issue-263920143, i.e. reduces execution time of the vdparser-test from approx. 10.5 s to 7.5 s.

GC: optimize alloc of small object by keeping track of unused pages

---

src/gc/impl/conservative/gc.d

Moves recovering small pages into sweep() and optimizes sweep by precalculating some common scenarios.
With the extended vdparser-test on win64:
* master: GC summary: 1355 MB,   13 GC 1443 ms, mark 1089 ms, sweep **199** ms, recover **150** ms, Pauses 1092 ms <  410 ms
* this PR: GC summary: 1355 MB,   13 GC 1226 ms, mark 1082 ms, sweep  **16** ms, recover **124** ms, Pauses 1085 ms <  408 ms

GC: optimize sweeping

---

src/core/sys/windows/dll.d
src/core/thread.d

another extract of https://github.com/dlang/druntime/pull/2514

add lowlevel thread support

---

src/object.d

makes reserve() a noop at compile-time allowing to CTFE

fix issue 12330 - array.reserve at compile time too

---

src/object.d

This is a followup to https://github.com/dlang/druntime/pull/2264
It is intended to resolve an error currently being encountered on the DMD side in https://github.com/dlang/dmd/pull/9516
```
Error: `alloca` cannot be interpreted at compile time, because it has no available source code
```

Fix object.__ArrayCast error message generation so it works with CTFE

---

src/rt/adi.d

It appears that `_adEq` was replaced a long time ago and is no longer needed.  See https://github.com/dlang/dmd/pull/9376

Remove no longer needed _adEq

---

src/core/internal/traits.d
src/core/thread.d

Committing the backport before it's in master... should give you a couple months to fix failing mecca in #2411 before gdc switches to ddmd/master when stage1 opens for gcc-10.

[dmd-cxx] Fix Issue 19481: mutex.d(95) Error: pthread_mutex_init failed

---

src/core/stdcpp/array.d

Part 2 for [1] blockade. 
[1] https://github.com/dlang/dmd/pull/9505

Add explicit cast in stc/core/stdcpp/array.d

---

src/core/exception.d

I think this was replaced by https://github.com/dlang/druntime/blob/79a966df9b9f3b3992f7d8c1155c2f0293d64be5/src/object.d#L4399
Let's see what the test suite says.

Remove no longer needed _d_switch_error

---

src/core/simd.d

This will remove the deprecation warning
```
src/core/simd.d(53): Deprecation: 32 byte vector types are only supported with -mcpu=avx
```
currently polluting druntime build output and facilitate advancement of the deprecation to an error.

Resolve deprecation warning for 32 byte vectors

---

src/core/internal/hash.d

Reduce the number of `hashOf` templates and reduce the number of lines of code. Also now floats and doubles no longer force hash chaining (the hash code of a float is now just the float's bits, after possibly regularizing NaN or -0.0).
EDIT: The initial motivation was simplifying the code regarding floats, which had become a bit tangled due to handling of imaginary and complex types.

Slight simplification in core.internal.hash

---

src/core/sys/windows/dll.d
src/core/thread.d

joinLowLevelThread: terminate thread when called from DllMain on windows
Addition to https://github.com/dlang/druntime/pull/2519 necessary for DLL support in https://github.com/dlang/druntime/pull/2514

allow lowlevel thread creation to fail

---

benchmark/gcbench/vdparser.d
src/gc/impl/conservative/gc.d
src/gc/pooltable.d

This removes recovering the free lists from the actual garbage collection and does it lazily during allocation. The advantage is a shorter collection time in the allocating thread (the world isn't stopped for the recovering phase) and memory only being written to when being reused anyway after allocation. Benchmarks don't show a notable difference either way, though.
I've also added the extended vdparser test I've been using for benchmarking larger memory usage.

GC: keep list of small pages to recover, defer into malloc

---

src/core/stdc/stdio.d

This is declared in core/sys/posix/stdio.d

core/stdc/stdio.d: Remove fseeko declaration for Musl.

---

src/core/sync/mutex.d

Checked on Solaris 11.5 Beta (which includes dlpi_tls_modid) to give the best possible.

core/sync/mutex.d: Solaris is not a well behaved C runtime

---

src/core/sys/posix/stdio.d

libc32 implements both e.g: fopen and fopen64, libc64 only has fopen.
Prefer the xxx64 functions if __USE_FILE_OFFSET64, this fixes a failing unittest in std.stdio (fseeko on a file > 2GB).

core/sys/posix/stdio.d: Add LARGEFILE support for Solaris i386

---

src/core/sys/solaris/dlfcn.d
src/core/sys/solaris/sys/link.d

Makes Solaris close to using elf_shared, though dlpi_tls_modid support is only in Solaris 11.5 (currently beta).

core/sys/solaris: Add nogc to dlfcn, fix Elfxx_Dyn declarations.

---

posix.mak
src/core/internal/arrayop.d
src/core/sync/event.d
src/core/time.d
src/rt/lifetime.d

This is already the way we build Phobos + Tools.
See also: https://github.com/dlang/phobos/pull/5546
CC @ZombineDev @CyberShadow

Make deprecation warnings compile errors

---

src/object.d
src/rt/aaA.d

Reducing bloat introduced with v2.085.

Suppress object.RTInfoImpl global if aggregate contains no pointers

---

src/core/internal/arrayop.d

I didn't know any better way to do this, so better ideas are very welcome!

Fix Issue 19796  -  wrong assumption of integral element type

---

src/core/sys/windows/shlobj.d

Occurrs when compiling with `-version=IE6`

Fix Windows compile error

---

src/core/sys/posix/ucontext.d
src/core/sys/solaris/link.d
src/core/thread.d

There's still a segfault in rt/aaA.d to address (there's a discrepancy between `_aaKeys` and `_aaValues` signatures in object.d and aaA.d).
That will be dealt with in a follow-up PR though.

Fix extern(C) bindings for Solaris 11/SPARC

---

src/core/runtime.d
src/core/sys/dragonflybsd/execinfo.d
src/core/sys/freebsd/execinfo.d
src/core/sys/netbsd/execinfo.d

Because the current implementations do not support non-x86, non-dmd platforms, and gdc can detect whether `-lexecinfo` is required at configure-time.
Best reviewed with https://github.com/dlang/druntime/pull/2556/files?w=1.

core.sys.bsd.execinfo: Add version BacktraceExternal for using libexecinfo backtrace

---

src/core/stdc/math.d

Linker warnings seen on FreeBSD 11
```
warning: powl has lower than advertised precision
warning: tgammal has lower than advertised precision
```
All convenience functions should be extern(D) to not conflict with C functions, should they suddenly exist.

core.stdc.math: Mark all non-extern functions as extern(D)

---

src/rt/backtrace/dwarf.d

Part of LDC since v1.10 (and has been rotting here upstream as part of #2151 for almost a year now).

rt.backtrace.dwarf: Add support for DWARF v4 & 64-bit DWARF and fix non-x86 alignment issues

---

src/core/sys/posix/ucontext.d
src/core/sys/solaris/link.d
src/core/thread.d

[dmd-cxx] Fix extern(C) bindings for Solaris 11/SPARC

---

src/core/runtime.d
src/core/sys/dragonflybsd/execinfo.d
src/core/sys/freebsd/execinfo.d
src/core/sys/netbsd/execinfo.d

[dmd-cxx] core.sys.bsd.execinfo: Add version BacktraceExternal for using libexecinfo backtrace

---

src/rt/dmain2.d

Seems to be an accidental addition, where a PR changed direction, but forgot to clean-up.

rt.dmain2: Remove unused _d_main_args

---

src/core/memory.d

`delete` has been deprecated in favor of `destroy`.  See https://dlang.org/deprecate.html#delete

[Trivial] Change suggestion for delete to destroy in core.memory

---

mak/SRCS
src/rt/backtrace/dwarf.d
src/rt/backtrace/elf.d
src/rt/backtrace/macho.d

Recent changes to core.runtime broke osx CI, as rt.backtrace.macho was a dependency of it.
@jacob-carlborg

[dmd-cxx] Synchronize rt.backtrace with druntime master

---

src/core/time.d

clock_gettime on CentOS 5.11 (Linux 2.6.18) supports only:
CLOCK_REALTIME
CLOCK_MONOTONIC
CLOCK_PROCESS_CPUTIME_ID
CLOCK_THREAD_CPUTIME_ID
CLOCK_REALTIME_HR
CLOCK_MONOTONIC_HR
Meaning that both the ClockType.coarse nor ClockType.raw tests will also fail as well as ClockType.bootTime.
dmd-cxx cherry-pick of #2580.

[dmd-cxx] core.time: Assume all clocks are missing on Linux_Pre_2639

---

src/core/time.d

clock_gettime on CentOS 5.11 (Linux 2.6.18) supports only:
CLOCK_REALTIME
CLOCK_MONOTONIC
CLOCK_PROCESS_CPUTIME_ID
CLOCK_THREAD_CPUTIME_ID
CLOCK_REALTIME_HR
CLOCK_MONOTONIC_HR
Meaning that both the ClockType.coarse nor ClockType.raw tests will also fail as well as ClockType.bootTime.
I don't think it's particularly good to add more version conditions for each linux version that introduced a new clock (in total, 2.6.18, 2.6.28, 2.6.32, and 2.6.39), so if any clock is missing, just assume others are as well.

core.time: Assume all clocks are missing on Linux_Pre_2639

---

src/core/memory.d

This issue was discovered while working on https://github.com/dlang/dmd/pull/9666
This test https://github.com/dlang/dmd/blob/b0007c1193dfb72bcfa8cef3f420fee68564ce49/test/runnable/sdtor.d#L186-L208 does not pass when `delete` is replaced with `__delete`.  This PR fixes that.

Fix Issue 19830 - core.memory.__delete destructs arrays of structs in the wrong order

---

changelog/freebsd-ttycom.dd
src/core/sys/posix/sys/ioccom.d
src/core/sys/posix/sys/ioctl.d
src/core/sys/posix/sys/ttycom.d

In FreeBSD, as in OSX, the tty part of ioctl is defined in sys/ttycom.h which is included by sys/ioctl.h.
In druntime, there were OSX part of definitions in ttycom.d, but there were no FreeBSD equivalent.
This change implements FreeBSD part of ttycom.d and ioccom.d, and public import core.sys.posix.sys.ttycom in ioctl.d.
The OSX users and FreeBSD users can now use full ioctls related to tty by importing core.sys.posix.sys.ioctl, like including sys/ioctl.h in C language. (For example, TIOCGWINSZ ioctl was
not provided in FreeBSD.)
Since there are only version(OSX) and version(FreeBSD) part in ttycom.d, public import'ing core.sys.posix.sys.ttycom from ioctl.d will make no harm to other platforms.

Convert FreeBSD's sys/ttycom.h into core.sys.posix.sys.ttycom
