dlang/druntime

benchmark/aabench/bulk.d, benchmark/aabench/string.d, benchmark/gcbench/conalloc.d, benchmark/gcbench/conappend.d, benchmark/gcbench/concpu.d, benchmark/gcbench/dlist.d, benchmark/gcbench/slist.d, benchmark/gcbench/testgc3.d, benchmark/gcbench/tree1.d, benchmark/gcbench/tree2.d, benchmark/gcbench/words.d, benchmark/runbench.d
- simpler old runbench script
- best of 10 for more stable timings
- align and cleanup output
=> improve benchmark script

src/core/internal/convert.d
Necessary for: https://github.com/D-Programming-Language/dmd/pull/4277
=> Supplemental fix for issue 13902, don't return a slice to local static array.

src/core/sys/linux/stdio.d, src/core/sys/posix/stdio.d
See https://issues.dlang.org/show_bug.cgi?id=13755
=> add fopencookie, fmemopen, open_memstream, open_wmemstream, setbuffer

src/rt/lifetime.d
=> [cleanup] Remove unused variadic versions of runtime functions

src/rt/lifetime.d
The old versions can be deleted once the compiler has been updated
=> Add new non-variadic versions of _d_newarraym*T

src/gc/bits.d, src/gc/gc.d
- remove unused sentinel offset
- always use core.bitop intrinsics
=> cleanup gc bits

src/gc/gc.d
This refactoring splits Gcx.fullcollect into functions prepare, markAll, sweep and recover. This improves readability and allows executing parts of the collection concurrently later.
I now have this refactoring in two of my branches, I think it is worth getting into main line.
=> refactor GC: split fullcollect into separate functions

README.md
=> Add link to bug tracker in README.md

src/rt/arrayassign.d
https://issues.dlang.org/show_bug.cgi?id=14024
The stable runtime behavior is important for CTFE.
=> Issue 14024 - unstable postblit/destructor call order on static array assignment

posix.mak, src/core/runtime.d, src/core/sys/posix/signal.d, src/rt/util/utf.d, win32.mak, win64.mak
Reverts D-Programming-Language/druntime#1128
=> Revert "DIP25: implement in druntime"

src/gc/gc.d
- after a collection new allocations are served
from the first pool not the last one leading to
less fragmentation
- GC.free still pushes to the list head
=> use a tail list to chain freelist elems in forward order

src/rt/config.d, src/rt/lifetime.d
In preparation for the warning in https://github.com/D-Programming-Language/dmd/pull/2885
=> Remove implicit conversions from array to bool

posix.mak, src/core/runtime.d, src/core/sys/posix/signal.d, src/rt/util/utf.d, win32.mak, win64.mak
Replaces https://github.com/D-Programming-Language/druntime/pull/1135
=> DIP25: implement in druntime

src/rt/aaA.d
We've had a really nasty heisenbug in production caused by code like this:
```d
bool[int] aa;
...
if (auto p = (k in aa))
{
aa.remove(k);
if (*p) ...
}
```
Built-in associative arrays must be safe. cc @MartinNowak
=> No more GC.free when removing entry from associative array

src/gcstub/gc.d
=> add gc_runFinalizers to gcstub.d

src/core/internal/traits.d, src/core/thread.d, src/rt/sections.d, src/rt/sections_elf_shared.d, src/rt/util/container/array.d, src/rt/util/container/common.d
- might only fail on resource exhaustion
=> mark Thread.start as nothrow

src/rt/sections_osx.d
Another one for https://github.com/D-Programming-Language/dmd/pull/2885
=> More implicit array to bool conversions

src/gc/gc.d
- use a small local buffer (32-byte) to gather bits
- batch process all bits of a page
=> clear bits pagewise

src/core/stdc/math.d
https://issues.dlang.org/show_bug.cgi?id=14157
=> fix Issue 14157

src/gc/config.d, src/gc/gc.d, src/gc/os.d
- keep track of used number of small/large pages
- update collect thresholds after each collection
- make heap size to used memory size ratio configurable
=> new heap growth strategy

benchmark/runbench.d
D files in an "extra" folder are considered part of a respective benchmark and are built together with it, e.g.
```
gcbench/vdparser.d
gcbench/vdparser.extra/parser/expr.d
gcbench/vdparser.extra/parser/decl.d
...
```
will be compiled with the extra folder as an additional import path:
```
dmd gcbench/vdparser.d -I gcbench/vdparser.extra gcbench/vdparser.extra/parser/expr.d gcbench/vdparser.extra/parser/decl.d ...
```
=> runbench: support additional source files to build a test

src/core/stdc/math.d, src/core/stdc/tgmath.d
=> fix Issue 14157. Part 2

src/core/atomic.d
see comments in https://github.com/D-Programming-Language/druntime/pull/1100
=> fix definition of hasDWCAS in PR1100

src/core/thread.d
- a lock is required to avoid a race between a pending signal and
entering a critical region
- any suspend signal may only be sent with the lock held
=> Revert "Merge pull request #1116 from MartinNowak/dontSuspendStartingThreads"

src/gc/config.d
`--DRT-gcopt=help` doesn't work anymore.
=> gc.config: fix parsing "help"

mak/DOCS, posix.mak, win32.mak, win64.mak
=> build documentation for core.stdc modules

src/rt/lifetime.d
- use compare-and-swap instead of synchronized
as the latter isn't really pure
- using cas instead of a global mutex
also heavily reduces contention
=> make __setArrayAllocLength really pure

src/core/time.d
This gives it the same semantics as all "normal" `to` functions in std.conv, allowing you to call it as `to!Duration(tickDur)` or in the current manner via UFCS. Fewer edge cases is good.
This also seems to fix conversions from `TickDuration` to `Duration`. At time of writing, the following fails to compile with the druntime master branch but compiles with this branch:
```d
import std.stdio;
import std.conv : to;
import std.datetime : Clock, Duration;
void main()
{
write("System has been up for ");
writeln(Clock.currSystemTick.to!Duration.total!"seconds", " seconds.");
}
```
=> Make TickDuration "to" a freestanding, non-member function

src/rt/util/container/array.d
replace invalid test with something similar but valid.
=> fix issue 14303 rt.util.container.array.Array has invalid unittest

src/core/demangle.d
https://issues.dlang.org/show_bug.cgi?id=14247
=> Issue 14247 - string within demangled symbol name should be made escape

src/gc/gc.d
This simplifies `ctfeBins` and inlines `findBin`, avoiding a gratuitious check. The original method was not inlined due to the static variable declared inside the `findBin`.
The benchmarks indicate an improvement by up to a few percent.
=> GC: improve performance by inlining findBin

src/object.di, src/object_.d
Context:
https://github.com/D-Programming-Language/druntime/pull/757
http://forum.dlang.org/post/wcoscawhmagambkydrye@forum.dlang.org
https://github.com/D-Programming-Language/druntime/pull/999
=> Removed deprecated clear method

src/core/time.d
and transform verify examples to doc comments
=> remove doc examples from core.time

src/core/bitop.d
and replace with unittest examples
=> remove doc examples from bitop

src/core/time.d
the to! template didn't seam to have a unittest
=> TickDuration to!() unittest

src/core/atomic.d
Place opening curly bracket on its own line and remove empty line of spaces.
=> [Whitespace] Style fixup for pull #1208.

src/rt/adi.d
=> use foreach to decode in rt/adi.d

src/rt/aaA.d
=> [Refactor] Don't use loop in `rt.aaA.nextpow2`.

src/rt/aApply.d
This is a straightforward refactor to modernize the style a bit, just because I was annoyed when reading it.
=> Refactor: rt.aApply

mak/MANIFEST, mak/SRCS, src/rt/tracegc.d
Druntime part of https://github.com/D-Programming-Language/dmd/pull/4621
It's basically a stub, and will get fleshed out when the idea is accepted (i.e. pulled).
=> add rt.tracegc

mak/MANIFEST, mak/SRCS, src/rt/profilegc.d, src/rt/tracegc.d
Adds memory profiler implementation.
=> add rt/profilegc.d

src/core/sys/windows/windows.d
https://msdn.microsoft.com/en-us/library/windows/desktop/aa364439%28v=vs.85%29.aspx
=> core.sys.windows.windows: Add FlushFileBuffers

src/gc/gc.d, src/gc/pooltable.d
Enabling some debug specifiers causes compilation errors...
=> Fix GC debug builds

src/core/time.d
See https://github.com/D-Programming-Language/dmd/pull/4643
=> Avoid silent truncating conversions (issue 3841).

src/core/demangle.d
https://issues.dlang.org/show_bug.cgi?id=14566
https://issues.dlang.org/show_bug.cgi?id=14567
=> Handle (undocumented) Nk and Nj mangled symbols

src/core/sys/posix/stdlib.d
It's defined in IEEE 1003.1 2008 edition.
=> Add support for mkdtemp().

src/core/time.d
don't really know if this is the right way to do this, but it's an opportunity to make use of Vladimir's new docs autotester :)
=> DOCS: fix core.thread.Thread.sleep link

src/object.d
https://issues.dlang.org/show_bug.cgi?id=14746
On stable branch instead of master (#1310)
=> [REG2.068a] Issue 14746 - Behavior change with struct destructor and alias this

src/core/memory.d
For reference: http://blog.experimentalworks.net/2015/07/lessons-learned-writing-a-filesystem-in-d/
=> core.memory add user notes

src/core/time.d
- move enum name and index function out of them template
- check const conversions once, instead of repeating
this for every operation
- using a const value guarantees that the method can be
called for mutable and immutable values as well
- 15% compile time and 10% binary size of unittest library
=> reduce excessive unittests and template bloat

mak/MANIFEST, posix.mak, src/core/sys/osx/sys/event.d, src/core/sys/posix/sys/msg.d
- remove tabs and trailing white space
- add missing files to MANIFEST
- don't rely on MANIFEST for the white space test
=> More white space fixes

mak/MANIFEST
https://issues.dlang.org/show_bug.cgi?id=14882
=> fix Issue 14882 - [REG] MANIFEST is missing test/common.mak

src/core/demangle.d
This trivial change reduces the size of the data section from 3126 to 2726 bytes, and the size of the object file from 26464 to 25041 bytes. There's a lot more that can be done to this module to reduce its footprint.
=> add put(char) overload

src/core/demangle.d, src/rt/lifetime.d
=> do overflow check correctly

src/core/demangle.d
Should not invent alternate terminology.
=> refactor demangle: use range terminology

src/core/cpuid.d
The idea is to:
1. consolidate private globals into a struct, reducing the number of pointless symbols in the object file
2. use a pointer to the struct instance to access the globals, which reduces the fixups in the executable image, making for faster loading and a smaller executable file size.
Worthwhile because core.cpuid is compiled into every D executable.
=> core.cpuid: emit fewer fixups

src/rt/profilegc.d
https://issues.dlang.org/show_bug.cgi?id=14926
=> fix Issue 14926 - Programs compiled using dmd 2.068 are generating dummy profilegc.log files

.gitignore
Ignore the generated folder made from the make process
=> Ignore the generated folder

mak/MANIFEST
Zip files broken again.
https://issues.dlang.org/show_bug.cgi?id=14990
=> fix Issue 14990 No rule to make target src/core/sys/stdio_msvc12.d

src/object.d
https://issues.dlang.org/show_bug.cgi?id=15009
=> Issue 15009 - Object.destroy calls unnecessary postblits for destruction of static arrays object

src/core/sys/linux/dlfcn.d, src/core/sys/posix/dlfcn.d, src/core/sys/posix/signal.d, src/core/sys/posix/sys/msg.d, src/core/sys/posix/sys/socket.d
This is the first set of declarations for SystemZ.
=> Add SystemZ declarations.

src/core/stdc/fenv.d, src/core/sys/linux/link.d, src/core/sys/posix/fcntl.d, src/core/sys/posix/sys/stat.d
=> Add more SystemZ declarations.

src/core/thread.d
Needed for https://github.com/D-Programming-Language/phobos/pull/3654
=> core.thread: Add Thread.id property, ThreadID type

src/core/runtime.d, src/rt/backtrace/dwarf.d, src/rt/backtrace/elf.d, test/exceptions/Makefile
Follow up to https://github.com/D-Programming-Language/druntime/pull/1354.
=> Support file/line dwarf in FreeBSD

src/rt/cover.d, test/coverage/Makefile, test/coverage/src-no_code.lst.exp, test/coverage/src-no_code_imp.lst.exp, test/coverage/src/no_code.d, test/coverage/src/no_code_imp.d
- needed to find source from coverage report
=> print filename in coverage reports for modules w/o code

src/core/time.d
https://issues.dlang.org/show_bug.cgi?id=15137
=> fix Issue 15137 - core.time: Support Duration/Duration and Duration%Duration

src/core/time.d
Duration should never have checked for division by 0 and thrown a
TimeException when it occurred. The OS/hardware already checks for that,
and it should be considered a logic error. Checking for it and possibly
throwing just slows the code down and makes it so that it can't be @nogc.
This is technically a breaking change, but it will only break code which
doesn't bother to avoid dividing by 0 and then catches TimeException
when it occurs, and such code is likely extremely rare, if it exists at
all. Given the fact that the odds of actually breaking code are
extremely low and that this allows us to make Duration fully @nogc except
for toString, I think that it's worth the risk.
=> Treat division by 0 as an error in Duration and consolidate code.

mak/MANIFEST
fix https://issues.dlang.org/show_bug.cgi?id=15223
=> add missing files to MANIFEST

src/core/sys/windows/winsock2.d
https://issues.dlang.org/show_bug.cgi?id=15128
=> fix Issue 15128 - "IP_ADD_MEMBERSHIP" error in winsock2.d

src/core/sys/linux/sys/inotify.d, src/core/sys/posix/setjmp.d, src/core/sys/posix/ucontext.d
Adds ucontext, setjmp and inotify.
=> Add more definitions for Linux/SystemZ.

src/object.d
https://issues.dlang.org/show_bug.cgi?id=15367
=> Issue 15367 - array of delegates comparison fails

src/object.d
This is a companion PR to <https://github.com/D-Programming-Language/dlang.org/pull/896>. Do not pull without that one.
=> update links to spec pages

mak/COPY, mak/MANIFEST, mak/SRCS, src/core/sys/unwind.d, win32.mak, win64.mak
Interface to libunwind. Needed for dwarf exception handling.
=> add core.sys.unwind

src/core/bitop.d
=> _popcnt intrinsic only available with DMD.

src/rt/dwarfeh.d
The trouble with using assert(0) in dwarfeh.d is that it throws an exception inside an exception, which then goes into an infinite loop. This makes things hard to debug. So have it produce a seg fault instead, which is easy to find out whodunit.
This is needed to help me figure out what is going wrong with https://github.com/D-Programming-Language/dmd/pull/5324 as I cannot reproduce it on my machine.
=> Dwarf EH: terminate instead of assert

src/object.d
See discussion https://github.com/D-Programming-Language/dmd/pull/5342 and http://www.digitalmars.com/d/archives/digitalmars/D/Catching_C_Exceptions_in_D_277799.html#N277849
=> Dwarf EH: add class Object.__cpp_type_info

src/object.d
This reverts commit 74e5d87148028134e6927c31e99c293e0e2f91bd, reversing
changes made to c36cc5180a3ad59b099dec91bf0055d2e6508753.
=> Revert "Merge pull request #1445 from WalterBright/message"

mak/COPY, mak/MANIFEST, mak/SRCS, src/rt/dwarfeh.d, src/rt/unwind.d, win32.mak, win64.mak
- add unwind header as internal module
#1449
see https://trello.com/c/ndzxBBqP/141-move-core-sys-unwind-to-rt-unwind
=> fixup of #1449

src/rt/arraycast.d
Reverts D-Programming-Language/druntime#1478
See https://github.com/D-Programming-Language/druntime/pull/1478#issuecomment-174185175
=> Revert "Optimize array cast for equivalence"

src/core/bitop.d
This fixes CTFE `popcnt()` which I accidentally broke in [#1452](https://github.com/D-Programming-Language/druntime/pull/1452).
That PR added optimized `popcnt()` by having it check `core.cpuid.hasPopcnt` to see if it can use the `_popcnt()` intrinsic. However, `hasPopcnt` is not accessible at compile time.
This PR simply skips that step if `__ctfe` is set, causing it to fall back to `soft_popcnt()` which works fine in CTFE.
=> Fix CTFE popcnt() regression

src/core/thread.d
Adds an example code into unittest to show how to create a new thread and start it with an anonymous function.
=> Example code to start thread with an anonymous function

src/core/bitop.d
* Fixed `bsf(ulong)` and `bsr(ulong)` for 32-bit CTFE - union repainting doesn't work in CTFE.
* Added `bswap(ulong)` - this should be made an intrinsic on 64-bit, but that's obviously outside the scope of this PR.
* Fixed CTFE `bitswap()` - `asm` doesn't work in CTFE.
* Consolidated both non-`asm` implementations of `bitswap()` into a single `private` `softBitswap()` template.
* `softBitswap()` now uses `bswap` for the final step, like the optimized assembly versions do.
=> More core.bitop improvements

src/core/thread.d
/SAFESEH is not supported by DMD, but with LDC.
https://issues.dlang.org/show_bug.cgi?id=15628
=> Fix issue 15628: exception handling in fibers with /SAFESEH

src/core/sys/posix/mqueue.d
This is a binding for POSIX message queues.
Reference: http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/mqueue.h.html
Linux overview man page: http://man7.org/linux/man-pages/man7/mq_overview.7.html
Ping @andreas-bok-sociomantic
=> Add core.sys.posix.mqueue, C bindings for POSIX's <mqueue.h>

src/gc/gc.d
- pass function via alias parameter to allow inlining
=> replace doLock/doUnlock with runLocked

src/rt/dwarfeh.d
Required for https://github.com/D-Programming-Language/dmd/pull/5469
=> fixes for reading EH info

src/core/thread.d, src/rt/sections_elf_shared.d
Fix for https://issues.dlang.org/show_bug.cgi?id=15513
As pointed out by @schuetzm, I did something wrong while merging a rebase from the master branch. So I closed PR 1506 and am creating this new one.
=> Fix15513 (revised)

test/shared/src/finalize.d
- the makefile already prints a Testing finalize
=> remove more pointless start/pass output

changelog.dd
=> update links to dlang

src/rt/dwarfeh.d
- only use __Unwind_GetIPInfo w/ glibc
=> fix Issue 15911 - undefined __Unwind_GetIPInfo for x86_64

changelog.dd, src/object.d
=> Deprecate TypeInfo.init

src/core/sys/posix/sys/utsname.d
Patch by @nykytenko, originally submitted at https://github.com/ldc-developers/druntime/pull/71.
=> Solaris: add utsname.

src/core/sys/windows/threadaux.d
This used to cause trouble with LDC built upon older druntime versions, but can also happen for user code.
=> fix issue 15976: swap out explicit TLS values during impersonating thread

src/core/cpuid.d
- Supports GDC based on front-end release 2.066.1
- Supports both AT&T and Intel syntax assemblers
- Supports x86, amd64 and x32
- Moves up the `stepping`, `model` and `family` calculation, as the `uint a` (holding the bits) got overwritten in the original code before being evaluated (See line 725 in the original code)
- Wrapper functions do **NOT** inline, that would require accessing the cached constants directly as GDC does not support cross module inlining
=> GDC support for core.cpuid

src/core/bitop.d
This pull request is intended to supersede [PR #1486](https://github.com/D-Programming-Language/druntime/pull/1486#issuecomment-199689712).
This fixes an issue identified by @denis-sh with the `ulong` versions that [I previously added](https://github.com/D-Programming-Language/druntime/pull/1452) to `core.bitop` for `bsf()` and `bsr()`: the `ulong` overloads were defined to forward to the `size_t` versions on 64-bit, but then `size_t` is just an alias for `ulong`, which would make the function infinitely recursive.
This was not a problem in testing, because on 64-bit the `ulong` function body is replaced by a compiler intrinsic on all current DMD platforms.
Still, this pull request solves this potential issue by adding a software fallback algorithm for bit scans - `softScan()` - just in …
=> Implement a software fallback algorithm for core.bitop.bsf() and bsr()

src/core/atomic.d
Added @trusted and @nogc where necessary, too.
=> fix Issue 14117 - core.atomic should be @safe

src/object.d
1. remove redundant header
2. replace open BUG comments with a more useful link to the bug report
3. remove fixed BUG comments
=> update comments in object.d

src/rt/util/random.d
=> rt.util.random: add attributes

src/core/sys/posix/termios.d
=> posix.termios: add Solaris.

mak/COPY, src/core/sys/openbsd/dlfcn.d, src/core/sys/posix/dirent.d, src/core/sys/posix/dlfcn.d, src/core/sys/posix/fcntl.d, src/core/sys/posix/grp.d, src/core/sys/posix/netdb.d, src/core/sys/posix/poll.d, win32.mak, win64.mak
Add OpenBSD definitions to the core.posix.* modules.
=> OpenBSD: Additions for core.posix.* modules, part 1

src/rt/util/container/array.d
`insertBack` doesn't have overflow protection, and so it can cause undefined behaviour or a crash to occur.  e.g:
```
auto ary = Array!size_t(null, -1);
ary.insertBack(0);  // SEGV.
```
This change actually helps GDC produce better code, see small test below.
Before: http://goo.gl/zp3Dto
After: http://goo.gl/LSvUgP
=> Check for overflow before incrementing length in insertBack

src/core/sys/posix/pthread.d, src/core/sys/posix/pwd.d, src/core/sys/posix/sched.d, src/core/sys/posix/semaphore.d, src/core/sys/posix/setjmp.d, src/core/sys/posix/signal.d, src/core/sys/posix/stdio.d, src/core/sys/posix/stdlib.d
Add OpenBSD definitions to core.sys.posix.* modules.
=> OpenBSD: Additions for core.sys.posix.*, part 2

src/rt/aaA.d
A woefully underdocumented module.
=> add some documentation to aaA.d

src/core/checkedint.d
Adds support for cent/ucent types. This is required for an D frontend
which supports cent/ucent.
=> Centify core.checkedint

benchmark/arrayops/arrayops.d, benchmark/arrayops/plot.R, benchmark/runbench.d
=> benchmark for array ops

src/core/sys/posix/pthread.d, src/core/thread.d
=> Add @nogc to pthread functions.

.codecov.yml
As we transition from Travis to CircleCi the script was never run there, so I just open this PR to verify everything is ok. Sorry for the noise.
=> add codecov config for dlang-bot

src/object.d
Reduce the thicket of templates in object.d
=> refactor: remove unnecessary object._rawDup() template

circleci.sh
- was querying for dmd instead of druntime PRs
=> find correct base branch for PRs

circleci.sh
- i.e. fix checking for empty/unbound CIRCLECI_PR_NUMBER
=> fix building non-PR builds

src/object.d
As per title.
This signature change is needed to make the test work.
=> ctfe-code is often annotated with pure @safe we want to print anyway

src/object.d
https://issues.dlang.org/show_bug.cgi?id=1761
Please review, thanks!
=> fix issue 1761 - TypeInfo.toString for function types always indicates no-parameter function

src/rt/dwarfeh.d, test/exceptions/Makefile, test/exceptions/chain.exp, test/exceptions/src/chain.d
Issue: https://issues.dlang.org/show_bug.cgi?id=16968
Forum discussion: https://forum.dlang.org/post/o2n7f8$2p1t$1@digitalmars.com
=> Fix missing bypassed chain in Error

src/core/stdc/string.d
Taking advantage of `-dip1000`
=> string.d: add return and scope

src/core/internal/string.d, src/object.d
=> [scope] add annotations to core.internal.string

src/gc/config.d
=> workaround sscanf bug in old snn.lib

Jenkinsfile
- finally moved repo under dlang
=> update pipeline ci repo url

src/core/sys/posix/pthread.d, src/core/sys/posix/sys/select.d
add pure keyword to functions in core/sys/posix/sys/select.d, and remove duplicate alias in core/sys/posix/pthread.d
=> apply changes for netbsd

src/object.d
Full implementation for __equals.
Handles integral types, objects, fp types, void arrays, arrays of arrays.
=> __equals for floats & objects & integral types

src/object.d
Fixes some bugs from https://github.com/dlang/druntime/pull/1814
Requires https://github.com/dlang/dmd/pull/6697 to be reverted first. Due to CTFE issues (https://issues.dlang.org/show_bug.cgi?id=17351) with static arrays passed as ref, we cannot support static array __equals yet. Remains to be discussed.
Dmd patch to enable this behaviour to be posted soon.
=> Array equals overload for dynamic arrays only

src/core/checkedint.d
Define overloads taking mixed widths, and guard division with the (frequent) case when both operands fit within one word.
=> Make mulu faster when not defined as an intrinsic

src/core/checkedint.d, src/core/cpuid.d, src/object.d
The way I see it, it's best practice to add either `const` or `immutable` everywhere it can be added. It acts not only as a sanity check, but as documentation to the future maintainer.
=> Added immutable to never modified variables in several files

src/core/sys/linux/sys/mman.d
- use permalinks
- add missing madvise flags
- deprecate gone MADV_*_PAGES (see https://sourceware.org/git/?p=glibc.git;a=commit;h=d4eed61f85791a8fc4f94ce4fb17997d4ee0eed3)
=> update linux mman.h headers

src/core/sys/windows/oaidl.d
See bug https://issues.dlang.org/show_bug.cgi?id=16205
=> Added missing values to oaidl.d

src/core/time.d
It's no longer required to have separate implementations for const and
non-const toString, so this fixes it so that we only have one. It also
clarifies the documentation.
=> Some minor improvements to Duration.toString.

changelog/unhandled.dd
- the fix was for `rt_trapExceptions == false`
=> fix changelog entry

test/shared/src/finalize.d, test/shared/src/load.d, test/shared/src/load_13414.d, test/shared/src/load_linkdep.d, test/shared/src/load_loaddep.d, test/shared/src/load_mod_collision.d
Don't care what the binary name is, just get the dirname and do the right thing.
=> Don't assert on what name the binary is

src/core/sys/windows/winioctl.d
blocking https://github.com/dlang/dmd/pull/7013
=> winioctl.d: inure against unary + - ~ integral promotion rules

mak/COPY, mak/SRCS, src/core/sys/linux/netinet/tcp.d, src/core/sys/linux/sys/netinet/tcp.d, win32.mak, win64.mak
- copy newly added headers to import folder
- fix core.sys.linux.sys.netinet pkg to core.sys.linux.netinet
=> cleanup core.sys.*.netinet headers

src/core/memory.d, src/gc/gcinterface.d, src/gc/impl/conservative/gc.d, src/gc/impl/manual/gc.d, src/gc/proxy.d
Add `@nogc` to the actual `GC` functions, as I have forgotten in #1954 
@andralex
=> Make GC addrof and sizeof nogc

src/core/memory.d, src/gc/gcinterface.d, src/gc/impl/conservative/gc.d, src/gc/impl/manual/gc.d, src/gc/proxy.d
Free doesn't/mustn't produce any garbage so it should be marked `@nogc`.
=> Mark GC free as @nogc

src/core/stdc/fenv.d, src/core/sys/linux/dlfcn.d, src/core/sys/linux/epoll.d, src/core/sys/linux/link.d, src/core/sys/linux/sys/eventfd.d, src/core/sys/linux/sys/inotify.d, src/core/sys/posix/dlfcn.d, src/core/sys/posix/setjmp.d, src/core/sys/posix/sys/msg.d, src/core/sys/posix/sys/socket.d, src/core/sys/posix/ucontext.d
This is now effectively compilable.
=> Finish off SPARC64 C bindings in druntime

win32.mak, win64.mak
Cherry-picked https://github.com/dlang/druntime/pull/1978 for the `stable` branch.
From https://github.com/braddr/at-client/pull/4#issuecomment-347937086
> Sorry, not staging, but stable. All tested branches need to have the changes. In fact, since I merged the auto-tester changes in before remembering to check stable, it's currently failing to build. That needs to be fixed asap or I'll have to revert the auto-tester or put in a temporary work around. It'd be best to just get the changes merged.
=> Fix DMD path to ../generated

src/rt/lifetime.d
=> Local imports for rt.lifetime

src/core/stdc/stdlib.d
=>  Add musl libc definitions to:  src_core_stdc_stdlib

src/core/sys/posix/utime.d
=>  Add musl libc definitions to:  src_core_sys_posix_utime

src/core/sys/posix/poll.d
=>  Add musl libc definitions to:  src_core_sys_posix_poll

src/core/stdc/time.d
=>  Add musl libc definitions to:  src_core_stdc_time

src/rt/trace.d
On non-Windows platforms, QueryPerformanceFrequency is not available and the frequency of RDTSC is unknown (e.g. on my Macbook it apparently is the CPU clock frequency, instead of the previously hardcoded 3_579_545 Hz). So when this function is not available, the time output no longer tries to calculate microseconds (and fail), but shows the timings in megaticks instead.
This change also adds LDC-specific code to read a CPU cycle counter on non-x86 target platforms.
The x86 manual assembly is chosen in favor of the LLVM intrinsic as it performs better with optimizations turned off. The generated machinecode is otherwise identical: https://godbolt.org/g/Le7dZF
Tested on OSX.
=> Fix trace profile timings when the frequency of the timer is unknown.

src/core/sys/posix/stdio.d
=>  Add musl libc definitions to:  src_core_sys_posix_stdio

src/core/sys/posix/arpa/inet.d
=>  Add musl libc definitions to:  src_core_sys_posix_arpa_inet

src/core/sys/posix/dlfcn.d
=>  Add musl libc definitions to:  src_core_sys_posix_dlfcn

src/core/stdc/string.d
=>  Add musl libc definitions to:  src_core_stdc_string

src/core/bitop.d, src/core/stdc/config.d, src/core/stdc/fenv.d, src/core/stdc/stdlib.d, src/core/sys/posix/pwd.d, src/core/thread.d, src/core/threadasm.S, src/object.d, src/rt/backtrace/elf.d, src/rt/unwind.d
Pinging @klickverbot and @ibuclaw.
=> Upstream some LDC patches

.codecov.yml
See also: https://github.com/dlang/dmd/pull/7711
=> Hide codecov/project and codecov/changes

src/object.d
Was: https://github.com/dlang/dmd/pull/7793
=> add test for issue 16739 - switch ignores case

src/core/stdc/assert_.d
Fix error compilation for Solaris.
=> Solaris: fix assert header file.

src/core/stdc/assert_.d, src/core/stdc/errno.d, src/core/stdc/fenv.d, src/core/stdc/locale.d, src/core/stdc/math.d, src/core/stdc/stdio.d, src/core/stdc/stdlib.d, src/core/stdc/string.d, src/core/stdc/time.d, src/core/stdc/wchar_.d
First PR in for uClibc definitions.
=> Add uClibc definitions to core.stdc.*

src/core/stdc/errno.d
Add Solaris errno correct interface.
=> Solaris: fix errno.

src/core/thread.d
Fix modify immutable error in Thread class.
=> Solaris: fix modify immutable error.

changelog/lazy-gc-init.dd
See also: https://github.com/dlang/druntime/pull/2057
Maybe a more few words would be more helpful?
Also shouldn't this require an update to the spec too?
CC @somzzz
=> Use upper-casing for the GC init changelog entry

src/object.d
blocking https://github.com/dlang/dmd/pull/7986
=> object.d: no 0 size structs for AAs

src/object.d
https://issues.dlang.org/show_bug.cgi?id=18652
=> Issue 18652 - hashOf example doesn't compile

src/object.d
Needed for https://github.com/dlang/dmd/pull/8067
=> Move DMD's object.d members to druntime

src/object.d
Got tripped up by the `__xdtor` thing.
=> Important to clean up aggregates too!

src/core/internal/string.d
core.internal.string functions.
=> Fix issue 18904 - remove possibility of infinite loop or crashes from

src/core/internal/hash.d
`core.internal.hash` has lines dating back to the [initial commit](https://github.com/dlang/druntime/commit/8df094c4d5e0c3db52c4f372fe91d686f3163ad8#diff-1cb07fafd18644ca9974aea7a74483e9) on November 16, 2013 that disable unaligned reads when using DMD and a comment that a DMD bug would prevent inlining. That is not true in the present day so the comment and alternative code branch have no purpose except to confuse.
With optimization enabled DMD produces the same code for
```d
return *cast(uint*)x;
```
and
```d
return ((cast(uint) x[3]) << 24) | ((cast(uint) x[2]) << 16) | ((cast(uint) x[1]) << 8) | (cast(uint) x[0]);
```
when `x` is `ubyte*`, so this patch is not expected to improve performance except for non-optimized builds.
=> Fix Issue 18943 - core.internal.hash remove outdated special case for DMD unaligned reads

src/core/internal/hash.d
This patch enables:
```d
@safe unittest
{
import core.internal.hash : hashOf;
static struct S { int a; int b; }
auto h = hashOf(S.init);
}
```
=> Fix Issue 18925 - core.internal.hash auto-hash for structs of scalar fields should be `@safe`

src/rt/lifetime.d
Implement:
1. eliminate gotos
2. minimize scope of variables
3. simplify control flow
4. use const
5. reduce indentation levels
More can be done, but this is enough for the moment.
=> refactor _d_arraysetlengthT()

src/core/internal/hash.d
Resubmission of #2223 to target stable, again.
=> Fix Issue 19005 - [REG2.081-b1] object.hashOf no longer works for std.datetime.date.Date

src/core/internal/hash.d
On machines that do not support unaligned memory access, `core.internal.hash` can use statically available alignment information to determine when `uint` reads can be used.
=> Fix Issue 18942 - core.internal.hash can take advantage of alignment info on non-x86

src/core/internal/parseoptions.d, src/core/runtime.d, src/rt/config.d
Split up from https://github.com/dlang/druntime/pull/2035
=> Fix typo + remove duplicate rt_configOption declaration

src/object.d
The low bits of `Object.toHash` are insufficiently varied. Depending on the platform the bottom 4, 3, or 2 bits of the result will always be zero. This is bad because the low bits of a hash code are typically the most significant for hashtable implementations. D's builtin AA deals with this and other potential defects by rehashing the hash codes it receives. Some 3rd party hashtable implementations do the same, but others assume that keys with a defined `toHash` have reasonable hashcodes that can be used without need for further mixing.
Fixing this is not hard and not computationally expensive. This PR also does a similar thing for raw pointers. Although it will not always be necessary for them the cost is low and it will frequently be a benefit.
=> Fix Issue 19072 - Object.toHash and typeid(void*).getHash(&ptr) should be more varied in their low bits

changelog/typeinfo-gethash.dd
=> add changelog for PR #2243

README.md
To avoid this when a PR is failing:
=> CircleCi status badge: only use the master branch

posix.mak
https://github.com/dlang/druntime/pull/2282 for stable.
=> [stable] Add buildkite-test target

src/core/thread.d
I came across this example in the core.thread documentation and realized there was no Run button.
This PR tries to fix that.
I replaced the outputs with the counter since I found it more appropriate for a unittest and to get rid of the import.
=> Moving Fiber example into unittest

.editorconfig
Companion to https://github.com/dlang/dmd/pull/8656
=> Fix newlines in .editorconfig

src/core/time.d
`clock_gettime` called with a valid `clock_id` and a valid `timespec` address is in principle allowed to fail if the number of seconds doesn't fit in `time_t`. If `time_t` is `long` or `ulong` we don't need to check for this since the current time won't overflow before 292 billion years A.D.
This PR also extends PR #2315 's improvments to `currSystemTick` to also apply to `currTime`.
=> Fix Issue 19280 - Remove unnecessary error checks in core.time, Part 2

src/core/internal/traits.d
Blocking https://github.com/dlang/phobos/pull/6762. Example of failure:
https://run.dlang.io/is/6k5F17
```d
import std.stdio;
struct S
{
int[4] a;
alias a this;
enum length = 1;
~this() { writeln("elaborate!"); }
}
void main()
{
import std.traits : hasElaborateDestructor1 = hasElaborateDestructor;
import core.internal.traits : hasElaborateDestructor2 = hasElaborateDestructor;
writeln(hasElaborateDestructor1!S);
writeln(hasElaborateDestructor2!S);
}
```
=> Fix hasElaborateDestructor & hasElaborateCopyConstructor for struct with static array alias & for nested structs/unions

src/core/sys/posix/aio.d
https://git.musl-libc.org/cgit/musl/tree/include/aio.h
=> core.sys.posix.aio: Add musl bindings

src/object.d
This change removes a shared static initializer from a `destroy`
implementation for structs, and with it a dependency on `memcpy`.
=> Remove static initializer from struct `destroy`.

src/object.d
These are all core functions. When I enter them in Google, I should be directed to at least one example.
Oh and yes, lots of stuff is still `@system`.
=> Add a few public examples to object.d

src/core/internal/traits.d
=> Add some traits

posix.mak, src/gc/impl/conservative/gc.d, test/gc/Makefile, test/gc/win64.mak, win64.mak
fix compilation and failures
adding a test that ensures it compiles and most GC tests are run
=> fix issue 12843 again: Unit tests fail when GC is compiled with SENTINEL

src/gc/impl/conservative/gc.d, src/gc/os.d
make sure, number of pages is multiplied with PAGESIZE as a size_t, not an uint
=> fix issue 19281 - GC mishandles allocations >= 4GB

src/core/runtime.d, test/shared/src/loadlibwin.d, win64.mak
restore definition to avoid breaking change for now
=> fix issue 19498 - undefined identifier rt_loadLibraryW

src/gc/impl/conservative/gc.d
This is an optimization inspired by a report on the forum: https://forum.dlang.org/thread/zrouxhbkssrncyinhvdz@forum.dlang.org
The idea is to keep track of the size of contiguous blocks of free pages in the large object pool, so it is unnecessary to ever scan it until the next used block. The necessary memory for this is already available as the bPageOffsets array is used for a similar purpose for allocated pages.
On my system, the rand_large benchmark is about 8% faster for Win32, and about 15% faster for Win64. Most of the time is saved during the sweep phase. The other benchmarks are not really affected because they don't use a lot of large allocations.
=> GC: keep track of the size of contiguous free pages to avoid loops

mak/COPY, mak/DOCS, mak/SRCS, mak/WINDOWS, src/core/stdcpp/type_traits.d
=> Add C++ type_traits

changelog/cpp_new.dd, mak/COPY, mak/DOCS, mak/SRCS, mak/WINDOWS, src/core/stdcpp/new_.d, src/core/stdcpp/xutility.d, test/common.mak, test/stdcpp/Makefile, test/stdcpp/src/new.cpp, test/stdcpp/src/new_test.d, test/stdcpp/win64.mak
`std::allocator` depends on this.
=> C++ operator new/delete bindings

src/core/stdcpp/string_view.d
Tidied `string_view` up a bit. Make it a bit more maintain-able.
=> Tidied up core.stdcpp.string_view a bit.

src/core/stdcpp/new_.d
It's easier to interact with C++ with no C++ exceptions!
=> Support nothrow new

src/core/sys/windows/commctrl.d
See https://issues.dlang.org/show_bug.cgi?id=19571
=> Fix issue 19571

src/gc/impl/conservative/gc.d
In addition to just moving the code from the top of the file, some leak detector code now wrapped in a struct so it can be moved aswell. The diff looks worse than it actually is.
=> gc: move debug code to the bottom of the source

src/core/sys/posix/sys/stat.d
=> core.sys.posix.sys.stat: Fix stat_t for musl

posix.mak, win32.mak, win64.mak
Upgrade to spec-conformant behavior
=> add -preview=fieldwise to build

src/core/sys/posix/sys/resource.d
Apparently I don't know how to use git. This is the non-screwed up version of pull #2486, which I accidentally managed to squash with another commit.
=> Add rusage struct for musl

src/core/sys/posix/fcntl.d
see https://github.com/kraj/uClibc/search?q=O_CLOEXEC&unscoped_q=O_CLOEXEC
=> [uClibc][core.sys.posix.fcntl] add O_CLOEXEC

src/core/sys/posix/sys/socket.d
add missing defs 
See:
https://github.com/kraj/uClibc/search?q=O_CLOEXEC&unscoped_q=O_CLOEXEC
https://github.com/kraj/uClibc/search?q=SOCK_NONBLOCK&unscoped_q=SOCK_NONBLOCK
https://github.com/kraj/uClibc/search?q=SOL_TCP&unscoped_q=SOL_TCP
=> [uClibc][core.sys.posix.sys.socket]

src/core/sys/windows/threadaux.d
extracted from https://github.com/dlang/druntime/pull/2514
=> core.sys.windows.threadaux: apply @nogc to helper functions

.circleci/config.yml, .circleci/run.sh
=> [CircleCi-stable] Fix build by using Ubuntu 18.04 as base

src/object.d
See https://forum.dlang.org/post/eijbfurdbbnhvepfaatb@forum.dlang.org
=> Add missing cast(string) in _d_assert_fail

src/core/sys/posix/aio.d
see https://github.com/coolshou/DIR-850L_A1/blob/master/rsdk-1.5.5-5281-EB-2.6.30-0.9.30.3-110714/config/uclibc/include/aio.h
=> [uclibc] add aio defs

src/core/stdc/stdio.d, src/core/stdc/time.d, src/core/sync/condition.d, src/core/sync/mutex.d, src/core/sync/semaphore.d, src/core/sys/posix/aio.d, src/core/sys/posix/fcntl.d, src/core/sys/posix/stdio.d, src/core/sys/posix/sys/socket.d, src/core/sys/solaris/dlfcn.d, src/core/sys/solaris/sys/link.d, src/core/sys/windows/shlobj.d, src/core/sys/windows/threadaux.d, src/core/time.d, src/gc/os.d
Another big import of system binding changes.
=> [dmd-cxx] Backport system binding updates

src/object.d
All AA tests currently SEGV on 32-bit Solaris/SPARC,
Closer investigation reveals object.d calls _aaValues (and _aaKeys) incorrectly:
While the implementation expects a struct AA
libdruntime/rt/aaA.d:
```
extern (C) inout(void[]) _aaValues(inout AA aa, in size_t keysz, in size_t valsz,
```
the call passes a void * instead in libdruntime/object.d:
```
inout(void)[] _aaValues(inout void* p, in size_t keysize, in size_t valuesize, const TypeInfo tiValArray) pure nothrow;
...
auto a = cast(void[])_aaValues(cast(inout(void)*)aa, Key.sizeof, Value.sizeof, typeid(Value[]));
```
The problem is that on 32-bit SPARC small structs are passed by reference, so there's a mismatch between caller and callee.
On 64-bit SPARC instead, they are passed by value, so the mismatch doesn't matter and the tests …
=> object: Declare private struct AA and fix aaA function signatures

src/core/runtime.d, src/core/stdc/math.d, src/core/sys/posix/fcntl.d, src/core/sys/posix/spawn.d, src/core/sys/posix/sys/stat.d, src/core/thread.d, src/rt/aApplyR.d, src/rt/config.d, src/rt/dmain2.d, src/rt/monitor_.d, src/rt/qsort.d
Mostly just looked at places discovered where failures were occurring on DragonFly/x86_64.
=> [dmd-cxx] Backport more port fixes from master

src/core/sys/linux/link.d, src/core/sys/posix/setjmp.d, src/core/sys/posix/sys/stat.d, src/core/sys/posix/ucontext.d
=> [dmd-cxx][S390] Add druntime bindings to fix SystemZ multilib builds

src/core/sys/posix/aio.d
=> [trivial][aio][uclibc] Add missing `else` from version checks

src/core/runtime.d
This is a step toward making unittest reporting better as discussed [here](https://forum.dlang.org/post/qbnamt$2h5h$1@digitalmars.com).
=> Better formatting of unittest failure

src/core/sys/windows/winbase.d
https://docs.microsoft.com/en-us/windows/desktop/api/minwinbase/ne-minwinbase-findex_info_levels
=> Add missing enum for FindFirstFileEx.

src/core/simd.d
The indentation in core.simd is cattywampus.  This PR attempts to fix it.
=> [Trivial] Fix indentation in core.simd

src/rt/alloca.d
Found another 16 byte stack alignment issue
=> alloca() - align to 16

src/core/simd.d
I couldn't find any tests for these in DMD or druntime.  Also, it appears the template constraint was missing the floating point types, but the implementation included them.
=> Add unittests for load/storeUnaligned in core.simd

changelog/linux-clone-unshare.dd, src/core/sys/linux/sched.d
Add them to core.sys.linux.sched.
=> Add clone and unshare Linux system calls

src/core/runtime.d
[This doc is pretty poor](https://dlang.org/phobos/core_runtime.html#.defaultTraceHandler)
=> Add documentation, example, and make code for defaultTraceHandler more readable

src/rt/util/container/hashtab.d
In support of https://github.com/dlang/dmd/pull/10130
=> Replace opIn_r with opBinaryRight in hashtab.d

src/rt/dmain2.d
... (`wmain`/`wWinMain`) and/or the option to tamper with the command-line arguments, which will be used by future ldc2/ldmd2 executables (e.g., expanding response files before forwarding to `_d_[w]run_main`, so that the compiler doesn't ignore `--DRT-*` options in the response file).
=> [Windows] rt.dmain2: Add _d_wrun_main for wide C entry points

test/common.mak, test/stdcpp/Makefile
Improve the stdcpp test makefile.
=> Refactor stdcpp tests makefile

changelog/std_vector.dd, mak/COPY, mak/DOCS, mak/SRCS, mak/WINDOWS, src/core/stdcpp/vector.d, test/stdcpp/Makefile, test/stdcpp/src/vector.cpp, test/stdcpp/src/vector_test.d, test/stdcpp/win64.mak
This is WIP, gotta wrangle CI.
=> std::vector

src/core/stdcpp/vector.d, test/stdcpp/src/vector.cpp, test/stdcpp/src/vector_test.d
Found some edge cases I missed in the tests.
=> std::vector fixes

changelog/std_string.dd, src/core/stdcpp/string.d, test/stdcpp/src/string_test.d
Removed `alias this`, added slice/index operators.
Improved tests.
=> std::string improvements

src/rt/sections_osx_x86_64.d, src/rt/util/utility.d
That one was merged before I became aware of it.
=> [stable] Follow-up on #2713

changelog/std_string.dd, src/core/stdcpp/string.d, test/stdcpp/Makefile, test/stdcpp/src/string_test.d
I knew something was wrong!!
It was all too easy...
=> Fix string tests not running

src/core/thread.d
=> Documentation fixes in core.thread.

src/object.d
=> Allow template opCall for update

src/object.d
Thanks @Laeeth for spotting it.
=> Fix typo in update docs

changelog/atomic_fetch_add.dd, src/core/atomic.d
Naked functions remove all the surrounding junk, and register utilisation matches calling convention.
Note: Not finished. I just need CI to run over it, and confirm the ABI is correct for all paltforms.
=> Further improve cas functions

src/core/sys/posix/dirent.d, src/core/sys/posix/pthread.d, src/core/sys/posix/pwd.d, src/core/sys/posix/sys/mman.d, src/core/sys/posix/sys/socket.d, src/core/sys/posix/sys/wait.d
=> [Musl] Fill in empty version blocks for extern(C) bindings

src/core/internal/atomic.d
@ibuclaw Thanks for spotting it!
=> Failure test was at the wrong indentation level.

changelog/std_optional.dd, mak/COPY, mak/DOCS, mak/SRCS, mak/WINDOWS, setmscver.bat, src/core/stdcpp/optional.d, test/stdcpp/Makefile, test/stdcpp/src/optional.cpp, test/stdcpp/src/optional_test.d
I think this is done; just gotta get the tests in order...
=> std::optional

src/object.d
Demangles the string from deco.
=> Fix Issue 3831 - writeln of a delegate typeid

src/rt/lifetime.d
clear padding area not completely zeroed for struct allocations with dtor
=> Issue 20155 - Allocating a struct with dtor on the GC heap can produce false pointers

src/core/internal/util/array.d
=> core/internal/array.d: replace Error with assert()

src/core/sys/posix/config.d
=> Fix __WORDSIZE definition for 32 bits Musl

src/core/sys/posix/sys/socket.d
=> [Musl] fix SO_* for MIPS

src/core/internal/convert.d
Doesn't really work due to limitations in DMD front-end.
A modified front-end that normalizes real values in the same way that integers are produces the correct result.
Likewise, this CTFE implementation produces the correct result at run-time.
=> core.internal.convert: Implement support for IBM extended float.

src/core/internal/lifetime.d
Copy code from object.destroy() to emplaceInitializer().
Source:
https://github.com/dlang/druntime/blob/77574b3226d667514f6927961ba636816afef042/src/object.d#L3375-L3392
=> Simplify emplaceInitializer

changelog/gc_in_finalizer.dd
* Correct documentation link
* Add a note about `GC.runFinalizers`
=> [changelog]: Improve GC.inFinalizer changelog entry

src/core/internal/execinfo.d
In case the 'module' part is a path containing dashes, which crept in with #2834.
=> [stable] Fix regression for GNU backtraces

src/core/sys/posix/fcntl.d, src/core/sys/posix/semaphore.d, src/core/sys/posix/sys/stat.d, src/core/sys/posix/sys/types.d
https://github.com/dlang/druntime/pull/2898 but for stable
=> stable: Fix broken 'stat' definitions for ARM, AArch64 & more

src/core/demangle.d
Trying to avoid exceptions for most C(++) mangled names.
=> core.demangle: Add fast path for obvious non-D names

src/core/thread/osthread.d
=> simplify versions in getStackBottom

src/core/sys/windows/w32api.d
Correct and update SDKDDKVERs based on Windows Kits values.
=> Update and fix SDKDDKVERs

src/gc/impl/conservative/gc.d, test/exceptions/src/line_trace.d
Blocking https://github.com/dlang/dmd/pull/10812
=> fix printf format

azure-pipelines.yml
building with LDC now needs DMD as a host compiler for tools, too
=> fix azure pipeline

src/rt/trace.d
Looking at this code, it is very obvious it hasn't been touched for years, if not over a decade.
It also needlessly exposes a bunch of C symbols which could easily conflict.
Here I am trying to refactor it gradually without triggering the issue I saw in #2969 .
=> rt/trace: Some refactorings & code cleanup

src/test_runner.d
The previous code failed to compile with LDC for non-ARM targets. Fix that via proper versioning and switch from LDC-specific `__asm` to GDC-style `asm`, incl. tampering with the FPU mode with GDC too.
=> [stable] Fix test_runner regression for LDC

src/core/sys/linux/dlfcn.d, src/core/sys/linux/elf.d, src/core/sys/linux/epoll.d, src/core/sys/linux/err.d, src/core/sys/linux/errno.d, src/core/sys/linux/execinfo.d, src/core/sys/linux/fcntl.d, src/core/sys/linux/ifaddrs.d, src/core/sys/linux/link.d, src/core/sys/linux/sched.d, src/core/sys/linux/stdio.d, src/core/sys/linux/string.d, src/core/sys/linux/sys/mman.d, src/core/sys/linux/sys/sysinfo.d, src/core/sys/linux/tipc.d, src/core/sys/linux/unistd.d
Add missing `@system` annotations.
=> add @system to core.sys.linux.*

src/object.d
Reported by @GilesBathgate: https://github.com/dlang/druntime/pull/3012#discussion_r400751879
=> object: Fix punctuation in example comment

src/core/internal/dassert.d, test/exceptions/src/assert_fail.d
This should finally unblock dlang/dmd#11027
=> Merge stable into master

src/core/cpuid.d
No reason to not upstream this.
cc @kinke @ibuclaw
=> [core.cpuid] LDC uses GNU style asm

src/rt/trace.d
cc @ibuclaw I'm presuming this implementation is also fine for GDC
=> [rt.trace] AArch64 implementation and LDC reposition

src/core/demangle.d
pelase see also https://github.com/dlang/dmd/pull/11049 and https://github.com/dlang/dlang.org/pull/2777
=> core.demangle: add FuncAttrLive

src/core/thread/fiber.d, src/gc/impl/conservative/gc.d, src/rt/backtrace/macho.d, src/rt/deh_win64_posix.d
Better reviewed commit-by-commit. I was going over a few things in druntime, and started to accumulate quite a lot of commits, so here is a first batch that should be dead-easy to review.
=> Some minors import / constant cleanup

mak/COPY, mak/SRCS, src/core/thread/context.d, src/core/thread/fiber.d, src/core/thread/osthread.d, src/core/thread/package.d
Factor out the common code dealing with stack contexts and callable.
=> Factorise Thread and Fiber

test/exceptions/Makefile
cc @kinke does this look fine to you?
=> upstream LDC changes for test/exceptions/Makefile

src/gc/os.d
Looks like this code branch is not covered by CI
=> Correct wrong import name

benchmark/aabench/bulk.d, benchmark/gcbench/vdparser.extra/vdc/interpret.d
* Replace TypeTuple with AliasSeq.
=> Use std.meta instead of std.typetuple

src/core/sys/posix/sys/ioctl.d
With apologies to @gizmomogwai, recreating his https://github.com/dlang/druntime/pull/3103 that I messed up while trying to edit the commit message. Targeting `stable`.
=> Fix issue 20832 - Fix ioctl request for TCSETS2

src/core/sys/darwin/sys/attr.d
Some of the stuff here is used by https://github.com/dlang/phobos/pull/7466.
=> Add module core.sys.darwin.sys.attr with getattrlist, setattrlist, searchfs, and related definitions

src/core/internal/moving.d
NB: this fix disregards DIP1014's advice to either not use `hasElaborateMove!T` within `__move_post_blt` or to use it only once at the start of the function.
=> [DIP1014] __move_post_blt: recursively call on fields that are static arrays & do not recursively call on non-field members

src/core/sys/posix/sys/ioctl.d
- Fix issue 20832 - Fix ioctl request for TCSETS2
=> merge stable

src/rt/util/utf.d
=> [dmd-cxx] Rename foreach variable to get rid of shadowing

src/core/math.d
Companion to https://github.com/dlang/phobos/pull/7565
=> fabs: make it pure, match it to std.math.fabs

src/core/internal/string.d
Last of the tryptic https://github.com/dlang/druntime/pull/3169 - https://github.com/dlang/phobos/pull/7568/files
=> Remove old (un)signedToTempString functions

src/core/internal/traits.d
Due to the lack of recognition for immutable, it wasn't possible to do certain atomic operations,
e.g. storing an immutable pointer to a struct into a shared pointer to an immutable struct.
=> Recognize immutable in core.internal.traits : hasUnsharedIndirections

src/rt/backtrace/dwarf.d
Nothing fancy, just clearing out cast, and putting logic together.
=> rt.backtrace.dwarf: Slightly refactor reading directories and source list

src/core/demangle.d
Implemented in dlang/dmd#11474
Inspired by #2847
=> Add demangling support for 'in' storage class

src/core/demangle.d
This was an oversight of the original PR caught by ibuclaw.
https://github.com/dlang/druntime/pull/3183#issuecomment-669025953
=> Fixup PR3183: Also recognize 'in ref' in demangler

posix.mak, win32.mak, win64.mak
=> Enable -preview=dtorfields for druntime

win64.mak
This may be useful for someone else.
(I hate windows)
=> Add comments for VS2019.

src/core/internal/hash.d
`object` imports `core.internal.hash` so the compiler was always opening `src/core/internal/convert.d` regardless of whether it was needed.
=> Avoid import of core.internal.convert when unneeded

src/core/thread/osthread.d, src/core/thread/threadbase.d
Found via https://github.com/dlang/dmd/pull/11781
=> Annotate attachThread as `nothrow`

src/core/sync/rwmutex.d
Remove overhead compared to argless `tryLock()` when the lock is immediately available. In other cases the system time can be checked one time fewer.
=> Make tryLock(Duration) more efficient at slight expense of verbosity

src/object.d
~~This is the simplest thing that works. Perhaps it would be worth trying to speed this up using a preallocated swap buffer and memcpy like the previous implementation was trying to do.~~
=> Fix Issue 21315 - TypeInfo_StaticArray.swap is broken

azure-pipelines.yml
=> Sync Azure CI script with DMD's

src/rt/critical_.d
There was some memoisation going on in the if condition, so this protects against multiple threads calling `new` to assign to the same pointer.
=> rt.critical_: Use atomics to read from/write to the _d_criticalenter2 parameter

src/rt/critical_.d
=> [dmd-cxx] rt.critical_: Implement _d_criticalenter2 library helper

src/core/attribute.d
This is the druntime part of adding support for Objective-C protocols.
=> Add UDA for optional Objective-C interface methods

src/core/memory.d
=> MEMSTOMP debug is not compatible with this GC unittest

src/core/thread/threadbase.d
Spent few days to find GC-related bug covered by this assertions
=> Adds stack scan assertions

src/rt/backtrace/dwarf.d
Needed for https://github.com/dlang/dmd/pull/11509
=> Update `LineNumberProgram` up to DWARF v5

benchmark/gcbench/vdparser.extra/vdc/parser/mod.d, benchmark/gcbench/vdparser.extra/vdc/util.d, src/core/demangle.d
Following https://github.com/dlang/dmd/pull/11989
=> Remove support for extern(Pascal)

mak/DOCS, src/core/internal/dassert.d
Give this module a proper documentation to make it easier to maintain.
=> Document and expose core.internal.dassert

src/core/simd.d
Added documentation on LOD/STO mnemonics.
=> fix Issue 8046 - simd.d needs some documentation

src/core/internal/backtrace/dwarf.d
Just some hanging commits I had locally.
=> Minor refactoring / documentation to the backtrace code

src/object.d
=> object: improve code style consistency

src/rt/monitor_.d
=> rt: monitor_: simplify _d_setSameMutex logic

src/rt/cover.d
=> rt: cover: complete documentation for _d_cover_register2 hook

src/object.d
=> object.d: Improve coverage by adding some missing unittests

mak/COPY, mak/SRCS, src/core/bitop.d, src/core/checkedint.d, src/core/cpuid.d, src/core/internal/traits.d, src/core/math.d, src/core/simd.d, src/core/sys/posix/locale.d, src/core/thread/osthread.d, src/core/vararg.d, src/core/volatile.d, src/rt/lifetime.d
Aligns up the intrinsics modules with what the compiler is capable of handling.
=> [dmd-cxx] Backport intrinsics modules from master, couple more Solaris fixes. 

src/core/sys/darwin/fcntl.d
This is the preparation for https://issues.dlang.org/show_bug.cgi?id=21627.
=> macOS: add core.sys.darwin.fcntl

mak/COPY, mak/DOCS, mak/SRCS
first PR is incorrect, and this fixes it.
=> Fixup #3372: Add new modules to COPY/DOCS/SRCS

src/core/sys/linux/epoll.d
=> sys/linux/epoll: add EPOLLWAKEUP constant, epoll_pwait() call and add documentation

src/core/stdc/stdlib.d, src/object.d
Time to give it a spin.
https://github.com/dlang/DIPs/blob/master/DIPs/accepted/DIP1034.md
=> DIP1034 add noreturn to object, abort, exit, _Exit

src/core/memory.d, src/rt/lifetime.d
In preparation for dlang/dmd#12242.
=> Remove usage of 'in' on _d_newitemU

src/core/memory.d, src/core/runtime.d, src/core/stdc/errno.d, src/core/stdc/math.d, src/core/stdc/stdio.d, src/core/stdc/wchar_.d
This also allows removal of some private function declarations.
=> Remove bodies of D functions that are trivial wrappers of C functions

src/core/sys/openbsd/unistd.d, src/core/sys/posix/unistd.d
From @PetarKirov's comment in https://github.com/dlang/druntime/pull/3402, create a new module `core/sys/openbsd/unistd.d` and put pledge and unveil in there.
=> Begin OpenBSD unistd.d extension module with plegde and unveil.

src/core/demangle.d
Added 'f' before mangled name as requested by @rainers in https://github.com/dlang/dmd/pull/12300#issuecomment-805544964
CC @ibuclaw
=> core.demangle: Fix mangling ambiguity, follow-up to #3408

src/object.d, src/rt/profilegc.d, src/rt/trace.d
Had this locally, but forgot to check-in.
=> [dmd-cxx] Add noreturn alias and more printf format fixes

test/exceptions/src/assert_fail.d
=> Add tests for struct equals

src/core/internal/backtrace/elf.d, src/core/internal/elf/dl.d, src/core/internal/elf/io.d, src/core/sys/openbsd/sys/link_elf.d, src/rt/sections.d, src/rt/sections_solaris.d
=> Fix (mostly) OpenBSD runtime, take 2

src/core/stdc/config.d, src/core/stdc/math.d, src/core/stdc/stdio.d, src/core/stdc/stdlib.d, src/core/stdc/tgmath.d, src/core/sys/darwin/mach/thread_act.d, src/core/sys/openbsd/sys/link_elf.d, src/core/sys/posix/stdio.d, src/core/sys/windows/com.d, src/core/sys/windows/dbghelp.d, src/core/thread/fiber.d, src/core/thread/osthread.d
Assuming that #3444 and #3446 get merged.
=> [dmd-cxx] Synchronize bindings with upstream druntime master

src/object.d
=> object.d: Remove if-statement whose condition is always true

src/core/internal/convert.d
Found by https://github.com/dlang/dmd/pull/12528
=> Fix lambda syntax in core.internal.convert test

src/core/internal/lifetime.d
Also simplify static array condition. Fix unit test not compiling on DMD & GDC with `double4`.
=> [stable] Followup to PR #3484 for vector base type enums

src/core/internal/backtrace/dwarf.d
This has actually been tested to work with LDC, fixing the `assert(0)` and **numerous** terrible issues of #3189 after looking at the [DWARF v5 spec](http://dwarfstd.org/doc/DWARF5.pdf) (section 6.2.4).
LLVM apparently puts all directory/file name strings into the new `.debug_line_str` section (`DW_FORM_line_strp` form code, one of various encoding options); reading the strings from there would require mmapping that section too, not just the `.debug_line` one.
So at least with LLVM, *all* source file paths (of according DWARF v5 line-number programs) in the exception backtrace string currently show up as `<unknown dir>/<unknown file>`.
=> [stable] Fix Issue 22081 - Utterly broken DWARF v5 support

src/object.d
needed for https://github.com/dlang/dmd/pull/12890
=> add cast(void) to silence warnings in tests

src/core/internal/dassert.d
Add missing DDoc comments and several notes to the implementation.
=> Improve documentation in dassert.d

src/core/demangle.d
introduced in https://github.com/dlang/dmd/pull/12952
Make both ways work for now.
=> account for name mangling adjustment

src/object.d
This reverts commit 1f9a9b00e057b0ebda9763caa9a46a8cb24c8bfe.
Someone wasn't paying attention and a test commit got merged. :-)
=> Revert "Revert "TypeInfo_Class: Make 2 superfluously virtual functions final""

src/core/internal/traits.d
Depends on: https://github.com/dlang/phobos/pull/8241
=> Fix core.internal.traits.Fields implementation for interfaces

posix.mak, src/core/internal/traits.d, test/traits/Makefile, test/traits/src/all_satisfy.d
This request fixes the regression (issue 22210) by reverting fe4556f (#3459) and 406e51c (#3463).
It also adds a unit test for issue  22210.
=> Fix issue 22210 - Partially revert #3459 and #3463

src/core/sys/freebsd/config.d
=> FreeBSD version 13.0-CURRENT

src/core/demangle.d, src/core/internal/lifetime.d, src/core/lifetime.d, src/core/sync/mutex.d, src/core/thread/osthread.d, src/core/thread/threadbase.d, src/object.d, src/rt/aaA.d
=> Prefer __traits(initSymbol) over TypeInfo.initializer()

src/core/internal/array/construction.d
This is needed so the compiler doesn't call `__ArrayDtor` to destroy the returned array `to` before the eventual exception is thrown back to the caller. In this case, `_d_arrayctor` has already destroyed the initialised elements of the array, while the rest cannot be destroyed, as they haven't been initialised yet.
This PR is needed for this other PR: https://github.com/dlang/dmd/pull/13116
=> [SAoC] Declare array returned by _d_arrayctor in union

posix.mak, src/core/lifetime.d, test/common.mak, win32.mak, win64.mak
Just changing the old switch name to the new name
=> Use `-preview=dip1000` instead of `-dip1000`

src/core/internal/convert.d
Uncovered by https://github.com/dlang/dmd/pull/13350
=> Add return ref ambiguity workaround for toUbyte

src/core/lifetime.d
Per discussion in https://github.com/dlang/druntime/pull/3638#discussion_r766310457:
Target is assumed uninitialzed, `move` would issue a destructor call if `T` has a destructor, thereby destructing garbage. This should be a recursive `moveEmplace` instead of `move`.
=> moveEmplace of static array to not try and destruct garbage

src/core/lifetime.d
...using the new alias assignment feature
=> Make `core.lifetime.forward` iterative instead of recursive

azure-pipelines.yml
Cherry-picks #3660 to master because of the upcoming brownouts.
=> Cherry-pick Azure upgrade to master

src/core/int128.d
`shr()` has already been optimized to not use a loop around `shr1`, so `sar` becomes `shr` plus sign extending logic.
=> core.int128: Optimize sar()

src/core/sys/posix/dirent.d
This struct is tied to the kernel, not the C run-time.
=> Issue 22689: core.sys.posix.sys.dirent: Separate OS dirent struct from C runtime functions and flags

src/core/lifetime.d
This is needed to simplify the lowering introduced in https://github.com/dlang/dmd/pull/13494 from
```d
throw (__ctfe ? new E(args) : __tmp = _d_newThrowable!E(), __tmp.__ctor(args), __tmp);
```
to
```d
throw _d_newThrowable!E(args);
```
=> Make `_d_newThrowable` return a fully constructed `Throwable`

src/core/sys/posix/sys/resource.d
More Linux-specific flags that were declared under `CRuntime_Glibc`.
=> Issue 22689: core.sys.posix.sys.resource: Separate OS-specific flags and types from C runtime types and functions

src/core/int128.d
Loosely based on the Hacker's Delight algorithm, which is also used in libdivide.  Unlike libdivide though, this has been further adapted so that `128 / 64 -> 128`, instead of `128 / 64 -> 64` in the 64-bit divisor case, which overflows `big128 / small64` (the opposite of what we want to happen).
Trivial cases are handled early: Divide by zero, single precision, numerator smaller than divisor.
This removes the last for/while loop in the `core.int128`.
=> core.int128: Optimize udivmod()

benchmark/gcbench/vdparser.extra/vdc/ast/node.d, benchmark/gcbench/vdparser.extra/vdc/ast/type.d, benchmark/gcbench/vdparser.extra/vdc/interpret.d, benchmark/gcbench/vdparser.extra/vdc/logger.d, src/core/internal/gc/impl/conservative/gc.d, src/object.d, src/rt/dmain2.d, src/rt/dwarfeh.d
=> Replace usages of classinfo with typeid

src/core/sys/windows/wingdi.d
See https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-geticmprofilew
=> Fix GetICMProfile signature

src/core/stdc/math.d
This version branch was left behind when all the others had pure added.
=> core.stdc.math: Annotate classify functions with pure for UClibc

src/object.d
As per comment:
> The xopEquals and xopCmp members are function pointers to member functions, which is not guaranteed to share the same ABI, as it is not known whether the `this` parameter is the first or second argument. This wrapper is to convert it to a delegate which will always pass the `this` parameter in the correct way.
Fixes last difference between GDC and DMD druntime Object interfaces.
The new implementation results in the same assembly as the old.  https://d.godbolt.org/z/5h9E5qcYT
The same probably should be done for xtoHash as well, but that is not immediately in the firing line for something that breaks GDC due to DMD's extern(D) divergence from the system x86 ABI (it'll likely bite us when methods are `thiscall` though).
=> object: Wrap fake member function calls into delegates

src/core/attribute.d
In accordance with Walter's post on the forum:
https://forum.dlang.org/post/stsalj$3a0$1@digitalmars.com
=> Make core.attribute.mustuse lower-case

test/hash/src/test_hash.d
Needed for https://github.com/dlang/dmd/pull/12689
=> Add explicit `return ref` to test_hash

src/core/internal/gc/bits.d, src/core/internal/gc/impl/conservative/gc.d, src/core/internal/gc/pooltable.d
Was looking into making `GC.stats` `@safe` and `@nogc`, and it is quite the rabbit hole.
Those changes at least should be non-controversial.
=> Add attributes to GC's `PoolTable` / `BitSet` and tidy up some GC internals

src/core/stdcpp/string.d
3rd try to fix freebsd failure in https://github.com/dlang/dmd/pull/13658
=> add return scope to as_array()

src/core/gc/gcinterface.d, src/core/internal/gc/impl/conservative/gc.d, src/core/internal/gc/proxy.d, src/core/memory.d
Better reviewed commit-by-commit.
=> `core.memory`: Make GC.[profile]stats safe/nothrow/nogc

src/importc.h
Easier to support it than argue about it.
=> fix Issue 22880 - importC: support __restrict__ __signed__ __asm__

src/core/exception.d
BetterC-compatible code should be allowed to import the symbols in this
module, as long as it does not attempt to use them at runtime when
compiled in BetterC mode.
=> Fix issue 22763 - importing std.utf fails in BetterC

.cirrus.yml
See https://github.com/dlang/dmd/pull/14076
=> cirrus.yml: Use an alternative mirror for FreeBSD 11

src/importc.h
C tools don't always support // comments.
Blocking https://github.com/dlang/dmd/pull/14121
=> no // comments in .h files

src/core/internal/array/appending.d
The current implementation is slow because it calls `copyEmplace` on every new element of the destination array. If `T` has a postblit, it is more efficient to blit all new elements at once and only then call `__xpostblit()` on them individually.
=> Optimise template `_d_arrayappendT`

posix.mak
After this succeeds, we'll do the other .c files in posix.mak.
=> compile posix errno_c.c file with ImportC

posix.mak
=> compile src/rt/*.c with ImportC

src/importc.h, win64.mak
Dogfooding ImportC for mscoff object files
=> compile mscoff .c files with ImportC
