dlang/druntime

- src/core/stdc/stdio.d
- src/core/sys/windows/dll.d
- src/core/thread.d
- src/rt/dmain2.d
Minimal reboot of https://github.com/dlang/druntime/pull/2505/ . This should hopefully contain only uncontroversial changes required to build druntime for MinGW. We have to hurry a bit to get this still into GCC-9, as that will likely be released next friday.
Related phobos PR: https://github.com/dlang/phobos/pull/6980
Related GDC PR: https://github.com/D-Programming-GDC/gcc/pull/14
> [GDC] GCC9 last-minute fix: MinGW changes to get druntime to build

- src/core/stdc/stdio.d
- src/core/sys/windows/dll.d
- src/core/thread.d
- src/rt/dmain2.d
Backport of https://github.com/dlang/druntime/pull/2586
> [dmd-cxx] GCC9 last-minute fix: MinGW changes to get druntime to build (Backport 2586)

- changelog/gc_parallel.dd
- src/core/gc/config.d
- src/core/sys/windows/dll.d
- src/core/thread.d
- src/gc/bits.d
- src/gc/impl/conservative/gc.d
- src/rt/msvc.c
- test/shared/src/dllgc.d
- test/shared/src/dllrefcount.d
- test/shared/win64.mak
- win32.mak
- win64.mak
I can make the commits separate PRs if it is desired, but this is why events and unmanaged threads are needed.
> add parallel marking to the GC

- src/core/sys/posix/aio.d
> core.sys.posix.aio: CRuntime_Bionic does not implement AIO

- mak/COPY
- mak/SRCS
- mak/WINDOWS
- src/core/sys/bionic/string.d
- src/core/sys/darwin/string.d
- src/core/sys/dragonflybsd/string.d
- src/core/sys/freebsd/string.d
- src/core/sys/linux/string.d
- src/core/sys/netbsd/string.d
- src/core/sys/netbsd/sys/featuretest.d
- src/core/sys/openbsd/string.d
memmem is a function present in the "string.h" header
of many posix operating systems, although its presence
in the standard library is not covered by the C standard
nor by the posix standard.
However it is present in most parts of posix implementations
of the C standard library, so i think it's possible to expose
it in the druntime.
memmem is very useful for analyzing data when pointers need to
be used, so far it was necessary to manually implement a similar
function to do it and it was quite inconvenient and redundant.
> Add memmem to core.sys

- src/core/stdc/fenv.d
- src/core/sys/posix/signal.d
- src/core/sys/posix/sys/types.d
- src/core/sys/posix/ucontext.d
A lot of the bindings assumes that CRuntime_Musl == X86_64.
Fixed that up in the bare minimum number of places, so that AArch64 on CRuntime_Musl passes all unittests.
> [musl] Add ports for targets other than x86_64

- src/core/bitop.d
The previous tests didn't demonstrate different results for different directions or magnitudes.
> Improve public core.bitop.rol/ror tests

- src/rt/dwarfeh.d
- test/exceptions/Makefile
- test/exceptions/src/catch_in_finally.d
NOT feeling good about this. Seems to work though???
Mostly opening this PR so tests get run.
This was not arrived at through any kind of insight, but mostly by flailing around.
Ping @donc . Help us Don Clugston, you're our only hope.
edit: @kinke ping? ("No. There is another.")
> Try to fix issue 19831 without understanding by copying the behavior from __dmd_personality_v0

- src/object.d
use CoreDdoc instead of D_Ddoc
the test case isn't so easy to reproduce as it relies on phobos.
> fix Issue 19701 - undefined reference to _D6object__T6hashOf

- src/rt/util/container/common.d
Move the zero-init check to compile time. Plus if the struct doesn't have elaborate assignment or an elaborate destructor we can use `t = T.init` instead of memset/memcpy. LDC optimizes memset to the same as `t = T.init` but for memcpy it is an improvement as the result of `typeid(T).initializer()` isn't a compile-time constant.
>  Improve rt.util.container.common.initialize!T(ref T) if is(T == struct)

- src/core/cpuid.d
As Hygon Dhyana Family 18h("HygonGenuine") share similar arch with AMD Family 17h,  reuse cf.probablyAMD for hygon dhyana process.
related kernel patch link
http://lkml.kernel.org/r/5ce86123a7b9dad925ac583d88d2f921040e859b.1538583282.git.puwen@hygon.cn
> Add Hygon Dhyana Processor CPU Vendor ID detection

- src/core/sys/windows/winldap.d
- src/core/sys/windows/winnt.d
Looked up and corrected most LDAP methods:
changed `char*` (`PCHAR`) arguments to `const(char)*` (`PCSTR`) where documentation says `const`.
Renamed some types to be the same as in the documentation. (purely aesthetic, fit in with adding the const to the parameters well)
Fixed a PLDAPControlW actually being PLDAPControlA in an ASCII method.
Changed `T[]` arguments to `T*` (fixes the referenced issue)
Did not test this with an actual connection yet. The definition is more like in my `ldap` package on dub now, which works for me.
> fix ldap bindings, fix issue 17248

- src/core/stdc/stdio.d
_IO_FILE aka FILE does not mirror the current version of glibc.
This PR fixes that. This came up through https://github.com/ldc-developers/ldc/issues/2782#issuecomment-495221392
> updated _IO_FILE of the glibc version

- src/core/thread.d
Blocking https://github.com/dlang/dmd/pull/9895
> Align fibers to 16 bytes on Linux

- src/core/thread.d
There's no reason to not do it on all x86 targets.
> Align fibers to 16 on x86 targets

- src/core/gc/gcinterface.d
- src/core/memory.d
- src/gc/impl/conservative/gc.d
- src/gc/impl/manual/gc.d
- src/gc/impl/proto/gc.d
- src/gc/proxy.d
- src/rt/profilegc.d
- src/rt/tracegc.d
- test/init_fini/src/custom_gc.d
- test/profile/Makefile
- test/profile/bothgc.log.exp
- test/profile/myprofilegc.log.exp
- test/profile/myprofilegc.log.freebsd.32.exp
- test/profile/myprofilegc.log.freebsd.64.exp
- test/profile/myprofilegc.log.linux.32.exp
- test/profile/myprofilegc.log.linux.64.exp
- test/profile/myprofilegc.log.osx.32.exp
- test/profile/myprofilegc.log.osx.64.exp
- test/profile/src/profilegc.d
This is a revamp of #1846 . I'm having a hard time understanding the results of the test cases added in the original PR. Any help would be appreciated.
cc @leandro-lucarella-sociomantic
Edit: It looks like there is a missing call to resetThreadStats that causes the tests to fail. Can anyone help?
> Rework of -profile=gc calculations

- posix.mak
- test/common.mak
This is required to be able to remove the hardcoded libraries that druntime/phobos depend on when the option `-defaultlib=` is given.
Was able to run the unittests with this change and https://github.com/dlang/dmd/pull/9831
This PR is a small piece in working towards a "pay for what you use" model and removing unnecessary interdependency between the compiler and the standard library.
> Stop relying on compiler to implicitly add pthread/math libraries

- src/core/internal/arrayop.d
- test/betterc/Makefile
- test/betterc/src/test19561.d
Known limitation: slice assignment to a scalar won't work in betterC for types of size other than 1 because the compiler will try to use _memset16/_memset32/etc. This can only be addressed in DMD rather than druntime.
> Issue 19561 - Enable array ops in betterC

- src/core/gc/gcinterface.d
- src/core/memory.d
- src/gc/impl/conservative/gc.d
- src/gc/impl/manual/gc.d
- src/gc/impl/proto/gc.d
- src/gc/proxy.d
- src/rt/tracegc.d
- test/init_fini/src/custom_gc.d
As pointed out by @rainers in #2607, having a way to reset the total memory allocated in a thread is a bad API design as if there are multiple clients they will be competing for the reset.
Instead clients can store the previous value and subtract the next reading to know how much memory was allocated between two arbitrary points and deal with potential overflow.
> gc: Remove resetThreadLocalStats()

- src/object.d
Note that if `lhs` doesn't override `opEquals` the `typeid` comparison will never have to be performed.
> Issue 19975 - object.opEquals(Object lhs, Object rhs) can skip typeid comparison when !lhs.opEquals(rhs)

- src/object.d
- src/rt/array/equality.d
Followup to https://github.com/dlang/druntime/pull/2634 and https://github.com/dlang/druntime/pull/2643
> object.d: Move __ArrayEq to rt

- mak/COPY
- mak/SRCS
- mak/WINDOWS
- src/object.d
- src/rt/array/casting.d
Followup to https://github.com/dlang/druntime/pull/2634
> Refactor object.d: Move __ArrayCast to rt

- mak/COPY
- mak/DOCS
- mak/SRCS
- mak/WINDOWS
- posix.mak
- src/object.d
- src/rt/array/capacity.d
Followup to https://github.com/dlang/druntime/pull/2644, https://github.com/dlang/druntime/pull/2643, and https://github.com/dlang/druntime/pull/2634
> Refactor objectd: Move array capacity functions to rt/array/capacity.d

- src/core/internal/traits.d
- src/object.d
There was an `_isStaticArray` implementation in `object.d` to support `destroy`.  However, [that functionality is already in `std.traits`](https://dlang.org/phobos/std_traits.html#isStaticArray).  So I removed the duplicate implementation in `object.d` and copied it to `core.internal.traits`.  A subsequent PR to Phobos can then be created to forward to the `core.internal.traits` implementation.
I may even follow up with a PR to deprecate [`__traits(isStaticArray)`](https://dlang.org/spec/traits.html#isStaticArray) in favor of the library implementation.
> Refactor object.d: Move isStaticArray to core.internal.traits

- test/exceptions/Makefile
This unittest can fail if there is a ~/.gdbinit file that changes the output of gdb.
For example this project: https://github.com/cyrus-and/gdb-dashboard
> Do not execute commands from any .gdbinit initialization files

- mak/DOCS
- posix.mak
- src/object.d
In my prior PRs (#2647, #2644, #2643, #2634), I did not realize we actually publish documentation on the internal API.  This PR repairs that:
cc @Vild.  I'm sorry, but I was wrong about not needing to document these; they need to be documented in the "Internal API" docs.  You'll just need to add an entry to the `mak/DOCS` file for any new files.
I'd like to remove the runtime lowerings from the object.d documentation, but I haven't yet found a solution to that.  I thought versioning it out with `version(CoreDoc)` would work, but it didn't because these templates are necessary for correct language behavior.  I'm investigating other methods.
> Add documentation for array runtime lowerings for the internal API docs

- changelog/atomic-msync.dd
- changelog/clock-monotonic.dd
- changelog/dlfcn-posix.dd
- changelog/exception-hiddenfunc.dd
- changelog/exception-setasserthandler.dd
- changelog/fiber-call.dd
- changelog/netinet-tcp.dd
- changelog/runtime-initerm.dd
- mak/COPY
- mak/SRCS
- mak/WINDOWS
- src/core/atomic.d
- src/core/exception.d
- src/core/runtime.d
- src/core/sys/linux/sys/netinet/tcp.d
- src/core/sys/posix/dlfcn.d
- src/core/sys/posix/time.d
- src/core/thread.d
It all started with `Fiber.call` then I went down the ~rabbit~ contributor's hole.
> Remove a bunch of old deprecated symbols

- src/core/internal/convert.d
DMD supports `(double x) => *cast(ulong*) &x` and `(int y) => *cast(uint*) &y` during CTFE so there's no need for elaborate measures to determine the bitwise representation of floats and doubles in CTFE.
> Issue 19976 - Simplify std.internal.convert.toUbyte CTFE path for float and double

- posix.mak
- src/core/cpuid.d
- test/cpuid/Makefile
- test/cpuid/src/cpuid.d
- test/cpuid/win64.mak
- win32.mak
- win64.mak
do not use i7 detection on AMD processors
use cpuid 0x8000_001E to detect the number of threads per core
It seems AMD uses the term "core" for "logical cores" or threads, too.
> fix Issue 19861 - core.cpuid reports the wrong number of threads

- src/core/internal/traits.d
- src/object.d
This PR implements the druntime side of [DIP1014](https://github.com/dlang/DIPs/blob/master/DIPs/accepted/DIP1014.md).
The accepted DIP is a little ambiguous about whether `nothrow` should be required on `opPostMove` (i.e. applied to `__move_post_blt`). Quoting: 
> `opPostMove`, if implemented, MUST be `nothrow`.
>
> [...]
> This proposal does require that `nothrow` be defined on `opPostMove`, because throwing would mean a change in the program flow from a place that appears to execute no code. There is a danger that this will be too confusing for the programmer to properly take into account.
>
> [...]
>
> The DIP author suggested the requirement could be eased to "a very hearty recommendation" because D moves "everywhere" and it is "impossible" to prevent it from doing so.
cc @Shachar
>  Implement druntime side of DIP1014

- src/object.d
- src/rt/array/capacity.d
dmd PR: https://github.com/dlang/dmd/pull/10106
`rt.array.capacity._d_arraysetlengthT` will call the `_d_arraysetlength{,iT}` depending on if `T` is zero initialized, this logic used to be inside of dmd.
> Translate _d_arraysetlengthT to template

- src/rt/sections_osx_x86.d
Rename to __tls_get_addr to keep same ABI.
This depends on dlang/dmd#7620 getting merged.
> Switch linkage of ___tls_get_addr to extern(C).

- src/core/internal/traits.d
- src/object.d
https://github.com/dlang/druntime/pull/2649  should not have been approved. The private `_isStaticArray!T` in `object` was only used in one place. The correct "refactoring" was to remove it not to promote it to `core.internal.traits` and make it public and start using it everywhere. The `isStaticArray` template is both slower and more complicated than what what it was replacing, with no justification for the replacement other than "it's possible".
Please save the library-building for Phobos.
> Remove the newly-added core.internal.traits.isStaticArray

- src/core/sys/dragonflybsd/sys/socket.d
- src/core/sys/posix/sys/socket.d
Concessions are made for IPX and APPLETALK, but they shouldn't really be there either (for all platforms, not just dragonfly).
FYI @dkgroot
> Move non-standard DragonflyBSD AF and PF constants to core.sys.dragonflybsd

- posix.mak
- win32.mak
- win64.mak
This PR adds a rule to the makefile for generating docs of the upcoming `core.experimental` modules.
It also adds a version identifier (`CoreUnittest`) that can be used to conditionally compile internal unit testing code, i.e. code that shouldn't be included in user code when compiled with `-unittest`.
We currently already have [two](https://github.com/dlang/druntime/pull/2608/files#diff-228b518f4545d060f900578830ade5daR90) [PRs](https://github.com/dlang/druntime/pull/2646/files#diff-228b518f4545d060f900578830ade5daR90) using `CoreUnittest` and [two](https://github.com/dlang/druntime/pull/2646/files#diff-228b518f4545d060f900578830ade5daR158) [PRs](https://github.com/dlang/druntime/pull/2662/files/45d20332263ec7ca876aa91183f6c9fdac25de01#diff-228b518f4545d060f900578830ade5daR155) adding …
> Add common base for core.experimental

- changelog/darwin-loader.dd
- src/core/sys/darwin/mach/loader.d
This also updates the file to match the macOS 10.15 SDK.
It's probably easiest to not look at the diff but look at the actual file.
> Add all missing symbols to `loader.d`

- src/core/sys/posix/pthread.d
* Darwin: Not available.
* NetBSD: According to man-page, pthread_condattr_getclock was added in 8.0,
which is very recent version. Left out for now.
> Add support for pthread_condattr_setclock/pthread_condattr_getclock

- src/object.d
- src/rt/array/capacity.d
This PR fixes two problem that happens when trying to apply https://github.com/dlang/dmd/pull/10106.
Firstly, it marks the hooks with `pragma(inline, false)` to not break the `dmd/dinterpret.d` ctfe interception code.
Secondly, it wraps both of the hooks inside of a template to force the compiler to create an instance of both function for every type that is used.
This fixes a undefined reference problem that can will happen when `Appender` from phobos is used with `-profile=gc`. The linker complains about a missing `_d_arraysetlengthTTrace!Tarr` instance, as phobos only had the `_d_arraysetlengthT!Tarr` instance compiled in its library, and not the `_d_arraysetlengthTTrace!Tarr` instance. By forcing both hooks to be always be instantiated, this problem will not happen.
> Move _d_arraysetlengthT* into a template to always instantiate both

- src/core/internal/hash.d
- test/hash/src/test_hash.d
https://issues.dlang.org/show_bug.cgi?id=20034
> Issue 20034 [Reg 2.087.0] hashOf of a non-scalar enum doesn't compile

- mak/COPY
- mak/DOCS
- mak/SRCS
- mak/WINDOWS
- src/object.d
- src/rt/array/construction.d
DMD PR: https://github.com/dlang/dmd/pull/10102
- This adds `rt.util.array` to `mak/COPY` as its a dependency for `_d_arrayctor`
- `_d_array{,set}ctor` uses `@trusted` to not break code, `pure` and `nothrow` can be automatically deduced by the compiler
- `_d_arraysetctor` no longer returns a return value as it causes warnings:
```
std/container/array.d(97): Warning: calling rt.array.constructor._d_arraysetctor!(const(Array!int))._d_arraysetctor without side effects discards return value of type const(Array!int)[], prepend a cast(void) if intentional
```
> Translate _d_array{,set}ctor to templates

- src/core/sys/freebsd/sys/event.d
- src/core/sys/freebsd/sys/mount.d
- src/core/sys/posix/dirent.d
- src/core/sys/posix/sys/stat.d
- src/core/sys/posix/sys/statvfs.d
This fixes building on FreeBSD >= 12 without introducing OS version conditions.
---
Since https://github.com/dlang/dmd/pull/8567 is still in endless bikeshedding mode, let's just do this already.
> Link to 32-bit inode symbols on FreeBSD

- mak/COPY
- mak/DOCS
- mak/SRCS
- mak/WINDOWS
- src/object.d
- src/rt/array/concatenation.d
dmd PR: https://github.com/dlang/dmd/pull/10064
This adds a templated entrypoint for _d_arraycatnTX entrypoints.
I don't think there should be any problems with this entrypoint but I do have problem with the dmd implementation.
> Add templated _d_arraycatnTX with tests

- src/core/runtime.d
The format specifier "%zu" doesn't exist in the MS C runtime before VS2015.
The segfault happens using DMD with Mingw-w64 libraries.
> Fix issue 20048: Unittest printing fails on Windows when using msvcr100.dll

- src/gc/impl/conservative/gc.d
- src/rt/sections_elf_shared.d
- src/rt/util/container/hashtab.d
In support of https://github.com/dlang/dmd/pull/10179
explicitly use `const` or `scope const` instead, until `in` is properly implemented.
The use of `in` as a parameter storage class is already discouraged in the documentation.  See https://dlang.org/spec/function.html#parameters
> Replace usages of `in` with `const scope`

- mak/COPY
- mak/DOCS
- mak/SRCS
- mak/WINDOWS
- src/rt/array/capacity.d
- src/rt/array/concatenation.d
- src/rt/array/utils.d
- src/rt/profilegc.d
This should be the final fix needed to be able to get https://github.com/dlang/dmd/pull/10106 to pass all the unittest.
This code uses a pure bypass technique I found inside of dmd's source code so no more ugly hacky casts are needed for calling `GC.stats()` and `accumulate`.
I've also refactored the two previous *Trace functions into `HookTraceImpl` to make sure that all the Trace functions are implemented correctly and to make it easier to change in the future.
The `HookTraceImpl` also contains a `if (...) assert(0);` check to make sure that the compiler does not remove the call to `accumulate`, which is what is currently happening in https://github.com/dlang/dmd/pull/10106.
> Cleanup and fix implementation of _d_array{setlengthT,catnTX}Trace

- src/core/attribute.d
Include it under `version(CoreDdoc)`.
> Make the  UDA visible in the generated docs

- mak/COPY
- mak/DOCS
- mak/SRCS
- mak/WINDOWS
- posix.mak
- src/core/internal/array/capacity.d
- src/core/internal/array/casting.d
- src/core/internal/array/comparison.d
- src/core/internal/array/concatenation.d
- src/core/internal/array/construction.d
- src/core/internal/array/equality.d
- src/core/internal/array/utils.d
- src/core/internal/util/array.d
- src/core/thread.d
- src/object.d
- src/rt/arrayassign.d
- src/rt/arraycat.d
- test/profile/mytrace.def.exp
Introducing `rt` as a public importable package caused a few things to break:
- [Digger](https://forum.dlang.org/post/qfkip6$e3q$1@digitalmars.com) and [users' personal installation scripts](https://forum.dlang.org/post/mailman.9997.1562298463.29801.digitalmars-d-announce@puremagic.com) did not expect the need to copy the `rt` package to the installation directory.
- [The new modules are included in `-deps` output](https://dlang.slack.com/archives/C1ZDW7FJM/p1563202138044600?thread_ts=1559465086.006300&cid=C1ZDW7FJM), meaning build tools relying on it for recursive compilation would require changes to ignore the `rt` package.
- Apparently the change also [broke the LDC build system](https://forum.dlang.org/post/pqrlfsgibsspgzkwuwhn@forum.dlang.org).
The arguments in favor of keeping the …
> Move rt.array to core.internal.array

- src/core/internal/array/capacity.d
- src/core/internal/array/casting.d
- src/core/internal/array/comparison.d
- src/core/internal/array/concatenation.d
- src/core/internal/array/construction.d
- src/core/internal/array/equality.d
- src/core/internal/array/utils.d
> core.internal.array: Fix "Source code" links in docs

- src/core/stdc/fenv.d
- src/core/stdc/inttypes.d
- src/core/stdc/locale.d
- src/core/stdc/stdio.d
- src/core/stdc/wchar_.d
- src/core/stdc/wctype.d
Followup to https://github.com/dlang/druntime/pull/2676 and https://github.com/dlang/phobos/pull/7110
This is the first of several PRs I intend to submit, breaking up https://github.com/dlang/druntime/pull/2677 into multiple PRs.
This PR only addresses C language bindings in `core.stdc`.  Since C does not have any concept of scoped pointers, I think it is arguably a mistake for these to be `in`.
explicitly use `const` or `scope const` instead, until `in` is …
> Replace `in` with `const scope` in `core.stdc`

- src/core/sys/darwin/dlfcn.d
- src/core/sys/darwin/mach/dyld.d
- src/core/sys/darwin/mach/getsect.d
- src/core/sys/darwin/pthread.d
- src/rt/sections_osx_x86.d
- src/rt/sections_osx_x86_64.d
Followup to 
This PR only addresses C language bindings in `core.sys.darwin`.
explicitly use `const` or `scope const` instead, until `in` is properly implemented.
The use of `in` as a parameter storage class is …
> Replace `in` with `const scope` in `core.sys.darwin`

- src/core/internal/array/capacity.d
- src/core/internal/array/concatenation.d
- src/core/internal/array/utils.d
Renamed HookTraceImpl template-function based on feedback from @JinShil 
https://github.com/dlang/dmd/pull/10106#discussion_r304543465
> Renamed HookTraceImpl to _d_HookTraceImpl

- mak/COPY
- mak/DOCS
- mak/SRCS
- mak/WINDOWS
- src/core/internal/array/appending.d
- src/core/internal/array/utils.d
- src/object.d
- src/rt/lifetime.d
dmd PR: https://github.com/dlang/dmd/pull/9982
This PR adds templated version of `_d_arrayappend{T,cTX}`.
- There are wrapper around each hook to fake the safety level of the real implementations to not break code.
- I only translated the entrypoints for the hooks and not the called functions. Because this would have taken took long. Future working can be done to rewrite these functions.
- `_d_arrayappend{c,w}d` were not translated because they did not use TypeInfo in their interface. But they were changed to use the new hooks.
> Translate _d_arrayappend{T,cTX} to templates

- src/rt/dwarfeh.d
currentLsd starts off with being null, so the function always breaks on the first loop without doing anything.
@FeepingCreature
> Test fix for 19831

- src/object.d
- src/rt/dmain2.d
Followup to 
This PR only addresses object.d, rt/dmain2.d, and only addresses non-controversial changes.  See https://github.com/dlang/druntime/pull/2685#discussion_r304370819 for some of the more controversial stuff.
implementing `in` now will likely break …
> Replace some usages of `in` with `const scope` for object.d and rt/dmain2.d

- src/core/sys/linux/dlfcn.d
- src/core/sys/linux/sys/xattr.d
Followup to 
This PR only addresses code in src/core/sys/linux
explicitly use `const` or `scope const` instead, until `in` is properly implemented.
The use of `in` as …
> Replace `in` with `const scope` for src/core/sys/linux

- src/core/sys/solaris/dlfcn.d
- src/core/sys/solaris/libelf.d
- src/core/sys/solaris/link.d
Followup to 
This PR only addresses code in src/core/sys/solaris
explicitly use `const` or `scope const` instead, until …
> Replace `in` with `const scope` for src/core/sys/solaris

- src/core/sys/posix/arpa/inet.d
- src/core/sys/posix/net/if_.d
- src/core/sys/posix/netinet/in_.d
Followup to 
This PR only addresses code in src/core/sys/posix/arpa|net|netinet
implementing `in` now will likely break code, …
> Replace `in` with `const scope` for src/core/sys/posix/arpa|net|netinet

- src/core/sys/posix/sys/ipc.d
- src/core/sys/posix/sys/mman.d
- src/core/sys/posix/sys/resource.d
- src/core/sys/posix/sys/select.d
- src/core/sys/posix/sys/shm.d
- src/core/sys/posix/sys/socket.d
- src/core/sys/posix/sys/stat.d
- src/core/sys/posix/sys/time.d
- src/core/sys/posix/sys/uio.d
Followup to 
This PR only addresses code in src/core/sys/posix/sys
implementing `in` now will likely break code, so it is …
> Replace `in` with `const scope` for src/core/sys/posix/sys

- src/core/sys/posix/dirent.d
- src/core/sys/posix/dlfcn.d
- src/core/sys/posix/fcntl.d
- src/core/sys/posix/grp.d
- src/core/sys/posix/iconv.d
- src/core/sys/posix/inttypes.d
- src/core/sys/posix/pthread.d
- src/core/sys/posix/pwd.d
- src/core/sys/posix/sched.d
- src/core/sys/posix/semaphore.d
- src/core/sys/posix/signal.d
- src/core/sys/posix/stdio.d
- src/core/sys/posix/stdlib.d
- src/core/sys/posix/termios.d
- src/core/sys/posix/time.d
- src/core/sys/posix/ucontext.d
- src/core/sys/posix/unistd.d
- src/core/sys/posix/utime.d
Followup to 
This PR only addresses code in src/core/sys/posix/
been properly implemented so its current implementation is …
> Replace `in` with `const scope` for src/core/sys/posix

- mak/WINDOWS
do not create directories unconditionally to avoid emitting error messages
> windows: cleanup copied import folders

- src/core/internal/array/construction.d
- src/core/internal/arrayop.d
- src/core/internal/parseoptions.d
- src/core/internal/utf.d
- src/core/internal/util/array.d
Followup to 
This PR only addresses code in src/core/internal
been properly implemented so its current implementation is equivalent …
> Replace `in` with `const` and `const scope` for src/core/internal

- src/core/sys/windows/stacktrace.d
- src/core/sys/windows/winldap.d
- src/core/sys/windows/winreg.d
- src/core/sys/windows/winuser.d
Followup to 
This PR only addresses code in src/core/sys/windows
explicitly use `const` or `scope const` instead, until …
> Replace `in` with `const` and `const scope` for src/core/sys/windows

- src/core/bitop.d
- src/core/gc/gcinterface.d
- src/core/internal/utf.d
- src/core/memory.d
- src/core/runtime.d
- src/core/time.d
Followup to 
https://github.com/dlang/druntime/pull/2696
https://github.com/dlang/druntime/pull/2702
This PR predominately addresses code in src/core/
`in` as a parameter storage class is defined as `scope const`. …
> Replace `in` with `const` and `const scope` in core

- appveyor.yml
- changelog/std_string.dd
- mak/COPY
- mak/DOCS
- mak/SRCS
- mak/WINDOWS
- setmscver.bat
- src/core/stdcpp/allocator.d
- src/core/stdcpp/exception.d
- src/core/stdcpp/string.d
- src/core/stdcpp/xutility.d
- test/stdcpp/src/string.cpp
- test/stdcpp/src/string_test.d
- test/stdcpp/win64.mak
- win64.mak
This is still WIP, but the MS implementation is fully working and usable.
This is blocked on:
* https://issues.dlang.org/show_bug.cgi?id=19179 and 
* implementation of DIP1014
> Added std::string

- setmscver.bat
- src/core/stdcpp/new_.d
- test/stdcpp/src/new_test.d
- test/stdcpp/win64.mak
Enable C++17 unit tests (including `string_view` which hasn't had unit tests run before) for windows where the compiler supports it.
Fixed a bug in `new` when C++17 is enabled.
> Enable C++17 tests

- src/core/gc/gcinterface.d
- src/core/memory.d
- src/gc/impl/conservative/gc.d
- src/gc/impl/manual/gc.d
- src/gc/impl/proto/gc.d
- src/gc/proxy.d
- test/init_fini/src/custom_gc.d
This PR also addresses https://github.com/dlang/druntime/pull/2704#pullrequestreview-268044024
cc @ZombineDev 
Followup to 
https://github.com/dlang/druntime/pull/2696
https://github.com/dlang/druntime/pull/2702
https://github.com/dlang/druntime/pull/2704
This PR predominately …
> Replace `in` with `const scope` for gc implementations

- mak/DOCS
- mak/SRCS
- src/rt/sections_elf_shared.d
- src/rt/sections_osx_x86_64.d
- src/rt/util/utility.d
This also avoids relying on the assumption that the current executable is always the first image.
> Fix shared libraries for LDC on macOS

- test/stdcpp/Makefile
Add GCC old ABI tests. Modern ABI has an interior pointer and is blocked on move constructors.
> std::string GCC tests

- .circleci/config.yml
- .circleci/run.sh
- mak/COPY
- mak/WINDOWS
- posix.mak
- src/core/atomic.d
- src/core/internal/attributes.d
See also:
- https://github.com/dlang/phobos/pull/6645 (Phobos PR)
CC @ZombineDev 
All tests:
```
make -f posix.mak betterC -j10  # all tests
```
Single test:
```
make -f posix.mak src/core/atomic.betterc
```
Useful for e.g. https://github.com/dlang/druntime/pull/2710 or https://github.com/dlang/druntime/pull/2705
> Add @betterC to druntime

- src/core/internal/string.d
- test/betterc/Makefile
- test/betterc/src/test20088.d
Fixes https://issues.dlang.org/show_bug.cgi?id=20088
Since the new `__ArrayCast` template hook, casting arrays is broken in betterC. The reason is that `__ArrayCast` indirectly depends on `TempStringNoAlloc.get`, which is not a template function and doesn't get linked in betterC.
> Make TempStringNoAlloc a template

- src/core/atomic.d
I made a mistake in the last PR choosing the wrong registers.
My memory was faulty! (I thought EDI was a caller-save reg; that's how long it's been!)
> Fix cas register usage

- changelog/deprecate-callStructDtorsDuringGC.dd
- src/rt/lifetime.d
Supersedes https://github.com/dlang/druntime/pull/2513
cc @rainers @edi33416 @andralex
> Deprecated callStructDtorsDuringGC

- CODEOWNERS
- mak/COPY
- mak/SRCS
- mak/WINDOWS
- src/core/atomic.d
- src/core/internal/atomic.d
- src/core/internal/traits.d
Pulled all the noise out into `core.internal.atomic`, which GDC/LDC can easily replace with intrinsics, and can be a reference for DMD intrinsics if that work happens.
`core.atomic` becomes platform agnostic.
> Extract atomic platform specific implementation into an implementation file

- src/core/atomic.d
This should fix the vibe.d build failure.
> Reintroduce const violation bug to fix vibe.d build failure

- src/core/sys/posix/sys/socket.d
As it was added in the proper location in an earlier PR.
> [Musl] Remove duplicate definition of SOCK_RAW

- src/core/internal/traits.d
I need these for core.atomic...
> Move some traits to druntime

- src/core/internal/arrayop.d
- src/core/internal/traits.d
- src/core/time.d
- src/rt/lifetime.d
They were in `core.internal.traits` and not publicly imported so safe to remove.
cc @TurkeyMan
> Remove legacy traits

- mak/COPY
- mak/SRCS
- mak/WINDOWS
- src/core/internal/entrypoint.d
- src/object.d
This will all be dead code until https://github.com/dlang/dmd/pull/10351 is merged.
> Add core.internal.entrypoint to move C main generation logic out of the compiler and into druntime

- src/core/internal/entrypoint.d
Followup to https://github.com/dlang/druntime/pull/2759. I forgot to add the DDoc file header.
> Add documentation header to core.internal.entrypoint

- mak/COPY
- mak/DOCS
- mak/SRCS
- mak/WINDOWS
- src/core/internal/array/operations.d
- src/object.d
Followup to https://github.com/dlang/druntime/pull/2647, https://github.com/dlang/druntime/pull/2644, https://github.com/dlang/druntime/pull/2643, and https://github.com/dlang/druntime/pull/2634
This is a continuation of work to clean up object.d and bring some older conventions in line with the current trends.  There's no change in functionality; this PR has only moved code to a new file ~and renamed `arrayOp` to `_arrayOp` to avoid needing a forwarding template~.
> Move core.internal.arrayop.d to core.internal.array/operations.d to join other array-related files

- mak/DOCS
- posix.mak
- src/core/internal/dassert.d
- src/object.d
Followup to #2647, #2644, #2643, #2634, #2763, and #2765
This is a continuation of work to clean up object.d
> Move _d_assert_fail from object.d to core.internal.dassert.d

- src/object.d
Followup to #2647, #2644, #2643, #2634, #2763, #2765, and #2766
The runtime hooks are only used by the compiler and should not be invoked directly by the user.  This PR moves them to the bottom of object.d's file so they appear last in the documentation.  `_cmp` had to be moved too due to a bug in the compiler causing a conflict with `core.internal.array.comparison.__cmp`.
> Demphasize runtime hooks in object.d's documentation

- mak/COPY
- mak/DOCS
- mak/SRCS
- mak/WINDOWS
- posix.mak
- src/core/internal/moving.d
- src/object.d
Followup to #2647, #2644, #2643, #2634, #2763, #2765, and #2766
~This code was added in https://github.com/dlang/druntime/pull/2638, but it doesn't currently appear to be used anywhere.~
~During the GSoC 2019 project for converting some runtime hooks to templates, we decided that we should be using the naming convention `_d_whatever` for any runtime templates such as this.  That naming convention is already the dominant convention in druntime, so it makes sense to keep it.  It also distinguishes runtime hooks from compiler-generated symbols that are prefixed with `__`.  A few of the templates don't follow the `_d_` convention, but I intend to remedy that with a later PR so all are consistent.~
> Move __move_post_blt from object.d to core.internal.moving.d

- mak/COPY
- mak/DOCS
- mak/SRCS
- mak/WINDOWS
- src/core/bitop.d
- src/core/volatile.d
This PR move the intrinsic volatileLoad and volatileStore into core.volatile,
as promised by the discussion in https://github.com/dlang/druntime/pull/892
and https://github.com/dlang/dmd/pull/4155.
Currently an alias is maintained in core.bitop to avoid broken code,
the alias is marked as deprecated to warn users of the displacement
occurred in the core.volatile
You should probably schedule a removal of the alias from core.bitop and
publish it in https://dlang.org/deprecate.html
> Fix Issue 13826 - Move volatileLoad/Store to core.volatile when the volatile keyword is removed

- src/object.d
Followup to #2647, #2644, #2643, #2634, #2763, #2765, #2766, #2769, and #2772 
This code is not used and appears to be part of a prior experiment.  If it's ever needed we can always recover it from GitHub's history.  Right now it's just more clutter in an already overly cluttered file.
> Remove some unused code from object.d

- src/object.d
Now that https://github.com/dlang/dmd/pull/10365 has been merged, we don't need to document those templates in object.d that are only intended for use by the compiler.  Unfortunately, these may appear in the documentation for one release until https://github.com/dlang/dmd/pull/10365 is folded into the release and dlang.org is updated to use the new compiler.
Also includes @ZombineDev's [suggestion](https://github.com/dlang/druntime/pull/2768#discussion_r318448688).
> Undocument public templates in object.d that are only intended for use by the compiler

- src/object.d
Followup to #2647, #2644, #2643, #2634, #2763, #2765, #2766, #2769, #2772 , #2774
This PR just moves the remaining individual compiler-support features to the bottom of the file to de-emphasize them and keep them separate from the code accessible to users.
> Move compiler-support code in object.d to the bottom of the file with the others

- src/object.d
Followup to #2647, #2644, #2643, #2634, #2763, #2765, #2766, #2769, #2772 , #2774, #2775 
Also, this makes the `Object` class dominate nearer to the top of the file.  This is object.d afterall.
> Reorganzie a few things in object.d so similar constructs are found next to each other

- src/core/atomic.d
Add missing features to the API.
Most functions are slightly more efficient.
Concentrate more specific work into less surface area.
Fixes Issue 20107 - core.atomic : Memory order is missing keys
Fixes Issue 20106 - core.atomic : atomicFence doesn't accept MemoryOrder
Fixes Issue 20105 - core.atomic 'cas' function is incomplete
Fixes Issue 18643 - Compiling error when combining CAS and numeric literal.
Fixes Issue 15007 - core.atomic match C++11
Fixes Issue 8831 - core.atomic: add compare-and-swap function with other result type
> Renovate core.atomic, improve and simplify the constraints on functions

- src/object.d
- src/rt/aaA.d
Followup to 
https://github.com/dlang/druntime/pull/2696
https://github.com/dlang/druntime/pull/2702
https://github.com/dlang/druntime/pull/2704
This PR predominately addresses code in rt/aaA.d
This PR is in support of https://github.com/dlang/dmd/pull/10382
`in` as a parameter …
> Replace `in` with `scope const` in `rt.aaA.d`

- src/rt/critical_.d
- src/rt/dmain2.d
These are the easy ones, `_d_setSameMutex` looks full of race conditions
> Fix some usages of shared.

- mak/DOCS
- posix.mak
These files only contain symbols for the compiler; not for the user.  Since they are in `core.internal` they probably should not be in the documentation.
This is now possible due to the fix in https://github.com/dlang/dmd/pull/10365 and https://github.com/dlang/druntime/pull/2771
> Remove core.internal documentation that only contain symbols for the compiler

- mak/COPY
- mak/SRCS
- mak/WINDOWS
- src/core/sys/bionic/err.d
- src/core/sys/darwin/err.d
- src/core/sys/dragonflybsd/err.d
- src/core/sys/freebsd/err.d
- src/core/sys/linux/err.d
- src/core/sys/netbsd/err.d
- src/core/sys/openbsd/err.d
- src/core/sys/solaris/err.d
err.h although not present in the posix standard it is however present
in most distributions based on Darwin, BSD and Linux
> Fix Issue 16380 - no bindings for err.h

- src/rt/trace.d
Unfortunately rdtsc can produce skewed results without mfence sometimes.
This is what GNU/Linux does in rdtsc_ordered function.
> Serialize rdtsc instruction on x86_64

- src/rt/sections_elf_shared.d
Required for https://github.com/dlang/dmd/pull/10390
> Add `return` to `DSO.moduleGroup()` in support of compiler fix for issue 20149

- src/rt/sections_android.d
The x86 linker scripts don't provide `__bss_end__`, use `_end` instead.
Linker scripts for reference: [x86_64](https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9/+/refs/heads/master/x86_64-linux-android/lib/ldscripts/elf_x86_64.xdc), [AArch64](https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+/master/aarch64-linux-android/lib/ldscripts/aarch64elf.xdc)
Linkability tested with LDC.
> [stable] rt.sections_android: Fix magic linker symbol name for x86 archs

- mak/COPY
- mak/SRCS
- mak/WINDOWS
- src/core/stdc/string.d
- src/core/sys/posix/locale.d
- src/core/sys/posix/string.d
- src/core/sys/posix/strings.d
```
It looks like most of POSIX 2008 is missing from Druntime.
This particular subset is used by Sociomantic's Ocean,
and were ported in an effort to remove duplication.
```
In the process, I've also altered `core.stdc.string` in order to be more future proof (attributes on the right), and alphabetically ordered (as the online documentation is).
> POSIX: Add core.sys.posix.{string,strings,locale}

- src/core/demangle.d
Since `lazy` is easily replaced with a delegate, I wonder if it is worth it at all. Should just use delegates.
> demangle.d: remove use of lazy

- src/core/runtime.d
> runtime.d: replace Error with assert()

- src/core/runtime.d
Such as Android, OpenBSD, musl, ...
> [stable] Fix regression for POSIX systems without backtrace[_symbols]

- src/core/thread.d
the Windows server exception chain validation fails because the initial exception entry is wrong in case the stack was aligned manually. 
See https://github.com/dlang/druntime/compare/master...rainers:issue13821?expand=1#diff-8bb12ed976acf0a5132e877ec5a01ea8L4717
> fix issue 13821 - fiber + exception + win server 2012 failures

- src/core/thread.d
- src/gc/impl/conservative/gc.d
- test/gc/Makefile
- test/gc/forkgc.d
clear thread handles and events for parallel marking in child process after fork
might also fix failing tests in https://github.com/dlang/druntime/pull/2802
> fix Issue 20227 - "Error: phread_mutex_destroy failed." after fork()

- src/gc/impl/conservative/gc.d
background scan threads now wait indefinitely, with termination continuously triggering the condition until all threads have woken up
> Issue 20219 - Idle D programs keep consuming CPU in Gcx.scanBackground

- changelog/wait_attributes.dd
- src/core/sys/posix/sys/wait.d
nothrow and @nogc are already present at the top of the file, so I added these as well since these functions are trivial integer bitwise operations.
> Make wstatus predicates pure and @safe

- azure-pipelines.yml
Will need some adaptions in dmd's files...
> try using dmd's azure-pipeline

- src/gc/impl/conservative/gc.d
- test/gc/Makefile
- test/gc/sigmaskgc.d
Issue https://issues.dlang.org/show_bug.cgi?id=20256
Conservative GC scan threads do not block signals when created, which can lead to unexpected behaviour if developer have to block signals for whole process.
This PR fix issue  by blocking all signals in conservative GC scanThreads.
> problem with signal handling and parallel GC on linux

- src/gc/impl/conservative/gc.d
- test/gc/Makefile
- test/gc/forkgc2.d
Make sure a fork does not happen while GC code is running, thus leaving it in an inconsistent state.
> Add fork handling to GC

- changelog/atomic_cas.dd
- changelog/atomic_exchange.dd
- changelog/std_string.dd
- changelog/std_vector.dd
- src/core/atomic.d
- src/core/internal/atomic.d
- src/core/internal/spinlock.d
So that other architectures can add their special sauce.
> Added `pause` to core.atomic

- src/object.d
It has no effect, and so just confuses matters.
> object.d: remove unnecessary scope attribute

- azure-pipelines.yml
- src/core/thread/fiber.d
This should fix the CI breakage, redoing #2801.
> fix issue 13821 again

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
If you compile the following with `-checkaction=context`:
```D
struct S {
S[] arr;
}
void main() {
assert(S.init == S.init);
}
```
You get:
```
(...)/src/druntime/import/core/internal/dassert.d(115): Error: forward reference to inferred return type of function call miniFormat(v.arr)
```
Changing the `auto` return type of miniFormat to `string` should fix it. 
I can add the test-case for this, but should that be in dmd or druntime?
> -checkaction=context: Fix recursive struct formatting

- src/core/internal/traits.d
- src/core/thread/osthread.d
As seen on at least Solaris, maybe SPARC/Linux as well.
> Fix Issue 19481: mutex.d(95) Error: pthread_mutex_init failed

- src/core/atomic.d
- src/core/internal/atomic.d
This is so it becomes trivial to use this with GCC/LLVM intrinsics based on C++11 and C11.
> core/atomic.d: Fix-up both public and internal API

- src/core/thread/fiber.d
Excess messages cause tests to be marked as failed.
> core/thread/fiber.d: Remove pragma(msg) from unittest

- src/core/sys/posix/sys/uio.d
This request fixes the type of `iovec.iov_len` declared in `core/sys/posix/sys/uio.d` from `uint` to `size_t` for `Runtime_Musl` environment.
The header of `core/sys/posix/sys/uio.d` says:
```d
//
// Required
//
/*
struct iovec
{
void*  iov_base;
size_t iov_len;
}
```
and `iov_len` is declared as `size_t` in other environments.
> Fix type of iovec.iov_len

- src/core/atomic.d
> [stable] core.atomic: Make type repainting in atomicLoad cheaper

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
The old implementation checked only for mutable void[]. 
The diff is slightly larger because i joined the (void[]), (some string) and (some other slice) branches to avoid redundant type checks.
The second commit enables actual formatting for void[] as an array of bytes instead of omitting it.
> Fix Issue 20315 - checkaction=context fails for const(void[]) argument

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
~~This includes #2837 to avoid calling toUtf8 on ubye[]s, ... without excessive template constraints~~
> Fix Issue 20322 - checkaction=context fails for wstring/dstring arguments

- src/core/stdc/fenv.d
https://github.com/dlang/druntime/pull/2844 to master
> core.stdc.fenv: Add missing import for ARM Musl

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
Marking all parameters as `const` additionally reduces the amount of instantiations of `miniFormat`
> Fix Issue 20346 - std.uuid does not compile with checkaction=context

- test/exceptions/src/assert_fail.d
The preceding `//` was missing and `https:` was interpreted as a label.
> Comment bugzilla link

- src/core/sys/freebsd/dlfcn.d
While currently `in` and `const` mean the same thing, they might not
in the future.
This is blocking [this pull request](https://github.com/dlang/dmd/pull/10506).
> Correctly use `in` in FreeBSD static asserts instead of `const`

- posix.mak
- win32.mak
- win64.mak
Build unittests with informative assert messages to improve the CI logs and ease bug hunting (inspired by dlang/phobos#7222).
Draft PR as this revealed some bugs in the implementation of `-checkaction=context`:
CC @burner
> Makefiles: Enable -checkaction-context for unittest builds

- src/core/sys/posix/locale.d
Simple typo:
Version(DragonflyBSD) -> Version(DragonFlyBSD)
> [minor/typo] Fix DragonFlyBSD typo in core/sys/posix/locale.d

- src/core/stdcpp/string.d
Use post-decrement instead of pre-decrement for the ref-count in order to compare the previous value to ref-count to 0.
GCC' std library code ([link](https://github.com/gcc-mirror/gcc/blob/431a9dda09087eb7345c451164a22e9ab6fe250e/libstdc%2B%2B-v3/include/bits/basic_string.h#L3268-L3273)) uses exchange add with `-1` which is the atomic equivalent of post-decrement.
The proper solution is to implement atomic ref counting but this is now blocking https://github.com/dlang/dmd/pull/10593 which in-turn is blocking https://github.com/dlang/druntime/pull/2722.
> Fix a bug in `core.stdcpp.string` port

- changelog/platform_dependent_execinfo.dd
- mak/COPY
- mak/DOCS
- mak/SRCS
- mak/WINDOWS
- posix.mak
- src/core/internal/execinfo.d
- src/core/runtime.d
- src/rt/backtrace/dwarf.d
The initial goal was to resolve link error on systems with musl-libc. This issue was partially solved by #2796 but it didn't support the use of an external execinfo implementation.
This very PR is meant to support all platforms (libc versions) with execinfo (backtrace) functionality included and those with an external execinfo library. In the external lib case, we need to set the corresponding version ID depending on which `backtrace_symbols` output format is used.
Modifications:
* many boilerplate code removed
* clarifying the usage of `CRuntime_Glibc`, `linux` and `Posix` version IDs in execinfo related code
* thorough execinfo availability introspection
* compile time helper code placed into a separated module (`core.internal.execinfo`)
> Refactoring and resolving inconsistency in platfrom dependent execinfo import

- src/core/sys/posix/sys/socket.d
Hello,
I've just noticed that SO_REUSEPORT is missing in the druntime for musl and AFAICS it has been in musl for some time now. I _think_ `socket.d` is missing the right definition for `SO_*` for all of mips though, see the header for mips from musl:
```
#define SO_DEBUG        1
#define SO_REUSEADDR    0x0004
#define SO_KEEPALIVE    0x0008
#define SO_DONTROUTE    0x0010
#define SO_BROADCAST    0x0020
#define SO_LINGER       0x0080
#define SO_OOBINLINE    0x0100
#define SO_REUSEPORT    0x0200
#define SO_SNDBUF       0x1001
#define SO_RCVBUF       0x1002
#define SO_SNDLOWAT     0x1003
#define SO_RCVLOWAT     0x1004
#define SO_RCVTIMEO     0x1006
#define SO_SNDTIMEO     0x1005
#define SO_ERROR        0x1007
#define SO_TYPE         0x1008
#define SO_ACCEPTCONN   0x1009
#define SO_PROTOCOL …
```
> [Musl] add definition for SO_REUSEPORT

- src/core/atomic.d
- src/core/internal/atomic.d
I want to fix this issue.
Some packages are breaking now. :cry:
https://issues.dlang.org/show_bug.cgi?id=20354
> Fix issue 20354: interface is not supported by cas

- src/rt/sections_elf_shared.d
AFAIK, the copy-relocation check is no longer required since the module collision checks has been removed.
> Remove _copyRelocSection symbol from druntime

- changelog/to-prec.dd
- src/core/math.d
Some floating point algorithms, such as Kahan-Babuska-Neumaier Summation,
require rounding to specific precisions. Rounding to precision after
every operation, however, loses overall precision in the general case
and is a runtime performance problem.
Adding these functions guarantee the rounding at required points in the
code, and document where in the algorithm the requirement exists.
Rebase of #1941.
> core.math: Add templated toPrec.

- src/rt/sections_elf_shared.d
DMD uses .init_array/.fini_array instead of .ctors/.dtors since this commit:
https://github.com/dlang/dmd/commit/082a9f459c863120929b86f1559a5e75fd2da60a
> Fix comment for global constructors

- src/object.d
- test/aa/src/test_aa.d
Applies to any type with a custom opAssign that doesn't return a ref to self.
> Fix Issue 20440 - Associative arrays with values whose opAssign doesn't return a ref don't support require function

- src/rt/sections_elf_shared.d
- test/thread/Makefile
- test/thread/src/tlsgc_sections.d
I've hit a segfault in a non-main thread, dereferencing a global TLS static variable, that appears to have been GC'd.
A printf inside `scanTLSRanges` confirmed this.
```
[39936000] scanTLS: tlsRanges{ .length = 4, .ptr = 703090}
[39937280] scanTLS: tlsRanges{ .length = 0, .ptr = 0}    <-- thread 2
[39937280] scanTLS: tlsRanges{ .length = 4, .ptr = 703090}
Segmentation fault (core dumped)
```
Linking against the `version(Shared)` libphobos library does not have the same problem, as `inheritLoadedLibraries` is called on each new thread entrypoint, which calls `getTLSRange` again to get all thread-local ranges.
Neither does this appear to affect other sections support, as they either get the addresses of the thread local `_tlstart`/`_tlsend` brackets, or call …
> rt.sections_elf_shared.d: Populate _tlsRanges in every thread

- src/core/thread/osthread.d
In `thread_entryPoint` we are allocating space using `rt.tlsgc.init`, but it is never given back with `rt.tlsgc.destroy`.
It *could* happen in the destructor for the class, but it checks first that the thread is registered. In this case, by the time the destructor is (eventually) reached, the `scope (exit)` block has already deregistered the thread, so it is basically a NOOP.
I'm adding the relevant cleanup code from the destructor into that `scope (exit)` block, but I'm not 100% sure it's the best place for it. Anyway, there should be no risk of double free, since as I said, the thread is already deregistered at that point.
> Fix Issue 20303 - Memory leak in core.thread

- changelog/unittest-default.dd
- src/core/runtime.d
This should have been done a long time ago, but I forgot about it. The note said it would be switched by 2.080, but we are pushing 2.090 next...
The new default behavior makes it so any unittests present will cancel the running of main, even on a successful test run. The old behavior can be had by passing in a DRT switch (see changelog notes).
> Switch default behavior of tests to only run tests when they are present

- changelog/gc_in_finalizer.dd
- src/core/gc/gcinterface.d
- src/core/memory.d
- src/gc/impl/conservative/gc.d
- src/gc/proxy.d
See the changelog entry and source code comments for details.
> Fix issue 17563 - Expose gc_inFinalizer

- src/core/internal/dassert.d
Reduces each template instantiation to a bare minimum depending on the supplied template arguments to reduce bloat.
Additionally this should avoid dubious error messages when failing to instantiate `miniFormatFakeAttributes`
> Move string concatenation out of _d_assert_fail

- src/core/exception.d
Note: `Class.alignof` doesn't reflect the class alignment, just the class reference's (i.e., `size_t.sizeof`).
> [stable] core.exception: Align TLS store for static Errors

- src/rt/dmain2.d
- test/config/Makefile
- test/config/src/test20459.d
```
This makes druntime argument parsing consistent with the behavior of
options on POSIX systems.
It also ensures that druntime argument can be passed down to other programs,
e.g. for 'dub' and 'rdmd'.
```
> Fix issue 20459 - Runtime arg parsing should stop at POSIX delimiter

- posix.mak
The auto-tester runs `make install` as part of the build step, but it shouldn't do anything on OSX 32 bits.
> Disable `make install` for the Darwin_64_32 target on the auto-tester

- src/core/atomic.d
- src/core/internal/atomic.d
Following on from #2596, rewrite to work with the new atomic API.
This has been peer reviewed by @TurkeyMan 
Best viewed with whitespace ignored, as the removals are only highlighted by indenting the DMD specific code into a version(DigitalMars) block.
> core/atomic.d: Add GDC atomic support code

- src/object.d
- test/exceptions/Makefile
- test/exceptions/src/refcounted.d
`chainTogether` unconditionally incremented the refcount of the second throwable,
even if it was returned without being chained to the first
> Fix Issue 20476 - chainTogether leaks exception with -dip1008

- src/core/sync/barrier.d
- src/core/sync/condition.d
- src/core/sync/semaphore.d
- src/core/sys/posix/sys/select.d
- src/etc/linux/memoryerror.d
user code:
```d
module foo;
import core.sync.barrier;
unittest 
{
assert(1 == 1);
}
```
library:
```d
module core.sync.barrier;
version(unittest) 
{
import core.sync.condition;
import core.sync.semaphore;
// other imports
// classes
// template instantiations
}
```
```bash
dmd -unittest foo.d
```
This is related to: https://github.com/dlang/phobos/pull/6450
> Removed version(unittest) blocks because they introduce big overhead

- src/core/internal/lifetime.d
- src/core/lifetime.d
`emplace` passes arguments by ref instead of using `forward`, this fixes it.
> Fix issue 20468 - `emplace` should forward argument lvalueness correctly

- src/core/thread/fiber.d
- src/gc/os.d
MAP_ANON is provided by core.sys.posix.sys.mman,
so the selective imports don't make sense.
> Remove redundant selective import of MAP_ANON

- src/core/demangle.d
- src/core/internal/convert.d
- src/core/lifetime.d
> More version(unittest) blocks removed

- src/core/sys/posix/fcntl.d
- src/core/sys/posix/semaphore.d
- src/core/sys/posix/sys/stat.d
- src/core/sys/posix/sys/types.d
I'm mostly interested in fixing ARMv7, AArch64 and SystemZ (s390x) for Alpine Linux, but added porting for a few other archs while I was at it.
Will PR against stable as well so we get it fixed in v2.090.1 and hopefully LDC 1.20.0
CC @Cogitri
> dmd-cxx: Fix broken 'stat' definitions for ARM, AArch64 & more

- src/core/internal/entrypoint.d
They served as a workaround for issue 20012 which was fixed in the meanwhile.
https://issues.dlang.org/show_bug.cgi?id=20012
> Remove obsolete pragma(mangle, ...) from entrypoint.d

- src/core/stdc/errno.d
Taken from https://www.winehq.org/pipermail/wine-cvs/2018-July/128910.html
> Fix issue 19909: core.stdc.errno missing POSIX error code on Windows

- mak/COPY
- mak/SRCS
- mak/WINDOWS
As reported by the following script:
```bash
#!/usr/bin/env bash
find_missing_headers() {
for header_file in $(find src/core/ -type f -name "*.d"); do
path="$(echo $header_file | sed -e 's,src/,,; s,/,\\\\,g')"
for make_file in ./mak/{COPY,SRCS,WINDOWS}; do
if ! grep -q "$path" "$make_file"
then
echo "$header_file";
break;
fi
done
done
}
find_missing_headers | sort
```
> Add missing files to makefiles in 'mak/'

- src/core/runtime.d
I just noticed that I forgot to update the docs. They should reflect the current behavior.
> Update docs to reflect current unittest algorithm defaults.

- src/core/stdc/stdint.d
https://github.com/bminor/musl/blob/05ac345f895098657cf44d419b5d572161ebaf43/arch/x86_64/bits/stdint.h#L1-L4
Those definitions are the same on all platforms: https://github.com/bminor/musl/search?p=1&q=int_fast16_t&unscoped_q=int_fast16_t
> [stable] Musl: Fix definitions for [u]int_fast{16,32}_t

- test/shared/src/load_13414.d
On Musl, dlclose is a no-op, save for the fact it invalidates the handler.
This is described in https://wiki.musl-libc.org/functional-differences-from-glibc.html,
and the fact that destructors are not run is explicitly documented.
> Musl: Disable test/shared load_13414 on Musl

- src/core/thread/osthread.d
Being inside the template create three copies of it.
> Don't use a priority cache per member

- src/object.d
This will break if someone instantiate `clear` with an explicit first argument, but that's the danger of IFTI.
> Fix issue 20559: AA.clear segfault when used with alias this

- src/core/sys/windows/w32api.d
> Fix Issue 16658: Default IE version set to 6.0

- src/core/sys/windows/psapi.d
Correct versioning PENUM_PAGE_FILE_CALLBACK
> Fix Issue 15322 - Correct versioning PENUM_PAGE_FILE_CALLBACK

- src/gc/impl/conservative/gc.d
- src/rt/util/container/treap.d
- src/rt/util/random.d
Discussion started from https://github.com/ldc-developers/druntime/pull/168.
> Fix Issue 20550 - Use fixed seeds for treaps in GC

- src/gc/impl/conservative/gc.d
- test/gc/Makefile
- test/gc/nocollect.d
- test/gc/win64.mak
Avoid collection when there is no small/large pool to reuse anyway.
Don't start parallel threads during shutdown
> fix Issue 20567 - GC should not start threads for parallel marking in simple programs

- src/core/thread/osthread.d
glibc's PTHREAD_MIN_STACK is incorrect, so I think adjustStackSize has still problem after https://github.com/dlang/druntime/pull/2904 merged.
> Adjust minimal stack size for thread-local storage in Glibc

- mak/DOCS
- posix.mak
https://dlang.org/phobos/core_thread.html
Those copy-pasted rules are really stupid and should probably be just like Phobos, a `foreach`.
> [stable] Add missing core.thread to documentation

- benchmark/runbench.d
This would be useful for benchmarking simd optimization.
> runbench: add -mcpu=native by default

- src/rt/backtrace/dwarf.d
DMD's implementation of dwarf debug data puts the directory in the filename directly. A more correct implementation, like LDC's, uses the `include_directories`  for that.
The current implementation only uses the filenames when printing the stacktrace. This means that stacktraces for programs compiled using LDC only contained the filename (not including the filepath).
```
package.d:2577 [0x55605bed2022]
stdio.d:3002 [0x55605bed8b53]
primitives.d:276 [0x55605bed8b00]
primitives.d:379 [0x55605bed88db]
format.d:3284 [0x55605bed8320]
format.d:4230 [0x55605bed81c9]
format.d:1854 [0x55605bed3058]
format.d:575 [0x55605bed2863]
stdio.d:1596 [0x55605bed22c6]
stdio.d:3927 [0x55605bed1652]
```
vs
```
/home/yazan/repos/d-devel/ldc/runtime/phobos/std/range/primitives.d:2458 [0x56518645c434] …
```
> Print source file directory in stack traces

- src/test_runner.d
This is required for the some of the Phobos math related tests to pass.
I'm not sure if this applies to other ARM/AArch64 platforms as well.
> Disable FPU fast mode for Apple ARM in test runner

- src/core/stdcpp/xutility.d
- src/rt/msvc.c
- win64.mak
implement weak symbol __stdio_common_vsprintf emitted by VC when compiling "snprintf" in phobos/etc/c/zlib/gzlib.c
detect msvcrt110 and msvcrt120
add test target to skip C++ tests and uuid.lib-test.
needed by https://github.com/dlang/dmd/pull/10814
> allow linking with MinGW libs if phobos is compiled with VS 2017+

- src/core/atomic.d
This template couldn't possibly compile, so it has clearly never been instantiated.
Fix the typo and document the trick which is being used.
The typo is `size_t *2` when clearly `size_t.sizeof*2` was meant.
> Fix typo in atomic.ValidateStruct

- changelog/page_size.dd
- src/core/memory.d
These will give the size of a system page in bytes.
> Add `pageSize` and `defaultPageSize`

- src/core/thread/fiber.d
got lost during refactoring #2689 due to missing imports. One disadvantage of using `static if (__traits(compiles, ... ))`.
> Fiber: restore usage of VirtualAlloc

- test/gc/Makefile
- test/gc/win64.mak
noticed in some logs where output is not mixed up, e.g. on azure:
```
D:\a\1\s\generated\Windows\Release\Win32\dmd.exe -m32mscoff -g -unittest -version=CoreUnittest -conf= -Isrc -defaultlib=lib\druntime32mscoff.lib -ofrecoverfree.exe -gx src/gc/impl/conservative/gc.d src/rt/lifetime.d src/object.d test/gc/recoverfree.d
.\recoverfree.exe
3 unittests passed
```
> GC tests: recoverfree and nocollect should not run unittests but main

- src/core/internal/switch_.d
- test/betterc/Makefile
- test/betterc/src/test20613.d
Even though it's not actually used at runtime, the `idup` template in object.d uses druntime features not available in betterC. This makes the compiler throw an error, even though that code is never used. That is a separate issue ([19268](https://issues.dlang.org/show_bug.cgi?id=19268)).
This works around the issue and also simplifies the translation between const items and immutable items with a cast instead of an idup. It should be much less CTFE churn as well.
Also added a betterC test for the issue.
> Fix 20613 - String switch in -betterC fails for 7+ labels

- src/rt/profilegc.d
- src/rt/trace.d
Blocking https://github.com/dlang/dmd/pull/10852
> Fix fprintf arg types

- src/core/memory.d
It doesn't start with a valid character for Assembler/C symbols.
```
/tmp/cc3PpJ3O.s: Assembler messages:
/tmp/cc3PpJ3O.s:6: Error: expected symbol name
/tmp/cc3PpJ3O.s:7: Error: Missing symbol name in directive
/tmp/cc3PpJ3O.s:7: Error: unrecognised symbol type "4"
/tmp/cc3PpJ3O.s:7: Error: junk at end of line, first unrecognised character is `c'
/tmp/cc3PpJ3O.s:8: Error: junk at end of line, first unrecognised character is `4'
/tmp/cc3PpJ3O.s:27: Error: expected comma after name `' in .size directive
/tmp/cc3PpJ3O.s:30: Error: junk at end of line, first unrecognised character is `c'
```
> core.memory: Fix mangle name of core.memory.initialize

- src/rt/trace.d
The whole module was `extern(C)` and the code seems very old.
It would probably benefit from some love, but at the moment I'm just cleaning up for the fact that the module ctors/dtors shouldn't be mangled as `extern(C)`.
See https://issues.dlang.org/show_bug.cgi?id=20627
> rt/trace: Restore `extern(D)` default, apply `extern(C)` selectively

- src/core/internal/convert.d
To prevent `core.math` from potentially importing more modules (the case for LDC). `core.internal.convert` seems to be imported from `object.d`, so extra global imports matter.
> [stable] core.internal.convert: Localize newly added core.math import

- src/core/internal/dassert.d
- src/gc/impl/conservative/gc.d
Blocking https://github.com/dlang/dmd/pull/10872
> Fix printf arg. types 2

- src/core/stdcpp/string.d
When issue 20655 ("attribute inference accepts unsafe union access as
@safe") is fixed, DMD correctly complains about these.
Needed for <https://github.com/dlang/dmd/pull/10884>.
> remove wrong @safe attributes

- src/core/cpuid.d
The old style is now deprecated.
> core.cpuid: Surround gcc-iasm operands with parentheses.

- src/core/cpuid.d
The old style is now deprecated.
This is the backport of #2985.
> [dmd-cxx] core.cpuid: Surround gcc-iasm operands with parentheses.

- src/core/internal/elf/dl.d
- src/core/internal/elf/io.d
- src/core/sys/linux/config.d
- src/core/sys/linux/link.d
- src/core/sys/posix/config.d
- src/rt/backtrace/elf.d
Paving the way for a revamped `rt.sections_android` coming up next (ldc-developers/druntime#178).
> core.internal.elf: Improve usability

- src/core/demangle.d
It's better to be explicit about what's happening.
> pure functions imply scope attribute, but not return attribute

- src/core/attribute.d
- src/object.d
Required for https://github.com/dlang/dmd/pull/10927.
Greatly "inspired" from https://github.com/dlang/druntime/pull/2639
> Add compiler-recognized UDA for Itanium ABI's abi-tags

- src/core/runtime.d
- src/rt/deh.d
- src/rt/deh_win32.d
- src/rt/deh_win64_posix.d
- src/rt/dwarfeh.d
Couple of low hanging fruit I caught while trying to debug the debug infos on OSX.
> Use `backtrace` on POSIX when available

- src/core/demangle.d
More of https://github.com/dlang/druntime/pull/2989
> pure functions imply scope attribute, but not return attribute 2

- src/core/demangle.d
> pure functions infer scope, but not return 3

- src/core/internal/abort.d
and so it cannot be used to call `assert(0, msg)`.
> abort() msg parameter escapes

- src/rt/sections_android.d
Instead of using magic compiler and linker symbols. This solves a bunch of related issues for LDC, see https://github.com/ldc-developers/ldc/issues/3350 - wrong `_end` for x86 architectures, bfd-linker-only support and a requirement wrt. having a D `main` function (in .so libs too) *and* feeding the containing object file as first object to the linker.
In case DMD ever supports Android, its codegen might have to be tweaked (emitting TLS data into sections `.tdata` and `.tbss`; no need for magic `_tls{start,end}` symbols anymore).
> Revamp rt.sections_android, switching to parsing the ELF headers

- src/core/internal/utf.d
- src/rt/aaA.d
- src/rt/monitor_.d
In support of https://github.com/dlang/dmd/pull/10924
> pure functions infer scope, but not return 5

- src/core/memory.d
- src/core/sys/darwin/mach/thread_act.d
The name `AppleARM` was used to indicate any of the platforms: iOS, tvOS and watchOS. The name was misleading since the version identifier for these platforms would be enabled also when compiling for the simulators. The simulators are running x86(-64).
> Rename `AppleARM` version identifier to `iOSDerived`

- .github/workflows/cxx.yml
- posix.mak
- test/common.mak
- test/stdcpp/Makefile
Building on https://github.com/dlang/dmd/pull/10964
This adds a Github action to test with multiple versions of clang on OSX and multiple versions of g++ on Linux. However it is not possible to test clang+Linux because DMD assumes we're targeting g++. Likewise it probably won't be possible to test Windows+clang or Windows+mingw (although I will give it a shot).
CC @TurkeyMan : This should allow us to test with the new ABI as well (by adding a matrix dimension).
> Implement Github actions to test `core.stdcpp`

- posix.mak
- src/core/sys/darwin/mach/getsect.d
- src/rt/dwarfeh.d
I want to use the auto tester to see what happens when we turn on markdown. ~~Don't merge, I may have to fix things first.~~
> Turn on markdown for druntime doc build

- src/core/internal/string.d
This is blocking dlang/dmd#11005.
> [stable] core.internal.string: Make non-mutable TempStringNoAlloc usable

- src/core/internal/dassert.d
This is blocking dlang/dmd#11005.
> [stable] core.internal.dassert: Fix miniFormat for structs with non-copyable fields

- src/core/sys/posix/signal.d
The ordering of some fields in  struct sigaction on s390x (64bit)
differs compared to s390 and other architectures.
This patch adjusts this order according to the definition of
glibc-src/sysdeps/unix/sysv/linux/s390/bits/sigaction.h
Without this fix e.g. the call
sigaction( suspendSignalNumber, &sigusr1, null ) in thread.d
leads to setting the sa_restorer field to 0xffffffffffffffff.
In case a signal, the signal handler returns to this address
and the process stops with a SIGILL.
This was observable in several execution testcases on s390x.
> [SystemZ] Fix layout of struct sigaction_t

- test/exceptions/Makefile
- test/exceptions/src/assert_fail.d
This test should only check the druntime component of `-checkaction=context`,
i.e. that `_d_assert_fail` yields an appropriate assert message. Using `assert`
directly linked this test to the lowering details and made changes changes
quite difficult because one cannot make changes to dmd and druntime in a
single PR (see e.g.  dlang/dmd#11005).
CC @kinke, @wilzbach
> Explicitly call _d_assert_fail in test/exceptions/assert_fail.d

- src/core/sys/posix/signal.d
[Cherry-pick of #3015]
The ordering of some fields in  struct sigaction on s390x (64bit)
differs compared to s390 and other architectures.
This patch adjusts this order according to the definition of
<glibc-src>/sysdeps/unix/sysv/linux/s390/bits/sigaction.h
Without this fix e.g. the call
sigaction( suspendSignalNumber, &sigusr1, null ) in thread.d
leads to setting the sa_restorer field to 0xffffffffffffffff.
In case a signal, the signal handler returns to this address
and the process stops with a SIGILL.
This was observable in several execution testcases on s390x.
> [dmd-cxx] [SystemZ] Fix layout of struct sigaction_t

- src/core/sys/windows/dbghelp.d
Fix UnDecorateSymbolNameFunc from dbghelp
UnDecorateSymbolName must be loaded from dbghelp, before it was always null.
The arguments of UnDecorateSymbolNameFunc were different than the Windows documentation.
The function DecorateSymbolName should only accept ASCII following what specified by its documentation, the Unicode version is UnDecorateSymbolNameW.
See https://docs.microsoft.com/en-us/windows/win32/api/dbghelp/nf-dbghelp-undecoratesymbolname
> Fix UnDecorateSymbolNameFunc from dbghelp

- src/core/sys/linux/sched.d
Unfortunately sched_getaffinity(2) can fail when a kernel have sparse
bitmap even if cpuset bitmap is larger than number of cpus.
So I want to use CPU_COUNT_S instead of CPU_COUNT in this case.
> Add CPU_COUNT_S

- .github/workflows/cxx.yml
Extend the current tests to include MSVC 2019 which is available on the Github runners.
CC @TurkeyMan @PetarKirov
> C++ interop tests: Test on Windows + MSVC 2019

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
Exclude structs wich are implicitly convertible to a slice due to `alias this`".
Fix for dlang/dmd#11027
> Fix Issue 20731 - checkaction=context fails for structs with 'alias <slice> this'

- src/core/stdc/stdio.d
Now that the annotations are ignored per https://github.com/dlang/dmd/pull/11030 we can add them.
> add pragma printf and scanf annotations to stdio.d

- .github/workflows/cxx.yml
This was accidentally removed in dlang/druntime#3025
Without it, some clause do not function properly (e.g. checking the compiler version),
and any attempt at downloading a new clang would fail.
> Github actions: Restore accidentally removed boilerplate

- changelog/isbaseof.dd
- src/object.d
- src/rt/cast_.d
- test/typeinfo/Makefile
- test/typeinfo/src/isbaseof.d
This is equivalent to C#/Java `isAssignableFrom` ~~with the argument swapped with the receiver~~. Naming the method "isAssignableFrom" would be more familiar to people coming from C#/Java (and I would find it convenient since it's one fewer difference to remember between languages) but is potentially misleading: "alias this" and overloadable opAssign mean that this would not actually indicate whether values of one type could be assigned to another.
~~I used the name "isDerivedFrom" since the phrase "derives from" appears in the D online documentation. Swapping the argument order is not ideal, so if someone can think of a sensible name that would work with the same argument order as "isAssignableFrom" please suggest one.~~
> Give TypeInfo_Class/TypeInfo_Interface.isBaseOf like C#/Java isAssignableFrom

- src/object.d
- src/rt/typeinfo/ti_double.d
- src/rt/typeinfo/ti_float.d
- src/rt/typeinfo/ti_real.d
Instead of x86-only XMM. Designate floats, doubles and non-x87 reals as well as all vector types as being passed in SIMD registers, if available.
[This is a tiny piece of ldc-developers/ldc#3393.]
> Generalize meaning of 2nd bit of TypeInfo.flags to pass-in-SIMD-register(s)

- .github/workflows/cxx.yml
This seems to be passing despite my initial concerns.
Also, I am seeing a random failure of stdcpp on some PRs / push, so let's see if it triggers here.
> Enable tests on Linux+Clang

- src/core/internal/lifetime.d
- src/object.d
This partially reverts #2883 (introduced in 2.091). The problem is that for every template instantiation, i.e., emplaced type, 2 new structs are generated, each of which comes with its TypeInfo etc. And that includes all types, incl. primitive types and zero-initialized ones.
So as before that PR, try to handle the trivial cases first, and only use a (simplified) union version if that's not possible. [The union version in #2883 is probably an improvement over the previously used static constant.]
And as Suleyman mentioned that it's code copied from `object.d`, I went the other way and use `emplaceInitializer` in object.d to get rid of needless code duplication.
> [stable] Fix code bloat regressions wrt. core.internal.lifetime.emplaceInitializer

- src/object.d
- src/rt/typeinfo/ti_cdouble.d
- src/rt/typeinfo/ti_cfloat.d
- src/rt/typeinfo/ti_creal.d
The AAPCS64 varargs implementation isn't trivial. As for the SysV x64 ABI, prepare for a `core.stdc.stdarg` implementation making use of `TypeInfo.argTypes()`.
[This is a tiny piece of ldc-developers/ldc#3393.]
> Add method TypeInfo.argTypes() for non-Apple AArch64 targets

- test/thread/src/fiber_guard_page.d
Don't depend on absolute offsets for Fiber private members.
> clean up test/thread/src/fiber_guard_page

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
First step towards `-checkaction=context` for unary expressions. Currently doesn't do any elaborate formatting as done for comparisons but suggestions are welcome.
> Extend _d_assert_fail for unary expressions

- src/core/simd.d
Now that the AVX deprecation in DMD is an error (dlang/dmd#9553), this static condition now works as expected.
Adding in 64-bit aliases, which is supported by MMX, ARM, and AArch64.
> Add 64-bit SIMD aliases, remove D_AVX condition.

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
This adds hexadecimal printing for pointers. ~~Note that it still prefers `toString` for struct pointers if possible (because toString will probably be more useful than raw pointer values).~~
> Fix Issue 20763 - checkaction=context does not format pointers

- changelog/darwin_bindings.dd
- mak/COPY
- mak/DOCS
- mak/SRCS
- src/core/sys/darwin/mach/nlist.d
- src/core/sys/darwin/mach/stab.d
Those bindings were missing, and will be required in order to complete https://issues.dlang.org/show_bug.cgi?id=20510
> Add `core.sys.darwin.mach.{nlist,stab}` bindings

- src/core/sync/condition.d
- src/core/sync/mutex.d
It is to solve [Issue 18011](https://issues.dlang.org/show_bug.cgi?id=18011) by adding shared methods to `core.sync.condition.Condition`.
I also added a shared version of `Mutex#handleAddr` because it is used in `Condition#wait()` method.
> Fix Issue 18011 - core.sys.condition cannot be used as shared

- src/core/internal/convert.d
There is no "Unused" field, and the lower fraction is not always an immediate extension of the higher fraction.
(It's not 1,7,56 -- it is 1,11,52).
A "double double" is really a pair of double precision numbers, both with sign and exponent fields.  If the first number has maximum exponent (so, it is infinity or a NaN), the second number is not
significant; otherwise, the sum of the two numbers (taken as exact numbers, no rounding, no truncation, etc.) is the represented number. The first number should be that, rounded to double precision.
So the second double does "add fraction bits" somewhat like this, but there is an implicit leading 1, for normal numbers, and there can be a gap between the two halves, too (like in 0x1p0 + 0x1p-100).
The implementation itself does not need changing, as …
> core.internal.convert: Correct documentation on layout of DoubleDouble

- src/core/internal/convert.d
Backporting #3066 to the dmd-cxx branch.
> [dmd-cxx] core.internal.convert: Correct documentation on layout of DoubleDouble

- src/core/sys/posix/netdb.d
Comparing the struct addrinfo declarations in <netdb.h>
```
struct addrinfo {
int ai_flags;           /* AI_PASSIVE, AI_CANONNAME, ... */
int ai_family;          /* PF_xxx */
int ai_socktype;        /* SOCK_xxx */
int ai_protocol;        /* 0 or IPPROTO_xxx for IPv4 and IPv6 */
#ifdef __sparcv9
int _ai_pad;            /* for backwards compat with old size_t */
#endif /* __sparcv9 */
socklen_t ai_addrlen;
char *ai_canonname;     /* canonical name for hostname */
struct sockaddr *ai_addr;       /* binary address */
struct addrinfo *ai_next;       /* next structure in linked list */
};
```
There's a mismatch here: the system version has no _ai_pad member on 32-bit SPARC.
> core.sys.posix.netdb: Fix SPARC32/Solaris declaration of addrinfo

- src/core/sys/posix/sys/stat.d
Solaris 11 <sys/stat.h> has
```
struct	stat {
dev_t		st_dev;
long		st_pad1[3];	/* reserved for network id */
ino_t		st_ino;
mode_t		st_mode;
nlink_t		st_nlink;
uid_t		st_uid;
gid_t		st_gid;
dev_t		st_rdev;
long		st_pad2[2];
off_t		st_size;
#if _FILE_OFFSET_BITS != 64
long		st_pad3;	/* future off_t expansion */
#endif
timespec_t	st_atim;
timespec_t	st_mtim;
timespec_t	st_ctim;
blksize_t	st_blksize;
blkcnt_t	st_blocks;
char		st_fstype[_ST_FSTYPSZ];
long		st_pad4[8];	/* expansion area */
};
```
st_pad3 is included in the non-largefile version of struct stat when it shouldn't be.
> core.sys.posix.sys.stat: Fix SPARC32/Solaris declaration of stat32_t

- src/core/math.d
This to follow the merge of dlang/dmd#10654.
> core.math: Re-enable disabled tests and update toPrec comment

- src/core/math.d
druntime part https://github.com/dlang/dmd/pull/7995
> Druntime part of fix for 18559

- mak/WINDOWS
- win32.mak
- win64.mak
- fixup for #3026
- fixes 32-bit release builds with ldc
(vcvars x86, but x64 default target of ldc)
> forward and use -m$(MODEL) when building tools with host dmd

- src/core/sys/posix/sys/stat.d
The pull had removed the right field, but from the wrong struct
> core.sys.posix.sys.stat: Fix previous SPARC32/Solaris change.

- src/core/sys/posix/sys/stat.d
(Backport)
The pull had removed the right field, but from the wrong struct
> [dmd-cxx] core.sys.posix.sys.stat: Fix previous SPARC32/Solaris change.

- test/thread/src/fiber_guard_page.d
The default initialized hard limit is pulled from sysconf(_SC_PAGESIZE), however this varies from platform to platform.  On one x86_64-linux server, the value is 4096, whilst on another powerpc64le-linux server, it is 65536.  It is for the latter PPC server, that the test failed, because the Fiber stack is never overflowed.
> test: Force Fiber guardPageSize to be same as stackSize

- src/core/internal/convert.d
There is no toPrec intrinsic for imaginary types, so must use .im to convert to real as needed.
> core.internal.convert: Handle ireal types on PPC

- src/core/stdc/fenv.d
- src/core/sys/posix/sys/stat.d
- src/core/sys/posix/sys/types.d
- src/core/sys/posix/ucontext.d
With this, both SPARC64 and its SPARC multilib are building phobos just fine.
No run-time test done just yet.
> core.sys: Add SPARC/CRuntime_Glibc bindings

- src/core/sys/posix/sys/stat.d
The non-64bit, non-largefile size on SPARC is 88.
> core.sys.posix.sys.stat: Fix typo from #3084

- mak/COPY
- mak/SRCS
- src/core/internal/vararg/aarch64.d
- src/core/internal/vararg/sysv_x64.d
- src/core/stdc/stdarg.d
- src/core/vararg.d
Complements dlang/dmd#11047. Targeting `stable` for simple inclusion in upcoming LDC v1.22.
> [stable] core.{stdc.stdarg,vararg}: Add support for non-Apple AArch64

- src/core/internal/elf/io.d
Slight refactoring and documentation of MMapRegion in order to make it less awkward to use for consumer that have no need for a typed mapping.
> MMapRegion: Split between typed and untyped, handle error

- src/core/internal/elf/io.d
Introduced by a bad rebase done in PR 3092, caught by @apz28 .
> TypedMMapRegion: Remove wrong duplicated assignment

- mak/COPY
- mak/SRCS
- mak/WINDOWS
- src/core/cpuid.d
- src/core/internal/lifetime.d
- src/core/internal/vararg/aarch64.d
- src/core/internal/vararg/sysv_x64.d
- src/core/math.d
- src/core/stdc/stdarg.d
- src/core/vararg.d
- src/object.d
- win32.mak
- win64.mak
- forward and use -m$(MODEL) when building tools with host dmd
- core.math: Remove static linkage from toPrec instantiation tests
- core.math: Use internal approxEqual to allow some inaccuracies on certain hardware
- core.math: Update toPrec comment to reflect how rounding is done.
- core.math: Re-enable disabled tests
- core.cpuid: Simplify GDC-style inline asm for 32-bit x86 hasCPUID()
- core.cpuid: Fix deprecated syntax for GDC-style inline asm
- Fix potential memory corruption
- Fix code bloat regressions wrt. core.internal.lifetime.emplaceInitializer
> merge stable

- src/core/internal/switch_.d
> switch_.d: remove use of typesafe variadic functions

- src/core/stdc/stdio.d
- src/core/stdc/wchar_.d
Fortunately, these attributes are currently ignored, so we can set them in anticipation of them not being ignored.
> add scope and const to variadic functions

- src/core/cpuid.d
> [dmd-cxx] fix Issue 19861 - core.cpuid reports the wrong number of threads

- changelog/depercate_object_selector.dd
- src/object.d
The reasoning being it's expected that other Objective-C related UDAs will be added in the future. These will have too common names to be imported into the `object` module. To make it consistent, deprecate `object.selector`. Instead the user needs to explicitly import `selector` using `import core.attribute : selector;`.
The impact is expected to be small. It only needs to be added once per module. It's expected that bindings need to only be created once. Tools can be used to generate the bindings automatically, in which case the tools can add the import automatically.
Will follow up with PRs in other projects to match this.
> Deprecate `object.selector`

- src/rt/util/container/treap.d
- src/rt/util/random.d
`rt.util.random.Rand48` is an LCG that holds its state in a 64-bit long but only makes use of the low 48 bits. Replacing it with an LCG that makes use of the full 64 bits is a strict improvement as it takes no additional space and is not slower.
This PR renames `Rand48` to "Rand" so the name will not be misleading. "Rand64" was not chosen because it could give the misimpression that the output is 64 bits.
> Change LCG in garbage collector treap to use full 64 bits of state instead of 48

- .github/workflows/cxx.yml
Removes the need to specify the token, as it is now specified by default.
> Update setup-dlang action to v1

- src/core/internal/parseoptions.d
- src/rt/config.d
- test/exceptions/src/rt_trap_exceptions.d
Needed for compatibility with @safe-by-default.
---
These `@system`-by-default function declarations were found using the deprecation message introduced in https://github.com/dlang/dmd/pull/11176.
> Add explicit @system attribute to extern functions

- src/core/sys/posix/sys/wait.d
This commit adds missing definitions for waitid() to be used.
Vibe.d projects currently do not compile because of this issue.
> Fix issue 20852: core.sys.posix.sys.wait missing definitions on FreeBSD

- src/core/sync/rwmutex.d
This is being submitted as a patch to D runtime because efficient implementation requires access to private fields of ReadWriteMutex.
> Add overloads of core.sync.rwmutex.ReadWriteMutex.Reader/Writer.tryLock that take a timeout duration

- src/core/sys/darwin/sys/attr.d
Achieves this by removing the field initializers. This should be fine because `core.sys.darwin.sys.attr.attrlist` has not yet appeared in a release.
> Followup to #3076: make core.sys.darwin.sys.attr.attrlist usable in betterC

- .github/workflows/cxx.yml
It was moved to the dlang-community organization last night.
> Github CI: Update action name

- src/gc/impl/conservative/gc.d
This is blocking https://github.com/dlang/dmd/pull/11236
The pragma annotation is superfluous anyway because the code wasn't compiled with `-inline`.
> cannot inline setPointerBitmapSmall()

- src/core/checkedint.d
Dividing `0x8000_0000_000_0000 / -1L` causes an arithmetic exception in 64 bit code. When the `muls()` unittests were inlined, the compiler tried to constant fold that division, and crashed.
Don't need more tests, as the newer dmd should inline the existing unittests.
> fix signed multiply overflow detection

- changelog/gc_suffixes.dd
- src/core/gc/config.d
- src/core/internal/parseoptions.d
- src/core/internal/traits.d
- src/gc/impl/conservative/gc.d
Rationale: this is need to fine-tune GC on low memory embedded devices.
User interface default units is MB, unchanged.
> Store memory-related GC options in bytes instead of megabytes.

- src/rt/cast_.d
- src/rt/lifetime.d
Fix errors:
```
src/rt/cast_.d(44): Error: `pure` function `_d_toObject` returns parameter `p`, annotate with `return`
src/rt/lifetime.d(403): Error: `pure` function `__arrayStart` returns parameter `info`, annotate with `return`
src/rt/cast_.d(44): Error: `pure` function `_d_toObject` returns parameter `p`, annotate with `return`
src/rt/lifetime.d(403): Error: `pure` function `__arrayStart` returns parameter `info`, annotate with `return`
```
generated by https://github.com/dlang/dmd/pull/10924
> add return annotations to pure functions

- src/rt/dmain2.d
- test/unittest/Makefile
The number returned by `runModuleUnitTests` is not the number of unittests, but the number of *modules* tested.
> Fix issue 20910: fix misleading unittest runner messages.

- src/core/sys/posix/ucontext.d
Added in https://sourceware.org/git/?p=glibc.git;a=commit;h=25123a1c5c96429d70e75b85a9749b405909d7f2
> core.sys.posix.ucontext: Add new ucontext_t field to save shadow stack (CET)

- mak/COPY
- mak/SRCS
- src/core/thread/fiber.d
- src/core/thread/osthread.d
- src/core/thread/package.d
- src/core/thread/threadbase.d
- src/core/thread/threadgroup.d
- src/core/thread/types.d
Rationale:
* This PR opens ways to write custom Thread implementations for support another architectures
* osthread.d contains incredible 4k lines
Split occurs along OS-specific code (`Thread` class, 'osthread.d', ~2.7k lines) and OS-independent code (`ThreadBase` abstract class, `threadbase.d`, ~1.4k lines). Two other small files is for: one is for supporting purposes and to avoid ctors/dtors cyclic dependencies and one fits `ThreadGroup` class what also moved from osthread.d.
PR was made, primarily, just by copying and pasting code and connecting it if it is need by changing attributes or passthrough from implementation to base class by `extern` symbols. Thus, code behaviour was not changed.
At the next stage it will be possible to move some `Thread` methods to `ThreadBase`. Currently …
> Split osthread.d

- src/core/thread/osthread.d
Fixes regression caused by #3135.
> core.thread.osthread: Re-add import gcc.builtins

- src/object.d
GDC supports C-style variadic arguments on all backends supported by GCC as intrinsics.  There is no desire to support the run-time based va_arg that uses TypeInfo.
> object: Don't compile in argTypes on all GNU targets

- src/core/memory.d
As noted by @WalterBright the test can fail spuriously because the tested pointer might actually reference a valid allocation base address for `memsize == 16`.
Now make sure, the used pointers are inside the area to reallocate.
> fix test for issue 11393 introduced by #2436

- .circleci/config.yml
- .circleci/run.sh
- posix.mak
- src/core/demangle.d
- src/core/time.d
Checking public examples is always worthwhile IMHO.
> Add publictests test checker to druntime (reboot of #2087)

- src/core/bitop.d
Prepare for adding this to the compiler as an intrinsic. It should generate an XCHG instruction.
> fix Issue 21026 - add core.bitop.bswap(ushort)

- src/core/internal/array/operations.d
Supercedes #3155. Unblocks dlang/dmd#7065.
> core.internal.array.operations: Add explicit cast from __vector(void[]) to return type

- src/core/simd.d
These are all broken, so no one can be using them (#3155 is evidence of this).
> Revert #1900 - Add overrides for __simd intrinsics

- src/object.d
All other TypeInfo derivatives use in, but this used scope const.
> TypeInfo_Enum: Fix equals/compare signature

- src/core/bitop.d
Will now work with betterC without all the template rigamarole.
Also adds missing unittests.
> take advantage of bswap(ulong) being an intrinsic

- src/core/bitop.d
https://github.com/dlang/druntime/pull/1495 says that DMD doesn't recognize rotate patterns. But it does, it recognizes the standard pattern. This #1495 uses an unusual pattern, and is not recognized by DMD.
This fixes it to use the usual pattern which DMD recognizes.
> core.bitop: use recognized pattern for rotates

- changelog/array_equality.dd
- src/core/internal/array/equality.d
* Use memcmp for more types (incl. pointers and some static arrays), and don't require both element types to be equivalent (e.g., use it for comparing `wchar[]` and `ushort[]` too).
* Simplify the non-memcmp branch - the previous code seemed to try to do what the compiler already does.
* The previous code for structs without custom `opEquals` basically enforced `-preview=fieldwise` via `.tupleof` comparison. This breaking change with 2.078 almost certainly wasn't intended (and not mentioned in the changelog) and led to undesirable inconsistent behavior.
This reverts that change in semantics.
* Avoid superfluously nested templates and convert the remaining `at()` helper to a module-level template to reduce the number of redundant instantiations.
> Revise core.internal.array.equality

- src/object.d
> No need for dstrcmp in object.d

- src/core/demangle.d
- src/core/internal/abort.d
- src/core/internal/string.d
- src/core/internal/util/array.d
- src/core/time.d
- src/object.d
This is dangerously close to meh, but it's the right thing. The radix is always known statically.
> EASY: Move radix to template parameter in unsignedToTempString

- src/core/demangle.d
- src/core/internal/abort.d
- src/core/internal/string.d
- src/core/internal/util/array.d
- src/core/time.d
- src/object.d
Reverts dlang/druntime#3167
It was force pushed while red and broke master. We should *never* do that.
See companion PR: https://github.com/dlang/phobos/pull/7567
> Revert "EASY: Move radix to template parameter in unsignedToTempString"

- src/core/sys/posix/signal.d
```
As explained in the comment, those functions are part of the
LSB (Linux Standard Base) core specs, hence why all runtimes
implement exactly the same interface.
This will also make those simples available on Musl.
```
Was trying to get eventcore working with `getaddrinfo_a` under Alpine when found this.
CC @Cogitri
> sys.posix.signal: SIGRT{MIN,MAX} is platform specific, not runtime

- src/core/demangle.d
Take advantage of the compiler doing syntax highlighting for us.
I don't know if it was intended to work this way, but it's a neat little trick for library writers.
Before:
After:
> Trivial: Improve error message on mangling error

- src/core/atomic.d
```
This should reduce the amount of boilerplate needed in the implementation,
and hopefully make the code easier to read for everyone.
```
I want to see how it shows up in the doc though, before we merge this.
> Refactor core.atomic : cas into a two-level template

- src/core/stdc/stdarg.d
This is targeting master since there is a chance certain template instantiations break when forced `@nogc`. I hope the test suite covers stdarg well.
> Fix issue 21055 - core.stdc.stdarg is not nogc

- src/rt/backtrace/dwarf.d
Because it is a pointer to an instruction, not just a size_t.
> Backtrace: Change address from size_t to const(void)*

- .github/workflows/cxx.yml
```
Matches what LDC did recently.
Hopefully this will also reduce the cache load,
potentially resulting in less cache eviction,
and so less downloads.
```
> Github Actions: Drop testing for LLVM < v6.0.0

- src/core/cpuid.d
The code:
```
uint[4] a;
asm {
mov a,EAX;
}
```
should fail because of a size mismatch. With https://github.com/dlang/dmd/pull/11570 it now does fail. The solution is to replace `a` with `a+0`. This blocks https://github.com/dlang/dmd/pull/11570
> fix bad size of operand in inline asm

- benchmark/gcbench/vdparser.extra/vdc/ast/node.d
that blocked https://github.com/dlang/dmd/pull/11581.
> remove deprecated usage of a class alocator in gc benchs

- src/core/time.d
Verified evaluating `is(immutable T == immutable Duration)` takes at most 85% the time and at most 77% the memory of `is(Unqual!T == Duration)`. Those figures include fixed compiler overhead since the point was not to precisely measure the difference but to verify that improvement was occurring.
> Reduce trait template use in core.time

- src/core/internal/convert.d
- src/core/internal/hash.d
Verified in an artificial benchmark that evaluating `__traits(isFloating, T) && is(T : real)` takes 85% or less the time and 66% or less the space of evaluating `is(Unqual!T == float) || is(Unqual!T == double) || is(Unqual!T == real))` as a template constraint even when `T` is always `float`.
> Reduce trait template usage in core.internal.hash core.internal.convert

- src/core/internal/string.d
Thanks to https://github.com/dlang/druntime/pull/3167 the buffer no longer has to be greatly oversized for the most common cases.
> unsignedToTempString no longer needs to always size the buffer for radix 2

- changelog/faster_profilegc.dd
- src/core/gc/gcinterface.d
- src/core/memory.d
- src/gc/impl/conservative/gc.d
- src/gc/impl/manual/gc.d
- src/gc/impl/proto/gc.d
- src/gc/proxy.d
- src/rt/tracegc.d
- test/init_fini/src/custom_gc.d
Replacing the call to GC.stats with a new function, which
only returns the needed information, makes the program fast again.
> Fix issue 21070: -profile=gc makes the program much slower

- win32.mak
- win64.mak
See https://github.com/dlang/dmd/pull/11653 for details.
> Disable Windows builds on auto-tester

- posix.mak
The preview is now enabled by default.
CC @wilzbach
> Remove deprecated -preview=markdown flag

- src/core/internal/array/equality.d
This is achieved by splitting off the all-scalar case ~~and by moving the `at` and `trustedCast` helper functions out of the body of `core.internal.array.equality.__equals`~~.
> Reduce template function instantiations related to array equality

- src/core/stdc/complex.d
For performance, and for some platforms (such as win32) they are header-only.
> make cimag() and creal() inlineable

- src/rt/deh.d
- src/rt/deh_win64_posix.d
- src/rt/dmain2.d
I've been looking into the exception-handling code on and off for a few months now, trying to make sense of all of it and see how to improve it. My original goal was to fix the code for OSX, but now I'm just yak shaving.
One of the great mystery was how stack frame are stored and generated. We have some [ugly hacks](https://github.com/dlang/druntime/blob/8baae6cb88813c0fc27e2f1ab5015206e64b3063/src/core/runtime.d#L794-L809) which I hope to get rid off, eventually. I'd also like to be able to provide a better user interface for the backtrace code so a user can cheaply store/display backtrace.
Anyway here's my findings. I don't think the fact that we have a GC-allocation in the middle of EH was expected / wanted, but it's the current state.
> Document `rt.deh`, plus some cleanups

- src/core/thread/osthread.d
- src/core/thread/threadbase.d
It's already `@nogc`, just not marked as such.
> Mark osthread.resume nogc

- src/core/internal/array/casting.d
Introduced by #3185. The compiler checks for matching lengths and no overlap (if bounds checks are enabled); for LDC, this is always delegated to a druntime function (DMD emits inline code in at least some circumstances), which means linking error regressions with `-betterC`.
> [stable] core.internal.array.casting: Prevent superfluous slice copy checks

- src/core/thread/threadbase.d
Caught by an LDC address-sanitizer test. Introduced by abec054a065e82c3fc47e9ebabac9f5e3952b55d.
> [stable] core.thread.threadbase: Fix memory leak regression

- src/core/threadasm.S
(Upstreaming patch from GDC)
The following build error in threadasm.S:
```
Error: opcode not supported on this processor: mips1 (mips1) `sdc1 $f20,(0*8-((6*8+4+(-6*8+4&7))))($sp)'
```
is due to the use of the MIPS II LDC1 and SDC1 hardware instructions for FP register load and store operations.  Instead use the L.D and S.D generic assembly instructions, which are strict aliases for the LDC1 and SDC1 instructions respectively and produce identical machine code where the assembly for the MIPS II or a higher ISA has been requested, however they become assembly macros and expand to compatible sequences of LWC1 and SWC1 hardware instructions where the assembly for the MIPS I ISA is in effect.
> core/threadasm.S: Fix assembly for MIPS I ISA

- src/core/stdc/math.d
- src/core/sys/posix/dirent.d
- src/core/sys/posix/sys/stat.d
Legacy symbols are still needed on macOS 10.16 "Big Sur" when targeting x86_64.
For AArch64 target, there is no need for such legacy symbols and the symbols are the same than on other Darwins.
This commit allows to build druntime and Phobos on Big Sur targetting either `arm64` or `x86_64`.
> [macOS Big Sur] libc symbols for both ARM Mac and x86_64 Mac

- mak/SRCS
No bug issue for the changelog because as far as I can see the addition of `core.stdcpp.utility` wasn't mentioned in any release notes.
> core.stdcpp.utility was not being copied to imports

- win32.mak
- win64.mak
Windows shells might not consider local files when not using an explicit path (`unittest`).
---
Maybe this will solve the reoccurring Azure issue.
> win**.mak: Use explicit path when running unittests

- azure-pipelines.yml
- src/rt/msvc.d
I've introduced the regression with #3223, because the `core.stdc.stdio.FILE` definition is for the MSVC 2015+ runtime and incompatible with older versions, such as 2013 used with the MinGW-based libs.
As the druntime repo here hasn't featured any MinGW CI job, the regression was unnoticed here but later showed up for the DMD repo. So I've added a corresponding CI job to prevent stuff like this in the future.
> Fix Azure CI regression

- src/rt/critical_.d
The current implementation of `synchronized` assumes that the compiler knows what the "target" size and alignment of D_CRITICAL_SECTION will be, and that is what will be allocated statically in the data section.  If the compiler gets either wrong then a crash at run-time may occur.
This new compiler helper instead allocates the size of the critical section on-demand.  So the compiler need only store a `__gshared void*` and pass its address to `_d_criticalenter2` on entering a `synchronized` code block.  Knowledge of the size and alignment of the OS critical section type now becomes a druntime issue, and anyone implementing an alternative D run-time is free to innovate without the need to modify the compiler.
dlang/dmd#11824 will be the eventual implementation of this on the compiler side, …
> rt.critical_: Implement _d_criticalenter2 library helper

- src/core/time.d
If device is booted and performs druntime unittests, this test will fail if it occures in less than 1 second from device start.
This is funny!
> time unittest fix for fast boot devices

- src/core/internal/array/appending.d
- src/core/internal/array/construction.d
- src/core/lifetime.d
With a function signature analogous to `moveEmplace()` - source ref first, then target ref. Allowing non-mutable target types T is required to invoke the correct copy constructor, see the tests.
`std.variant` has a similar [implementation](https://github.com/dlang/phobos/blob/6224cb03a5e272ffc6f0b95b2a8fff498925cc36/std/variant.d#L665-L714) (but insufficient wrt. copy constructors), and there might be more potential usage sites in
druntime/Phobos/user code.
Destructing a partially copied static array has been adopted from copy-constructing a new dynamic array: https://github.com/dlang/druntime/blob/b7391cd28b5d1fff9ffa9d6e675f08c4b4b5385f/src/core/internal/array/construction.d#L49-L71
> core.lifetime: Add copyEmplace() to simulate copy-construction

- .cirrus.yml
Requires https://github.com/dlang/dmd/pull/11868 ~~and an installed GitHub 'app' for this repo~~.
> Add Cirrus CI

- src/core/runtime.d
- src/core/sys/windows/stacktrace.d
Instead, initialize it once as part of `rt_init()`.
Keep it as a module ctor instead of manually initializing it in `rt_init()` because `defaultTraceHandler` might depend on other modules and their module ctors; that's the case for Windows, where generating a trace requires the `core.sys.windows.stacktrace` module ctor to be run first.
> Fix Issue 14226 - Don't initialize/overwrite global trace handler with each thread

- src/rt/critical_.d
Such casting was required for the previous interface of core.atomic, which only permitted shared data ([see dmd-cxx PR for this feature](https://github.com/dlang/druntime/pull/3248)).  However this better implies the intent that the memory being allocated/stored is intended to be accessed from multiple threads.
> rt.critical_: Add casts to shared for _d_criticalenter2

- src/core/threadasm.S
`sub` instruction with set of registers `sp` and `r1` is not supported in <s>EABI</s> **thumb** and causes translation error.
Present PR splits this instruction into two simplier.
above line `sub sp, r1, #72` also will be affected to this issue, but I don't change it because I not tried to run it with FPU platform yet. (When someone will need it, they can fix it analogically without examining details of ARM assembler.)
> Compilation for embedded ARM fix

- test/stdcpp/src/array.cpp
- test/stdcpp/src/string_view.cpp
These 2 files don't compile on Ubuntu 20.10 anymore.
> [stable] Fix stdcpp integration test for g++/libstdc++ 10

- src/core/stdcpp/vector.d
- test/stdcpp/src/vector_test.d
Only pertains to 64-bit Windows since that's the only platform currently supported by core.stdcpp.vector.
> Fix: core.stdcpp.vector cannot have core.stdcpp.vector as element

- src/gc/os.d
Can be invoked if try to allocate big pool on small memory amount
> Adds out of memory check

- src/core/internal/traits.d
- src/core/lifetime.d
A tiny follow-up to #3239. Trying to use it in `std.variant` showed these issues.
> core.lifetime: Fix copyEmplace() wrt. shared/mutability qualifiers

- src/object.d
If the type might contain pointers perform the swap in pointer-sized chunks in case a garbage collection pass occurs partway through the function. Directly affected TypeInfo subclasses that were not overriding swap:
- TypeInfo_AssociativeArray
- TypeInfo_Class
- TypeInfo_Delegate
- TypeInfo_Interface
- TypeInfo_Struct
> TypeInfo.swap must not allow reachable memory to be freed if interrupted by a garbage collection pass

- src/core/internal/convert.d
- src/rt/dmain2.d
The second change just makes it easier to slip in `version (GNU) { version (X86) { ... } }` into the FreeBSD block that sets FPU precision.
> core.internal.convert: Add support for FreeBSD x86 reals

- changelog/musl-32bits.dd
- src/core/sys/posix/sys/types.d
As explained in the comment, `time_t` on Musl is now always 64 bits,
but used to be 32 bits on 32 bits systems.
CC @Cogitri
> CRuntime_Musl: Support v1.2.0 for 32 bits

- .github/workflows/cxx.yml
```
Unfortunately, the documentation states that github.base_ref and github.base_ref
are only available in pull requests, so instead we're using 'github.ref' when
base_ref is empty.
```
Tested on my branch, works.
> GH Action: Check out the correct branch after merge

- src/core/thread/osthread.d
`createLowLevelThread` returns `ThreadID.init` if error occured
> thread.d unittest: assertion added

- src/core/sys/darwin/mach/loader.d
because restricting it to be native-only makes cross-compilation unusable.
> let everybody load core.sys.darwin.mach.loader

- src/core/sys/posix/sys/stat.d
All places updated here are all dead code as constants used in the static condition are all set to false in the config module.
Otherwise, they would have all failed to compile with:
```
Error: returning `this.st_atim.tv_sec` escapes a reference to parameter `this`
...
```
> core.sys.posix.sys.stat: Update all stat_t helper functions with correct attributes

- .cirrus.yml
- mak/COPY
- src/core/sys/freebsd/config.d
- src/core/sys/freebsd/sys/event.d
- src/core/sys/freebsd/sys/mount.d
- src/core/sys/posix/dirent.d
- src/core/sys/posix/sys/stat.d
- src/core/sys/posix/sys/types.d
Rebase of #2280, with `__FreeBSD_version` nits.
Haven't yet tested the second commit against gdc/freebsd.  But the first passes the testsuite and all unittests.
> Issue 17596: Version bindings so that they work for both FreeBSD 11 and 12

- benchmark/gcbench/vdparser.extra/vdc/parser/mod.d
- benchmark/gcbench/vdparser.extra/vdc/util.d
- src/core/demangle.d
Notable dead feature (never been supported) in gdc that should definitely be removed. :-)
> [dmd-cxx] Remove support for extern(Pascal)

- src/core/sys/posix/ucontext.d
This is so that ucontext_t is the correct size on X32.
> core.sys.posix.ucontext: Use (u)long for X86_64 definitions of ucontext_t that use 'long long'

- changelog/accidentally-exposed-sigs.dd
- src/core/thread/osthread.d
Come with some refactoring to this code. It slightly changes the semantic, but I don't think that specific case is realistic.
> Make publicly-exposed {suspend,resume}SignalNumber private

- src/core/cpuid.d
Old assemblers do not recognize xgetbv, and there is no easy way to conditionally compile based on the assembler used.
> core.cpuid: Use .byte sequence instead of xgetbv instruction

- src/object.d
- test/typeinfo/Makefile
- test/typeinfo/src/enum_.d
Also offTi but as that does not seem to be implemented yet mentioning it in the change log would be confusing.
> Fix TypeInfo_Enum.destroy and TypeInfo_Enum.postblit not calling destroy and postblit of base type

- src/core/sys/posix/stdio.d
Best reviewed with [?w=1](https://github.com/dlang/druntime/pull/3298/files?diff=unified&w=1).
The declarations of getdelim and getline have been group in with the other IEEE 1003.1 CX functions, L_ctermid was missing all the BSD-style targets, so that has been added as well.
When it comes to getdelim and getline support:
- CRuntime_Glibc, CRuntime_UClibc, CRuntime_Musl have had support either since first release, or before standardization.
- CRuntime_Bionic has had support for an undetermined number of years, but I don't think it really matters.
- Darwin has had support since 10.7 (2011), I intend to make the gate more granular soon by introducing something similar to `__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__`.
- FreeBSD has had support since version 8.0, for this `__FreeBSD_version …
> core.sys.posix.stdio: Conditionally declare getdelim and getline, add missing L_ctermid

- src/rt/aaA.d
- test/aa/src/test_aa.d
This can easily lead to InvalidMemoryOperation (e.g. in Vibe.d).
> Fix 21442: Do not call shrink for AA in finalizers

- src/core/atomic.d
I noticed a mistake in the documenttion on the `cas` function in `core.atomic`. It wrongly states that the second category of overloads expect the `writeThis` to be a pointer, this should be `ifThis`. I made some additional clarifications as well.
Specifically, I removed the phrase about the return value as it does not apply exclusively to the first category. It made no sense to add it somewhere else, as the return value is already documented correctly as well.
> Fix documentation of cas

- .cirrus.yml
- .github/workflows/cxx.yml
This currently trigger a (small) deprecation message.
The rationale is that HOST_DC should be any D compiler,
while HOST_DMD expects a DMD-like compiler.
> Cirrus, Github CI: Use HOST_DMD instead of HOST_DC

- src/core/stdcpp/vector.d
- test/stdcpp/src/vector_test.d
Related discussion at https://forum.dlang.org/thread/efjydhujahujqjrvmnsk@forum.dlang.org
> Fix inscrutable template error when core.stdcpp.vector of a struct with a core.stdcpp.vector field is referenced before the struct's definition

- src/core/sys/freebsd/sys/event.d
- src/core/sys/freebsd/sys/mount.d
- src/core/sys/posix/dirent.d
- src/core/sys/posix/sys/stat.d
- src/core/sys/posix/sys/statvfs.d
Support for `.symver` in the GNU toolchain only came in starting from [binutils 2.35](https://sourceware.org/binutils/docs-2.35/as/Symver.html#Symver), even then, calling such symbols directly is still not supported by gas.
See https://d.godbolt.org/z/PsdPGT
> freebsd: Don't use versioned symbols with GDC

- src/core/memory.d
- test/gc/Makefile
- test/gc/attributes.d
Those functions never worked, and would cause an infinite recursion.
In a non-optimized build that would exhaust the stack and trigger a SEGV,
however in the optimized build we distribute, it results in an infinite
loop as tail call optimization is performed.
> Fix 21484: Infinite loop in core.memory : GC.{get,set,clr}Attr(const scope void*...)

- src/core/sys/posix/ucontext.d
- src/core/thread/fiber.d
It turns out I was wrong about the size, and there is a data field that brings the sizeof ucontext_t to some 1088 bytes, not 56. :-)
This isn't headers copied ad verbatim, rather I've collapsed all fields into static arrays where it made sense to do so.
On testing core.thread, I came across an issue specific to Darwin makecontext() implementation where the ucontext_t object [isn't set-up](https://github.com/Apple-FOSS-Mirror/Libc/blob/2ca2ae74647714acfc18674c3114b1a5d3325d7d/x86_64/gen/makecontext.c#L98-L107) if the stack size is smaller than MINSIGSTKSZ.
Although I don't see this mentioned anywhere in the ucontext documentation, I just went with applying this to all targets that use the fallback ucontext_t implementation, on the assumption that ucontext preserving the current signal mask …
> Darwin: more fixes for ucontext_t implementation of core.thread.Fiber

- src/core/sys/linux/execinfo.d
Make extern C functions in core.sys.linux.execinfo `@nogc`
> Add @nogc to core.sys.linux.execinfo

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
The operator is not required at compile time and can hence be passed as a runtime parameter to create less unique template instations.
CC @Geod24
> Pass operator as a runtime parameter to _d_assert_fail

- src/object.d
If everything a function does is wrapped in a trusted lambda instead mark the function as trusted.
> Remove unnecessary trusted lambdas

- src/core/memory.d
- src/rt/lifetime.d
As hopefully idiomatic alternative to the `&[value][0]` 'pattern', which doesn't compile anymore since dlang/dmd#10124 (because the element of the array literal is an rvalue now).
> core.memory: Add moveToGC() to promote values to new GC allocations

- src/core/internal/backtrace/dwarf.d
See https://github.com/dlang/druntime/pull/3321 for the full context.
Technically, the first commit could be discarded since `processCallback` is reused by `traceInfoOpApplyImpl2`, but it just makes the code much easier to reason about and opens up the possibility to fold it into the `opApply` directly in the future.
> Refactor some backtrace code to make it possible to use libunwind

- src/core/stdc/stdarg.d
The compiler handles all va_arg functions as intrinsics.
> core.stdc.stdarg: Don't import core.internal.vararg when using GDC

- changelog/libunwind.dd
- mak/COPY
- mak/DOCS
- mak/SRCS
- src/core/internal/backtrace/dwarf.d
- src/core/internal/backtrace/handler.d
- src/core/internal/backtrace/libunwind.d
- src/core/runtime.d
Each individual commit gradually refactor things, the second-to-last commit adds simple bindings, and the last commit adds actual support. I had a hard time getting this to a point where there is absolutely no breaking change, but after months of work, it's finally there.
The code left in `dwarf.d` is not pretty, but is surely much better than before. The main issue is that when we run the state machine, we need to iterate on all `Location`s to fill them, but when the user iterate, they iterate one `Location` at a time.
This forces us to keep an array, as re-running the state machine for every iteration would lead to insufferable performance issues (not actually benchmarked).
A proper solution would probably be to extend the debug infos emitted so we can do lookups more efficiently, but …
> Add experimental support for libunwind-based stack trace printing

- src/core/sys/posix/config.d
> [stable] Android: Fix compilability regression wrt. missing __USE_FILE_OFFSET64

- mak/COPY
- mak/DOCS
- mak/SRCS
- src/core/internal/backtrace/unwind.d
- src/rt/dwarfeh.d
As discussed when core.internal.backtrace.libunwind was introduced (PR 3321),
druntime already depends on the high-level functions of the libunwind API,
which are part of C++ Itanium ABI.
By moving them in the same package, we will allow the backtrace handler
to use _Unwind_Backtrace (which is a GNU extension implemented by LLVM)
and dladdr to get the addresses and function names.
> Move rt.unwind to core.internal.backtrace

- src/core/internal/backtrace/dwarf.d
- src/core/internal/backtrace/handler.d
- src/core/runtime.d
```
This idea was suggested during the review of the new libunwind feature,
and is already used in LDC. Thanks to the recent refactoring,
we can improve on LDC's version by skipping the double demangling/iteration.
```
CC @kinke : I was backporting https://github.com/dlang/druntime/pull/3321 and related to LDC v1.25.0-beta.1 (otherwise the Alpine packages are utterly broken) and figured I might as well integrate your suggestion. By the way, any chance that those PRs could actually be backported to v1.25.0 in ldc-developers/druntime or you want to follow the exact feature set of upstream's druntime ?
> backtrace: Look for _d_throwdwarf instead of skipping frames

- src/core/internal/backtrace/dwarf.d
- src/core/internal/backtrace/handler.d
- src/core/runtime.d
Mostly authored by @kinke , I just modified the `return` statement to keep https://github.com/dlang/druntime/commit/553a557270a9373a48bc9bde7f2bcb562d38d9ba
> backtrace: Get rid of traceHandlerOpApplyImpl2 redundancy

- src/core/lifetime.d
This is currently blocking this PR [1] in dmd.
The commented test looks like this:
```d
static struct S2
{    
int i;
@disable this(this);
this(ref S2){}
}    
S2 s2 = void;
static assert(!__traits(compiles, emplace(&s2, 1)));       // this line is commented                                                                             
emplace(&s2, S2.init);
```
Emplace is not able to run this test because the copy constructor cannot be called with an rvalue (1) and its definition has masked the default constructor.
With the fix in [1], the copy constructor no longer disables default construction and therefore emplace is able to work in this scenario.
I commented the code because it is currently blocking [1], however, after [1] is merged I will uncomment it and make it a runnable test.
[1] …
> Temporarily comment one test

- src/core/internal/backtrace/libunwind.d
- src/core/runtime.d
See https://android.googlesource.com/platform/external/libunwind_llvm/+/ndk-r21/include/__libunwind_config.h#24.
[Just 2 things overlooked for #3329.]
> core.internal.backtrace.libunwind: Tiny fixup for Android i686

- src/core/internal/lifetime.d
It's probably a compiler bug that this makes a difference, but it does make a difference, e.g., for this unittest:
https://github.com/dlang/phobos/blob/e2f756866c9e71265c6cc1c9019bec16e8c1b304/std/container/array.d#L1606-L1617
when making Phobos use the druntime version of `emplace[Ref]` - failing to compile with `need 'this' for 'opCall' of type 'pure nothrow @nogc @safe MyClass(return MyClass p)'`.
This workaround unblocks https://github.com/dlang/phobos/pull/7745.
The Phobos version uses `__traits(compiles)` [but doesn't properly forward r/lvalue-ness of the args]:
https://github.com/dlang/phobos/blob/e2f756866c9e71265c6cc1c9019bec16e8c1b304/std/conv.d#L5031
> Little core.internal.lifetime.emplaceRef() CTFE fix/workaround

- src/object.d
Calculating size_t and ptrdiff_t should make druntime more portable by avoiding the dependency of version (D_LP64) blocks.
> object: calculate size_t and ptrdiff_t instead of use version block

- .gitignore
Adding *.lst files to .gitignore is important to prevent files from being tracked
by git. These files are generated by the compiler for code coverage and
shouldn't be tracked. On other hand, those are extremely useful in development
to check whether certain code is covered or not by unit tests.
> git: prevent *.lst file being tracked by adding to .gitignore

- src/core/internal/dassert.d
Generate code that detects the correct enum member (or defaults to the base type in case of an invalid enum value).
> Fix 21544 - -checkaction=context formats enum members as their base type

- src/rt/cover.d
- test/coverage/Makefile
- test/coverage/src-merge_override.lst_1.exp
- test/coverage/src-merge_override.lst_2.exp
- test/coverage/src/merge_override.d
Merging different versions of the same source file could lead to mismatched
covered lines if the source code actually changes. Changing the .lst file
format will open a huge breaking change and rely on timestamps is impractical.
As an alternative to this, we can deeply compare the source code with generated
.lst which also has a copy of the original source code.
> Fix Issue 14790: rt: cover: coverage merge should detect changed source code

- mak/DOCS
- posix.mak
- src/core/internal/elf/dl.d
- src/core/internal/util/array.d
- src/core/sys/posix/mqueue.d
- src/object.d
- src/rt/aApplyR.d
- src/rt/aaA.d
- src/rt/cast_.d
- src/rt/cmath2.d
- src/rt/critical_.d
- src/rt/ehalloc.d
- src/rt/invariant.d
- src/rt/memset.d
- src/rt/monitor_.d
- src/rt/msvc.d
- src/rt/tlsgc.d
- src/rt/tracegc.d
- src/rt/util/typeinfo.d
---
This PR regenerates `mak/DOCS` files, fix some wrong documentation on `Params` and `Source` sections.
Also, if someone knows a better approach for generating `$(DOCDIR)/%.html : src/%.d $(DMD)` makefile targets in a more generic way, would be cool. I don't know much about Makefile and I think that's kinda dirty, although this approach was already there.
> Fix issue 21309 along with other dead links on dlang.org

- src/core/internal/array/comparison.d
- src/rt/util/typeinfo.d
Because taking these types out of the language would be [no small feat](https://github.com/dlang/dmd/pull/12069), the simplest place to begin is to stop testing for it.  Listed as the first point to tackle in [issue 14488](https://issues.dlang.org/show_bug.cgi?id=14488).
> Remove tests for complex and imaginary types

- src/core/internal/convert.d
This function isn't used anywhere in druntime, and as it's internal, probably doesn't even need a deprecation cycle.
> core.internal.convert: Deprecate complex toUbyte

- src/core/lifetime.d
Some `auto ref` args weren't forwarded.
> core.lifetime.emplace(): Properly forward r/lvalue-ness of arguments

- mak/COPY
- mak/DOCS
- mak/SRCS
- src/core/internal/util/math.d
- src/core/time.d
- src/rt/aaA.d
- src/rt/cover.d
> Remove duplicated definitions for .min() and .max() functions

- src/core/sys/posix/locale.d
- `struct lconv` did not match any platform I looked at.
- Musl doesn't have the linux-specific definitions.
- OpenBSD has its own unique interface.
- Solaris doesn't implement the extended API set.
> core.sys.posix.locale: Fix definitions for Musl, Bionic,OpenBSD and Solaris

- src/core/sys/posix/pthread.d
- src/core/sys/posix/sys/types.d
PTHREAD_ONCE_INIT was missing on OpenBSD, and pthread_once_t was incorrectly declared on DragonFly.
> DragonFly/OpenBSD: Fix pthread_once_t and PTHREAD_ONCE_INIT definitions

- mak/COPY
- mak/SRCS
- src/core/sys/darwin/sys/sysctl.d
- src/core/sys/dragonflybsd/sys/sysctl.d
- src/core/sys/freebsd/sys/sysctl.d
- src/core/sys/netbsd/sys/sysctl.d
- src/core/sys/openbsd/sys/sysctl.d
There might be a few enum definitions still missing, but at least the usage in phobos std.file and std.parallelism is covered.
> Add platform-specific sysctl declarations

- mak/COPY
- mak/SRCS
- src/core/sys/bionic/stdlib.d
- src/core/sys/darwin/stdlib.d
- src/core/sys/dragonflybsd/stdlib.d
- src/core/sys/freebsd/stdlib.d
- src/core/sys/netbsd/stdlib.d
- src/core/sys/openbsd/stdlib.d
- src/core/sys/solaris/stdlib.d
This is to replace declarations in `core.internal.elf.dl`
> Add platform-specific getprogname/setprogname function declarations

- src/core/thread/osthread.d
It's present both [here](https://github.com/dlang/druntime/blob/39dbe9f15832e4ab5459d0a53f40b770845b6515/src/core/thread/osthread.d#L108-L113) and [here](https://github.com/dlang/druntime/blob/39dbe9f15832e4ab5459d0a53f40b770845b6515/src/core/thread/osthread.d#L1398-L1403).
> core.thread.osthread: Remove duplicate version scope

- src/core/sys/darwin/mach/dyld.d
This is meant to replace extern(C) declarations in std.parallelism.
> core.sys.darwin.mach.dyld: Add NS functions from dyld.h

- src/rt/sections_elf_shared.d
See https://github.com/gcc-mirror/gcc/blob/25f303e9a27a0d799f9979446d9f11ed62b8d648/libphobos/libdruntime/gcc/sections/elf_shared.d#L760-L772. It's also relevant for LDC.
> [stable] rt.sections_elf_shared: Upstream MIPS/RISC-V fix wrt. .so dependency names from GDC

- src/core/sys/posix/locale.d
Originally I looked at a Solaris 11.3 SPARC server, these are present in 11.4 onwards.
> core.sys.posix.locale: Complete the Solaris bindings

- src/core/stdc/complex.d
- src/core/stdc/tgmath.d
These will eventually be replaced with `__c_complex_float` and others after the deprecation period.
> Deprecate cfloat/cdouble/creal stdc bindings

- mak/COPY
- mak/DOCS
- mak/SRCS
The file core.sys.darwin.ifaddrs, introduced in PR #3215,
was not copied, meaning users can't import it.
In addition, some files missing from DOCS were added.
> [Stable] Darwin: Add missing files to DOCS / SRCS

- CODEOWNERS
- mak/COPY
- mak/DOCS
- mak/SRCS
- posix.mak
- src/core/internal/gc/bits.d
- src/core/internal/gc/impl/conservative/gc.d
- src/core/internal/gc/impl/manual/gc.d
- src/core/internal/gc/impl/proto/gc.d
- src/core/internal/gc/os.d
- src/core/internal/gc/pooltable.d
- src/core/internal/gc/proxy.d
- test/gc/Makefile
- test/gc/win64.mak
Much like the move from `rt` to `core.internal`, this makes it available for power user and for the compiler.
> Move gc package to core.internal

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
This commits add another overload of `_d_assert_fail` that is capable
of formatting arbitrary value tuples.
This enables `-checkaction=context` to work with `tupleof` and other
tuples used inside an `assert`.
CC @Geod24
> Fix 21472 (1/2) - Add tuple formatting to _d_assert_fail`

- test/hash/src/test_hash.d
These are due for deprecation.
> test_hash: Remove hashOf tests for complex types

- src/core/stdc/config.d
- src/rt/memset.d
Can now be added to druntime as dlang/dmd#12167 is merged.
Start using them in `rt.memset`, which does not result in any changes to the generated assembly.
> core.stdc.config: Add `c_complex_float`, `c_complex_double`, and `c_complex_real` aliases

- posix.mak
- src/core/stdc/config.d
- src/rt/util/typeinfo.d
- win32.mak
- win64.mak
Implements phase 3 of https://issues.dlang.org/show_bug.cgi?id=14488
To get around the deprecation errors when building druntime, we can use the new aliases for the "magic" complex types to build to the built-in TypeInfo classes.  These have been marked as deprecated with the provisional removal date of after version 2.105.
Druntime can now be built with `-transition=complex`.
> rt.util.typeinfo: Deprecate typeinfo for built-in complex and imaginary types

- src/core/internal/backtrace/dwarf.d
Introduced by #3322. `image.baseAddress()` must not be called if `!image.isValid()`, otherwise a segfault occurs if the executable file/image could not be opened (e.g., because of the process changing the initial working dir and https://issues.dlang.org/show_bug.cgi?id=21656).
> core.internal.backtrace.dwarf: Fix segfault regression in case executable cannot be opened

- src/core/sys/posix/signal.d
```
The argument is sent to another process, and can contain a pointer.
Additionally, there is currently a PR in DMD to forbid using
'in' with extern(C) functions when '-preview=in' is provided
(dlang/dmd#12242).
```
As mentioned in the PR, this doesn't cover everything, but this usage looks really out of place.
> sigqueue: sigval argument is not scope

- src/core/internal/dassert.d
These deprecations are issued when real.sizeof = double.sizeof.
This is a workaround for https://issues.dlang.org/show_bug.cgi?id=20759.
> Fix 21666 - Remove deprecations w.r.t. real formatting for checkaction=context

- .github/workflows/cxx.yml
```
We're having issues due to yet another change by Github to their image,
and Ubuntu 16.04 is EOL soon, so just drop it along with clang 6 and 7
which are not available on Ubuntu 18.04, the new supported LTS.
```
This has been done in https://github.com/dlang/dmd/pull/12269 already.
> Github CI: Drop Ubuntu 16.04 and clang < 8

- src/rt/cover.d
dont use the same buffer to read+split the LST and read+split the D. (reg introduced in #3341)
> fix issue 21712 - [REG 2.096.0] sometimes coverage *.lst files are corrupted

- src/core/lifetime.d
To avoid future regressions w.r.t. to -betterC.
CC @kinke
> core.lifetime: Tag -betterC compatible unittests

- src/core/atomic.d
- src/core/internal/atomic.d
dmd aliases casWeak to casStrong.
> Fix Issue 21701 - casWeak is not implemented

- src/core/stdcpp/allocator.d
- test/stdcpp/src/allocator.cpp
- test/stdcpp/src/allocator_test.d
This bug resulted in assertion failures when deleting large blocks of memory using core.stdcpp.allocator on Windows. `_Allocate_manually_vector_aligned` only sets a sentinel when `version(_DEBUG)` so `_Adjust_manually_vector_aligned` should only check for this sentinel when `version(_DEBUG)`.
Additionally change the linkage of those functions from C++ to D to avoid possible linker confusion.
> core.stdcpp.allocator: _Adjust_manually_vector_aligned checks for sentinel unconditionally (Windows only)

- src/core/sys/posix/unistd.d
Hello --
It was pointed out to me on the dlang forums that this is the correct location to add bindings for pledge and unveil for OpenBSD. Both are found in `<unistd.h>`.
These two facilities are expected to always be present on an OpenBSD system. They are parts of OpenBSD's sandboxing strategy.
> Add pledge and unveil to core/sys/posix/unistd.d for OpenBSD

- test/aa/src/test_aa.d
The `__traits(compiles, ...)` fails because of the `@safe` postblit doing pointer cast which is unrelated to the AA functions.
All other actions in this test are inferred as `@safe` (even though they shouldn't because of the postblit).
---
Noticed this test because it triggers a bug in dmd's semantic, see https://github.com/dlang/dmd/pull/11925#issuecomment-803896423
> Fix invalid test in test_aa.d

- src/core/sys/posix/unistd.d
This variable is declared in unistd.h in glibc and musl.  Other platforms document it, but usually require you to declare it explicitly in the user program, or have it as a different name/macro.
[Phobos](https://github.com/dlang/phobos/blob/d8cde81d0a73cce66c57e81a9dbe8089dee21250/std/process.d#L157-L173) has some extern declarations for it, it should instead be importing druntime to get the symbol.
> core.sys.posix.unistd: Add non-standard environ variable

- src/object.d
Similar to https://github.com/dlang/phobos/pull/7892 for std.concurrency, and other Phobos modules.
Rendered: http://dtest.dlang.io/artifact/website-897ea29f92707d10b66a724326e039ed18f94b09-3d330dcf5bd502ae8297bfac1cfae8c4/web/phobos-prerelease/object.html
> object docs: Group symbol links in a table

- mak/COPY
- mak/DOCS
- mak/SRCS
- src/core/sys/windows/stdc/malloc.d
Only added malloc-related functions and not any of the heapwalk stuff - someone can add it later if they require it.
This covers extern(C) functions that are currently declared in [Phobos](https://github.com/dlang/phobos/blob/1c77cdad29161f8bdb84475ffa52c22e7745a883/std/experimental/allocator/mallocator.d#L199-L206).
@adamdruppe `export` should be OK here?
```
0000000000000000 T _aligned_recalloc
0000000000000000 I __imp__aligned_recalloc
0000000000000000 T _aligned_realloc
0000000000000000 I __imp__aligned_realloc
0000000000000000 T _aligned_offset_recalloc
0000000000000000 I __imp__aligned_offset_recalloc
0000000000000000 T _aligned_offset_realloc
0000000000000000 I __imp__aligned_offset_realloc
0000000000000000 T _aligned_offset_malloc
0000000000000000 I __imp__aligned_offset_malloc …
```
> core.sys.windows.malloc: New bindings module for malloc.h

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
It was superseeded by the variadic hook.
> Remove legacy _d_assert_fail overload

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
The template constraint was intended to avoid collisions with the
unary hook but also prevented instances for zero elements.
`combine` was adapted to print empty arrays as `()`.
> Fix 21764 - checkaction=context doesn't work for empty tuples

- src/core/internal/dassert.d
If the key type is of a non-copyable type, this will fail to compile.
If the type has side effect, so would an assert fail, which we definitely don't want.
> dassert: Avoid copying the key type

- test/profile/Makefile
- test/profile/both.def.exp
It's an outdated relict.
---
Also added the `cat ...` for better error reports.
> Remove old .def file from test/profile

- test/profile/Makefile
Sorting the declarations avoids issues w.r.t. the ordering of these functions.
> Make profile tests independent of semantic evaluation order

- src/core/stdc/errno.d
Hello --
This syncs OpenBSD's errno list from our (OpenBSD's) sys/errno.h.
Discovered when I tried to build dlib on OpenBSD, which uses EPROTO but it was not exposed in druntime.
Thanks!
> Sync OpenBSD errno from -current sys/errno.h

- src/core/thread/osthread.d
- test/thread/Makefile
- test/thread/src/join_detach.d
This is useful when a thread terminates before the
caller is able to join(). With a reset `m_addr`, caller would segfault.
> Fix Issue 21784: Allow detached threads to be joined

- test/stdcpp/Makefile
Although the compilers seem to accept it (only some warnings), the code in memory.cpp requires C++11 or newer.
> stdcpp test: build memory.cpp with std=c++11

- src/core/stdc/math.d
Hello --
On OpenBSD, there is no __fpclassifyd. It is named __fpclassify.
See here: https://github.com/openbsd/src/blob/master/include/math.h#L477
Thanks!
> On OpenBSD, __fpclassifyd is named __fpclassify

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
Alternative to omission implemented in #2720
> -checkaction=context: Mark context pointer of structs

- src/core/thread/osthread.d
PR #3418 allowed them on Posix; extend it to Windows too. The added `test/thread/src/join_detach.d` test now passes on Windows (tested by LDC).
> [stable] Allow detached threads to be joined on Windows too

- src/object.d
> [dmd-cxx] object: Don't set WithArgTypes on GNU+AArch64 targets

- src/object.d
GDC does not use argTypes on any target.
> object: Don't set WithArgTypes on GNU+AArch64 targets

- src/rt/memset.d
- src/rt/util/typeinfo.d
- src/rt/util/utility.d
The `creal` interfaces in `rt.memset` and `rt.util.typeinfo` are not compatible with C complex reals, so define our own type internally distinct from `core.stdc.config`.
Based on @kinke's original work, and unblocks #3428.
> rt.util: Define D complex types, use them in rt instead of the C complex types

- posix.mak
- win32.mak
- win64.mak
In preparation for making `-transition=complex` the default in D.
> Remove -transition=complex from the Makefiles

- src/core/stdc/config.d
- src/rt/util/typeinfo.d
MSVC has `_{F,D,L}complex` typedefs in complex.h (see https://docs.microsoft.com/en-us/cpp/c-runtime-library/complex-math-support?view=msvc-160). `_Lcomplex` (for `__c_complex_real`) uses its 64-bit `long double`. And the alignments are regular (4/8/8 bytes).
> core.stdc.config: Fix magic __c_complex_* enums for Windows

- mak/COPY
- src/core/builtins.d
- src/object.d
Makes it easier to recognize `__ctfeWrite` as a builtin function and removes some clutter from `object.d` (especially if further builtins are added in the future)
Proposed in dlang/dmd#12412
> Move __ctfeWrite to core.builtins

- src/core/sys/windows/com.d
- src/core/sys/windows/dbghelp.d
To avoid any mismatches if someone is compiling with System == C (such as `-mabi=sysv` on gdc).
> core.sys.windows: Use 'extern(Windows)' instead of System

- src/core/stdc/stdlib.d
MinGW targets always links to one of `libcrtdll`, `libmsvcrt` (default for gdc), `libcmt`, or `libucrt` (default for ldc?).  Rather than having to duplicate all of `CRuntime_Microsoft` to `MinGW` where there's missing definitions, MinGW should instead be a sub-target, where deviations (such as proper 80-bit real support) are handled within.
Doing it this way means that GDC can support building druntime and phobos on x86_64-w64-mingw32.
Ping @kinke to check this.
> core.stdc.stdlib: MinGW is a sub-target of CRuntime_Microsoft

- src/core/stdc/tgmath.d
Because `CRuntime_Microsoft` is also predefined (on gdc), they didn't get picked up.
> core.stdc.tgmath: Declare fabsf and fabsl aliases on MinGW

- src/core/stdc/math.d
Same as #3439, but for the C math module.
Best reviewed with whitespace differences disabled.
> core.stdc.math: MinGW is a sub-target of CRuntime_Microsoft

- src/core/sys/posix/stdio.d
Phobos `std.stdio` unconditionally declares `flockfile` and `funlockfile` in the `GENERIC_IO` path, so they must all exist on these platforms - and indeed, looking up system headers, I can see that they are all present.
Adding it to druntime means we can remove the extern declaration from Phobos.
> core.sys.posix.stdio: Add flockfile and other related POSIX declarations for more targets

- src/core/stdc/stdio.d
~The functions `_fputc_nolock` and `_fgetc_nolock` are macros on MinGW, so they've been added in as templated functions.~
Edit: moved them to a gdc-internal msvc support module.
> core.stdc.stdio: Add 'under-the-hood' C I/O functions for DigitalMars, Microsoft, and Glibc runtimes

- src/core/sys/darwin/mach/thread_act.d
- src/core/thread/fiber.d
- src/core/thread/osthread.d
These are the common druntime bits.  The other half of it involves gcc-specific inline assembly (or external asm sources).
> core.thread: Add Fiber support for PPC/Darwin targets

- src/core/bitop.d
They were first deprecated in 2.089.0.
> core.bitop: Add deprecated note for volatileLoad and volatileStore

- src/core/runtime.d
The default test runner may print the exception message twice when a unittest fails. This usually isn't an issue, but if the message spans several lines and multiple tests are failing, the console output quickly becomes noisy and difficult to read. 
Since `_d_print_throwable` will print the message anyway, I don't see a need for the `printf` call. After this change, the `printf` call only happens in that specific case where the loop continues without calling `_d_print_throwable`, so the exception message is printed exactly once either way.
I couldn't find a related issue on bugzilla, but since this is a small change I hope it's ok without one.
> Remove extra exception message on unittest failure

- test/thread/Makefile
It sometime fails due to race conditions in the thread cleanup code.
CC @thewilsonator
> Temporarily disable join_detach test

- src/core/checkedint.d
s.t. they appear in the generated documentation. Also added some empty lines to make the examples more readable.
Not sure if all unittests should be included or only one per operation (.e.g. `adds` and `addu`), see
http://dtest.dlang.io/artifact/website-a80ae23e1a409c9b0b6b0115a2086c7cfeb0f958-139360407733b386329fa03f8057c0f1/web/phobos-prerelease/core_checkedint.html
> Turn checkedint unittests into public examples and tag @betterC

- src/core/lifetime.d
Defining the helper function as a template ensures that it is available when not linking druntime.
(`pragma(inline, true)` didn't work)
> Fix 19783 - Fail to emplace struct with betterC

- src/core/internal/array/comparison.d
- src/core/internal/string.d
- src/core/time.d
- src/object.d
- src/rt/trace.d
- src/rt/util/typeinfo.d
Was previously being done some places but not all. This PR does not include changes in https://github.com/dlang/druntime/pull/3450.
> Consistently compare ints with `(a > b) - (a < b)`

- src/core/attribute.d
- src/core/builtins.d
Exposes a common module to import these compiler-specific modules - used occasionally throughout druntime and phobos - without the need to repeat `version (GNU)`/`version (LDC)` everywhere.
Ping @kinke for review/thoughts/approval/rejection of the idea.
> core.{attribute,builtins}: Publicly import GDC and LDC builtins and attributes.

- src/core/internal/traits.d
No measured difference in compile times or memory consumed.
> Simplify anySatisfy, allSatisfy, maxAlignment

- src/core/sys/darwin/dlfcn.d
Add `RTLD_NEXT`, `RTLD_DEFAULT`, `RTLD_SELF`, and `RTLD_MAIN_ONLY`.
> Add non-posix search for dlsym

- src/core/internal/traits.d
This implements `Unqual` with only two pattern matches. First gets rid of `inout`, `const`, and `immutable`. Second gets rid of `shared`, if present.
Memory taken in synthetic tests decreases. by 4%. Time is about the same.
> Faster and smaller Unqual

- src/core/stdc/math.d
Some blocks became redundant because of #3201
> Remove unnecessary extern (D) blocks in cmath

- src/core/stdc/math.d
`>`,` >=`, `<`, `<=` are already defined in D to evaluate to false when the operands are unordered.
https://dlang.org/spec/expression.html#floating-point-comparisons
> Remove unnecessary !isunordered from cmath isgreater etc.

- src/core/internal/traits.d
Woke up with this little idea - no need to test with `static if`, integrate the pattern match in the template definition.
> Even smaller and simpler Unqual

- src/core/internal/traits.d
Follow up to https://github.com/dlang/druntime/pull/3459.
I didn't find a way to simplify
```d
template maxAlignment(Ts...)
if (Ts.length > 0)
{
enum maxAlignment =
{
size_t result = 0;
static foreach (T; Ts)
if (T.alignof > result) result = T.alignof;
return result;
}();
}
```
in the same manner because of the template restriction.
It can be done if the restriction `if (Ts.length > 0)` is replaced by a
`static assert(Ts.length > 0)`
inside of `maxAlignment` though. But that's Phobos style, afaict.
> Simplify anySatisfy and allSatisfy further

- src/core/sys/dragonflybsd/dlfcn.d
- src/core/sys/freebsd/dlfcn.d
- src/core/sys/netbsd/dlfcn.d
- src/core/sys/posix/dlfcn.d
The private templates have been removed because it does not accept `scope`.
> dlfcn.d: Fix static asserts for dlopen symbols

- src/core/sys/dragonflybsd/dlfcn.d
- src/core/sys/freebsd/dlfcn.d
- src/core/sys/netbsd/dlfcn.d
- src/core/sys/posix/dlfcn.d
> [dmd-cxx] dlfcn.d: Fix static asserts for dlopen symbols

- src/core/thread/osthread.d
Unblocks https://github.com/dlang/dmd/pull/12520, @thewilsonator
> Annotate `toThread` parameter `t` with `return scope`

- src/core/internal/dassert.d
It gets called from `_d_assert_fail` with a `scope` string. The reason it currently compiles is because it's pure, so [Issue 20150](https://issues.dlang.org/show_bug.cgi?id=20150) applies. Blocker for https://github.com/dlang/dmd/pull/12010.
> Add scope to invertCompToken

- src/core/internal/backtrace/handler.d
The first commit is required top fix Libunwind integration (which LDC uses), the second is an optimization.
> Libunwind: Use dladdr to get function name (+ fix gc_inFinalizer)

- src/rt/dwarfeh.d
I encountered this message while working on a large project
and was puzzled as to why I couldn't find the string 'uncaught exception'
anywhere in my code or dependencies'.
> rt/dwarfeh: Improve error message on uncaught exception

- posix.mak
- src/core/internal/lifetime.d
- test/lifetime/Makefile
- test/lifetime/src/large_aggregate_destroy_21097.d
This fixes `destroy` and `core.internal.lifetime.emplaceInitializer` for large aggregates by preventing stack allocation for LDC and DMD.
For DMD, it also fixes a codegen issue for large static array of structs where `destroy`/`emplaceInitializer` would generate a string of `mov` instructions proportional to the size of the array.
~~Intentionally did not add unittests for this issue here, but instead added a runnable test case to the testsuite, to prevent a very large unittest binary. Test is added in separate DMD PR: https://github.com/dlang/dmd/pull/12509.~~
Tests have been added to this PR.
> Fix Issue 21097 - prevent stack allocation when destroying large aggregates

- src/rt/dmain2.d
- src/rt/sections_win32.d
- src/rt/sections_win64.d
GDC defines its own version of these functions for shared library integration in `gcc.sections` (based off elf_shared), because phobos as a shared library should just work out of the box on Win32 and Win64.
As rt_loadLibrary and rt_unloadLibrary is define here for Posix targets, moving here as well for Windows to avoid symbol conflicts.
> windows: Move rt_loadLibrary and rt_unloadLibrary to rt.sections

- src/object.d
`.dup` and `.idup` used to be built-in properties of arrays along with `.sort` and `.reverse`.
In 2014 [they got implemented as druntime functions](https://github.com/dlang/druntime/pull/760), but being 7 years old, they now have the following shortcomings:
- `scope` inference of the input array fails, making it a blocker for [issue 20150 - dip1000 defeated by pure](https://issues.dlang.org/show_bug.cgi?id=20150)
- it does not account for copy-constructors, only postblits
- since 2018, the implicit conversion to `immutable` of e.g. `char[].dup` [relies on a compiler hack](https://github.com/dlang/dmd//commit/ab5a18635adaa3e2271e0f4b569500a89ac74235#diff-88cc711d774668de0af3461742be476454e8374545722dfd77457a3264aecf32R804).
This PR addresses the first two points, the third point depends on …
> Rewrite `object.dup` to work with `scope` and copy constructors

- src/core/atomic.d
- src/core/demangle.d
- src/core/gc/gcinterface.d
- src/core/internal/array/appending.d
- src/core/internal/array/casting.d
- src/core/internal/array/concatenation.d
- src/core/internal/convert.d
- src/core/internal/gc/impl/conservative/gc.d
- src/core/internal/gc/impl/manual/gc.d
- src/core/internal/gc/impl/proto/gc.d
- src/core/internal/gc/proxy.d
- src/core/lifetime.d
- src/core/memory.d
- src/object.d
- src/rt/lifetime.d
- src/rt/tracegc.d
- test/hash/src/test_hash.d
- test/init_fini/src/custom_gc.d
This PR is similar to https://github.com/dlang/phobos/pull/8076, but for druntime and for https://github.com/dlang/dmd/pull/12010 instead of https://github.com/dlang/dmd/pull/10924
It's probably too big to merge in one go, this is a proof of concept that can later be split up into smaller chunks for easier review.
The offending functions were found with something I cobbled together in dmd: https://github.com/dkorpel/dmd/commit/7d1f0c5f68ff9127d06c8d54e391be71c15dc4a8
It outputs this when running druntime unittests:
```
src/core/internal/dassert.d(221): parameter `a` of `idup` is cheating `scope`
src/object.d(3410): parameter `value` of `getElement` is cheating `scope`
src/core/internal/dassert.d(164): parameter `val` of `atomicLoad` is cheating `scope`
src/core/atomic.d(1161): parameter …
```
> Annotate pure functions with return/scope

- src/core/exception.d
- test/allocations/Makefile
- test/allocations/src/alloc_from_assert.d
Otherwise, an assert failure in a dtor (or anything GC-called) result in an InvalidMemoryOperationError.
> core/exception: Use staticError when throwing Exception

- src/core/internal/lifetime.d
The cases where it's needed are restricted to struct types; don't create unused and conflicting declarations for primitive types etc.
> [stable] core.internal.lifetime: Fix recent regressions for emplaceInitializer()

- src/core/internal/dassert.d
As newly required for https://github.com/dlang/druntime/blob/c163fe678c58dc3a268cfa5deb93b8c8dedac2f1/src/core/internal/lifetime.d#L181 with LDC, which allows comparing vectors for equality/identity (unlike DMD).
Previously, `float4` would fail to compile (expected `ireal`), and `int4` would print some scalar integer.
> [stable] core.internal.dassert: Add support for vectors in miniFormat()

- src/core/sys/posix/stdio.d
Fixing compilation of `std.stdio` for Android.
> [stable] core.sys.posix.stdio: Add missing flockfile() etc. for Android/Bionic

- src/core/sys/posix/arpa/inet.d
```
POSIX defines those two constant at a fixed value,
no need to version it by platform, we're in a POSIX header.
This make it more future-proof for other platforms / C Runtime,
and fix a build error with Musl.
```
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/netinet_in.h.html
> arpa/inet: Deduplicate INET[6]_ADDRSTRLEN

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
The message formatting isn't `@nogc` yet and hence caused an `InvalidMemoryOperationError` when called from a finalizer.
CC @Geod24
> Fix 21996 - Skip message formatting for checkaction=context in finalizer

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
Some small patches that allow `-checkaction=context` to work at compile time:
- use druntime's internal implementation instead of LibC
- avoid reinterpreting casts
- skip floats and `void[]`, return a warning instead
---
Best reviewed per commit.
~~Depends on dlang/dmd#12514~~
> Issue 21998 - Support more types during CTFE with checkaction=context

- src/core/memory.d
GC implementations are required to return null for any non-GC pointer,
so `GC.addrOf` can never violate memory safety.
> Mark GC.addrOf as trusted

- src/core/internal/hash.d
- test/hash/src/test_hash.d
Also incidentally do not pass vectors by ref to `toHash`.
> [stable] hashOf does not work on enum types whose base type is a SIMD vector

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
... when formatting values for `-checkaction=context` and print the
aggregate members as a fallback. This ensures that an unrelated error
does not mask the assertion failure.
> Fix 22026 - Catch exceptions thrown by user-defined toString methods... 

- src/object.d
This ensures deterministic behaviour in case of an exception and
avoids dtor calls on uninitialized elements.
> Fix 21983 -  Initialize remaining elements in a partially dup'ed array if postblit/copy ctor throws

- test/exceptions/src/assert_fail.d
Those functions don't need to be templates and normal functions allow
for better error messages.
> Remove empty template parameter list from checktion=context tests

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
`extern(C++)` classes don't have a `toString` by default and hence could
not be formatted before. Treating them like structs should at least
provide some meaningful output although it could miss inherited members
for subclasses.
> Fix 22085 - Format members of extern(C++) classes without toString

- posix.mak
Segmentation faults or linker errors occur on 32-bit PIE platforms if any object is not compiled with -fPIC.
> Issue 21488 - Always compile druntime library with -fPIC on POSIX targets

- src/core/checkedint.d
Explanation of why a single compare-and-branch is enough for `addu`:
For unsigned integrals, if we add `r = x + y`:
- if there is no carry, then `r >= x` and `r >= y`;
- if there is carry, then `r < x` and `r < y`.
Also, let us look at the implementation of `subu`. One compare-and-branch suffices for `subu`. It should suffice for `addu` as well. (-:
Testing information 1 (correctness):
```
$ cd src/core/
$ rdmd -unittest --main checkedint.d
1 modules passed unittests
```
Testing information 2 (improvement of generated code):
Comparison of generated machine code (DMD for Win32):
```
$ dmd -O -release -unittest checkedint.d -of=checkedint.d.obj
```
For `uint` overload: Before: 2 cmp instructions, 2 conditional-jump instructions. After: 1 cmp instruction, 1 conditional-jump instruction.
For …
> core.checkedint.addu: Faster (like subu: only one compare-and-branch).

- src/core/checkedint.d
Reverts dlang/druntime#3496
Testing to see if this resolves https://github.com/dlang/dmd/pull/12823#issuecomment-875115091
> Revert "core.checkedint.addu: Faster (like subu: only one compare-and-branch)."

- azure-pipelines.yml
Working pipelines finish within 30 minutes, this prevents choking up the PR queue when there are real issues going on that cause Azure CI to stop and stall until the timeout limit.
(Also, cirrus CI timeout is set at 60m too).
https://github.com/dlang/druntime/blob/3ed15ad1b8d76d048b426ed9dacf6378cdf5167f/.cirrus.yml#L32
> azure-pipelines.yml: Reduce timeout time to 60 minutes

- src/core/lifetime.d
Continuation of https://github.com/dlang/druntime/pull/3480
It was mentioned in the discussion that the two-argument `move(source, target)` is not compatible because dip1000 wants the target to be the first parameter. However, the fixes for the single parameter variant were also incomplete in that PR. This adds the missing `scope` and `return`.
> Make `move` -dip1000 compatible

- src/core/internal/atomic.d
I fear this is rather just putting lipstick on the pig, rather than addressing the real problem that `CanCAS` is just wrong in its assumptions.
This condition means that both the ix86 and x32 unit-tests don't pass cleanly with gdc, where there's a libatomic library providing for 128-bit CAS operations (and in x32's case, it's done natively inline).
> core.atomic: Allow 128-bit CAS operations if runtime has128BitCAS

- src/object.d
Blocking https://github.com/dlang/dmd/pull/12812
`ModuleInfo.addrOf` is a return-ref method returning a pointer to `this` with an offset. Functions that return `this.addrOf` should therefore also be ref-return.
> Add `return` to moduleinfo methods returning `this`

- src/core/internal/execinfo.d
- src/core/sys/openbsd/execinfo.d
Hello --
In preparation for an official (from our OpenBSD perspective) package of GDC, I'd like to add backtrace support. OpenBSD ships a compatible libexecinfo its base system these days.
As for the D support, this is a copy-paste-rename job from the NetBSD execinfo.d file.
Thanks.
> Add OpenBSD backtrace support

- src/core/sys/posix/fcntl.d
- src/core/sys/windows/sqlext.d
Uncovered by https://github.com/CyberShadow/tree-sitter-d/issues/3. Octal literals were deprecated in 2011 and removed from the language in 2014. However, 00 to 07 are still tolerated by dmd since they are the same in octal and decimal. They are not in the specification though, and they don't get highlighted as number literals in Visual Studio Code.
> Remove usage of octal literals

- src/core/internal/dassert.d
- test/exceptions/src/assert_fail.d
Detect overlapped fields by checking the offsets of adjacent members. Those are replaced by a placeholder because we cannot determine wich of the overlapped fields is valid (if any).
---
This currently requires more CTFE for each instantiantion of `formatMembers`. The overlap detection could be done at runtime by embedding the `offsets` array. But this could create unused `miniFormat` instantions if they are only required by overlapped fields. Not sure which approach is preferrable...
> Fix 22126 - Don't print overlapped fields with -checkaction=context

- src/rt/lifetime.d
`delete` is due to be removed from the language in https://github.com/dlang/dmd/pull/12900.
> rt.lifetime: Call library functions directly instead of using deprecated 'delete' keyword

- src/core/internal/gc/impl/conservative/gc.d
- test/gc/Makefile
- test/gc/sentinel1.d
- test/gc/sentinel2.d
These tweaks were useful while debugging https://github.com/dlang-community/libdparse/pull/445.
They might as well be upstreamed.
CC @rainers
> GC debugging aids

- .cirrus.yml
- azure-pipelines.yml
- changelog/UniqueTypeInfoNames.md
- src/core/internal/gc/impl/conservative/gc.d
- src/object.d
- src/rt/aaA.d
- src/rt/util/typeinfo.d
Making the `TypeInfo_Struct` names truly unique and more compact at the same time. Requires compiler support: https://github.com/dlang/dmd/pull/12928
Caching the demangled name in the instance itself isn't possible because `TypeInfo.toString()` is `const`. I had to remove its `pure` in order to cache the demangled name in a per-thread AA (and using `const void*` as key, as `const TypeInfo_Struct` leads to an infinite recursion...).
> TypeInfo_Struct: Switch to stored mangled name & demangle lazily (with per-thread cache)

- src/object.d
- test/exceptions/src/refcounted.d
If you catch a dip1008 `Throwable` and chain it with a new `Exception` or `Error` via the constructor the reference count isn't incremented, leading to the original throwable being freed while the new one still has a reference to it.
> Fix Issue 22143 - Throwable ctor doesn't increment chained exception's ref count

- changelog/forkgc.dd
- src/core/exception.d
- src/core/gc/config.d
- src/core/internal/gc/bits.d
- src/core/internal/gc/impl/conservative/gc.d
- src/core/internal/gc/os.d
- test/gc/Makefile
- test/gc/hospital.d
Attempt to rebase https://github.com/dlang/druntime/pull/2604 to see whether it still fails
> #2604 rebased - fork() based garbage collector

- src/core/sys/posix/arpa/inet.d
~~This PR also changes the linkage of those functions from C to D when we're defining them in D runtime.~~
> [stable] On OpenBSD and Android make core.sys.posix.arpa.inet: htonl, htons, ntohl, & ntohs work correctly on big endian architectures

- src/core/stdc/math.d
Currently testing with LDC / DMD, will mark as ready when the CI passes.
> Fix 22178: fpclassify is pure on Musl too

- src/object.d
Added unittest that verifies that safety is inferred from safety of `Key/Value.this(this)` when present. When postblit is not present `AA.keys/values` should be unconditionally `@safe`.
Closes https://issues.dlang.org/show_bug.cgi?id=14439.
> Fix Issue 14439 - aa's keys, values not usable in @safe context 

- src/core/checkedint.d
https://github.com/dlang/druntime/pull/3511#issuecomment-875154147 ...
> core.checkedint.addu: Faster (like subu: only one compare-and-branch) (resubmit).

- mak/COPY
- mak/DOCS
- mak/SRCS
- src/core/sys/linux/fs.d
- src/core/sys/linux/io_uring.d
---
`io_uring` bindings support are extremely important for implementing efficient IO for future eventloop drivers coming to D programming language.
These headers were generated and manually adapted. `linux/io_uring.h` is dependent of `linux/fs.h` due to `__kernel_rwf_t` type and its `RWF_*` flags.
I'm not entirely sure what's the interface of linux headers on the runtime, but I think those headers have a good fit here.
> Add linux/io_uring.h and linux/fs.h bindings

- src/core/internal/array/operations.d
It seems that this PR [1] forgot to add checks for OOB accesses. ~~I had to modify `_d_assert_fail` to be able to put a nice error message.~~
[1] https://github.com/dlang/druntime/pull/1891
> Fix Issue 21110 - OOB memory access, safety violation

- .cirrus.yml
As DMD bumped that base image, and druntime CI depends on the DMD CI scripts (libcurl3 vs. libcurl4 etc.).
> Fix Cirrus CI (bump Ubuntu to 18.04)

- src/object.d
No idea what they are good for anyway; the `info` might be handy due to `TypeInfo_Interface` having a `TypeInfo_Class info` field.
> TypeInfo_Class: Make 2 superfluously virtual functions final

- .cirrus.yml
- src/object.d
~This in the hope to avoid accidental regressions such as #3546~
Dependent fix now moved to dlang/dmd#12985
> Cirrus CI: Add FreeBSD 11 pipeline

- src/core/atomic.d
I made a mistake in https://github.com/dlang/druntime/pull/3480 by adding just `return` without `scope`. That would suggest `ref T val`  would return a `T*` like `&val`, but they return a `T`. This trips up `SharedRegion` in std.allocator after applying https://github.com/dlang/dmd/pull/12812 because of this:
```D
localCurrent = atomicLoad(this._current);
```
Which would needlessly turn `localCurrent` into a `scope` pointer since `atomicLoad`'s signature suggests it's essentially returning `&this` which it isn't.
> Make atomic functions return scope, not ref return

- src/rt/cast_.d
- test/shared/Makefile
- test/shared/src/classdef.d
- test/shared/src/dynamiccast.d
- test/shared/win64.mak
> Fix Issue 22218 - Dynamic casts across binary boundaries can easily fail

- src/core/attribute.d
- src/core/internal/gc/proxy.d
- src/core/stdcpp/exception.d
- src/core/stdcpp/typeinfo.d
- src/rt/lifetime.d
GDC and LDC don't emit symbols as weak by default, but a number of functions in druntime require weak semantics to interface with them.
Note: Not all of the functions in `core.stdcpp` that could be weak are tagged as `@weak` because there are more differences between DMD and GDC/LDC that warrant a separate PR.
> core.attribute: Add weak enum for tagging symbols that should have weak linkage

- src/core/exception.d
The "m" functions were replaced by "p" functions in #1761.
> core.exception: Remove dead comment about ModuleInfo functions

- src/core/thread/osthread.d
Reboot of https://github.com/dlang/druntime/pull/3520 which I can't re-open.The bug is gone now [Issue 20150 - -dip1000 defeated by pure](https://issues.dlang.org/show_bug.cgi?id=20150) is fixed, so this PR simply adds a test case.
> Add test case for issue 22124

- src/core/internal/qsort.d
- src/rt/adi.d
Since the removal of built-in `.sort`, the xopCmp path has been untested in `TypeInfo_Struct.compare`.
> Add tests for TypeInfo_Struct xopEqual and xopCmp

- src/core/internal/backtrace/unwind.d
Pulled from #3552.  Catching C++ exceptions on 32-bit causes a segfault due to misalignment of the generic unwind exception.
> core.internal.backtrace.unwind: Align _Unwind_Exception to 16 on 32-bit

- src/core/stdcpp/typeinfo.d
Extracted from #3552, without this OSX and FreeBSD hits `static assert(false)` when importing this module.
> core.stdcpp.typeinfo: Add implementation of typeinfo for CppRuntime_Clang

- src/core/stdcpp/exception.d
Pulled from #3552. When the OMF pipelines use this module, linker errors occur about mismatched function signatures.  So a different version has been extracted that does not trigger the linker failures.
> core.stdcpp.exception: Add separate implemention of exception for CppRuntime_DigitalMars

- src/core/stdcpp/typeinfo.d
Pulled from #3552.  Opaque classes still have their `.init` symbol added to ModuleInfo when the module is compiled, but because it is opaque, this symbol is never defined either.  So switching it to a struct avoids any subsequent linker errors.
> core.stdcpp.typeinfo: Use extern(C++, class) struct for the internal class type_info for CppRuntime_Gcc

- mak/SRCS
- src/core/stdcpp/exception.d
- src/core/stdcpp/typeinfo.d
- test/stdcpp/Makefile
- test/stdcpp/src/exception.cpp
- test/stdcpp/src/exception_test.d
- test/stdcpp/src/typeinfo.cpp
- test/stdcpp/src/typeinfo_test.d
**Upstreamed**:
- Change destructors from `extern(D)` -> `@weak extern(C++)`
- Change CppRuntime_Microsoft `exception.what` from `extern(D)` -> `@weak extern(C++)`
- Add `assert(0)` to CppRuntime_Microsoft `exception._Doraise`
- Add missing `bad_exception.what` for GenericBaseException
- Add `@nogc:` to core.stdcpp.typeinfo
- Add `nothrow` to `type_info.before` and `type_info.name`
- Mark CppRuntime_Gcc `type_info` as abstract
- Add definitions to CppRuntime_Gcc and CppRuntime_Clang `bad_cast.what` and `bad_typeid.what`
**New**: Things found to be broken just by adding tests. (Moved to other PRs).
- ~Change CppRuntme_Gcc `__class_type_info` from `class` -> `extern(C++, class) struct`~
- ~Add implementation of `typeinfo` for CppRuntime_Clang~
- ~Fix the alignment of `_Unwind_Exception` to …
> core.stdcpp: Upstream differences between dmd and gdc/ldc druntimes

- src/core/internal/hash.d
- src/rt/aaA.d
Current code:
```d
size_t h = 0;
foreach (key, ref val; aa)
{
size_t[2] hpair;
hpair[0] = key.hashOf();
hpair[1] = val.hashOf();
h += hpair.hashOf();
}
```
Proposed code:
```d
size_t h = 0;
foreach (ref key, ref val; aa)
h += hashOf(hashOf(val), hashOf(key));
```
On a 32-bit machine the old code is equivalent to:
```d
size_t h = 0;
foreach (key, ref val; aa)
{
size_t k = hashOf(hashOf(key), 0);
k = hashOf(hashOf(val), h);
k = fmix32(k ^ (size_t.sizeof * 2)); // fmix32 being the MurmurHash3 finalizer.
h += k;
}
```
On a 64-bit machine the work involved is greater. That level of mixing at each step is excessive.
Note:
Writing `hashOf(val, hashOf(key))` might seem better than `hashOf(hashOf(key), hashOf(key))` as it possibly avoids redundancy, but that can't be used by the `TypeInfo`-based …
> Speed up hashOf for associative arrays

- src/core/sys/linux/fs.d
For which there's no `_IO()` etc. in `core.sys.posix.sys.ioctl`.
> [stable] core.sys.linux.fs: Fix compilability for Bionic and Musl C runtimes

- src/core/exception.d
> [stable] core.exception: Add slice-versions of _d_arraybounds_{slice,index}

- test/exceptions/Makefile
Previously, the `grep` command would fail without any context whatsoever.
> test/exceptions: Facilitate troubleshooting by printing stderr output

- src/core/sys/windows/ddeml.d
Several definitions in `core.sys.windows.ddeml` have remained commented out from [the beginning](https://github.com/smjgordon/bindings/commit/0ef8028041a5ac03a83828f1d9100dd0365980e9), I don't know why. These seem to be the correct translations.
> Define remaining symbols in core.sys.windows.ddeml.

- changelog/openbsd_ioctls.dd
- src/core/sys/posix/sys/filio.d
- src/core/sys/posix/sys/ioccom.d
- src/core/sys/posix/sys/ioctl.d
- src/core/sys/posix/sys/ttycom.d
Hello --
I would like to add ioctl support for OpenBSD.
Follows the same code style from macOS and FreeBSD.
Checked against OpenBSD 7.0-beta
Discovered this was missing when trying to build https://github.com/DigitalMars/med
Thanks!
> Add ioctls for OpenBSD.

- src/core/internal/traits.d
Currently there is duplicated code in druntime and phobos that [this PR](https://github.com/dlang/phobos/pull/7148) tried to address, however, the PR got stalled and the 2 implementations have [diverged](https://github.com/dlang/phobos/pull/7696/).
I am trying to merge the [original PR](https://github.com/dlang/phobos/pull/7148), however, the implementations need to be synced for that.
> Backport Fix Issue 15425 to druntime

- test/shared/Makefile
- test/shared/src/dynamiccast.d
So that debug and release versions of the `shared` integration testsuite can be run in parallel (in the same working dir) without file conflicts. This problem was encountered with LDC.
> [stable] Slightly tweak dynamiccast integration test

- src/core/sys/windows/dll.d
> Fix issue 22328: Specific D types are used instead of Windows type aliases

- src/core/lifetime.d
- test/betterc/Makefile
- test/betterc/src/test22336.d
As emplace itself already works in `betterC` and same `T.init` blitting is used in the file already, I've used it instead of unavailable `TypeInfo`.
> Fix issue 22336 - betterC move of non zero structs

- src/core/sync/rwmutex.d
I'm casting away `shared` instead of using `core.atomic.atomicOp` because the later has an overhead, and we're already in the critical section, so no further synchronization should be needed at this point.
About the unit tests, I didn't see any example in core.sync.Mutex, so I just cloned the unit tests, this time using the shared version.
> Fix Issue 20936 - core.sync.rwmutex should have shared overloads (and make it usable in @safe code)

- src/core/exception.d
> More readable message in ArrayIndexError

- src/core/sys/openbsd/dlfcn.d
Hello --
This is a simple sync of OpenBSD dlfcn.h
Sets the comment to the correct reference file, adds some bits now supported.
Thanks.
> Sync OpenBSD dlfcn.

- src/core/sys/linux/perf_event.d
Fixes build regressions caused by #3160.  Ping @maxhaton
> core.sys.linux.perf_event: Add missing D runtime linux ports

- posix.mak
Fix Issue 22455 - Remove useless conditional assignment of DISABLED_TESTS in posix.mak
> Remove useless conditional assignment of DISABLED_TESTS

- src/core/internal/gc/impl/conservative/gc.d
This is an alternative PR to #1568.
This pull request doesn't always use the user facing documentation found in core.memory, but does where applicable(the documentation is small). Otherwise I wrote a small tidbit for the function along with Params, Returns, and Throws sections for consistency. I tried to not go into too much detail as more of the actual implementation is in Gcx and should be documented there. 
I also deleted a bunch of commented out debug statements that don't add anything to the code and should be removed.
> Add documentation to GC struct (Alt)

- posix.mak
In [an attempt](https://github.com/dlang/dlang.org/pull/1687) to reduce the mess in the dlang.org Makefile, it makes sense and helps to use the same variable names for the same things.
`DOC_OUTPUT_DIR` and `STDDOC` are already used at Phobos + DMD.
> Unify Makefile variables for dlang.org: Rename DOCDIR -> DOC_OUTPUT_DIR, DOCFMT -> STDDOC

- src/core/sys/linux/sys/mman.d
Links are still clickable, just loads the version currently in `HEAD`.
> core.sys.linux.sys.mman: Remove commit hash reference from urls

- src/core/thread/fiber.d
> fix Issue 21919 - darwin: SEGV in core.thread tests on OSX 11

- .cirrus.yml
> [stable] cirrus: Switch to big-sur image

- .cirrus.yml
Now that dlang/dmd#13279 is merged we can finally switch to macOS BigSur on Cirrus CI on `master`.
This reverts commit 2985abd83467ae5c0f5be283dce9af116dbcfeb3.
> ci: Re-introduce "cirrus: switch to big-sur image"

- src/core/internal/array/construction.d
This change is needed by PR https://github.com/dlang/dmd/pull/13116 so that the return value of `_d_arrayctor` is used and not ignored. Because `_d_arrayctor` was and still is a strongly pure function, ignoring its return value causes warnings and risks being removed by the compiler.
> Use return value of _d_arrayctor

- src/core/internal/backtrace/libunwind.d
Fixes build on unsupported platforms.
> core.internal.backtrace.libunwind: Restrict usage to just DRuntime_Use_Libunwind, same as its only importer

- src/core/sys/linux/perf_event.d
Fixes build on BigEndian targets.
> core.sys.linux.perf_event: Remove import of std.bitmanip

- src/core/thread/osthread.d
Hello,
found a code location using the deprecated automatic type conversion. Here is a simple fix.
I have successfully tested the change on a recent OpenIndiana system.
> fix deprecated automatic type conversion

- src/core/stdc/stdlib.d
Digitalmars runtime does not implement it. But it is not a reason to do not include into C stdlib interface header.
> add aligned_alloc

- src/rt/sections_android.d
- src/rt/sections_osx_x86.d
- src/rt/sections_osx_x86_64.d
- src/rt/sections_solaris.d
- src/rt/sections_win32.d
- src/rt/sections_win64.d
https://github.com/dlang/druntime/pull/2785 added it for sections_elf_shared.d, this PR adds it for the rest of the platforms as well. See also: https://github.com/dlang/dmd/pull/12689
> Add explicit `return` to `moduleGroup`

- src/rt/config.d
- test/config/Makefile
- test/config/src/test22523.d
Otherwise configuration options passed after the `--` will still affect
the current process.
> Fix 22523 - Ensure that `rt_cmdlineOption` stops at `--`

- src/core/sys/windows/dbghelp.d
To allow modifying the search paths for .pdb files.
> core.sys.windows.dbghelp: Add SymSetSearchPath() functionality

- src/core/memory.d
After https://github.com/dlang/druntime/pull/3201, I think the `/* FIXME pure */` can be turned into an actual `pure`, with the only one stopping it being https://github.com/dlang/dmd/pull/13047.
> Add pure to GC functions

- src/core/sys/darwin/mach/nlist.d
`scope` has no meaning for a `ushort`. Remove it, as `return ref` is what is intended anyway.
Blocking https://github.com/dlang/dmd/pull/13357
> remove unnecessary scope keyword

- src/core/lifetime.d
After switching to `__traits(initSymbol)` in #3626.
> Test & document that emplace() works with -betterC and C++ classes now

- src/core/demangle.d
- src/core/internal/string.d
- src/core/internal/utf.d
- src/core/memory.d
- src/core/stdc/string.d
- src/core/stdc/wchar_.d
- src/core/sys/bionic/string.d
- src/core/sys/darwin/string.d
- src/core/sys/dragonflybsd/string.d
- src/core/sys/freebsd/string.d
- src/core/sys/linux/string.d
- src/core/sys/netbsd/string.d
- src/core/sys/openbsd/string.d
- src/core/sys/posix/string.d
- src/core/sys/posix/sys/socket.d
- src/object.d
- src/rt/aaA.d
- src/rt/cast_.d
- src/rt/lifetime.d
- src/rt/monitor_.d
See: https://forum.dlang.org/post/qqfqdsdhqwrrckturpal@forum.dlang.org
The idea is to consistently use `return scope` and `return ref` and no other variations. However, it does make these signatures longer and more 'attribute soup'-y.
> Turn `return` without `ref` into `return scope`

- src/core/lifetime.d
- src/object.d
This implements a template version of `_d_delstruct` to replace the homonymous function from `rt.lifetime.d`.
> Translate _d_delstruct to template

- src/core/internal/array/construction.d
This PR changes `_d_arrayctor` from a pure function to a weakly pure function.
This change is required because the removal of the `_d_arrayctor` hook implemented in this PR: https://github.com/dlang/dmd/pull/13116, lowers constructions such as the one below to calls to `_d_arrayctor`:
```d
struct S {};
const S[2] b;
const S[2] a = b;
```
The above code is lowered to `_d_arrayctor(a, b)`. For const and immutable arguments, the function is **strongly pure**, and since its return value is ignored, the compiler might choose to remove the call altogether.
In order to avoid this behaviour, `_d_arrayctor` has to be made **weakly pure**, which is what the added 3rd parameter does.
> Make _d_arrayctor weakly pure

- src/core/internal/elf/io.d
`mmap()` errors lead to `TypedMMapRegion.data` being null, which previously wasn't handled and led to segfaults - while trying to
resolve DWARF file/line infos for an exception backtrace.
This backtrace code needs to be as resilient as possible, so give up on the first mmap error now.
> core.internal.elf.io: Fix segfaults after mmap errors

- posix.mak
Found this while running the modularization tests. My hope is that it will help with this error:
```
generated/linux/release/64/benchmark.o:benchmark/runbench.d:function _D3std3uni__T13InversionListTSQBcQBb8GcPolicyZQBh__T3addTSQCeQCd__TQCcTQBqZQCkZQBbMFNaNbNcNfQBjZQBn: error: undefined reference to '_D3std3uni17CodepointInterval1aMNgFNaNbNcNdNiNfZNgk'
--
  | generated/linux/release/64/benchmark.o:benchmark/runbench.d:function _D3std3uni__T13InversionListTSQBcQBb8GcPolicyZQBh__T3addTSQCeQCd__TQCcTQBqZQCkZQBbMFNaNbNcNfQBjZQBn: error: undefined reference to '_D3std3uni17CodepointInterval1bMNgFNaNbNcNdNiNfZNgk'
  | generated/linux/release/64/benchmark.o:benchmark/runbench.d:function _D3std3uni__T13InversionListTSQBcQBb8GcPolicyZQBh__T3subTSQCeQCd__TQCcTQBqZQCkZQBbMFNaNbNcNfQBjZQBn: error: …
```
> Pass the correct dmd to the benchmark run

- src/core/lifetime.d
- src/object.d
[This PR](https://github.com/dlang/dmd/pull/13398) changed the lowering of `delete` expressions from the old hook to a [new one](https://github.com/dlang/druntime/pull/3639) that uses templates. The latter PR only implemented `_d_delstruct` and not `_d_delstructTrace`. This PR adds `_d_delstructTrace` as an alias that eventually calls the same `_d_delstruct`.
> Add template `_d_delstructTrace`

- src/core/internal/backtrace/elf.d
- src/core/internal/elf/io.d
- test/exceptions/Makefile
By porting Phobos' `thisExePath()` to druntime (for ELF platforms), in a `@nogc nothrow` fashion for low-level usage in exception
backtraces.
> Fix Issue 21656 - Read correct ELF executable for DWARF file/line infos

- src/core/sys/posix/sys/stat.d
Fixes bootstrap of D on mipsel64, where the first compiler couldn't read any files with the error message:
```
read error: Success
```
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=103604
> core.sys.posix.sys.stat: Fix shape of stat_t on MIPS N32 and N64 targets

- src/core/lifetime.d
This is needed because the dmd frontend will now check whether the deleted type is a struct with a destructor and if the said destructor is callable from where the delete expression is encountered.
Signed-off-by: teo <teodor.dutu@gmail.com>
> Fix `_d_delstruct` unittest - correctly mark destructor as `nothrow`

- mak/DOCS
- posix.mak
- src/core/builtins.d
Don't think we have much in the way of documentation for builtins so I added some here.
> Fix Issue 22064 - Missing docs for core.builtins

- src/core/internal/elf/io.d
Hello,
this PR replaces the function call to `sizeof` in `thisExePath` using the method call syntax on Illumos/Solaris. Otherwise the compilation fails.
> fix call of `sizeof` in `thisExePath` on Illumos/Solaris

- azure-pipelines.yml
See devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/#windows
> Azure: Replace deprecated vs2017-win2016 image with windows-2019

- win32.mak
OPTLINk tends to crash when linking `unittest.exe` (which creates a GUI window that hangs the CI scripts). So only check whether the unittests can be compiled and defer the actual test execution to the Win32 + MSCoff / Win64 builds.
CC @radcapricorn @RazvanN7
> Don't link & run unittests for Win32 + OMF due to OPTLINK issues

- src/core/lifetime.d
- src/object.d
This adds a templated version of `_d_newThrowable` to be used for lowering expressions like `throw new E("something");` in the compiler's frontend.
> Implement templated version of `_d_newThrowable`

- changelog/safe_opequals.dd
- src/object.d
- src/rt/util/typeinfo.d
I laid out in the ProtoObject dip thread how the real problem has nothing to do with Object, but rather with a helper function. It unnecessarily goes through Object instead of using the types actually passed to it and thus misses the static information available to it.
By simply making the helper function into a template, it is able to use the full static information and thus infer its attributes.
There is a migration path here though: users will want to get away from Object.opEquals. Delete the word `override` and you can offer an overload instead, which can then more specified parameters. We might want to outright deprecate Object.opEquals to inform people about the migration path, but even with it still being there, you can add the overload today, as I did in TypeInfo (both as an …
> @safe class comparisons

- src/core/sys/posix/sys/socket.d
Hi --
This syncs socket.d with what OpenBSD currently has in that C header file.
Thanks!
> Fix Issue 22669 - OpenBSD: Sync socket.d

- src/core/sys/linux/sys/inotify.d
Fix Issue 22670 - Support *BSD kqueue-backed API-compatible inotify shim library
This is a bit of a weird one, so I'll reproduce the bugzilla report here for ease of read/review:
While inotify is a Linux interface, there exists a kqueue-backed API-compatible inotify shim library for the BSDs (including macOS): https://github.com/libinotify-kqueue/libinotify-kqueue
It is modern and upkept in terms of maintenance.
I would like to add support for this in druntime.
I believe it makes the most sense to leave the inotify module where it is under the Linux system, since it is a Linux interface. Program and library authors will be able to keep doing the right thing, i.e., assuming that inotify is a Linux interface and needs no compatibility concern for non-Linux systems, ensuring no breakage in …
> Add support for the *BSD kqueue-backed inotify shim library.

- src/object.d
This PR aims to improve the documentation and the examples of the AA-specific functions `byKeyValue`, `byKey`, `byValue`, `keys`, and `values`.
(Continuation of #3401.)
> Fix Issue 21014 - aa.byKeyValue, byKey, byValue very under-documented

- CODEOWNERS
- mak/DOCS
- mak/SRCS
- src/core/int128.d
This is the opening salvo to support the `cent` type in D. It'll be needed by both the compiler and the generated executables. This version is not optimized, it just establishes a baseline of functionality.
It's built to be used as a standalone package, or have the compiler generate calls to, or have the compiler use it internally to bootstrap cent support.
It's byte endianness independent.
> add core.int128

- src/core/int128.d
`shl()` and `shr()` have already been optimized to not use a foreach loop around `shl1` and `shr1` respectively, so implement rotation as `(c <<  n) | (c >> 128-n)` for `rol` and `(c >> n) | (c << 128-n)` for `ror`.
> core.int128: Optimize rol() and ror()

- src/core/int128.d
Computes `mul()` by multiplying each 32-bit word of the value, adding any carry bits over. Because this doesn't care about recording any value that overflows 128-bits, we can unroll what would have been `foreach (i; 0..4) foreach(j; 0..4)` loop into four iterations that multiply the lower words of `c2` with the next higher word of `c1`.
> core.int128: Optimize mul()

- src/core/int128.d
@ibuclaw 's suggestions from https://github.com/dlang/druntime/pull/3663
> optimize int128.d

- src/core/math.d
It was removed in https://github.com/dlang/phobos/commit/b4f675fe150afaa577d6a41d6013ca33d932bd57
Fix Issue 22683 - core.math.rndtonl can't be linked
> Remove external reference to rndtonl.

- mak/COPY
- mak/SRCS
- src/__builtins.d
The motivation is that every C compiler has its own builtins, and those builtins appear in the preprocessed output fed to the ImportC compiler. The existing technique of hardwiring a wretched few of them into the compiler, and unctuously telling people that ImportC only supports Standard C11 for the rest is just not viable.
The possibility of the compiler supporting every nutburger C extension is completely unrealistic.
An earlier idea is to create our own `#include` file which the user adds to his preprocessor command. That only partially solves the problem, though, because many things are simply not expressible in Standard C11, which is why they were extensions in the first place. It also adds nasty friction borne by the user, and the point of ImportC is to eliminate friction.
But, I …
> Add __builtins.d to be imported by ImportC modules

- src/__builtins.d
by redirecting them to core.stdc.stdarg.
> finish __builtins support for stdarg

- src/core/sys/darwin/dlfcn.d
- src/core/sys/dragonflybsd/dlfcn.d
- src/core/sys/freebsd/dlfcn.d
- src/core/sys/linux/dlfcn.d
- src/core/sys/netbsd/dlfcn.d
- src/core/sys/openbsd/dlfcn.d
- src/core/sys/posix/dlfcn.d
- src/core/sys/solaris/dlfcn.d
The DL library is part of the C runtime, not the OS, so it doesn't make any sense to hide GlibC functions and flags behind `version(linux)`, which ultimately breaks ports such as kFreeBSD (which is `CRuntime_Glibc` with a `FreeBSD` kernel) due to it picking the FreeBSD C flags.
The `Dl_info` struct and `dladdr` function was also found to be duplicated across Posix and OS modules, so these have been removed from the OS too.
> core.sys.posix.dlfcn: Move and remove duplicate dlopen and dladdr arguments

- src/core/sys/posix/stdio.d
Incorrectly, it assumes that OS versions and CRuntime versions are mutually exclusive.  They are not in the case of kFreeBSD, which is both `CRuntime_Glibc` _and_ `FreeBSD` (kernel).
> core.sys.posix.stdio: Fix condition for declaring P_tmpdir

- src/rt/tracegc.d
The complete fix depends on the DMD and Phobos PRs are well, but this particular change is independent enough that it ought to be mergeable as-is. Regardless of how issue 14892 will ultimately be fixed, it will involve wrapping `_d_newarrayU` anyway, so might as well do this now.
> Issue 14892: need to wrap _d_newarrayU as well for -profile=gc.

- src/core/sys/posix/sys/mman.d
The reverse of #3678.  All mman.h flags are tied to the OS, not the C runtime.  Having these flags behind `CRuntime_Glibc` again breaks kFreeBSD, because the underlying kernel expects the `FreeBSD` flags to be passed.  So all flags have been moved into OS-specific version blocks, whilst the functions are still behind C-specific versions.
@Geod24 this would also fix the garbage collector on mips-musl and ppc64-musl targets, because you only had x86-specific flags declared.
> core.sys.posix.sys.mman: Split mman OS flags from C runtime functions

- src/core/sys/posix/sched.d
Merge more types and flags that are OS specific (though annoyingly Musl wanted to be different from Linux until it saw the error of its ways, but is now stuck with it's legacy mistake).
> Issue 22689: core.sys.posix.sys.sched: Separate OS-specific flags and types from C runtime functions

- src/core/sys/posix/sys/shm.d
More definitions that still wrongly assumed Glibc == Linux.
However, of the ones I've looked at so far, the glibc bindings are utterly wrong anyway, and don't take into account architecture differences.  And once again, Musl seems to have got its own idea about how the `shmid_ds` type should be defined too, but these can all be addressed in a follow-up.  For now, this is just fixing the non-Linux+Glibc case.
> Issue 22689: core.sys.posix.sys.shm: Separate OS-specific flags and types from C runtime functions

- src/core/sys/posix/fcntl.d
More definitions where `CRuntime_Glibc` was implicitly assumed to mean `linux`.  Because `CRuntime_Musl` defined more flags than `CRuntime_Glibc`, there's quite a bit of merging the two together into the Linux block.
> Issue 22689: core.sys.posix.fcntl: Separate OS-specific flags and types from C runtime functions

- src/core/sys/posix/sys/ipc.d
More definitions that are broken on non-linux `CRuntime_Glibc` platforms.
> Issue 22689: core.sys.posix.sys.ipc: Separate OS-specific flags and types from C runtime functions

- src/core/sys/posix/poll.d
These flags follow the OS, not the runtime.
> Issue 22689: core.sys.posix.poll: Separate OS-specific flags from C runtime types and functions

- src/core/thread/osthread.d
We shouldn't be poking around the thread library internals, because they _are_ subject to change under the rug, despite what the comment says.
As the issue this code references is also [in a reopened state](https://issues.dlang.org/show_bug.cgi?id=13416), it seems unlikely this actually fixes anything either.
> Issue 13416: Remove libthr hack from core.thread.osthread

- src/core/int128.d
Apparently I missed pushing the test by 7 minutes in #3675.  @RazvanN7
> core.int128: Add test for udivmod where lower bits of denominator > upper

- src/core/sys/posix/stdc/time.d
For instance, kFreeBSD follows uses Glibc's implementation of `clock()`, which is XSI conformant.
> core.sys.posix.stdc.time: Prefer CRuntime definitions over OS definitions of CLOCKS_PER_SEC

- src/core/sys/posix/sys/stat.d
More types and flags that are tied to the kernel, not the run-time.
> Issue 22689: core.sys.posix.sys.stat: Separate OS-specific types and flags from C runtime functions

- src/core/sys/posix/sys/socket.d
More types and flags that are tied to the kernel, not the run-time.
On inspection of differences between Glibc and Musl, it was found that Glibc had some incorrect bindings anyway, so Linux has been fixed in that regard.
> Issue 22689: core.sys.posix.sys.socket: Separate OS-specific types and flags from C runtime functions

- src/core/sys/posix/signal.d
More kernel types that are behind version `CRuntime_Glibc`.
> Issue 22689: core.sys.posix.signal: Separate OS-specific types and flags from C runtime functions

- src/core/sys/posix/sys/wait.d
More types and flags that are tied to the kernel, not the run-time.
> core.sys.posix.sys.wait: Separate OS-specific types and flags from C runtime functions

- src/core/sys/posix/termios.d
More types and flags that are tied to the kernel, not the run-time.
> Issue 22689: core.sys.posix.termios: Separate OS-specific types and flags from C runtime functions

- src/core/sys/posix/sys/types.d
`udev_t` and friends are tieds to the underlying kernel, whereas `pthread_t` is part of the run-time implementation.
Only Musl deviates away from this by forcing 64-bit time_t by default.
> core.sys.posix.sys.types: Separate OS-specific types from C runtime types

- azure-pipelines.yml
- win32.mak
The previous assumption was `MODEL=32` because `MODEL=32mscoff` is built by `win64.mak`.
Verified locally because Azure requires further changes outside of this repository.
> Make win32.mak compatible with MODEL=32omf

- posix.mak
The public examples shouldn't depend on anything hidden by
`-version=CoreUnittest` because user code won't specify it.
`-checkaction=context` is already used for all other unittest builds and
omitted here because it may introduce spurious linker errors (WIP).
CC @kinke
> Omit -version=CoreUnittest and -checkaction=context for example tests

- src/core/memory.d
- src/rt/tracegc.d
- test/profile/myprofilegc.log.freebsd.32.exp
- test/profile/myprofilegc.log.freebsd.64.exp
- test/profile/myprofilegc.log.linux.32.exp
- test/profile/myprofilegc.log.linux.64.exp
- test/profile/myprofilegc.log.osx.32.exp
- test/profile/myprofilegc.log.osx.64.exp
- test/profile/src/profilegc.d
GC allocations via core.memory.GC.* also need to be traced by `-profile=gc`.
> Fix 14892: Add tracing wrappers for core.memory.GC allocation calls.

- src/core/demangle.d
- src/core/lifetime.d
druntime uses getLinkage inappropriately in a couple places. The spec says it can return System so we should treat that the same as C/Windows where appropriate, and Throwable should only be a D class, not just not Windows/C++ class - remember, there's Objective-C classes too. The fix is to check what you expect, not a hardcoded list.
> Fix #22702 - make compilant with getLinkage returning System or Obj-C

- src/core/sys/posix/sys/ioctl.d
This is a Linux interface, not `CRuntime_Glibc`.  All that the C run-time exposes is an `ioctl()` function.
> core.sys.posix.sys.ioctl: Separate OS-specific types and flags from C runtime functions

- src/core/sys/posix/ucontext.d
> core.sys.posix.ucontext: Separate OS-specific types from C runtime functions

- src/core/stdc/math.d
I've accidentally stumbled upon this.
> core.stdc.math: Fix atan2l for uclibc

- win32.mak
- win64.mak
The target might require the host compiler, e.g. when run as a standalone target instead of a dependency.
Previously `make -f .\win32.mak copydir` failed due to `$(DMD)` expanding to the empty string:
```
"make" -f mak/WINDOWS copydir HOST_DMD="dmd" MODEL=32 IMPDIR="import"
conf= -c -o- -Isrc -Iimport -Hfimport\core\sync\barrier.di src\core\sync\barrier.d
Error: 'conf=' not found
```
> win**.mak: Forward DMD for copyDir

- src/object.d
~~This depends on https://github.com/dlang/dmd/pull/13593.~~
> Fix Issue 22717 - TypeInfo_Struct.equals swaps lhs and rhs parameters

- src/core/internal/elf/dl.d
- src/core/sys/linux/config.d
- src/core/sys/linux/dlfcn.d
- src/core/sys/linux/errno.d
- src/core/sys/linux/netinet/in_.d
- src/core/sys/linux/string.d
- src/core/sys/linux/sys/mman.d
- src/core/sys/posix/aio.d
- src/core/sys/posix/config.d
- src/core/sys/posix/spawn.d
- src/core/sys/posix/sys/mman.d
- src/core/sys/posix/sys/stat.d
- src/core/sys/posix/sys/statvfs.d
Following up from refactoring types and constants back into `version(linux)` code blocks.  There's a lot of uses of the Glibc-specific `__USE` manifest constants, all of which are just thin wrappers around more standard conditionals (e.g: glibc, musl, etc. all define them, but only glibc and uclibc have `__USE`).
Interestingly, Musl always defines `_XOPEN_SOURCE=700`, which mismatches the defaults set in `core.sys.posix.config`.  In a follow-up, that should be dealt with.
> core.sys.posix.config: Deprecate non-standard __USE manifest constants

- src/__builtins.di
https://docs.microsoft.com/en-us/cpp/cpp/int8-int16-int32-int64?view=msvc-170
> Add aliases for Visual C built in types extension

- src/__builtins.di
There doesn't seem to be a comprehensive list anywhere on just what all of these are. So we'll just add them piecemeal as required.
> fix Issue 22535 - ImportC: gcc/clang math intrinsics are rejected

- src/__builtins.di
Not a whole lot we can do with the ones other than bswap.
> fix Issue 22721 - importC: some gnu builtins are rejected

- src/core/sys/posix/sys/mman.d
Since the kernel/libc refactoring, this type is no longer split into two, rather `off_t` is always declared as either the 32-bit or 64-bit variant depending on `FILE_OFFSET64`.
> core.sys.posix.sys.mman: Fix definition of mmap64 for UClibc

- src/core/stdc/stdio.d
For the same reason as the Glibc version path, `off_t` is defined behind a `static if()` condition, and due to symbol resolution problems in the compiler, probably stemming from mixing of `version` and `static if` - [an unfixed bug](https://issues.dlang.org/show_bug.cgi?id=21171).
> core.stdc.stdio: Don't import off_t for either Bionic or UClibc

- src/core/sys/posix/aio.d
Partially reverts #2522.  Both [uClibc](https://git.uclibc.org/uClibc/tree/docs/uClibc_vs_SuSv3.txt#n91) and [uClibc-NG](https://cgit.uclibc-ng.org/cgi/cgit/uclibc-ng.git/tree/docs/uClibc_vs_SuSv3.txt#n91) say that AIO is unimplemented.
Which makes the source of these bindings very questionable.
> sys.posix.aio: Remove inaccurate bindings for uClibc

- src/core/sys/posix/config.d
This is for compatibility with core.sys.linux.config and version(linux) bindings.
Prevents any regressions from hitting Musl from the recent linux kernel/libc refactorings. @Geod24
> core.sys.posix.config: Ensure _GNU/DEFAULT/ATFILE_SOURCE is defined for all CRuntimes

- src/core/sys/posix/sys/shm.d
Added to not trigger the `static assert(false)`, however they are added as deprecated, because according to [upstream](https://android.googlesource.com/platform/bionic.git/+/refs/heads/master/libc/include/sys/shm.h), the default SELinux configuration on Android means that they are unusable anyway.
> core.sys.posix.sys.shm: Add bindings for Bionic runtime

- src/core/int128.d
As seen in https://buildkite.com/dlang/dmd/builds/24257#b5ea2644-79a0-4a55-937c-cd71aefad002
> core.int128: Fix linter warning 'variable C20_0 is never used'

- win32.mak
The makefile explicitly targets `-m32omf`, `-m32mscoff` is built by  `win64.mak`. The recent update to support `MODEL=32omf` broke support  for `MODEL=32` which used to indicate the old default (32 + OMF).
Ignoring the external `MODEL` parameter here fixes several components (e.g. the installer repo) that rely on the old behaviour. This hack is acceptable IMO because `win32.mak` never supported 32 + MS COFF and will become obsolete once `-m32omf` is removed.
---
EDIT: Marked as a draft, need to check e.g. the installer repo (in additional to the local CI)
> win32.mak: Explicitly use 32omf instead of $(MODEL)

- src/__builtins.di
Use `lazy` to not evaluate argument.
> fix Issue 22721 - importC: some gnu and clang builtins are rejected

- mak/COPY
- posix.mak
- src/importc.h
ImportC needs a .h file to precede all other .h files, to account for things like weird extensions. __builtins.d cannot handle it all, because it happens only after preprocessing has completed.
This will reduce the burden of ImportC having to support every nutburger C extension from the Dawn of Man in a much easier manner, usually by just adding a simple macro.
While this currently needs to be added manually, I expect it will become automatically added when dmd learns how to fork the preprocessor.
> add src/importc.h

- src/importc.h
Adding importc.h to druntime is making life easier for ImportC.
> fix Issue 22756 - ImportC: no __builtin_offsetof

- src/core/stdc/stdio.d
- src/rt/msvc.d
- test/betterc/Makefile
- test/betterc/src/test19933.d
- test/betterc/win64.mak
- win64.mak
moved C runtime check into template function
> fix issue 19933 and 18816: MSVC: Undefined std{in,out,err} with -betterC

- src/core/sys/posix/sys/ipc.d
- src/core/sys/posix/sys/types.d
This was causing static assert to trigger on Solaris.
> core.sys.posix.sys.ipc: Add missing bindings for Darwin and Solaris targets

- src/core/internal/array/appending.d
It's returning the parameter by ref, not by value
> Mark _d_arrayappend return ref instead of return scope

- src/core/lifetime.d
Use `pureMalloc` instead of `malloc`. Needed for https://github.com/dlang/dmd/pull/13494/.
> Allow `_d_newThrowable` to be pure

- src/object.d
```
Throwable.message was introduced as an alternative to the .msg field.
While it sounds like a good idea, in practice, no one uses it because '.msg'
is well established. But anyone wanting to use it will hit two main issues:
it is neither safe nor nothrow, while accessing '.msg' is safe/nothrow/pure/nogc.
While it woudl be too constraining to require pure/nogc, safe is commonly expected
in modern D code, and in the context of exception handling, so is nothrow accessor.
While this is technically a breaking change, the fact that message is currently
unusable and almost unused should be convincing enough to accept this change.
Additionally, message is still marked as __future, which would yield a message
on any code that failed to override it.
```
CC @ibuclaw
> Make Throwable.message safe and nothrow

- src/core/time.d
Currently, core.time freely allocates when toString is called.
With this sink delegate, Appender can be provided to reduce the number
of allocations, or even a static buffer to avoid allocations altogether.
This pattern is recognized by std.format.
> Make `core.time : Duration.toString` work with sink delegates

- src/core/stdcpp/string.d
Having `inout` infer `return` is going away, see https://github.com/dlang/dmd/pull/13658
Add `return` in explicitly.
> use explicit return instead of inferring from inout for _Get_data() and _Getal() methods

- src/core/stdcpp/string.d
Fix this message:
```
../../src/core/stdcpp/string.d(171): Error: scope variable `s` assigned to non-scope parameter `this` calling core.stdcpp.string.basic_string!(char, char_traits!char, allocator!char).basic_string.as_array
```
from https://github.com/dlang/dmd/pull/13658
> add return scope to as_array()

- src/core/time.d
And remove the internal alias which was a leftover for a previous
iteration of the code that wasn't templated.
> Add DDOC for `core.time : Duration.toString` `sink` parameter

- src/core/time.d
The original changes to toString, to support sink delegates,
did not make toString templated, hence the need to check
the GC usage at run time (and the lack of attributes).
However, now that toString is templated, this is no longer needed,
and putting nogc on the unittest is much better.
> Put attributes on core.time : Duration.toString unittest

- src/core/stdcpp/exception.d
- src/core/stdcpp/typeinfo.d
See https://issues.dlang.org/show_bug.cgi?id=22815 wrt. `extern(D)` ctors.
> [stable] core.stdcpp: Make constructors extern(D) and methods @nogc

- src/core/sys/posix/sys/stat.d
Bootstrapped on powerpc-linux-gnu and powerpc64-linux-gnu.
There is no change in the ppc64 layout/size despite adding the explicit padding field, so we manage to avoid more problems there.
> fix Issue 22822 - core.sys.posix.sys.stat: PPC stat_t bindings corrupt

- src/core/sys/posix/locale.d
Typo meant that `static assert(false)` got triggered.
> core.sys.posix.locale: Fix DragonFlyBSD condition

- src/core/stdc/stdio.d
Both Solaris and Bionic were still defining `stdout` and others in core.stdc.stdio, which cause a link failure when building without druntime.
> fix Issue 22829 - [REG master] Undefined symbol stderr first referenced in file test19933.o

- src/core/stdc/fenv.d
Otherwise you get undefined identifier errors.
> core.stdc.fenv: Fix missing import on linux/SPARC

- src/core/stdc/stdint.d
Reverts #[3400](https://github.com/dlang/druntime/pull/3400), then splits up the definitions into per platform bindings.
> fix Issue 22834 - core.stdc.stdint aliases are not platform independent

- src/core/stdc/stdint.d
MSVC documentation says it's an [`int`/`uint`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/standard-types?view=msvc-170), but the MinGW headers have [`short`/`ushort`](https://github.com/mirror/mingw-w64/blob/c6e13e0c105eab7797c2373819b49fff6b05566c/mingw-w64-headers/crt/stdint.h#L60-L61).
> core.stdc.stdint: Fix fast16_t definitions on MinGW

- src/core/internal/gc/bits.d
Bug found with AddressSanitizer, for the unittest with this code:
```
GCBits bits;
bits.alloc(10000);
auto data = bits.data;
GCBits src;
src.alloc(67);
src.data[0] = 0x4;
bits.copyRangeRepeating(2, 10000, src.data, 67);  <---- triggers the bug
```
The bug happens for the loop iteration in copyRangeRepeating that calls copyRange where these are the values of variables in copyRange:
cntWords = 2
target = 1342
last = 1408
lastWord = 22
lastOff = 0
firstOff = 62
len = 67
Overread happens on `source[cntWords]`.
I am not 100% certain of this fix, but proof of correctness of this fix:
Let's assume `firstOff == 3`, then `source[cntWords] << firstOff` has value `0bxx...xxxxx000` in bits.
For `lastOff == 2`, then `mask = (BITS_2 << lastOff) - 1  ==  (2 << lastOff) - 1 == 0b1000 - 1 == 0b111`. …
> Prevent buffer overread in core.internal.gc.bits

- src/rt/lifetime.d
Ensure the dereference happens on an aligned boundary.
i.e: In [runnable/testaa.d ](https://github.com/dlang/dmd/blob/d396d53a9dd5719ed6c97457dc2fe26f3a9c58df/test/runnable/testaa.d#L1087-L1104), the TypeInfo_Struct generated for `Array10970!C10970` has the values (on 64-bit):
```
structTypeInfoSize(ti) = 8
ti.tsize = 17
blkInf.size = 32
```
So `*(p + ti.tsize) = null` sets `p[17 .. 25] = null`, but we only need to set `p[16 .. 24] = null`, because the next expression sets `p[24 .. 32] = ti`.
I shouldn't have to explain why dereferencing an address at an offset of 17 is bad. :-)
> fix Issue 22844 - [REG 2.089] SIGBUS, Bus error in _d_newitemU

- src/rt/lifetime.d
Don't dereference the type-punned `init` pointer unless it's alignment is on the same boundary as the `T` that it is being cast to.
> fix Issue 22846 - [REG 2.066] SIGBUS, Bus error in _d_newarrayiT

- src/core/stdc/config.d
- src/core/stdcpp/new_.d
They trigger warnings w.r.t. empty declarations
> Remove trailing semicolons from core.stdc[pp] bindings

- mak/COPY
- mak/SRCS
- src/core/sys/openbsd/pwd.d
Fix Issue 22908 - OpenBSD: Add getpwnam_shadow and getpwuid_shadow function prototypes
> Add core.sys.openbsd.pwd module.

- src/core/stdcpp/string.d
`return scope` was added to `core.stdcpp.string.basic_string.as_array` in https://github.com/dlang/druntime/pull/3754 for `version(CppRuntime_Microsoft)` and in https://github.com/dlang/druntime/pull/3757 for `version(CppRuntime_Clang)`, because the`inout -> return ref` implication was removed and `return`/`scope` inference was not good at dealing with the ambiguity of `return ref` and `return scope`. 
Now with https://github.com/dlang/dmd/pull/13860, it turns out that for `version(CppRuntime_Clang)` `return scope` is incorrect, because it has a small buffer optimization, so it should be `return ref`. For uniformity, I made the `version(CppRuntime_Microsoft)` return ref as well.
> Fix return scope -> return ref in as_array()

- src/rt/dmain2.d
- test/exceptions/Makefile
- test/exceptions/src/message_with_null.d
The previous implementation simply forwarded the pointer + length to
`fprintf` and didn't check the return value. This caused the message to
be truncated for the following cases:
- it contains `\0` (the bug report)
- the length is greater than `int.max`
This commit changes the implementation s.t. it uses `fwrite` instead
which doesn't stop at `\0` and (theoretically) supports lengths up to
`size_t.max`
---
Also added a commit to make `test/exceptions` less noisy (because the `huge_message` test would generate a huge log entry)
> Fix 20778 - Ensure that _d_print_throwable prints the entire message

- src/core/thread/context.d
The file is named `context.d`, not `package.d`.
> Fix 21086 - Correct link core.thread.context

- src/core/atomic.d
Avoid possible unnecessary const to mutable conversion, which is not implicit for pointers. See [Issue 21631](https://issues.dlang.org/show_bug.cgi?id=21631) for details.
> core.atomic.cas: add 'const' attribute to local variable 'arg1'

- src/core/internal/array/casting.d
Still needs a bug report. First I want to see it pass CI, as I'm not sure if there's a test somewhere for this message.
> Fix confusing message on array cast failure.

- mak/COPY
Had overlooked this.
Blocking https://github.com/dlang/phobos/pull/8426
> copy core/int128.d to import directory

- src/core/int128.d
All function implementations and tests have been tweaked to use struct initializers instead of literals, as that saves on having to use `version (LittleEndian) else` all over the place.  Shouldn't have any effect on an optimizing compiler.
> core.int128: Match Cent layout on BigEndian targets

- src/object.d
- src/rt/aaA.d
Found by https://github.com/dlang/dmd/pull/13993
```
../druntime/import/object.d(3447): Error: escaping reference to outer local variable `aa`
DustMite/dustmite.d(1849):        instantiated from here: `RoundRobinCache!(Tuple!(Entity, "origRoot", Reduction, "r"), Entity)`
```
> Add `scope` to __aaGet functions

- src/core/internal/array/appending.d
- src/object.d
- src/rt/lifetime.d
The previous hook was wrapped in a template to easily define `_d_arrayappendTTrace` as an alias to `_d_HookTraceImpl`. That implementation forced `_d_arrayappendT` to be declared `@trusted pure` to make it callable from `pure` contexts. This is problematic when the hook calls `copyEmplace` on a type whose postblit is impure. In this case, `copyEmplace` is impure, which creates a conflict with `_d_arrayappendT`'s forced purity.
This PR removes the aforementioned template and leaves it up to the compiler to infer the purity of `_d_arrayappendT`. This change is required for the new lowering of `CatAssignExp`: https://github.com/dlang/dmd/pull/13495.
> Rework `_d_arrayappendT` to be a template function

- src/core/internal/array/appending.d
- src/core/internal/array/utils.d
- src/object.d
When I reworked `_d_arrayappendT` to a template (https://github.com/dlang/druntime/pull/3805), I believed I could recreate `_d_arrayappendTTrace` in the compiler by just instantiating the old alias:
```d
_d_HookTraceImpl!(Tarr, _d_arrayappendT, errorMessage);
```
However, this assumption turned out to be incorrect because `_d_HookTraceImpl` retrieves the types of the hook's parameters using `Parameters!Hook`. This expression triggered an error when `Hook` is a template because the types of its parameters weren't inferred yet.
The solution I chose was to add an explicit `_d_arrayappendTTrace` hook that uses a string mixin for the prints. This change is needed by https://github.com/dlang/dmd/pull/13495.
> Add explicit `_d_arrayappendTTrace` hook

- src/rt/sections_solaris.d
Fix Issue 23051 - OpenBSD: Build broken on 2.100.0-beta.1 due to the inout attribute no longer implying the return attribute
> Mark gcRanges() with return attribute

- src/core/simd.d
https://issues.dlang.org/show_bug.cgi?id=23048 and https://issues.dlang.org/show_bug.cgi?id=23048 are the result of not using the SIMD instructions correctly, and how to use them correctly is unclear. So I added clarifying examples.
> add clarifying examples of SIMD usage

- src/__builtins.di
this way the modules are only imported for code that needs them
<del>this also includes a fix to make `__builtin_expect` use c_long since that requires adding an import, it's done using an alias to keep it lazy without having to type `imported!"..."` for every use</del> (edit: will do separately)
i checked and all the affected functions still work like before
```C
// C code
void va(int x, ...)
{ 
va_list ap, ap2;
__builtin_va_start(ap, x);
int y = __builtin_va_arg(ap, int);
__builtin_va_copy(ap2, ap);
__builtin_va_end(ap2);
__builtin_va_end(ap);
}
int main()
{
float f = __builtin_fabsf(1.0f);
double d = __builtin_fabs(1.0);
long double ld = __builtin_fabsl(1.0L);
long x = __builtin_expect(0, 0);
va(0, 0);
}
```
this now doesn't list any `core.stdc.*` modules in the output of `dmd -v …
> __builtins: replace top-level imports with imported

- src/__builtins.di
since it's a C function [documented](https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html#index-_005f_005fbuiltin_005fexpect) as taking "long"
> fix Issue 23065: importC: __builtin_expect should use c_long

- src/core/sys/posix/sys/socket.d
Missing some declarations for macOS/Darwin.
Tested on a virtual machine.
> Fix issue 23060: MacOS: core.sys.posix.sys.socket missing some definitions

- src/core/memory.d
- src/core/thread/osthread.d
- src/core/thread/threadbase.d
The function rt_moduleTlsDtor must be called before thread_detachThis,
because the memory referenced by thread-local storage could be freed
by the GC after thread_detachThis. A thread-local static destructor
called by rt_moduleTlsDtor could access the already freed memory.
Calling rt_moduleTlsDtor first prevents this.
Links in core.memory to thread_attachThis / thread_detachThis did not
work and are fixed now.
Also added links between thread_attachThis and thread_detachThis.
> Improve documentation for thread_attachThis / thread_detachThis

- src/importc.h
Per [duser@neet.fi](mailto:duser@neet.fi) 's suggestion
> fix Issue 23067 - importC: offsetof macro assumes size_t is defined

- src/object.d
When it's explicitly *not* requested.
> Don't re-initialize D class instances in destroy!false()

- changelog/posix_gc_signals.dd
- src/core/memory.d
- src/core/thread/osthread.d
This is a revival of @9il's issue (Bugzilla Issue 15939, PR #1565), but fixed up / rebased on master.
As well, with this migration to the SIGRT signals, we no longer have to modify the signals for Android, so that line has been nixed.
Here is my rationale for this change (copied from the now-dead PR):
> Is there any reason why this hasn't been merged, other then a pending rebase? `SIGUSR1`/`SIGUSR2` *seems* rather problematic to use for something as low-level as the runtime, and I could easily imagine how this could shoot a developer in the foot if they're not aware. In fact, I think I've actually been burnt by this exact problem, as a C library that I wrapped was using `SIGUSR1`/`SIGUSR2`, and it was causing a variety of seemingly random issues (and as a library developer, I don't …
> [trivial] Move SIGUSR1/SIGUSR2 to SIGRT for GC

- src/core/thread/fiber.d
- src/core/thread/threadbase.d
- src/object.d
blocking https://github.com/dlang/dmd/pull/14164
> Object.getHash() shouldn't be casting away const

- src/rt/arrayassign.d
- src/rt/lifetime.d
- src/rt/tracegc.d
`_d_arrayappendT`, `_d_arrayappend{,set}ctor` and `_d_delstruct` were converted to templates and their lowerings in DMD now use the new template hooks.
`_d_array{,set}ctor`:
- DMD: https://github.com/dlang/dmd/pull/13116
- DRuntime: https://github.com/dlang/druntime/pull/2655
`_d_delstruct`:
- DMD: https://github.com/dlang/dmd/pull/13398
- DRuntime: https://github.com/dlang/druntime/pull/3639
`_d_arrayappendT`:
- DMD: https://github.com/dlang/dmd/pull/13495
- DRuntime: https://github.com/dlang/druntime/pull/2632
This PR removes the old non-template hooks as they are no longer used.
> Remove previously templated hooks

- src/core/sys/dragonflybsd/sys/elf32.d
- src/core/sys/dragonflybsd/sys/elf64.d
- src/core/sys/elf/package.d
- src/core/sys/freebsd/sys/elf32.d
- src/core/sys/freebsd/sys/elf64.d
- src/core/sys/linux/elf.d
- src/core/sys/netbsd/sys/elf32.d
- src/core/sys/netbsd/sys/elf64.d
- src/core/sys/openbsd/sys/elf32.d
- src/core/sys/openbsd/sys/elf64.d
- src/core/sys/solaris/sys/elftypes.d
- src/core/sys/solaris/sys/link.d
Solaris has a few more definitions outside of `core.sys.solaris.elf` that would otherwise conflict with `core.sys.elf`.  Annoyingly, Solaris insists on adding an extra field `d_off` to the `Elf32_Dyn` union, so have split up the `Elf#_Dyn` definitions again as well.
Bootstrapped on x86_64-pc-solaris2.11, and druntime/phobos is building again.
> core.sys.solaris.sys.link: Move shared ELF values to core.sys.elf

- src/core/lifetime.d
https://github.com/dlang/dmd/pull/13494 is blocked because it attempted to lower `new Exception(args)` to `_d_newThrowable!Exception(args)` and have `_d_newThrowable` call `Exception`'s ctor. This created a few errors due to how `forward!args` works with -dip1008.
Until -dip1008 is fixed, this PR removes the call to `Exception`'s ctor from `_d_newThrowable`, leaving this task to the compiler.
> Do not call throwable's ctor from `_d_newThrowable`

- src/rt/ehalloc.d
It was replaced by a template hook:
- https://github.com/dlang/druntime/pull/3661
- https://github.com/dlang/dmd/pull/13494
> Remove old `_d_newThrowable` hook

- src/core/internal/array/equality.d
at least in the happy case where it is comparing strings.
dmd's inliner would do better if it operated on the intermediate code rather than the AST, but in the meantime, this will speed up string compares.
> modify __equals() so dmd can inline it

- mak/DOCS
- posix.mak
- src/core/sync/package.d
The ddoc text is bare, I'm not familiar with the module so I'm not writing a comprehensive description yet, but this should fix the 404 and allow you to `import core.sync;`.
Makefiles updated similar to https://github.com/dlang/druntime/pull/2941
> Fix issue 21781 - Add core/sync/package.d for documentation

- src/rt/minfo.d
See https://github.com/dlang/dlang.org/pull/2702
> rt/minfo.d: Replace Error with assert()

- mak/COPY
- mak/IMPORTS
- mak/WINDOWS
- posix.mak
- win32.mak
- win64.mak
I can't see any good reason why all modules in mak/IMPORTS should be shipped as generated `.di` headers.
Move them all to COPY, and kill the .di generation recipes.  The `import` recipe has been kept around as a convenience alias to `copy` for now.
> makefiles: Remove mak/IMPORTS and header .di generation recipes

- src/rt/dmain2.d
- src/rt/lifetime.d
This was removed in https://github.com/dlang/druntime/pull/3361, but a stub was left.
> Remove `lifetime_init`

- src/core/sys/windows/winsock2.d
Ping @WalterBright 
This took 10 minutes.
> Mark all functions with a @safe interface as @trusted

- .github/workflows/cxx.yml
- appveyor.yml
- win64.mak
* Remove unused variables.
* Default to a matching MSVC `cl.exe` in PATH instead of an ancient Visual Studio 2010 installation.
* Remove explicit 32-bit recipes, requiring a separate make invocation.
> Clean up win64.mak

- src/core/stdc/stdarg.d
- src/core/vararg.d
Fixing previous wrong implementation according to RISCV Calling
Convention. Arguments larger than 2\*XLEN bits are replaced by the
address, and others with 2\*XLEN-bit alignment should be aligned in
register or stack.
> RISCV: Fix vararg implementation

- win32.mak
Use ImportC to compile .c files for druntime Win32 library
> compile .c files with ImportC

- src/rt/lifetime.d
It's 13 years old and is not used anywhere as far as I can see.
> Remove unused Array struct

- src/rt/aaA.d
Add `druntime` support to initialize an AA. Currently you have to add and then remove a dummy key/value pair to actually allocate the AA. This is needed if you want to give out references to the same AA before populating it.
https://issues.dlang.org/show_bug.cgi?id=10535
The syntax to do this will be `new AA`. I suggested that syntax and it was supported by @jacob-carlborg and @rainers here: https://github.com/dlang/druntime/pull/2504#issuecomment-469454754
I have the `dmd` counterpart ready ~~to submit.~~ https://github.com/dlang/dmd/pull/14257
> [rt/aaA] Add _aaNew function to initialize AA

- src/core/thread/osthread.d
OpenBSD does not provide SIGRTMIN or SIGRTMAX definitions.
Workaround is to use SIGUSR1 for SIGRTMIN and 32 for SIGRTMAX.
32 is the max signal number on OpenBSD.
This unbreaks the build on OpenBSD.
> Fix Issue 23228 - OpenBSD: No SIGRTMIN or SIGRTMAX

- src/rt/aaA.d
`_aaNew` was added recently in #3863.
This makes it consistent with `_d_assocarrayliteralTX` also returning `Impl*`.
I'm also hoping this will fix the test failures for some platforms with https://github.com/dlang/dmd/pull/14257 as I'm using `el_bin(OPcall, TYnptr` not `TYstruct` - couldn't get the latter to work.
Also flesh out docs for `_d_assocarrayliteralTX`.
> Change `_aaNew` to return `Impl*`, not `AA`

- src/importc.h
This doesn't actually fix it, it just sets the predefined C11 macro indicating VLAs are not supported.
> fix Issue 23213 - ImportC - variable length array does not compile

- src/core/internal/array/appending.d
It was introduced in https://github.com/dlang/druntime/pull/2632, but the two branches look identical to me.
> Remove string mixin from `_d_arrayappendcTX`

- posix.mak
- win32.mak
- win64.mak
So that auto-tester cloning the old druntime repository becomes just a no-op.
> Disable Posix builds on auto-tester
